#!/usr/bin/env python3
"""Сборка контента ранга D — модули D1 «Мир вокруг» (D-01…D-05) и
D2 «Мочь и иметь» (D-06…D-10), plan://M12#12.3–12.4.

Паттерн build_e1 (детерминированный seed, авто-вывод упражнений из пулов,
дистракторы ±50 — wordranks.distractor_pool). specs/01 §6, specs/02 §2.

Выход:
  data/phrases/phrases-d.json
  data/lessons/exercises-d.json
  data/lessons/lessons-d.json
  data/raw/phrase_audio_d.tsv
"""
from build_d_pools2 import LESSONS_D3_D4
from build_d_pools3 import LESSONS_D5_D6
from build_e1 import build_rank

# --------------------------------------------------------------------------
# D1 «Мир вокруг»
# --------------------------------------------------------------------------
D01 = [
    ("I am working now.", "Я сейчас работаю.", None),
    ("She is sleeping.", "Она спит.", None),
    ("He is reading a book.", "Он читает книгу.", None),
    ("We are watching TV.", "Мы смотрим телевизор.", None),
    ("They are playing football.", "Они играют в футбол.", None),
    ("I am still learning English.", "Я всё ещё учу английский.", None),
    ("She is still here.", "Она всё ещё здесь.", None),
    ("He is still waiting.", "Он всё ещё ждёт.", None),
    ("We are still friends.", "Мы всё ещё друзья.", None),
    ("I am living in Moscow these days.", "В эти дни я живу в Москве.", None),
    ("These days I work a lot.", "В последнее время я много работаю.", None),
    ("She is studying these days.", "В последнее время она учится.", None),
    ("Are you working now?", "Ты сейчас работаешь?", None),
    ("Is he sleeping?", "Он спит?", None),
    ("Are they coming?", "Они идут?", None),
    ("What are you doing?", "Что ты делаешь?", None),
    ("Where is she going?", "Куда она идёт?", None),
    ("Why are you laughing?", "Почему ты смеёшься?", None),
    ("I am not working today.", "Я сегодня не работаю.", None),
    ("She is not sleeping.", "Она не спит.", None),
    ("We are not watching TV.", "Мы не смотрим телевизор.", None),
    ("They are not playing now.", "Они сейчас не играют.", None),
    ("He is not listening.", "Он не слушает.", None),
    ("I am not laughing.", "Я не смеюсь.", None),
    ("The sun is shining.", "Солнце светит.", None),
    ("It is raining.", "Идёт дождь.", None),
    ("It is snowing.", "Идёт снег.", None),
    ("The bus is coming.", "Автобус едет.", None),
    ("The train is leaving.", "Поезд отправляется.", None),
    ("Someone is singing.", "Кто-то поёт.", None),
    ("The baby is crying.", "Малыш плачет.", None),
    ("People are walking in the park.", "Люди гуляют в парке.", None),
    ("I am waiting for you.", "Я жду тебя.", None),
    ("She is cooking dinner.", "Она готовит ужин.", None),
    ("He is writing a message.", "Он пишет сообщение.", None),
    ("They are talking about the film.", "Они говорят о фильме.", None),
    ("We are going home now.", "Мы сейчас идём домой.", None),
    ("Look! It is starting.", "Смотри! Начинается.", None),
    ("Listen! Someone is playing the piano.", "Слушай! Кто-то играет на пианино.", None),
    ("I am thinking about you.", "Я думаю о тебе.", None),
    ("She is looking for her keys.", "Она ищет свои ключи.", None),
    ("He is making coffee.", "Он готовит кофе.", None),
    ("The city is waking up.", "Город просыпается.", None),
    ("Life is changing.", "Жизнь меняется.", None),
]

D02 = [
    ("I know this word.", "Я знаю это слово.", None),
    ("Yes, I know this city.", "Да, я знаю этот город.", None),
    ("I know him.", "Я знаю его.", None),
    ("She knows the answer.", "Она знает ответ.", None),
    ("Do you know this city?", "Ты знаешь этот город?", None),
    ("I don't know.", "Я не знаю.", None),
    ("Nobody knows.", "Никто не знает.", None),
    ("Everyone knows it.", "Все это знают.", None),
    ("How do you know?", "Откуда ты знаешь?", None),
    ("I want some tea.", "Я хочу чаю.", None),
    ("She wants to help.", "Она хочет помочь.", None),
    ("He wants to sleep.", "Он хочет спать.", None),
    ("What do you want?", "Что ты хочешь?", None),
    ("I don't want to go.", "Я не хочу идти.", None),
    ("We want to stay here.", "Мы хотим остаться здесь.", None),
    ("They want to win.", "Они хотят победить.", None),
    ("I love this song.", "Я люблю эту песню.", None),
    ("She loves books.", "Она любит книги.", None),
    ("He loves his job.", "Он любит свою работу.", None),
    ("I love you.", "Я люблю тебя.", None),
    ("We love this city.", "Мы любим этот город.", None),
    ("I like this film.", "Мне нравится этот фильм.", None),
    ("She likes coffee.", "Ей нравится кофе.", None),
    ("He doesn't like fish.", "Ему не нравится рыба.", None),
    ("Do you like music?", "Тебе нравится музыка?", None),
    ("I need help.", "Мне нужна помощь.", None),
    ("She needs time.", "Ей нужно время.", None),
    ("We need a plan.", "Нам нужен план.", None),
    ("He needs money.", "Ему нужны деньги.", None),
    ("I don't need it.", "Мне это не нужно.", None),
    ("This book belongs to me.", "Эта книга принадлежит мне.", None),
    ("It belongs to her.", "Это принадлежит ей.", None),
    ("That idea belongs to him.", "Эта идея принадлежит ему.", None),
    ("I understand you.", "Я тебя понимаю.", None),
    ("Do you understand me?", "Ты меня понимаешь?", None),
    ("She doesn't understand.", "Она не понимает.", None),
    ("I believe you.", "Я тебе верю.", None),
    ("He believes in luck.", "Он верит в удачу.", None),
    ("I remember her name.", "Я помню её имя.", None),
    ("Do you remember me?", "Ты меня помнишь?", None),
    ("I mean it.", "Я серьёзно.", None),
    ("What do you mean?", "Что ты имеешь в виду?", None),
    ("She means well.", "Она хочет как лучше.", None),
    ("I see the problem.", "Я вижу проблему.", None),
    ("I hope you are right.", "Надеюсь, ты прав.", None),
]

D03 = [
    ("There is a café near here.", "Здесь рядом есть кафе.", None),
    ("There is a bank in this street.", "На этой улице есть банк.", None),
    ("There is a pharmacy next door.", "Рядом есть аптека.", None),
    ("There is a park in our city.", "В нашем городе есть парк.", None),
    ("There is a problem.", "Есть проблема.", None),
    ("There is a way out.", "Есть выход.", None),
    ("There is a hotel near the station.", "Возле вокзала есть отель.", None),
    ("There is water in the bottle.", "В бутылке есть вода.", None),
    ("There is milk in the fridge.", "В холодильнике есть молоко.", None),
    ("There is a market on Sundays.", "По воскресеньям есть рынок.", None),
    ("There are two cafés here.", "Здесь есть два кафе.", None),
    ("There are many people in the street.", "На улице много людей.", None),
    ("There are a lot of tourists here.", "Здесь много туристов.", None),
    ("There are some shops near the hotel.", "Возле отеля есть несколько магазинов.", None),
    ("There are three rooms in the house.", "В доме три комнаты.", None),
    ("There are good restaurants in this area.", "В этом районе есть хорошие рестораны.", None),
    ("There are no buses at night.", "Ночью нет автобусов.", None),
    ("There are two ways to do it.", "Есть два способа это сделать.", None),
    ("There is a solution.", "Есть решение.", None),
    ("There is a church on the square.", "На площади есть церковь.", None),
    ("There is a bridge over the river.", "Через реку есть мост.", None),
    ("There is a hospital in this town.", "В этом городе есть больница.", None),
    ("There is an ATM near the shop.", "Возле магазина есть банкомат.", None),
    ("There is free wifi here.", "Здесь есть бесплатный вайфай.", None),
    ("There is a mistake in the text.", "В тексте есть ошибка.", None),
    ("There is a metro station nearby.", "Рядом есть станция метро.", None),
    ("There is a bus stop here.", "Здесь есть автобусная остановка.", None),
    ("There is a post office in the centre.", "В центре есть почта.", None),
    ("There is a big mall in this district.", "В этом районе есть большой торговый центр.", None),
    ("There are flowers in the room.", "В комнате есть цветы.", None),
    ("There are books on the table.", "На столе есть книги.", None),
    ("There are clouds in the sky.", "На небе есть облака.", None),
    ("There are children in the yard.", "Во дворе есть дети.", None),
    ("There are old houses in this street.", "На этой улице есть старые дома.", None),
    ("There are many places to see.", "Есть много мест, которые стоит посмотреть.", None),
    ("Is there a café near here?", "Здесь рядом есть кафе?", None),
    ("Is there a problem?", "Есть проблема?", None),
    ("Is there a hotel in the town?", "В городе есть отель?", None),
    ("Is there any milk?", "Есть молоко?", None),
    ("Are there any shops here?", "Здесь есть магазины?", None),
    ("Are there many tourists today?", "Сегодня много туристов?", None),
    ("What is there in the box?", "Что есть в коробке?", None),
    ("There is no time.", "Времени нет.", None),
    ("There is nothing to fear.", "Нечего бояться.", None),
]

D04 = [
    ("There isn't a bank here.", "Здесь нет банка.", None),
    ("There isn't any milk.", "Молока нет.", None),
    ("There isn't a hospital in the village.", "В деревне нет больницы.", None),
    ("There aren't any shops here.", "Здесь нет магазинов.", None),
    ("There aren't many cafés in this area.", "В этом районе мало кафе.", None),
    ("There isn't much time.", "Времени не так много.", None),
    ("There isn't a pharmacy here.", "Здесь нет аптеки.", None),
    ("There aren't any buses today.", "Сегодня нет автобусов.", None),
    ("There is nothing on the table.", "На столе ничего нет.", None),
    ("There is nobody at home.", "Дома никого нет.", None),
    ("Where is the bank?", "Где банк?", None),
    ("Where is the nearest café?", "Где ближайшее кафе?", None),
    ("Where is the metro station?", "Где станция метро?", None),
    ("Where is the toilet?", "Где туалет?", None),
    ("Where is the exit?", "Где выход?", None),
    ("Where is the centre?", "Где центр?", None),
    ("The pharmacy is in Main Street.", "Аптека на Мейн-стрит.", None),
    ("The hotel is on the square.", "Отель на площади.", None),
    ("The shop is at the corner.", "Магазин на углу.", None),
    ("The keys are on the table.", "Ключи на столе.", None),
    ("The cat is under the table.", "Кот под столом.", None),
    ("The book is in the bag.", "Книга в сумке.", None),
    ("The café is next to the bank.", "Кафе рядом с банком.", None),
    ("The park is behind the church.", "Парк за церковью.", None),
    ("The station is in front of the hotel.", "Вокзал напротив отеля.", None),
    ("The bank is between the shop and the café.", "Банк между магазином и кафе.", None),
    ("The museum is near the river.", "Музей рядом с рекой.", None),
    ("It is on the left.", "Это слева.", None),
    ("It is on the right.", "Это справа.", None),
    ("Go straight and it is there.", "Идите прямо — и вы на месте.", None),
    ("It is across the street.", "Это через дорогу.", None),
    ("It is two blocks from here.", "Это в двух кварталах отсюда.", None),
    ("It is not far from here.", "Это недалеко отсюда.", None),
    ("It is five minutes on foot.", "Это пять минут пешком.", None),
    ("Is it far from here?", "Это далеко отсюда?", None),
    ("Is there a pharmacy near here?", "Здесь рядом есть аптека?", None),
    ("Is the station near?", "Вокзал рядом?", None),
    ("Are there any cafés open now?", "Сейчас есть открытые кафе?", None),
    ("Is there a toilet here?", "Здесь есть туалет?", None),
    ("The supermarket is closed today.", "Супермаркет сегодня закрыт.", None),
    ("The museum is open on Mondays.", "Музей работает по понедельникам.", None),
    ("The café is open until ten.", "Кафе открыто до десяти.", None),
    ("Excuse me, where is the station?", "Извините, где вокзал?", None),
    ("Excuse me, is there a bank near here?", "Извините, здесь рядом есть банк?", None),
]

D05 = [
    ("I know that you are right.", "Я знаю, что ты прав.", None),
    ("She says that she is busy.", "Она говорит, что занята.", None),
    ("He thinks that we are wrong.", "Он думает, что мы не правы.", None),
    ("I believe that it is true.", "Я верю, что это правда.", None),
    ("We hope that you are OK.", "Мы надеемся, что у тебя всё хорошо.", None),
    ("I remember that day.", "Я помню тот день.", None),
    ("There is a café near the station.", "Возле вокзала есть кафе.", None),
    ("There are many shops in the centre.", "В центре много магазинов.", None),
    ("There isn't a pharmacy here.", "Здесь нет аптеки.", None),
    ("Where is the nearest bank?", "Где ближайший банк?", None),
    ("I am working now.", "Я сейчас работаю.", None),
    ("She is not sleeping.", "Она не спит.", None),
    ("What are you doing?", "Что ты делаешь?", None),
    ("They are playing in the yard.", "Они играют во дворе.", None),
    ("I still remember this song.", "Я всё ещё помню эту песню.", None),
    ("He is still waiting for you.", "Он всё ещё ждёт тебя.", None),
    ("These days I am reading a lot.", "В последнее время я много читаю.", None),
    ("I want to know the truth.", "Я хочу знать правду.", None),
    ("She wants to stay.", "Она хочет остаться.", None),
    ("We need more time.", "Нам нужно больше времени.", None),
    ("Do you know this man?", "Ты знаешь этого человека?", None),
    ("I don't understand this word.", "Я не понимаю это слово.", None),
    ("I love this place.", "Мне нравится это место.", None),
    ("The shop is next to the café.", "Магазин рядом с кафе.", None),
    ("The hotel is on the left.", "Отель слева.", None),
    ("It is raining again.", "Опять идёт дождь.", None),
    ("The sun is shining.", "Солнце светит.", None),
    ("I am waiting for the bus.", "Я жду автобус.", None),
    ("She is looking for a job.", "Она ищет работу.", None),
    ("He is making breakfast.", "Он готовит завтрак.", None),
    ("There is someone at the door.", "У двери кто-то есть.", None),
    ("Is there a problem?", "Есть проблема?", None),
    ("Are there any tickets?", "Есть билеты?", None),
    ("There is no time to wait.", "Нет времени ждать.", None),
    ("I know where it is.", "Я знаю, где это.", None),
    ("She knows what she wants.", "Она знает, чего хочет.", None),
    ("I think that there is a way.", "Думаю, что выход есть.", None),
    ("We believe that the city is beautiful.", "Мы верим, что город красивый.", None),
    ("He says that there are two cafés.", "Он говорит, что есть два кафе.", None),
    ("I hope that there is a hotel.", "Надеюсь, что отель есть.", None),
    ("Nobody knows the answer.", "Никто не знает ответа.", None),
    ("Everyone is waiting.", "Все ждут.", None),
    ("It is important to me.", "Это важно для меня.", None),
    ("This place is beautiful.", "Это место красивое.", None),
]

# --------------------------------------------------------------------------
# D2 «Мочь и иметь»
# --------------------------------------------------------------------------
D06 = [
    ("I can swim.", "Я умею плавать.", None),
    ("She can drive.", "Она умеет водить.", None),
    ("He can cook well.", "Он хорошо готовит.", None),
    ("We can help you.", "Мы можем тебе помочь.", None),
    ("They can speak English.", "Они умеют говорить по-английски.", None),
    ("I can see the sea.", "Я вижу море.", None),
    ("I can hear you.", "Я тебя слышу.", None),
    ("She can come tomorrow.", "Она может прийти завтра.", None),
    ("You can do it.", "Ты сможешь это сделать.", None),
    ("I can't swim.", "Я не умею плавать.", None),
    ("He can't come today.", "Он не может прийти сегодня.", None),
    ("I can't hear you.", "Я тебя не слышу.", None),
    ("She can't drive.", "Она не умеет водить.", None),
    ("We can't wait.", "Мы не можем ждать.", None),
    ("They can't help us.", "Они не могут нам помочь.", None),
    ("I can't find my phone.", "Я не могу найти свой телефон.", None),
    ("I can't open the door.", "Я не могу открыть дверь.", None),
    ("She can't stop laughing.", "Она не может перестать смеяться.", None),
    ("He can't sleep.", "Он не может уснуть.", None),
    ("I can't believe it.", "Я не могу в это поверить.", None),
    ("I can do this alone.", "Я могу сделать это сам.", None),
    ("I can't do this alone.", "Я не могу сделать это один.", None),
    ("Can you swim?", "Ты умеешь плавать?", None),
    ("Can she drive?", "Она умеет водить?", None),
    ("Can they help us?", "Они могут нам помочь?", None),
    ("Can you see it?", "Ты это видишь?", None),
    ("Can you hear me now?", "Теперь меня слышно?", None),
    ("What can you do?", "Что ты умеешь делать?", None),
    ("Where can I buy a ticket?", "Где я могу купить билет?", None),
    ("How can I help you?", "Чем я могу помочь?", None),
    ("You can be anything.", "Ты можешь стать кем угодно.", None),
    ("It can be dangerous.", "Это может быть опасно.", None),
    ("This can wait.", "Это может подождать.", None),
    ("Anyone can make mistakes.", "Любой может ошибаться.", None),
    ("I can show you the way.", "Я могу показать тебе дорогу.", None),
    ("We can take a taxi.", "Мы можем взять такси.", None),
    ("You can call me later.", "Ты можешь позвонить мне позже.", None),
    ("I can walk there.", "Я могу дойти туда пешком.", None),
    ("She can sing really well.", "Она действительно хорошо поёт.", None),
    ("He can fix it.", "Он может это починить.", None),
    ("Money can't buy love.", "Деньги не могут купить любовь.", None),
    ("I can wait a little.", "Я могу немного подождать.", None),
    ("We can try again.", "Мы можем попробовать снова.", None),
    ("Nobody can help me.", "Никто не может мне помочь.", None),
]

D07 = [
    ("Can you help me?", "Вы можете мне помочь?", None),
    ("Can you help me, please?", "Помогите мне, пожалуйста.", None),
    ("Can you repeat that?", "Вы можете повторить?", None),
    ("Can you say it again?", "Вы можете сказать это снова?", None),
    ("Can you speak slowly?", "Вы можете говорить медленнее?", None),
    ("Can you open the window?", "Вы можете открыть окно?", None),
    ("Can you close the door?", "Вы можете закрыть дверь?", None),
    ("Can you pass me the salt?", "Передадите мне соль?", None),
    ("Can you call a taxi?", "Вы можете вызвать такси?", None),
    ("Can you take a photo?", "Вы можете сделать фото?", None),
    ("Can you show me on the map?", "Вы можете показать на карте?", None),
    ("Can you write it down?", "Вы можете это записать?", None),
    ("Can I ask you something?", "Можно вас кое о чём спросить?", None),
    ("Can I sit here?", "Можно здесь сесть?", None),
    ("Can I come in?", "Можно войти?", None),
    ("Can I open the window?", "Можно открыть окно?", None),
    ("Can I have a coffee, please?", "Можно кофе, пожалуйста?", None),
    ("Can I have the bill?", "Можно счёт?", None),
    ("Can I pay by card?", "Можно оплатить картой?", None),
    ("Can I try it on?", "Можно это примерить?", None),
    ("Can I borrow your pen?", "Можно взять вашу ручку?", None),
    ("Can I take your seat?", "Можно занять ваше место?", None),
    ("Can I have a minute?", "Можно минуту вашего внимания?", None),
    ("Can I see the menu?", "Можно посмотреть меню?", None),
    ("Can I have some water?", "Можно воды?", None),
    ("Can I park here?", "Здесь можно парковаться?", None),
    ("Can I smoke here?", "Здесь можно курить?", None),
    ("Can I use your phone?", "Можно воспользоваться вашим телефоном?", None),
    ("I can help you.", "Я могу вам помочь.", None),
    ("Yes, of course you can.", "Да, конечно можно.", None),
    ("Yes, you can.", "Да, можно.", None),
    ("No, you can't.", "Нет, нельзя.", None),
    ("Sorry, you can't.", "Извините, нельзя.", None),
    ("Sure, no problem.", "Конечно, без проблем.", None),
    ("Sorry, I am busy.", "Извини, я занят.", None),
    ("Can you tell me the time?", "Скажете, сколько времени?", None),
    ("Can you wait a minute?", "Вы можете минутку подождать?", None),
    ("Can you hold my bag?", "Подержите мою сумку?", None),
    ("Can I help you?", "Чем могу помочь?", None),
    ("How can I help?", "Чем я могу помочь?", None),
    ("Can you hear the music?", "Ты слышишь музыку?", None),
    ("Can we sit outside?", "Можно сесть на улице?", None),
    ("Can we order now?", "Можно сделать заказ?", None),
    ("Can we go home now?", "Можно уже домой?", None),
    ("Can I have two tickets?", "Можно два билета?", None),
]

D08 = [
    ("I have a ticket.", "У меня есть билет.", None),
    ("I have got a ticket.", "У меня есть билет.", ["I have a ticket."]),
    ("She has a phone.", "У неё есть телефон.", None),
    ("She has got a phone.", "У неё есть телефон.", ["She has a phone."]),
    ("He has a car.", "У него есть машина.", None),
    ("We have a plan.", "У нас есть план.", None),
    ("They have a small house.", "У них маленький дом.", None),
    ("I have a question.", "У меня есть вопрос.", None),
    ("Do you have a pen?", "У тебя есть ручка?", None),
    ("I have got a pen.", "У меня есть ручка.", None),
    ("Have you got a pen?", "У тебя есть ручка?", ["Do you have a pen?"]),
    ("I have got two brothers.", "У меня есть два брата.", ["I have two brothers."]),
    ("She has got a dog.", "У неё есть собака.", ["She has a dog."]),
    ("We have got tickets.", "У нас есть билеты.", ["We have tickets."]),
    ("He has got an idea.", "У него есть идея.", ["He has an idea."]),
    ("I haven't got money.", "У меня нет денег.", None),
    ("I don't have money.", "У меня нет денег.", ["I haven't got money."]),
    ("Has she got a car?", "У неё есть машина?", None),
    ("She hasn't got a car.", "У неё нет машины.", None),
    ("We haven't got time.", "У нас нет времени.", None),
    ("They haven't got children.", "У них нет детей.", None),
    ("I don't have a visa.", "У меня нет визы.", None),
    ("He doesn't have a phone.", "У него нет телефона.", None),
    ("Have you got a map?", "У тебя есть карта?", None),
    ("I have got a map.", "У меня есть карта.", None),
    ("Have you got children?", "У вас есть дети?", None),
    ("What have you got there?", "Что у тебя там?", None),
    ("I have got a bad feeling.", "У меня плохое предчувствие.", None),
    ("I have my passport with me.", "Мой паспорт при мне.", None),
    ("I have my luggage with me.", "Мой багаж при мне.", None),
    ("She has her keys.", "Ключи при ней.", None),
    ("I have got a headache.", "У меня болит голова.", None),
    ("He has got a cold.", "Он простудился.", None),
    ("We have got a problem.", "У нас проблема.", None),
    ("You have got a message.", "У тебя есть сообщение.", None),
    ("The room has got a window.", "В комнате есть окно.", None),
    ("The hotel has got wifi.", "В отеле есть вайфай.", None),
    ("The house has got a garden.", "У дома есть сад.", None),
    ("This phone has got a good camera.", "У этого телефона хорошая камера.", None),
    ("Have you got a table for two?", "У вас есть столик на двоих?", None),
    ("Have you got anything cheaper?", "У вас есть что-нибудь дешевле?", None),
    ("Have you got a bigger size?", "У вас есть размер побольше?", None),
    ("Do you have change?", "У вас есть мелочь?", None),
    ("Do you have a room?", "У вас есть номер?", None),
    ("I have a reservation.", "У меня бронь.", None),
    ("We have got a long way to go.", "Нам ещё долго идти.", None),
    ("You have got a friend here.", "Здесь у тебя есть друг.", None),
]

D09 = [
    ("Stop!", "Стой!", None),
    ("Wait!", "Подожди!", None),
    ("Listen!", "Слушай!", None),
    ("Look!", "Смотри!", None),
    ("Come here!", "Иди сюда!", None),
    ("Sit down.", "Садись.", None),
    ("Stand up.", "Встань.", None),
    ("Open the door.", "Открой дверь.", None),
    ("Close the window.", "Закрой окно.", None),
    ("Give me the bag.", "Дай мне сумку.", None),
    ("Take my hand.", "Возьми меня за руку.", None),
    ("Follow me.", "Следуй за мной.", None),
    ("Follow the signs.", "Следуйте указателям.", None),
    ("Turn left.", "Поверните налево.", None),
    ("Turn right.", "Поверните направо.", None),
    ("Go straight.", "Идите прямо.", None),
    ("Turn left and go straight.", "Поверните налево и идите прямо.", None),
    ("Go back.", "Вернитесь назад.", None),
    ("Go upstairs.", "Поднимитесь наверх.", None),
    ("Go downstairs.", "Спуститесь вниз.", None),
    ("Cross the street.", "Перейдите дорогу.", None),
    ("Take the first street on the left.", "Сверните на первую улицу слева.", None),
    ("Call the police.", "Вызовите полицию.", None),
    ("Call a doctor.", "Вызовите врача.", None),
    ("Help me!", "Помогите!", None),
    ("Be careful!", "Осторожно!", None),
    ("Be quiet.", "Тише.", None),
    ("Hurry up!", "Поторопись!", None),
    ("Keep moving.", "Продолжай идти.", None),
    ("Stay here.", "Оставайся здесь.", None),
    ("Don't stop.", "Не останавливайся.", None),
    ("Don't touch it.", "Не трогай это.", None),
    ("Don't be afraid.", "Не бойся.", None),
    ("Don't be late.", "Не опаздывай.", None),
    ("Don't look back.", "Не оглядывайся.", None),
    ("Don't give up.", "Не сдавайся.", None),
    ("Don't worry.", "Не волнуйся.", None),
    ("Don't move.", "Не двигайся.", None),
    ("Don't cry.", "Не плачь.", None),
    ("Please, sit down.", "Пожалуйста, садитесь.", None),
    ("Please, wait here.", "Пожалуйста, подождите здесь.", None),
    ("Trust me.", "Доверься мне.", None),
    ("Believe me.", "Поверь мне.", None),
    ("Hold the door.", "Придержи дверь.", None),
    ("Get out!", "Уходи!", None),
]

D10 = [
    ("I can swim well.", "Я хорошо плаваю.", None),
    ("She can drive a car.", "Она умеет водить машину.", None),
    ("I can't find my keys.", "Я не могу найти свои ключи.", None),
    ("Can you help me, please?", "Помогите мне, пожалуйста.", None),
    ("Can I have the bill?", "Можно счёт?", None),
    ("Can I pay by card?", "Можно оплатить картой?", None),
    ("I have got a ticket.", "У меня есть билет.", ["I have a ticket."]),
    ("She has got a question.", "У неё есть вопрос.", ["She has a question."]),
    ("I haven't got time.", "У меня нет времени.", None),
    ("Have you got a pen?", "У тебя есть ручка?", ["Do you have a pen?"]),
    ("Have you got a map?", "У тебя есть карта?", None),
    ("I have got a map.", "У меня есть карта.", None),
    ("We have a problem.", "У нас проблема.", None),
    ("They have a plan.", "У них есть план.", None),
    ("Stop and listen.", "Остановись и слушай.", None),
    ("Don't stop here.", "Не останавливайся здесь.", None),
    ("Turn left and go straight.", "Поверните налево и идите прямо.", None),
    ("Follow me, please.", "Следуйте за мной, пожалуйста.", None),
    ("Don't worry about me.", "Не волнуйся за меня.", None),
    ("Be careful with the steps.", "Осторожно со ступеньками.", None),
    ("Take my hand and come with me.", "Возьми меня за руку и пойдём со мной.", None),
    ("There is a café near the hotel.", "Возле отеля есть кафе.", None),
    ("There are two banks in this street.", "На этой улице два банка.", None),
    ("There isn't a toilet here.", "Здесь нет туалета.", None),
    ("Where is the nearest pharmacy?", "Где ближайшая аптека?", None),
    ("The museum is next to the park.", "Музей рядом с парком.", None),
    ("I am working now.", "Я сейчас работаю.", None),
    ("What are you doing?", "Что ты делаешь?", None),
    ("She is looking for her phone.", "Она ищет свой телефон.", None),
    ("They are waiting for the taxi.", "Они ждут такси.", None),
    ("I know that you can do it.", "Я знаю, что ты сможешь это сделать.", None),
    ("She says that she has time.", "Она говорит, что у неё есть время.", None),
    ("He thinks that there is a way.", "Он думает, что выход есть.", None),
    ("I want to help you.", "Я хочу тебе помочь.", None),
    ("We need a taxi.", "Нам нужно такси.", None),
    ("I love this city.", "Я люблю этот город.", None),
    ("Do you know this street?", "Ты знаешь эту улицу?", None),
    ("I don't understand you.", "Я тебя не понимаю.", None),
    ("Can you speak slowly, please?", "Говорите медленнее, пожалуйста.", None),
    ("Can I sit here?", "Можно здесь сесть?", None),
    ("You can do anything.", "Ты можешь всё.", None),
    ("Sorry, I can't help you now.", "Извини, я не могу помочь тебе сейчас.", None),
    ("I have got an idea.", "У меня есть идея.", ["I have an idea."]),
    ("Don't be shy.", "Не стесняйся.", None),
    ("Have a good day!", "Хорошего дня!", None),
]

RULE_D01 = """**Present Continuous — процесс прямо сейчас.**
am / is / are + глагол+-ing: I **am working** now. She **is sleeping**.
Отрицание: I **am not** working. Вопрос: **Are** you working?
**still** = «всё ещё»: I am **still** learning English.
**these days** = «в последнее время»: These days I am living in Moscow.
Слова-маркеры: now, still, these days, Look!, Listen!"""

RULE_D02 = """**Глаголы состояния — без Continuous.**
know, want, love, like, need, understand, believe, remember, mean, belong —
это состояния, а не процессы: I **know** him. She **wants** to help.
❌ I am knowing him.
⚠️ Ловушка: «I am thinking» — только о процессе обдумывания («раздумываю»),
о мнении — I **think** (that) you are right."""

RULE_D03 = """**there is / there are — «есть, находится».**
Единственное число: **There is** a café near here.
Множественное: **There are** two cafés here.
Порядок слов русский↔английский разный: «Здесь есть кафе» → **There is** a café here.
Отрицание: There is **no** time. / There isn't a bank here."""

RULE_D04 = """**there is/are: вопросы и предлоги места.**
Вопрос: **Is there** a café near here? — Yes, there is. / No, there isn't.
**Where is** the bank? — It is in Main Street.
Предлоги места: **in** the bag, **on** the table, **at** the corner,
**next to** the bank, **under** the table, **between** the shop and the café,
**in front of** the hotel, **behind** the church."""

RULE_D05 = """**Повторение №5: всё вместе.**
Present Continuous ↔ глаголы состояния: What **are** you **doing**? — I **know** him.
there is/are ±?: **Is there** a pharmacy near here?
Предлоги места: next to, between, behind, in front of.
⚠️ Запятая: в русском перед «что» запятая нужна, в английском перед **that** — нет:
I know **that** you are right. (без запятой!)"""

RULE_D06 = """**can — умение и возможность.**
Без to, без -s: I **can swim**. She **can drive**.
Отрицание: I **can't** swim. (= cannot)
Вопрос: **Can** you swim? — Yes, I can. / No, I can't.
can + глагол всегда в одной форме: ❌ She cans drive."""

RULE_D07 = """**Can you…? / Can I…? — просьба и разрешение.**
Вежливая просьба: **Can you** help me, please?
Разрешение: **Can I** sit here? — Yes, you can. / No, you can't.
please делает просьбу вежливой. Ответ: Sure, no problem! / Sorry, I am busy."""

RULE_D08 = """**have got / have — «иметь».**
Британский вариант: I **have got** a ticket. = I **have** a ticket.
3-е лицо: She **has got** a phone.
Отрицание: I **haven't got** money. = I **don't have** money.
Вопрос: **Have you got** a pen? = **Do you have** a pen?"""

RULE_D09 = """**Повелительное наклонение.**
Глагол в чистой форме: **Stop!** **Listen!** **Follow me!**
Отрицание: **Don't** + глагол: **Don't stop.** **Don't be late!**
Вежливость: Please + повелительное: **Please, wait here.**
Указания маршрута: Turn left. Go straight. Follow the signs."""

RULE_D10 = """**Повторение №6: can, have got, повелительное.**
can: Can you help me? — Sorry, I can't.
have got: Have you got a map? — Yes, I have.
Повелительное: Don't worry. Follow me.
Всё вместе: Can I have a coffee? — Sure, have a seat."""

LESSONS_D = [
    {
        "id": "les-d-01", "module": "mod-d-1",
        "title": "Present Continuous: процесс. still, these days",
        "gp_id": "gp-d-01", "gp_title": "Present Continuous: закрепление",
        "rule_md": RULE_D01,
        "phrases": D01,
        "rule_cloze": [
            ("I ___ working now.", ["am"]),
            ("She ___ sleeping.", ["is"]),
            ("___ you working now?", ["Are"]),
        ],
        "quotes": [("q-attack-on-titan-0006", "keep"), ("q-fma-fma-b-0004", "Keep")],
        "trap_id": "trap-articles",
        "vocab_band": {"list": "ngsl-spoken", "from": 281, "to": 340},
        "phrasebook_topic": "directions",
        "quotes_topic": "now",
        "bebris_video": {"lesson": "2.1", "playlist_index": 552, "youtube_id": "6Y-aBWo-xFk", "title": None},
        "answer_question": [("What are you doing?", "I am working now.")],
        "find_error": [("I am work now.", "I am working now.")],
        "verb_tense": [
            ("She ___ sleeping now.", "now", ["is sleeping"]),
            ("They ___ football now.", "now", ["are playing"]),
            ("I ___ still learning English.", "still", ["am still learning"]),
        ],
    },
    {
        "id": "les-d-02", "module": "mod-d-1",
        "title": "Глаголы состояния: know, want, love — без Continuous",
        "gp_id": "gp-d-02", "gp_title": "Глаголы состояния без Continuous",
        "rule_md": RULE_D02,
        "phrases": D02,
        "rule_cloze": [
            ("I ___ this word.", ["know"]),
            ("She ___ to help.", ["wants"]),
            ("This book ___ to me.", ["belongs"]),
        ],
        "quotes": [("q-supernatural-0011", "want"), ("q-black-mirror-0004", "happens")],
        "trap_id": "trap-interested",
        "vocab_band": {"list": "ngsl-spoken", "from": 341, "to": 400},
        "phrasebook_topic": None,
        "quotes_topic": "feelings",
        "bebris_video": {"lesson": "2.16", "playlist_index": 567, "youtube_id": "VNoNT1ao4O0", "title": None},
        "answer_question": [("Do you know this city?", "Yes, I know this city.")],
        "find_error": [("I am knowing him.", "I know him.")],
        "verb_tense": [
            ("I ___ him.", "know", ["know"]),
            ("She ___ books.", "love", ["loves"]),
            ("We ___ a plan.", "need", ["need"]),
        ],
    },
    {
        "id": "les-d-03", "module": "mod-d-1",
        "title": "there is / there are: «есть, находится»",
        "gp_id": "gp-d-03", "gp_title": "Конструкция there is / there are",
        "rule_md": RULE_D03,
        "phrases": D03,
        "rule_cloze": [
            ("___ a café near here.", ["There is"]),
            ("___ two cafés here.", ["There are"]),
            ("___ a problem?", ["Is there"]),
        ],
        "quotes": [("q-star-wars-0005", "There"), ("q-game-of-thrones-0021", "is")],
        "trap_id": "trap-articles",
        "vocab_band": {"list": "ngsl-spoken", "from": 401, "to": 460},
        "phrasebook_topic": "directions",
        "quotes_topic": "city",
        "bebris_video": {"lesson": "2.261", "playlist_index": 812, "youtube_id": "GEorr2nlRyw", "title": None},
        "answer_question": [("Is there a café near here?", "There is a café near here.")],
        "find_error": [("There is two cafés here.", "There are two cafés here.")],
        "verb_tense": [
            ("___ a bank in this street.", "there + ед.ч.", ["There is"]),
            ("___ many people in the street.", "there + мн.ч.", ["There are"]),
            ("___ a hotel near the station?", "вопрос", ["Is there"]),
        ],
    },
    {
        "id": "les-d-04", "module": "mod-d-1",
        "title": "there is/are: − и ?; предлоги места",
        "gp_id": "gp-d-04", "gp_title": "Отрицания/вопросы there is; предлоги места",
        "rule_md": RULE_D04,
        "phrases": D04,
        "rule_cloze": [
            ("There ___ any shops here.", ["aren't"]),
            ("The pharmacy is ___ Main Street.", ["in", "on"]),
            ("The café is ___ to the bank.", ["next"]),
        ],
        "quotes": [("q-game-of-thrones-0010", "There's"), ("q-star-wars-0017", "looking")],
        "trap_id": "trap-to-home",
        "vocab_band": {"list": "ngsl-spoken", "from": 461, "to": 520},
        "phrasebook_topic": "directions",
        "quotes_topic": "city",
        "bebris_video": None,
        "answer_question": [("Where is the nearest café?", "The café is next to the bank.")],
        "find_error": [("The cat is under of the table.", "The cat is under the table.")],
        "verb_tense": [
            ("___ there a pharmacy near here?", "вопрос", ["Is"]),
            ("The book is ___ the bag.", "внутри", ["in", "inside"]),
            ("The station is ___ front of the hotel.", "напротив", ["in"]),
        ],
    },
    {
        "id": "les-d-05", "module": "mod-d-1",
        "title": "Повторение №5: Continuous, состояния, there is/are",
        "gp_id": "gp-d-05", "gp_title": "Повторение модуля D1 + диктант",
        "rule_md": RULE_D05,
        "phrases": D05,
        "rule_cloze": [
            ("I know ___ you are right.", ["that"]),
            ("___ there a problem?", ["Is"]),
            ("She is ___ for a job.", ["looking"]),
        ],
        "quotes": [("q-attack-on-titan-0007", "world"), ("q-lord-of-the-rings-0009", "is")],
        "trap_id": "trap-comma-that",
        "vocab_band": {"list": "ngsl-spoken", "from": 521, "to": 580},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("Is there a problem?", "There is a problem.")],
        "find_error": [("I know, that you are right.", "I know that you are right.")],
        "verb_tense": [
            ("I ___ that you are right.", "мнение", ["think"]),
            ("What ___ you doing?", "процесс", ["are"]),
            ("___ there many shops in the centre?", "вопрос", ["Are"]),
        ],
    },
    {
        "id": "les-d-06", "module": "mod-d-2",
        "title": "can: умение и возможность (+/−)",
        "gp_id": "gp-d-06", "gp_title": "Модальный глагол can",
        "rule_md": RULE_D06,
        "phrases": D06,
        "rule_cloze": [
            ("I ___ swim. (умение)", ["can"]),
            ("I ___ do this alone.", ["can't"]),
            ("___ you swim?", ["Can"]),
        ],
        "quotes": [("q-lord-of-the-rings-0006", "can't"), ("q-fma-fma-b-0015", "Can't")],
        "trap_id": "trap-very-like",
        "vocab_band": {"list": "ngsl-spoken", "from": 581, "to": 640},
        "phrasebook_topic": None,
        "quotes_topic": "abilities",
        "bebris_video": {"lesson": "2.293", "playlist_index": 844, "youtube_id": "5mFaI_cnaB8", "title": None},
        "answer_question": [("Can you swim?", "I can swim.")],
        "find_error": [("She cans drive.", "She can drive.")],
        "verb_tense": [
            ("He ___ come today.", "can + не мочь", ["can't"]),
            ("They ___ speak English.", "умение", ["can"]),
            ("___ you see it?", "вопрос", ["Can"]),
        ],
    },
    {
        "id": "les-d-07", "module": "mod-d-2",
        "title": "Can you…? / Can I…? Просьба и разрешение",
        "gp_id": "gp-d-07", "gp_title": "Просьбы и разрешения с can",
        "rule_md": RULE_D07,
        "phrases": D07,
        "rule_cloze": [
            ("___ you help me, please?", ["Can"]),
            ("___ I sit here?", ["Can"]),
            ("Can you ___ that again? (повторить)", ["repeat"]),
        ],
        "quotes": [("q-attack-on-titan-0009", "May"), ("q-supernatural-0004", "can't")],
        "trap_id": "trap-question-word-order",
        "vocab_band": {"list": "ngsl-spoken", "from": 641, "to": 700},
        "phrasebook_topic": "directions",
        "quotes_topic": "requests",
        "bebris_video": {"lesson": "2.294", "playlist_index": 845, "youtube_id": "y8pcQGaMKI0", "title": None},
        "answer_question": [("Can you help me?", "I can help you.")],
        "find_error": [("You can help me?", "Can you help me?")],
        "verb_tense": [
            ("___ I have a coffee, please?", "разрешение", ["Can"]),
            ("___ you open the window?", "просьба", ["Can"]),
            ("Can I ___ here?", "сесть", ["sit"]),
        ],
    },
    {
        "id": "les-d-08", "module": "mod-d-2",
        "title": "have got / have: «иметь»",
        "gp_id": "gp-d-08", "gp_title": "have got и have",
        "rule_md": RULE_D08,
        "phrases": D08,
        "rule_cloze": [
            ("I ___ got a ticket.", ["have"]),
            ("She ___ got a phone.", ["has"]),
            ("___ you got a pen?", ["Have"]),
        ],
        "quotes": [("q-star-wars-0006", "have"), ("q-breaking-bad-0020", "need")],
        "trap_id": "trap-articles",
        "vocab_band": {"list": "ngsl-spoken", "from": 701, "to": 760},
        "phrasebook_topic": None,
        "quotes_topic": "things",
        "bebris_video": {"lesson": "2.246", "playlist_index": 797, "youtube_id": "0vQxLfCmYfI", "title": None},
        "answer_question": [("Have you got a pen?", "I have got a pen.")],
        "find_error": [("Does she has got a car?", "Has she got a car?")],
        "verb_tense": [
            ("She ___ got a dog.", "3-е лицо", ["has"]),
            ("I ___ got time.", "не иметь", ["haven't"]),
            ("___ you got a map?", "вопрос", ["Have"]),
        ],
    },
    {
        "id": "les-d-09", "module": "mod-d-2",
        "title": "Повелительное наклонение: Stop! Don't stop!",
        "gp_id": "gp-d-09", "gp_title": "Повелительное наклонение",
        "rule_md": RULE_D09,
        "phrases": D09,
        "rule_cloze": [
            ("___ the door. (открой)", ["Open"]),
            ("___ touch it.", ["Don't"]),
            ("___ left. (поворот)", ["Turn"]),
        ],
        "quotes": [("q-lord-of-the-rings-0001", "Fly"), ("q-black-mirror-0013", "Shut")],
        "trap_id": "trap-no-do-negative",
        "vocab_band": {"list": "ngsl-spoken", "from": 761, "to": 820},
        "phrasebook_topic": "directions",
        "quotes_topic": "directions",
        "bebris_video": None,
        "answer_question": [("Where is the café?", "Turn left and go straight.")],
        "find_error": [("Turn to left.", "Turn left.")],
        "verb_tense": [
            ("___ be late!", "запрет", ["Don't"]),
            ("___ me, please.", "следовать", ["Follow"]),
            ("___ up!", "поторопиться", ["Hurry"]),
        ],
    },
    {
        "id": "les-d-10", "module": "mod-d-2",
        "title": "Повторение №6: can, have got, повелительное",
        "gp_id": "gp-d-10", "gp_title": "Повторение модуля D2",
        "rule_md": RULE_D10,
        "phrases": D10,
        "rule_cloze": [
            ("___ you help me, please?", ["Can"]),
            ("I ___ got a ticket.", ["have"]),
            ("___ worry.", ["Don't"]),
        ],
        "quotes": [("q-fma-fma-b-0020", "Stop"), ("q-supernatural-0014", "hunting")],
        "trap_id": "trap-third-person-s",
        "vocab_band": {"list": "ngsl-spoken", "from": 821, "to": 880},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("Have you got a map?", "I have got a map.")],
        "find_error": [("We cans help you.", "We can help you.")],
        "verb_tense": [
            ("___ I sit here?", "разрешение", ["Can"]),
            ("He ___ got an idea.", "3-е лицо", ["has"]),
            ("___ follow the signs.", "указание", ["Follow"]),
        ],
    },
]

if __name__ == "__main__":
    # Полный ранг D: D1+D2 (этот файл) + D3/D4 + D5/D6 (модули пулов)
    ALL_D = LESSONS_D + LESSONS_D3_D4 + LESSONS_D5_D6
    build_rank(ALL_D, rank="D", stem="d", seed=20260929)
