#!/usr/bin/env python3
"""Пулы уроков D5 «В движении» (D-21…D-25) и D6 «Сборка» (D-26…D-28).

plan://M12#12.7. Импортируется build_d.py (LESSONS_D5_D6). D-27 — transform-пары
(affirmative, negative, question|None): упражнение строит цепочку трансформаций.
"""

# --------------------------------------------------------------------------
# D5 «В движении»
# --------------------------------------------------------------------------
D21 = [
    ("I usually work at home.", "Обычно я работаю дома.", None),
    ("I am working at home now.", "Сейчас я работаю дома.", None),
    ("She usually drinks tea.", "Обычно она пьёт чай.", None),
    ("She is drinking coffee now.", "Сейчас она пьёт кофе.", None),
    ("He usually walks to work.", "Обычно он ходит на работу пешком.", None),
    ("He is taking a taxi today.", "Сегодня он едет на такси.", None),
    ("We usually watch films in the evening.", "Обычно мы смотрим фильмы вечером.", None),
    ("We are watching a film now.", "Сейчас мы смотрим фильм.", None),
    ("They usually live in Moscow.", "Обычно они живут в Москве.", None),
    ("They are living in Berlin these days.", "В последнее время они живут в Берлине.", None),
    ("I always get up at seven.", "Я всегда встаю в семь.", None),
    ("Today I am getting up at nine.", "Сегодня я встаю в девять.", None),
    ("What do you usually do on Sundays?", "Что ты обычно делаешь по воскресеньям?", None),
    ("What are you doing now?", "Что ты делаешь сейчас?", None),
    ("Where do you work?", "Где ты работаешь?", None),
    ("Where are you working this month?", "Где ты работаешь в этом месяце?", None),
    ("Do you often travel?", "Ты часто путешествуешь?", None),
    ("Are you travelling now?", "Ты сейчас в поездке?", None),
    ("I don't usually eat meat.", "Я обычно не ем мясо.", None),
    ("I am not eating meat this week.", "Я не ем мясо на этой неделе.", None),
    ("The shop opens at nine.", "Магазин открывается в девять.", None),
    ("The shop is opening now.", "Магазин сейчас открывается.", None),
    ("The train leaves at six.", "Поезд отправляется в шесть.", None),
    ("Look, the train is leaving.", "Смотри, поезд отправляется.", None),
    ("Water boils at 100 degrees.", "Вода кипит при 100 градусах.", None),
    ("The water is boiling.", "Вода кипит.", None),
    ("I read every day.", "Я читаю каждый день.", None),
    ("I am reading a new book now.", "Сейчас я читаю новую книгу.", None),
    ("She teaches English.", "Она преподаёт английский.", None),
    ("She is teaching us today.", "Сегодня она ведёт у нас занятие.", None),
    ("It often rains here.", "Здесь часто идёт дождь.", None),
    ("It is raining again.", "Опять идёт дождь.", None),
    ("I'm looking for a gift.", "Я ищу подарок.", None),
    ("I usually buy gifts online.", "Обычно я покупаю подарки онлайн.", None),
    ("We are waiting for the taxi.", "Мы ждём такси.", None),
    ("We usually wait outside.", "Обычно мы ждём на улице.", None),
    ("He never wears a hat.", "Он никогда не носит шапку.", None),
    ("He is wearing a hat today.", "Сегодня он в шапке.", None),
    ("My phone works fine.", "Мой телефон работает хорошо.", None),
    ("My phone is not working.", "Мой телефон не работает.", None),
    ("This week I am very busy.", "На этой неделе я очень занят.", None),
    ("I am studying English these days.", "В последнее время я учу английский.", None),
    ("Every day is different.", "Каждый день другой.", None),
    ("Right now everything is fine.", "Прямо сейчас всё хорошо.", None),
]

D22 = [
    ("What do you do?", "Чем ты занимаешься?", None),
    ("I do my job well.", "Я хорошо делаю свою работу.", None),
    ("Do your homework.", "Делай домашнее задание.", None),
    ("I do the shopping on Saturdays.", "Я делаю покупки по субботам.", None),
    ("Can you do me a favour?", "Можешь оказать мне услугу?", None),
    ("We do business together.", "Мы ведём дела вместе.", None),
    ("He does the cooking at home.", "Дома готовит он.", None),
    ("I don't do sports.", "Я не занимаюсь спортом.", None),
    ("She does her best.", "Она старается изо всех сил.", None),
    ("What does he do for a living?", "Чем он зарабатывает на жизнь?", None),
    ("I make coffee every morning.", "Я готовлю кофе каждое утро.", None),
    ("She makes tea for us.", "Она готовит нам чай.", None),
    ("He makes a lot of money.", "Он зарабатывает много денег.", None),
    ("I made a mistake.", "Я сделал ошибку.", None),
    ("Don't make noise.", "Не шуми.", None),
    ("Let's make a plan.", "Давай составим план.", None),
    ("It makes sense.", "Это логично.", None),
    ("This machine makes bread.", "Эта машина делает хлеб.", None),
    ("I'm making dinner now.", "Я сейчас готовлю ужин.", None),
    ("She is making a call.", "Она звонит.", None),
    ("They make films.", "Они снимают фильмы.", None),
    ("Did you make a decision?", "Ты принял решение?", None),
    ("Make yourself at home.", "Чувствуй себя как дома.", None),
    ("I can make it on time.", "Я успею вовремя.", None),
    ("Do it again.", "Сделай это снова.", None),
    ("Make it cheaper, please.", "Сделайте дешевле, пожалуйста.", None),
    ("What do you do for a living?", "Чем ты зарабатываешь на жизнь?", None),
    ("I do exercises in the morning.", "Я делаю зарядку по утрам.", None),
    ("Who makes the rules here?", "Кто устанавливает здесь правила?", None),
    ("We did a good job.", "Мы хорошо поработали.", None),
    ("He did nothing all day.", "Он весь день ничего не делал.", None),
    ("She did the right thing.", "Она поступила правильно.", None),
    ("That makes me happy.", "Это делает меня счастливым.", None),
    ("Money doesn't make you happy.", "Деньги не делают тебя счастливым.", None),
    ("Do you do yoga?", "Ты занимаешься йогой?", None),
    ("I did the dishes.", "Я помыл посуду.", None),
    ("Make a list.", "Составь список.", None),
    ("I need to make a call.", "Мне нужно позвонить.", None),
    ("Do your best!", "Постарайся на максимум!", None),
    ("It doesn't make sense.", "Это не имеет смысла.", None),
    ("We made friends quickly.", "Мы быстро подружились.", None),
    ("Do it for me.", "Сделай это для меня.", None),
    ("He makes me laugh.", "Он меня смешит.", None),
    ("What does this word mean?", "Что означает это слово?", None),
]

D23 = [
    ("I go to work by bus.", "Я езжу на работу на автобусе.", None),
    ("I go home at six.", "Я иду домой в шесть.", None),
    ("She goes to the gym.", "Она ходит в спортзал.", None),
    ("We go there every summer.", "Мы ездим туда каждое лето.", None),
    ("Let's go!", "Пойдём!", None),
    ("Go away!", "Уходи!", None),
    ("How do you go to work?", "Как ты добираешься до работы?", None),
    ("I go on foot.", "Я хожу пешком.", None),
    ("Come in!", "Входи!", None),
    ("Come here, please.", "Подойди сюда, пожалуйста.", None),
    ("Can you come tomorrow?", "Ты можешь прийти завтра?", None),
    ("He comes home late.", "Он приходит домой поздно.", None),
    ("Come with me.", "Иди со мной.", None),
    ("I'm coming!", "Иду!", None),
    ("How do I get to the station?", "Как мне добраться до вокзала?", None),
    ("How do we get there?", "Как нам туда добраться?", None),
    ("I get home at seven.", "Я добираюсь домой в семь.", None),
    ("It gets dark early.", "Рано темнеет.", None),
    ("I get tired in the evening.", "Я устаю вечером.", None),
    ("Did you get my message?", "Ты получил моё сообщение?", None),
    ("I get up at seven.", "Я встаю в семь.", None),
    ("Take me to the airport, please.", "Отвезите меня в аэропорт, пожалуйста.", None),
    ("Take me to this address.", "Отвезите меня по этому адресу.", None),
    ("Stop here, please.", "Остановитесь здесь, пожалуйста.", None),
    ("How much is the ride?", "Сколько стоит поездка?", None),
    ("Is it far from here?", "Это далеко отсюда?", None),
    ("I'm going home now. Bye!", "Я иду домой. Пока!", None),
    ("She goes home by metro.", "Она ездит домой на метро.", None),
    ("We went home by taxi.", "Мы поехали домой на такси.", None),
    ("Where does this bus go?", "Куда идёт этот автобус?", None),
    ("This train goes to London.", "Этот поезд идёт в Лондон.", None),
    ("The number five bus goes to the centre.", "Пятый автобус идёт в центр.", None),
    ("Get in, please.", "Садитесь, пожалуйста.", None),
    ("Where do I get off?", "Где мне выходить?", None),
    ("Two tickets to the centre.", "Два билета до центра.", None),
    ("When is the next train?", "Когда следующий поезд?", None),
    ("The bus is coming.", "Автобус подходит.", None),
    ("I come here often.", "Я часто сюда прихожу.", None),
    ("Goodbye, see you later!", "До свидания, до встречи!", None),
    ("I'm going to the shop.", "Я иду в магазин.", None),
    ("He gets to work by bike.", "Он добирается до работы на велосипеде.", None),
    ("Don't go yet.", "Ещё не уходи.", None),
    ("We are going the wrong way.", "Мы идём не туда.", None),
    ("How long does it take?", "Сколько это занимает?", None),
]

D24 = [
    ("I would like a coffee, please.", "Я бы хотел кофе, пожалуйста.", None),
    ("I would like to order.", "Я бы хотел сделать заказ.", None),
    ("Would you like some tea?", "Не хотите чаю?", None),
    ("I'd like a ticket to London.", "Я бы хотел билет до Лондона.", None),
    ("I'd like to pay now.", "Я хотел бы оплатить сейчас.", None),
    ("Would you like anything else?", "Что-нибудь ещё?", None),
    ("No, that's all, thanks.", "Нет, это всё, спасибо.", None),
    ("Can I have the bill, please?", "Можно счёт, пожалуйста?", None),
    ("Can I pay by card?", "Можно оплатить картой?", None),
    ("Cash, please.", "Наличными, пожалуйста.", None),
    ("Can I help you?", "Чем могу помочь?", None),
    ("I'm just looking, thanks.", "Я просто смотрю, спасибо.", None),
    ("How much is it altogether?", "Сколько всё вместе?", None),
    ("I'll take two.", "Я возьму два.", None),
    ("Anything else?", "Что-нибудь ещё?", None),
    ("That's everything.", "Это всё.", None),
    ("Where is gate 5?", "Где пятый выход на посадку?", None),
    ("Where is check-in?", "Где регистрация?", None),
    ("Where is passport control?", "Где паспортный контроль?", None),
    ("Where is the departure hall?", "Где зал вылета?", None),
    ("What time is the flight?", "Во сколько рейс?", None),
    ("The flight is delayed.", "Рейс задерживается.", None),
    ("Here is my ticket.", "Вот мой билет.", None),
    ("Here is my passport.", "Вот мой паспорт.", None),
    ("Do I need a visa?", "Мне нужна виза?", None),
    ("Where is the baggage claim?", "Где выдача багажа?", None),
    ("My flight leaves at noon.", "Мой рейс вылетает в полдень.", None),
    ("First class or economy?", "Первый класс или эконом?", None),
    ("Window or aisle seat?", "У окна или у прохода?", None),
    ("I have one bag.", "У меня один чемодан.", None),
    ("Can I have a window seat?", "Можно место у окна?", None),
    ("Is this seat free?", "Это место свободно?", None),
    ("Fasten your seat belt.", "Пристегните ремень.", None),
    ("Can you repeat that, please?", "Повторите, пожалуйста.", None),
    ("Just a moment, please.", "Одну минуту, пожалуйста.", None),
    ("I would like a room for two nights.", "Я бы хотел номер на две ночи.", None),
    ("I'd like to change my ticket.", "Я хотел бы изменить билет.", None),
    ("Sorry, we are closed.", "Извините, мы закрыты.", None),
    ("We are open until nine.", "Мы открыты до девяти.", None),
    ("Can I see the menu?", "Можно посмотреть меню?", None),
    ("The same for me, please.", "Мне то же самое, пожалуйста.", None),
    ("It was delicious, thank you.", "Было вкусно, спасибо.", None),
    ("Keep the change.", "Сдачи не надо.", None),
    ("Have a nice day!", "Хорошего дня!", None),
]

D25 = [
    ("I usually work at home.", "Обычно я работаю дома.", None),
    ("I am working now.", "Сейчас я работаю.", None),
    ("What are you doing?", "Что ты делаешь?", None),
    ("What do you usually do on Sundays?", "Что ты обычно делаешь по воскресеньям?", None),
    ("She usually drinks tea.", "Обычно она пьёт чай.", None),
    ("She is drinking coffee now.", "Сейчас она пьёт кофе.", None),
    ("I make coffee every morning.", "Я готовлю кофе каждое утро.", None),
    ("I do my job well.", "Я хорошо делаю свою работу.", None),
    ("She made a mistake.", "Она сделала ошибку.", None),
    ("Do your best!", "Постарайся на максимум!", None),
    ("Can you do me a favour?", "Можешь оказать мне услугу?", None),
    ("It makes sense.", "Это логично.", None),
    ("I go to work by bus.", "Я езжу на работу на автобусе.", None),
    ("I go home at six.", "Я иду домой в шесть.", None),
    ("Come here, please.", "Подойди сюда, пожалуйста.", None),
    ("How do I get to the station?", "Как мне добраться до вокзала?", None),
    ("Take me to the station, please.", "Отвезите меня на вокзал, пожалуйста.", None),
    ("Take me to the airport, please.", "Отвезите меня в аэропорт, пожалуйста.", None),
    ("Where is the baggage claim?", "Где выдача багажа?", None),
    ("Where is check-in?", "Где регистрация?", None),
    ("I would like a coffee, please.", "Я бы хотел кофе, пожалуйста.", None),
    ("I'd like to pay now.", "Я хотел бы оплатить сейчас.", None),
    ("Can I have the bill, please?", "Можно счёт, пожалуйста?", None),
    ("Would you like anything else?", "Что-нибудь ещё?", None),
    ("No, that's all, thanks.", "Нет, это всё, спасибо.", None),
    ("Window or aisle seat?", "У окна или у прохода?", None),
    ("My flight leaves at noon.", "Мой рейс вылетает в полдень.", None),
    ("The flight is delayed.", "Рейс задерживается.", None),
    ("Here is my passport.", "Вот мой паспорт.", None),
    ("I'm looking for a gift.", "Я ищу подарок.", None),
    ("I usually buy gifts online.", "Обычно я покупаю подарки онлайн.", None),
    ("It often rains here.", "Здесь часто идёт дождь.", None),
    ("It is raining again.", "Опять идёт дождь.", None),
    ("I get up at seven.", "Я встаю в семь.", None),
    ("I get home at seven.", "Я добираюсь домой в семь.", None),
    ("The bus is coming.", "Автобус подходит.", None),
    ("When is the next train?", "Когда следующий поезд?", None),
    ("Two tickets to the centre.", "Два билета до центра.", None),
    ("How long does it take?", "Сколько это занимает?", None),
    ("Fasten your seat belt.", "Пристегните ремень.", None),
    ("I'm just looking, thanks.", "Я просто смотрю, спасибо.", None),
    ("Can I see the menu?", "Можно посмотреть меню?", None),
    ("Keep the change.", "Сдачи не надо.", None),
    ("Have a nice day!", "Хорошего дня!", None),
    ("We are going the wrong way.", "Мы идём не туда.", None),
]

# --------------------------------------------------------------------------
# D6 «Сборка»
# --------------------------------------------------------------------------
D26 = [
    ("I don't have anything.", "У меня ничего нет.", None),
    ("I have nothing.", "У меня ничего нет.", ["I don't have anything."]),
    ("I don't know anyone here.", "Я здесь никого не знаю.", None),
    ("I know no one here.", "Я здесь никого не знаю.", ["I don't know anyone here."]),
    ("She didn't say anything.", "Она ничего не сказала.", None),
    ("He never says anything.", "Он никогда ничего не говорит.", None),
    ("Nobody called me.", "Никто мне не звонил.", None),
    ("Anyone can do it.", "Любой может это сделать.", None),
    ("You can take anything you like.", "Можешь взять всё, что хочешь.", None),
    ("Ask anyone in the street.", "Спроси любого на улице.", None),
    ("I can't see anything.", "Я ничего не вижу.", None),
    ("I can see nothing.", "Я ничего не вижу.", ["I can't see anything."]),
    ("There isn't anything in the box.", "В коробке ничего нет.", None),
    ("There is nothing in the box.", "В коробке ничего нет.", ["There isn't anything in the box."]),
    ("I don't want anything.", "Я ничего не хочу.", None),
    ("I want nothing.", "Я ничего не хочу.", ["I don't want anything."]),
    ("Nothing matters.", "Ничего не имеет значения.", None),
    ("Everything matters.", "Всё имеет значение.", None),
    ("Something is better than nothing.", "Что-то лучше, чем ничего.", None),
    ("I don't eat anything sweet.", "Я не ем ничего сладкого.", None),
    ("We don't have any cash.", "У нас нет наличных.", None),
    ("Do you have any cash?", "У вас есть наличные?", None),
    ("Can I pay in cash?", "Можно заплатить наличными?", None),
    ("I don't need any help.", "Мне не нужна никакая помощь.", None),
    ("I need no help.", "Мне не нужна никакая помощь.", ["I don't need any help."]),
    ("Don't tell anyone.", "Никому не говори.", None),
    ("I didn't tell anybody.", "Я никому не сказал.", None),
    ("Nobody knows the way.", "Никто не знает дорогу.", None),
    ("Anybody home?", "Есть кто дома?", None),
    ("I never drink anything strong.", "Я никогда не пью ничего крепкого.", None),
    ("He doesn't watch anything on TV.", "Он ничего не смотрит по телевизору.", None),
    ("I can't believe anything he says.", "Я не верю ничему, что он говорит.", None),
    ("Nothing is impossible.", "Нет ничего невозможного.", None),
    ("I don't see anyone.", "Я никого не вижу.", None),
    ("I see no one.", "Я никого не вижу.", ["I don't see anyone."]),
    ("We didn't buy anything.", "Мы ничего не купили.", None),
    ("I'm not going anywhere.", "Я никуда не иду.", None),
    ("I'm going nowhere.", "Я никуда не иду.", ["I'm not going anywhere."]),
    ("It didn't change anything.", "Это ничего не изменило.", None),
    ("Don't worry about anything.", "Ни о чём не волнуйся.", None),
    ("I never say never.", "Я никогда не говорю «никогда».", None),
    ("Not now.", "Не сейчас.", None),
    ("Not at all.", "Вовсе нет.", None),
    ("I don't mind at all.", "Я совершенно не против.", None),
]

# D-27: фразы-этапы трансформаций (каждая строка — отдельная фраза урока);
# TRANSFORM_CHAINS ниже связывает их в цепочки утверждение → отрицание → вопрос
D27 = [
    ("I know him.", "Я знаю его.", None),
    ("I don't know him.", "Я его не знаю.", None),
    ("Do you know him?", "Ты его знаешь?", None),
    ("She is at home.", "Она дома.", None),
    ("She is not at home.", "Её нет дома.", None),
    ("Is she at home?", "Она дома?", None),
    ("There is a bank here.", "Здесь есть банк.", None),
    ("There isn't a bank here.", "Здесь нет банка.", None),
    ("Is there a bank here?", "Здесь есть банк?", None),
    ("He has got a car.", "У него есть машина.", None),
    ("He hasn't got a car.", "У него нет машины.", None),
    ("Has he got a car?", "У него есть машина?", None),
    ("She is working now.", "Она сейчас работает.", None),
    ("She is not working now.", "Она сейчас не работает.", None),
    ("Is she working now?", "Она сейчас работает?", None),
    ("They are friends.", "Они друзья.", None),
    ("They are not friends.", "Они не друзья.", None),
    ("Are they friends?", "Они друзья?", None),
    ("He likes tea.", "Ему нравится чай.", None),
    ("He doesn't like tea.", "Ему не нравится чай.", None),
    ("Does he like tea?", "Ему нравится чай?", None),
    ("There are some shops here.", "Здесь есть несколько магазинов.", None),
    ("There aren't any shops here.", "Здесь нет магазинов.", ["There are no shops here."]),
    ("Are there any shops here?", "Здесь есть магазины?", None),
    ("I have some money.", "У меня есть немного денег.", None),
    ("I don't have any money.", "У меня нет денег.", ["I have no money."]),
    ("She is looking for a job.", "Она ищет работу.", None),
    ("She is not looking for a job.", "Она не ищет работу.", None),
    ("Is she looking for a job?", "Она ищет работу?", None),
    ("He tells the truth.", "Он говорит правду.", None),
    ("He doesn't tell the truth.", "Он не говорит правды.", None),
    ("Does he tell the truth?", "Он говорит правду?", None),
    ("Open the door.", "Открой дверь.", None),
    ("Don't open the door.", "Не открывай дверь.", None),
    ("It is a beautiful city.", "Это красивый город.", None),
    ("It is not a beautiful city.", "Это некрасивый город.", None),
    ("Is it a beautiful city?", "Это красивый город?", None),
    ("I feel good.", "Я хорошо себя чувствую.", None),
    ("I don't feel good.", "Я плохо себя чувствую.", None),
    ("We can help you.", "Мы можем тебе помочь.", None),
    ("We can't help you.", "Мы не можем тебе помочь.", None),
    ("Can we help you?", "Мы можем вам помочь?", None),
    ("She knows the answer.", "Она знает ответ.", None),
    ("She doesn't know the answer.", "Она не знает ответа.", None),
    ("Does she know the answer?", "Она знает ответ?", None),
    ("I am ready.", "Я готов.", None),
    ("I am not ready.", "Я не готов.", None),
    ("Am I ready?", "Я готов?", None),
]

D28 = [
    ("I know him.", "Я знаю его.", None),
    ("I don't know him.", "Я его не знаю.", None),
    ("There is a bank here.", "Здесь есть банк.", None),
    ("There isn't a bank here.", "Здесь нет банка.", None),
    ("He has got a car.", "У него есть машина.", None),
    ("Has he got a car?", "У него есть машина?", None),
    ("She is working now.", "Она сейчас работает.", None),
    ("Is she working now?", "Она сейчас работает?", None),
    ("He likes tea.", "Ему нравится чай.", None),
    ("Does he like tea?", "Ему нравится чай?", None),
    ("I have some money.", "У меня есть немного денег.", None),
    ("I don't have any money.", "У меня нет денег.", ["I have no money."]),
    ("How much is this?", "Сколько это стоит?", None),
    ("How much does it cost?", "Сколько это стоит?", None),
    ("How many people are there?", "Сколько там людей?", None),
    ("I need advice.", "Мне нужен совет.", None),
    ("We need more information.", "Нам нужно больше информации.", None),
    ("She is so kind.", "Она такая добрая.", None),
    ("It is such a beautiful city.", "Это такой красивый город.", None),
    ("Who knows the answer?", "Кто знает ответ?", None),
    ("What makes you happy?", "Что делает тебя счастливым?", None),
    ("I agree with you.", "Я с тобой согласен.", None),
    ("I don't agree.", "Я не согласен.", None),
    ("Tell me the truth.", "Скажи мне правду.", None),
    ("He told me everything.", "Он рассказал мне всё.", None),
    ("Say it in English.", "Скажи это по-английски.", None),
    ("I don't feel well.", "Мне нездоровится.", None),
    ("I'm waiting for you.", "Я жду тебя.", None),
    ("He is looking for a job.", "Он ищет работу.", None),
    ("I usually work at home.", "Обычно я работаю дома.", None),
    ("I am working now.", "Сейчас я работаю.", None),
    ("She makes tea for us.", "Она готовит нам чай.", None),
    ("I do my job well.", "Я хорошо делаю свою работу.", None),
    ("I go home at six.", "Я иду домой в шесть.", None),
    ("Take me to the airport, please.", "Отвезите меня в аэропорт, пожалуйста.", None),
    ("I would like a coffee, please.", "Я бы хотел кофе, пожалуйста.", None),
    ("Can I pay by card?", "Можно оплатить картой?", None),
    ("Where is check-in?", "Где регистрация?", None),
    ("I don't have any cash.", "У меня нет наличных.", None),
    ("I have nothing.", "У меня ничего нет.", None),
    ("Nobody knows the way.", "Никто не знает дорогу.", None),
    ("Can you do me a favour?", "Можешь оказать мне услугу?", None),
    ("What do you usually do on Sundays?", "Что ты обычно делаешь по воскресеньям?", None),
    ("I can't see anything.", "Я ничего не вижу.", None),
    ("Have a nice day!", "Хорошего дня!", None),
]

RULE_D21 = """**Present Simple vs Present Continuous.**
Обычно/всегда/никогда (habit) — Present Simple: I **usually work** at home.
Сейчас/сегодня/в последнее время (process) — Present Continuous:
I **am working** at home **now**. **These days** I **am living** in Berlin.
Сравни: What **do** you **usually do**? vs What **are** you **doing** now?"""

RULE_D22 = """**do / make.**
do — работа, обязанности, действия вообще: **do** your job, **do** homework,
**do** the shopping, **do** a favour, **do** your best.
make — создание результата: **make** coffee, **make** money, **make** a mistake,
**make** a plan, **make** a call, **make** sense.
⚠️ Русское «делать» — не ориентир: think English!"""

RULE_D23 = """**Глаголы движения: go, come, get.**
**go** — туда (от говорящего): I **go** to work. **go home** — БЕЗ to!
**come** — сюда (к говорящему): **Come** here! He **comes** home late.
**get** — добираться/становиться: **get** to the station, **get** home,
**get** tired, **get** up.
Транспорт: by bus / by metro / by bike / on foot / take a taxi."""

RULE_D24 = """**Заказ и оплата: would like + can.**
Вежливый заказ: I **would like** a coffee. = I'**d like** a coffee.
**Would you like**…? — предложение: Would you like some tea?
Оплата: Can I **pay by** card? / **in** cash. **Cash or card?**
Ответ на «Anything else?»: No, **that's all**, thanks."""

RULE_D25 = """**Повторение №9: движение, заказ, do/make.**
PS vs PC: обычно vs сейчас. do/make по смыслу.
go home (без to!), come here, get to the station.
I'd like… / Can I pay by card? / that's all, thanks."""

RULE_D26 = """**Двойное отрицание: anything / anyone.**
В английском ОДНО отрицание в предложении: I **don't** have **anything**.
= I have **nothing**. ❌ I don't have nothing.
anyone/anybody — о людях: I don't know **anyone** here. = I know **no one**.
never/nowhere — тоже отрицания: I **never** say never."""

RULE_D27 = """**Трансформации: ± и ?.**
Утверждение → отрицание: I know him. → I **don't** know him.
Отрицание → вопрос: **Do** you know him? (do приезжает, know без -s)
there is → Is there…? / has got → Has he got…? / can → Can we…?
some → **any** в отрицаниях и вопросах: some money → **any** money."""

RULE_D28 = """**Большое повторение перед Вратами C.**
Всё ранга D: there is/are, can, have got, some/any/no, much/many,
неисчисляемые, so/such, вопросы к подлежащему, say/tell/ask,
feel + предлоги, PS vs PC, do/make, движение, would like,
двойное отрицание, трансформации ±?.
Вперёд, Охотник — Врата C ждут."""

LESSONS_D5_D6 = [
    {
        "id": "les-d-21", "module": "mod-d-5",
        "title": "Present Simple vs Present Continuous",
        "gp_id": "gp-d-21", "gp_title": "Привычка против процесса",
        "rule_md": RULE_D21,
        "phrases": D21,
        "rule_cloze": [
            ("I usually ___ at home.", ["work"]),
            ("I ___ working at home now.", ["am"]),
            ("Look! The train ___ leaving.", ["is"]),
        ],
        "quotes": [("q-stranger-things-0007", "doing"), ("q-supernatural-0010", "working")],
        "trap_id": "trap-third-person-s",
        "vocab_band": {"list": "ngsl-spoken", "from": 1481, "to": 1540},
        "phrasebook_topic": "shop",
        "quotes_topic": "now",
        "bebris_video": None,
        "answer_question": [("What are you doing now?", "I am working now.")],
        "find_error": [("I am usually working at home.", "I usually work at home.")],
        "verb_tense": [
            ("She usually ___ tea.", "обычно", ["drinks"]),
            ("She is ___ coffee now.", "сейчас", ["drinking"]),
            ("It often ___ here.", "обычно", ["rains"]),
        ],
    },
    {
        "id": "les-d-22", "module": "mod-d-5",
        "title": "do / make",
        "gp_id": "gp-d-22", "gp_title": "do и make",
        "rule_md": RULE_D22,
        "phrases": D22,
        "rule_cloze": [
            ("___ your homework.", ["Do"]),
            ("She ___ tea for us.", ["makes"]),
            ("Can you ___ me a favour?", ["do"]),
        ],
        "quotes": [("q-game-of-thrones-0017", "do"), ("q-breaking-bad-0021", "business")],
        "trap_id": "trap-do-make",
        "vocab_band": {"list": "ngsl-spoken", "from": 1541, "to": 1600},
        "phrasebook_topic": "shop",
        "quotes_topic": "work",
        "bebris_video": None,
        "answer_question": [("What do you do?", "I do my job well.")],
        "find_error": [("She makes her homework every day.", "Do your homework.")],
        "verb_tense": [
            ("He ___ a lot of money.", "зарабатывать", ["makes"]),
            ("We did a good ___.", "работа", ["job"]),
            ("It doesn't ___ sense.", "иметь смысл", ["make"]),
        ],
    },
    {
        "id": "les-d-23", "module": "mod-d-5",
        "title": "go, come, get; go home",
        "gp_id": "gp-d-23", "gp_title": "Глаголы движения",
        "rule_md": RULE_D23,
        "phrases": D23,
        "rule_cloze": [
            ("I go ___ at six.", ["home"]),
            ("___ here, please.", ["Come"]),
            ("How do I ___ to the station?", ["get"]),
        ],
        "quotes": [("q-the-100-0009", "go"), ("q-the-100-0002", "meet")],
        "trap_id": "trap-to-home",
        "vocab_band": {"list": "ngsl-spoken", "from": 1601, "to": 1660},
        "phrasebook_topic": "taxi",
        "quotes_topic": "transport",
        "bebris_video": None,
        "answer_question": [("How do I get to the station?", "Take me to the station, please.")],
        "find_error": [("I go to home at six.", "I go home at six.")],
        "verb_tense": [
            ("I go ___ at six.", "домой (без to!)", ["home"]),
            ("She ___ to the gym.", "ходить (3 л.)", ["goes"]),
            ("Can you ___ tomorrow?", "прийти", ["come"]),
        ],
    },
    {
        "id": "les-d-24", "module": "mod-d-5",
        "title": "Заказ и оплата: would like + can",
        "gp_id": "gp-d-24", "gp_title": "would like, вежливый заказ",
        "rule_md": RULE_D24,
        "phrases": D24,
        "rule_cloze": [
            ("I ___ like a coffee, please.", ["would"]),
            ("___ you like some tea?", ["Would"]),
            ("Can I pay ___ card?", ["by"]),
        ],
        "quotes": [("q-star-wars-0001", "May"), ("q-attack-on-titan-0001", "Give")],
        "trap_id": "trap-articles",
        "vocab_band": {"list": "ngsl-spoken", "from": 1661, "to": 1720},
        "phrasebook_topic": "airport",
        "quotes_topic": "travel",
        "bebris_video": None,
        "answer_question": [("Would you like anything else?", "No, that's all, thanks.")],
        "find_error": [("I would like coffee, please.", "I would like a coffee, please.")],
        "verb_tense": [
            ("I'd ___ to pay now.", "хотеть (вежл.)", ["like"]),
            ("Can I pay ___ cash?", "наличными", ["in"]),
            ("Where is ___ 5?", "выход на посадку", ["gate"]),
        ],
    },
    {
        "id": "les-d-25", "module": "mod-d-5",
        "title": "Повторение №9: движение и заказ",
        "gp_id": "gp-d-25", "gp_title": "Повторение модуля D5",
        "rule_md": RULE_D25,
        "phrases": D25,
        "rule_cloze": [
            ("I ___ working now.", ["am"]),
            ("I go ___ at six.", ["home"]),
            ("I ___ like a coffee, please.", ["would"]),
        ],
        "quotes": [("q-lord-of-the-rings-0016", "rule"), ("q-solo-leveling-0014", "stronger")],
        "trap_id": "trap-do-make",
        "vocab_band": {"list": "ngsl-spoken", "from": 1721, "to": 1780},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("Are you ready to order?", "I would like to order.")],
        "find_error": [("I am usually working at home.", "I usually work at home.")],
        "verb_tense": [
            ("She ___ tea for us.", "готовить", ["makes"]),
            ("I do my ___ well.", "работа", ["job"]),
            ("When is the ___ train?", "следующий", ["next"]),
        ],
    },
    {
        "id": "les-d-26", "module": "mod-d-6",
        "title": "Двойное отрицание: anything / anyone",
        "gp_id": "gp-d-26", "gp_title": "Одно отрицание в предложении",
        "rule_md": RULE_D26,
        "phrases": D26,
        "rule_cloze": [
            ("I don't have ___.", ["anything"]),
            ("I know ___ here.", ["no one"]),
            ("___ called me.", ["Nobody"]),
        ],
        "quotes": [("q-black-mirror-0008", "can't"), ("q-supernatural-0013", "never")],
        "trap_id": "trap-double-negative",
        "vocab_band": {"list": "ngsl-spoken", "from": 1781, "to": 1840},
        "phrasebook_topic": "shop",
        "quotes_topic": "negation",
        "bebris_video": None,
        "answer_question": [("Do you have any cash?", "I don't have any cash.")],
        "find_error": [("I don't have nothing.", "I don't have anything.")],
        "verb_tense": [
            ("I can't see ___.", "ничего", ["anything"]),
            ("I see ___. (= not anything)", "ничего", ["nothing"]),
            ("Don't tell ___.", "никому", ["anyone", "anybody"]),
        ],
    },
    {
        "id": "les-d-27", "module": "mod-d-6",
        "title": "Трансформации: + → − → ?",
        "gp_id": "gp-d-27", "gp_title": "Трансформации предложений",
        "rule_md": RULE_D27,
        "phrases": D27,
        "rule_cloze": [
            ("I ___ know him.", ["don't"]),
            ("___ you know him?", ["Do"]),
            ("Is ___ a bank here?", ["there"]),
        ],
        "quotes": [("q-lord-of-the-rings-0007", "not"), ("q-lord-of-the-rings-0010", "no")],
        "trap_id": "trap-no-do-negative",
        "vocab_band": {"list": "ngsl-spoken", "from": 1841, "to": 1900},
        "phrasebook_topic": None,
        "quotes_topic": "transform",
        "bebris_video": {"lesson": "1.17", "playlist_index": 38, "youtube_id": "_z9rz35ks2A", "title": None},
        "answer_question": [("Is she working now?", "She is working now.")],
        "find_error": [("I not know him.", "I don't know him.")],
        "verb_tense": [
            ("He ___ like tea.", "отрицание", ["doesn't"]),
            ("___ he like tea?", "вопрос", ["Does"]),
            ("There ___ any shops here.", "отрицание", ["aren't"]),
        ],
        "transform": [
            ("I know him.", "I don't know him.", "Do you know him?"),
            ("She is at home.", "She is not at home.", "Is she at home?"),
            ("There is a bank here.", "There isn't a bank here.", "Is there a bank here?"),
            ("He has got a car.", "He hasn't got a car.", "Has he got a car?"),
            ("She is working now.", "She is not working now.", "Is she working now?"),
            ("They are friends.", "They are not friends.", "Are they friends?"),
            ("He likes tea.", "He doesn't like tea.", "Does he like tea?"),
            ("There are some shops here.", "There aren't any shops here.", "Are there any shops here?"),
            ("She is looking for a job.", "She is not looking for a job.", "Is she looking for a job?"),
            ("He tells the truth.", "He doesn't tell the truth.", "Does he tell the truth?"),
            ("Open the door.", "Don't open the door.", None),
            ("I have some money.", "I don't have any money.", None),
            ("It is a beautiful city.", "It is not a beautiful city.", "Is it a beautiful city?"),
            ("I feel good.", "I don't feel good.", None),
            ("We can help you.", "We can't help you.", "Can we help you?"),
        ],
    },
    {
        "id": "les-d-28", "module": "mod-d-6",
        "title": "Большое повторение перед Вратами C",
        "gp_id": "gp-d-28", "gp_title": "Сборка всего ранга D",
        "rule_md": RULE_D28,
        "phrases": D28,
        "rule_cloze": [
            ("There ___ a bank here.", ["is"]),
            ("He has got a car. → ___. (вопрос)", ["Has he got a car?"]),
            ("I don't have ___ money.", ["any"]),
        ],
        "quotes": [("q-star-wars-0009", "fail"), ("q-solo-leveling-0011", "weakest")],
        "trap_id": "trap-comma-that",
        "vocab_band": {"list": "ngsl-spoken", "from": 1901, "to": 1960},
        "phrasebook_topic": "airport",
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("Would you like to pay now?", "I'd like to pay now.")],
        "find_error": [("I don't have nothing.", "I don't have anything.")],
        "verb_tense": [
            ("I ___ him.", "знать (отриц.)", ["don't know"]),
            ("___ she know the answer?", "вопрос", ["Does"]),
            ("Who ___ the answer?", "кто знает", ["knows"]),
        ],
        "transform": [
            ("She knows the answer.", "She doesn't know the answer.", "Does she know the answer?"),
            ("I am ready.", "I am not ready.", "Am I ready?"),
        ],
    },
]
