#!/usr/bin/env python3
"""Пулы уроков B3 «Связные фразы» (B-15…B-19), B4 «Чужая речь» (B-20…B-24)
и B5 «Свободный разговор» (B-25…B-30) — план M15#15.4. specs/01 §8.
"""

B15 = [
    ("The man who lives here is a doctor.", "Мужчина, который живёт здесь, — врач.", None),
    ("The woman who called you is my sister.", "Женщина, которая тебе звонила, — моя сестра.", None),
    ("The book that I read was great.", "Книга, которую я прочитал, была отличной.", None),
    ("The film that we watched was boring.", "Фильм, который мы смотрели, был скучным.", None),
    ("This is the house that I told you about.", "Это дом, о котором я тебе говорил.", None),
    ("The people who work here are friendly.", "Люди, которые здесь работают, дружелюбные.", None),
    ("He is the one who knocks.", "Это тот, кто стучит.", None),
    ("She is the person who helped me.", "Она человек, который мне помог.", None),
    ("The bus that goes to the centre is number five.", "Автобус, который идёт в центр, — пятый.", None),
    ("The café which is near the station is good.", "Кафе, которое возле вокзала, хорошее.", None),
    ("The hotel that we stayed at was small.", "Отель, в котором мы остановились, был маленьким.", None),
    ("The friend who came yesterday is from Spain.", "Друг, который пришёл вчера, из Испании.", None),
    ("This is the place where we first met.", "Это место, где мы впервые встретились.", None),
    ("That is the reason why I called.", "Вот причина, почему я позвонил.", None),
    ("This is the town where I was born.", "Это город, где я родился.", None),
    ("Do you know the man who is standing there?", "Ты знаешь мужчину, который там стоит?", None),
    ("I know a café that serves great coffee.", "Я знаю кафе, где подают отличный кофе.", None),
    ("She has a friend who speaks Japanese.", "У неё есть друг, который говорит по-японски.", None),
    ("We visited the church that was built in the 12th century.", "Мы посетили церковь, построенную в XII веке.", None),
    ("The train that leaves at six is usually empty.", "Поезд, отправляющийся в шесть, обычно пустой.", None),
    ("The phone that I bought last week doesn't work.", "Телефон, который я купил на прошлой неделе, не работает.", None),
    ("The food that she cooked was delicious.", "Еда, которую она приготовила, была очень вкусной.", None),
    ("That's all I know.", "Это всё, что я знаю.", None),
    ("That's everything I wanted to say.", "Это всё, что я хотел сказать.", None),
    ("Anyone who wants to come is welcome.", "Любой, кто хочет прийти, — добро пожаловать.", None),
    ("Nothing that I do is right.", "Ничто из того, что я делаю, неправильно.", None),
    ("Everything that happens has a reason.", "Всё, что происходит, имеет причину.", None),
    ("The ones who stay are the strongest.", "Те, кто остаются, — сильнейшие.", None),
    ("People who live in glass houses shouldn't throw stones.", "Люди, живущие в стеклянных домах, не должны бросать камни.", None),
    ("A friend who helps you in need is a friend indeed.", "Друг, который помогает в беде, — настоящий друг.", None),
    ("The road that leads home.", "Дорога, которая ведёт домой.", None),
    ("The person who told you that was wrong.", "Человек, который тебе это сказал, ошибался.", None),
    ("I like the photos that you took.", "Мне понравились фото, которые ты сделал.", None),
    ("The music that they play is too loud.", "Музыка, которую они включают, слишком громкая.", None),
    ("The story that he told was funny.", "История, которую он рассказал, была смешной.", None),
    ("This is the best film that I have ever seen.", "Это лучший фильм, который я когда-либо видел.", None),
    ("The only thing that matters is love.", "Единственное, что важно, — это любовь.", None),
    ("The moment when everything changed.", "Момент, когда всё изменилось.", None),
    ("The day when we met.", "День, когда мы встретились.", None),
    ("The city that never sleeps.", "Город, который никогда не спит.", None),
    ("The one who laughs last laughs best.", "Хорошо смеётся тот, кто смеётся последним.", None),
    ("I need someone who understands me.", "Мне нужен кто-то, кто меня понимает.", None),
    ("This is the man I was telling you about.", "Это тот человек, о котором я тебе рассказывал.", None),
    ("The car that is parked outside is mine.", "Машина, припаркованная снаружи, — моя.", None),
    ("I know him.", "Я его знаю.", None),
    ("She called me.", "Она позвонила мне.", None),
    ("We met them.", "Мы встретили их.", None),
    ("He helped us.", "Он нам помог.", None),
    ("They found it.", "Они нашли это.", None),
    ("I saw her.", "Я её видел.", None),
    ("She knows them.", "Она их знает.", None),
    ("We like it.", "Нам это нравится.", None),
]

B16 = [
    ("I enjoy reading.", "Я с удовольствием читаю.", None),
    ("She enjoys cooking.", "Она с удовольствием готовит.", None),
    ("He enjoys travelling.", "Он с удовольствием путешествует.", None),
    ("We enjoy watching films.", "Мы с удовольствием смотрим фильмы.", None),
    ("They enjoy swimming.", "Они с удовольствием плавают.", None),
    ("I finished reading the book.", "Я закончил читать книгу.", None),
    ("She finished cleaning the room.", "Она закончила убирать комнату.", None),
    ("He finished working at six.", "Он закончил работать в шесть.", None),
    ("Stop talking!", "Хватит разговаривать!", None),
    ("Stop worrying.", "Хватит волноваться.", None),
    ("Stop complaining.", "Хватит жаловаться.", None),
    ("I stopped smoking last year.", "Я бросил курить в прошлом году.", None),
    ("Don't stop trying.", "Не переставай пытаться.", None),
    ("I want to go home.", "Я хочу пойти домой.", None),
    ("She wants to stay.", "Она хочет остаться.", None),
    ("He wants to help.", "Он хочет помочь.", None),
    ("We want to travel.", "Мы хотим путешествовать.", None),
    ("They want to win.", "Они хотят выиграть.", None),
    ("I need to rest.", "Мне нужно отдохнуть.", None),
    ("She needs to study.", "Ей нужно учиться.", None),
    ("I decided to leave.", "Я решил уйти.", None),
    ("We decided to stay.", "Мы решили остаться.", None),
    ("He decided to change his job.", "Он решил сменить работу.", None),
    ("She decided to travel.", "Она решила путешествовать.", None),
    ("I hope to see you soon.", "Надеюсь скоро тебя увидеть.", None),
    ("We hope to visit Rome.", "Надеемся посетить Рим.", None),
    ("I promise to be careful.", "Обещаю быть осторожным.", None),
    ("I plan to start next week.", "Планирую начать на следующей неделе.", None),
    ("I'd like to book a table.", "Я хотел бы забронировать столик.", None),
    ("I'd love to visit Japan.", "Я бы с удовольствием посетил Японию.", None),
    ("I agree to help.", "Я согласен помочь.", None),
    ("I offer to drive.", "Я предлагаю повести машину.", None),
    ("I refuse to answer.", "Я отказываюсь отвечать.", None),
    ("I learned to swim.", "Я научился плавать.", None),
    ("She taught me to cook.", "Она научила меня готовить.", None),
    ("It's difficult to understand.", "Трудно понять.", None),
    ("It's easy to learn the basics.", "Легко выучить основы.", None),
    ("It's important to be honest.", "Важно быть честным.", None),
    ("It's too late to change.", "Слишком поздно менять.", None),
    ("It's nice to see you.", "Рад тебя видеть.", None),
    ("It's hard to say goodbye.", "Трудно прощаться.", None),
    ("It's dangerous to swim here.", "Опасно здесь плавать.", None),
    ("It's time to go.", "Пора идти.", None),
    ("It's never too late to learn.", "Учиться никогда не поздно.", None),
]

B17 = [
    ("We check in online.", "Мы регистрируемся онлайн.", None),
    ("Check in at the desk.", "Зарегистрируйтесь на стойке.", None),
    ("What time do we check in?", "Во сколько мы регистрируемся?", None),
    ("Check out is at noon.", "Выезд в полдень.", None),
    ("We checked out early.", "Мы выехали рано.", None),
    ("What time do we check out?", "Во сколько мы выезжаем?", None),
    ("The plane takes off at six.", "Самолёт взлетает в шесть.", None),
    ("The plane took off on time.", "Самолёт взлетел вовремя.", None),
    ("We took off late.", "Мы взлетели с опозданием.", None),
    ("Get on the bus.", "Садись на автобус.", None),
    ("We got on the wrong train.", "Мы сели не на тот поезд.", None),
    ("Where do I get on?", "Где мне сесть?", None),
    ("Get off at the next stop.", "Выйди на следующей остановке.", None),
    ("We got off at the wrong station.", "Мы вышли не на той станции.", None),
    ("Where do I get off for the museum?", "Где мне выйти к музею?", None),
    ("We set off early in the morning.", "Мы выехали рано утром.", None),
    ("They set off at dawn.", "Они отправились на рассвете.", None),
    ("Let's set off before the traffic.", "Давайте выедем до пробок.", None),
    ("The plane is taking off.", "Самолёт взлетает.", None),
    ("Please fasten your seatbelt for take-off.", "Пристегните ремни на взлёте.", None),
    ("We landed safely.", "Мы благополучно приземлились.", None),
    ("The flight was smooth.", "Полёт прошёл спокойно.", None),
    ("Turn on the light.", "Включи свет.", None),
    ("Turn off the phone.", "Выключи телефон.", None),
    ("Turn up the volume.", "Сделай громче.", None),
    ("Turn down the music.", "Сделай музыку тише.", None),
    ("He turned up late.", "Он появился с опозданием.", None),
    ("She turned down the offer.", "Она отклонила предложение.", None),
    ("Check in your luggage.", "Сдайте багаж.", None),
    ("I checked in my suitcase.", "Я сдал чемодан.", None),
    ("We set off on our journey.", "Мы отправились в путь.", None),
    ("It's time to set off.", "Пора отправляться.", None),
    ("Get in the car.", "Садись в машину.", None),
    ("Get out of the taxi.", "Выходи из такси.", None),
    ("He got in and drove away.", "Он сел в машину и уехал.", None),
    ("We got out at the hotel.", "Мы вышли у отеля.", None),
    ("Take off your shoes.", "Сними обувь.", None),
    ("Put on your jacket.", "Надень куртку.", None),
    ("The plane will take off soon.", "Самолёт скоро взлетит.", None),
    ("We are checking out tomorrow.", "Мы выезжаем завтра.", None),
    ("I need to check in for my flight.", "Мне нужно зарегистрироваться на рейс.", None),
    ("Don't forget to check out.", "Не забудь выехать.", None),
    ("The journey begins.", "Путешествие начинается.", None),
    ("Bon voyage!", "Счастливого пути!", None),
    ("I enjoy reading books.", "Я с удовольствием читаю книги.", None),
    ("He asked where I lived.", "Он спросил, где я живу.", None),
    ("I saw it yesterday.", "Я видел это вчера.", None),
    ("I finish my work.", "Я заканчиваю работу.", None),
    ("I finished my work.", "Я закончил работу.", None),
    ("She goes home.", "Она идёт домой.", None),
    ("She went home.", "Она пошла домой.", None),
    ("They build a house.", "Они строят дом.", None),
    ("They built a house.", "Они построили дом.", None),
    ("It is quite good.", "Это довольно хорошо.", ["It's quite good."]),
    ("I enjoy reading books.", "Я с удовольствием читаю книги.", None),
    ("It's cold, isn't it?", "Холодно, не так ли?", None),
    ("Yes, it is.", "Да.", None),
    ("He asked where I lived.", "Он спросил, где я живу.", None),
    ("It's good enough.", "Это достаточно хорошо.", None),
    ("I saw it yesterday.", "Я видел это вчера.", None),
    ("I finish my work.", "Я заканчиваю работу.", None),
    ("I finished my work.", "Я закончил работу.", None),
    ("She goes home.", "Она идёт домой.", None),
    ("She went home.", "Она пошла домой.", None),
    ("They build a house.", "Они строят дом.", None),
    ("They built a house.", "Они построили дом.", None),
]

B18 = [
    ("I'll look it up.", "Я это посмотрю.", None),
    ("Look up the word in the dictionary.", "Посмотри слово в словаре.", None),
    ("You can look it up online.", "Можешь посмотреть это онлайн.", None),
    ("I found out the truth.", "Я узнал правду.", None),
    ("She found out about the party.", "Она узнала о вечеринке.", None),
    ("How did you find out?", "Откуда ты узнал?", None),
    ("I'll find out and tell you.", "Я узнаю и скажу тебе.", None),
    ("It turned out to be true.", "Это оказалось правдой.", None),
    ("It turned out he was right.", "Оказалось, он был прав.", None),
    ("Everything turned out well.", "Всё закончилось хорошо.", None),
    ("The party turned out to be fun.", "Вечеринка оказалась весёлой.", None),
    ("Don't give up!", "Не сдавайся!", None),
    ("He gave up smoking.", "Он бросил курить.", None),
    ("She gave up trying.", "Она перестала пытаться.", None),
    ("Never give up on your dreams.", "Никогда не отказывайся от мечты.", None),
    ("I gave up on the idea.", "Я отказался от этой идеи.", None),
    ("We ran out of money.", "У нас кончились деньги.", None),
    ("We ran out of time.", "У нас кончилось время.", None),
    ("I ran out of patience.", "У меня кончилось терпение.", None),
    ("The milk ran out.", "Молоко закончилось.", None),
    ("I'm looking forward to the trip.", "Я с нетерпением жду поездки.", None),
    ("I'm looking forward to seeing you.", "Жду встречи с тобой.", None),
    ("We look forward to your visit.", "Ждём вашего визита.", None),
    ("I can't wait!", "Не могу дождаться!", None),
    ("I get along with my colleagues.", "Я хорошо ладлю с коллегами.", None),
    ("Do you get along with your neighbours?", "Ты хорошо ладишь с соседями?", None),
    ("They don't get along.", "Они не ладят.", None),
    ("We get along well.", "Мы хорошо ладим.", None),
    ("I work out at the gym.", "Я тренируюсь в зале.", None),
    ("It worked out fine.", "Всё сложилось хорошо.", None),
    ("Things will work out.", "Всё наладится.", None),
    ("I need to figure it out.", "Мне нужно это понять.", None),
    ("I can't figure it out.", "Не могу понять.", None),
    ("She figured out the answer.", "Она поняла ответ.", None),
    ("I'm tired. — Cheer up!", "Я устал. — Не унывай!", None),
    ("Calm down!", "Успокойся!", None),
    ("Slow down!", "Помедленнее!", None),
    ("Hold on a second.", "Подожди секунду.", None),
    ("Hang on, I'm coming.", "Подожди, я иду.", None),
    ("Come on, you can do it!", "Давай, ты сможешь!", None),
    ("Go on, tell me more.", "Продолжай, расскажи ещё.", None),
    ("Carry on with your work.", "Продолжай работать.", None),
    ("Keep going!", "Продолжай!", None),
    ("Saving people, hunting things. The family business.", "Спасать людей, охотиться на нечисть. Семейный бизнес.", None),
]

B19 = [
    ("The man who lives here is a doctor.", "Мужчина, который живёт здесь, — врач.", None),
    ("I enjoy reading.", "Я с удовольствием читаю.", None),
    ("I want to go home.", "Я хочу пойти домой.", None),
    ("It's important to be honest.", "Важно быть честным.", None),
    ("We check in online.", "Мы регистрируемся онлайн.", None),
    ("The plane takes off at six.", "Самолёт взлетает в шесть.", None),
    ("Get on the bus.", "Садись на автобус.", None),
    ("We set off early.", "Мы выехали рано.", None),
    ("I'll look it up.", "Я это посмотрю.", None),
    ("I found out the truth.", "Я узнал правду.", None),
    ("It turned out to be true.", "Это оказалось правдой.", None),
    ("Don't give up!", "Не сдавайся!", None),
    ("We ran out of money.", "У нас кончились деньги.", None),
    ("I'm looking forward to the trip.", "Я с нетерпением жду поездки.", None),
    ("I get along with my colleagues.", "Я хорошо ладлю с коллегами.", None),
    ("The book that I read was great.", "Книга, которую я прочитал, была отличной.", None),
    ("She is the person who helped me.", "Она человек, который мне помог.", None),
    ("Stop talking!", "Хватит разговаривать!", None),
    ("She wants to stay.", "Она хочет остаться.", None),
    ("I decided to leave.", "Я решил уйти.", None),
    ("Check out is at noon.", "Выезд в полдень.", None),
    ("Get off at the next stop.", "Выйди на следующей остановке.", None),
    ("Turn on the light.", "Включи свет.", None),
    ("He turned up late.", "Он появился с опозданием.", None),
    ("Look up the word.", "Посмотри слово.", None),
    ("She gave up trying.", "Она перестала пытаться.", None),
    ("Things will work out.", "Всё наладится.", None),
    ("This is the place where we first met.", "Это место, где мы впервые встретились.", None),
    ("The film that we watched was boring.", "Фильм, который мы смотрели, был скучным.", None),
    ("I finished reading the book.", "Я закончил читать книгу.", None),
    ("I hope to see you soon.", "Надеюсь скоро тебя увидеть.", None),
    ("The bus that goes to the centre is number five.", "Автобус, который идёт в центр, — пятый.", None),
    ("We took off late.", "Мы взлетели с опозданием.", None),
    ("How did you find out?", "Откуда ты узнал?", None),
    ("He is the one who knocks.", "Это тот, кто стучит.", None),
    ("I'd love to visit Japan.", "Я бы с удовольствием посетил Японию.", None),
    ("It's never too late to learn.", "Учиться никогда не поздно.", None),
    ("Never give up on your dreams.", "Никогда не отказывайся от мечты.", None),
    ("I can't figure it out.", "Не могу понять.", None),
    ("Calm down!", "Успокойся!", None),
    ("Keep going!", "Продолжай!", None),
    ("Come on, you can do it!", "Давай, ты сможешь!", None),
    ("This is the best film that I have ever seen.", "Это лучший фильм, который я когда-либо видел.", None),
    ("Bon voyage!", "Счастливого пути!", None),
    ("I enjoy reading books.", "Я с удовольствием читаю книги.", None),
    ("He asked where I lived.", "Он спросил, где я живу.", None),
    ("I saw it yesterday.", "Я видел это вчера.", None),
    ("I finish my work.", "Я заканчиваю работу.", None),
    ("I finished my work.", "Я закончил работу.", None),
    ("She goes home.", "Она идёт домой.", None),
    ("She went home.", "Она пошла домой.", None),
    ("They build a house.", "Они строят дом.", None),
    ("They built a house.", "Они построили дом.", None),
    ("It is quite good.", "Это довольно хорошо.", ["It's quite good."]),
    ("I enjoy reading books.", "Я с удовольствием читаю книги.", None),
    ("It's cold, isn't it?", "Холодно, не так ли?", None),
    ("Yes, it is.", "Да.", None),
    ("He asked where I lived.", "Он спросил, где я живу.", None),
    ("It's good enough.", "Это достаточно хорошо.", None),
    ("I saw it yesterday.", "Я видел это вчера.", None),
    ("I finish my work.", "Я заканчиваю работу.", None),
    ("I finished my work.", "Я закончил работу.", None),
    ("She goes home.", "Она идёт домой.", None),
    ("She went home.", "Она пошла домой.", None),
    ("They build a house.", "Они строят дом.", None),
    ("They built a house.", "Они построили дом.", None),
]

B20 = [
    ("This bridge was built in 1900.", "Этот мост построен в 1900 году.", None),
    ("The cake is made with chocolate.", "Торт сделан из шоколада.", None),
    ("The room was cleaned yesterday.", "Комната была убрана вчера.", None),
    ("The letter was sent last week.", "Письмо отправлено на прошлой неделе.", None),
    ("The tickets were booked online.", "Билеты забронированы онлайн.", None),
    ("English is spoken here.", "Здесь говорят по-английски.", None),
    ("This word is used every day.", "Это слово используется каждый день.", None),
    ("The results will be announced tomorrow.", "Результаты будут объявлены завтра.", None),
    ("The problem will be solved.", "Проблема будет решена.", None),
    ("The new hotel will be opened soon.", "Новый отель скоро откроется.", None),
    ("The window was broken.", "Окно было разбито.", None),
    ("The car was stolen.", "Машину угнали.", None),
    ("My bag was lost.", "Моя сумка потерялась.", None),
    ("The flight was cancelled.", "Рейс был отменён.", None),
    ("The meeting was postponed.", "Встреча была перенесена.", None),
    ("The road was closed.", "Дорога была закрыта.", None),
    ("The shop is closed on Sundays.", "Магазин закрыт по воскресеньям.", None),
    ("The museum is visited by millions.", "Музей посещают миллионы.", None),
    ("This book was written by a famous author.", "Эта книга написана известным автором.", None),
    ("The song was sung beautifully.", "Песня была исполнена красиво.", None),
    ("The dinner was cooked by my mother.", "Ужин приготовила моя мама.", None),
    ("The house was designed by an architect.", "Дом спроектирован архитектором.", None),
    ("The film was directed by Spielberg.", "Фильм снял Спилберг.", None),
    ("The prize was won by a young girl.", "Приз выиграла молодая девушка.", None),
    ("It was invented in the 19th century.", "Это было изобретено в XIX веке.", None),
    ("Paper is made from wood.", "Бумагу делают из дерева.", None),
    ("Wine is produced in France.", "Вино производят во Франции.", None),
    ("Rice is grown in Asia.", "Рис выращивают в Азии.", None),
    ("Coffee is grown in Brazil.", "Кофе выращивают в Бразилии.", None),
    ("People die if they are killed.", "Люди умирают, если их убивают.", None),
    ("I was born in Moscow.", "Я родился в Москве.", None),
    ("She was raised by her grandmother.", "Её воспитала бабушка.", None),
    ("We were told to wait.", "Нам сказали ждать.", None),
    ("He was asked to leave.", "Его попросили уйти.", None),
    ("I was given a second chance.", "Мне дали второй шанс.", None),
    ("She was offered a job.", "Ей предложили работу.", None),
    ("It is said that…", "Говорят, что…", None),
    ("It is believed that…", "Считается, что…", None),
    ("It is known that…", "Известно, что…", None),
    ("It was reported that…", "Сообщалось, что…", None),
    ("Nothing was said.", "Ничего не было сказано.", None),
    ("Everything has been arranged.", "Всё устроено.", None),
    ("The bill has been paid.", "Счёт оплачен.", None),
    ("Your order has been shipped.", "Ваш заказ отправлен.", None),
]

B21 = [
    ("He said he was busy.", "Он сказал, что занят.", None),
    ("She said she would come.", "Она сказала, что придёт.", None),
    ("He said he had finished.", "Он сказал, что закончил.", None),
    ("She told me she was tired.", "Она сказала мне, что устала.", None),
    ("He told us he was leaving.", "Он сказал нам, что уходит.", None),
    ("They said they didn't know.", "Они сказали, что не знают.", None),
    ("She said she liked it.", "Она сказала, что ей понравилось.", None),
    ("He asked if I was ready.", "Он спросил, готов ли я.", None),
    ("She asked where I lived.", "Она спросила, где я живу.", None),
    ("He asked what time it was.", "Он спросил, сколько времени.", None),
    ("They asked if we wanted to come.", "Они спросили, хотим ли мы прийти.", None),
    ("She asked why I was late.", "Она спросила, почему я опоздал.", None),
    ("He told me to wait.", "Он велел мне подождать.", None),
    ("She told us to follow her.", "Она велела нам следовать за ней.", None),
    ("They told him to stop.", "Они велели ему остановиться.", None),
    ("He told me not to worry.", "Он сказал мне не волноваться.", None),
    ("She told them to be quiet.", "Она велела им помолчать.", None),
    ("He asked me to help.", "Он попросил меня помочь.", None),
    ("She asked us to leave.", "Она попросила нас уйти.", None),
    ("Could you tell me where the station is?", "Не подскажете, где вокзал?", None),
    ("Could you tell me how to get to the centre?", "Не подскажете, как добраться до центра?", None),
    ("Do you know when the bus leaves?", "Вы знаете, когда отходит автобус?", None),
    ("Do you know if the shop is open?", "Вы знаете, магазин открыт?", None),
    ("I wonder what he meant.", "Интересно, что он имел в виду.", None),
    ("I wonder if she knows.", "Интересно, знает ли она.", None),
    ("I don't know what to say.", "Не знаю, что сказать.", None),
    ("I don't know if I can help.", "Не знаю, смогу ли я помочь.", None),
    ("He explained that it was difficult.", "Он объяснил, что это трудно.", None),
    ("She explained why she was late.", "Она объяснила, почему опоздала.", None),
    ("He mentioned that he had been ill.", "Он упомянул, что болел.", None),
    ("She admitted that she was wrong.", "Она признала, что была неправа.", None),
    ("He denied that he had said it.", "Он отрицал, что это говорил.", None),
    ("She promised that she would call.", "Она обещала, что позвонит.", None),
    ("He suggested that we go out.", "Он предложил нам выйти.", None),
    ("She reminded me to buy bread.", "Она напомнила мне купить хлеб.", None),
    ("He warned me to be careful.", "Он предупредил меня быть осторожным.", None),
    ("She informed us that the flight was delayed.", "Она сообщила нам, что рейс задержан.", None),
    ("They announced that the show was cancelled.", "Они объявили, что шоу отменено.", None),
    ("He replied that he didn't know.", "Он ответил, что не знает.", None),
    ("She answered that she agreed.", "Она ответила, что согласна.", None),
    ("He whispered that he loved her.", "Он прошептал, что любит её.", None),
    ("She shouted that she was angry.", "Она закричала, что злится.", None),
    ("He wrote that he missed us.", "Он написал, что скучает по нам.", None),
    ("She texted me that she had arrived.", "Она написала мне, что приехала.", None),
    ("He said yes.", "Он сказал «да».", None),
    ("She said no.", "Она сказала «нет».", None),
    ("He asked why.", "Он спросил почему.", None),
    ("She told me.", "Она сказала мне.", None),
    ("He replied.", "Он ответил.", None),
    ("She agreed.", "Она согласилась.", None),
    ("He denied it.", "Он это отрицал.", None),
    ("I wonder.", "Интересно.", None),
]

B22 = [
    ("Nice weather, isn't it?", "Хорошая погода, не так ли?", None),
    ("It's cold today, isn't it?", "Сегодня холодно, не так ли?", None),
    ("You are from Russia, aren't you?", "Ты из России, не так ли?", None),
    ("She works here, doesn't she?", "Она работает здесь, не так ли?", None),
    ("He likes coffee, doesn't he?", "Ему нравится кофе, не так ли?", None),
    ("They live in London, don't they?", "Они живут в Лондоне, не так ли?", None),
    ("You know the answer, don't you?", "Ты знаешь ответ, не так ли?", None),
    ("We met before, didn't we?", "Мы уже встречались, не так ли?", None),
    ("You can swim, can't you?", "Ты умеешь плавать, не так ли?", None),
    ("She could help, couldn't she?", "Она могла бы помочь, не так ли?", None),
    ("He should rest, shouldn't he?", "Ему следует отдохнуть, не так ли?", None),
    ("You will come, won't you?", "Ты придёшь, не так ли?", None),
    ("It was good, wasn't it?", "Было хорошо, не так ли?", None),
    ("They were late, weren't they?", "Они опоздали, не так ли?", None),
    ("You have finished, haven't you?", "Ты закончил, не так ли?", None),
    ("She has been to Paris, hasn't she?", "Она была в Париже, не так ли?", None),
    ("You haven't seen my keys, have you?", "Ты не видел мои ключи?", None),
    ("It isn't raining, is it?", "Дождя нет, правда?", None),
    ("He isn't coming, is he?", "Он не придёт, да?", None),
    ("She doesn't know, does she?", "Она не знает, правда?", None),
    ("You don't smoke, do you?", "Ты не куришь, правда?", None),
    ("They didn't call, did they?", "Они не звонили, да?", None),
    ("You can't drive, can you?", "Ты не умеешь водить, правда?", None),
    ("He won't mind, will he?", "Он не будет против, правда?", None),
    ("You aren't you, are you?", "Ты — это не ты, не так ли?", None),
    ("That was fun, wasn't it?", "Было весело, не так ли?", None),
    ("The food is delicious, isn't it?", "Еда вкусная, не так ли?", None),
    ("This is beautiful, isn't it?", "Это красиво, не так ли?", None),
    ("You speak English well, don't you?", "Ты хорошо говоришь по-английски, не так ли?", None),
    ("She plays the piano, doesn't she?", "Она играет на пианино, не так ли?", None),
    ("He's been working hard, hasn't he?", "Он усердно работал, не так ли?", None),
    ("You'd rather stay, wouldn't you?", "Ты бы лучше остался, не так ли?", None),
    ("There's a problem, isn't there?", "Есть проблема, не так ли?", None),
    ("Nothing happened, did it?", "Ничего не случилось, правда?", None),
    ("Nobody knows, do they?", "Никто не знает, правда?", None),
    ("Everyone came, didn't they?", "Все пришли, не так ли?", None),
    ("Let's go, shall we?", "Пойдём, хорошо?", None),
    ("Open the door, will you?", "Открой дверь, хорошо?", None),
    ("Don't be late, will you?", "Не опаздывай, хорошо?", None),
    ("Help me with this, can you?", "Помоги мне с этим, хорошо?", None),
    ("Sit down, won't you?", "Садитесь, пожалуйста.", None),
    ("Pass the salt, would you?", "Передай соль, пожалуйста.", None),
    ("You know what I mean, don't you?", "Ты понимаешь, о чём я, не так ли?", None),
    ("I told you so, didn't I?", "Я же говорил, не так ли?", None),
]

B23 = [
    ("I'm afraid of flying.", "Я боюсь летать.", None),
    ("She is afraid of dogs.", "Она боится собак.", None),
    ("He is afraid of heights.", "Он боится высоты.", None),
    ("I'm not afraid of the dark.", "Я не боюсь темноты.", None),
    ("Are you afraid of spiders?", "Ты боишься пауков?", None),
    ("She is good at cooking.", "Она хорошо готовит.", None),
    ("He is good at his job.", "Он хорош в своей работе.", None),
    ("I'm good at swimming.", "Я хорошо плаваю.", None),
    ("Are you good at chess?", "Ты хорошо играешь в шахматы?", None),
    ("She is bad at singing.", "Она плохо поёт.", None),
    ("He is bad at lying.", "Он плохо врёт.", None),
    ("I'm interested in history.", "Я интересуюсь историей.", None),
    ("She is interested in art.", "Она интересуется искусством.", None),
    ("Are you interested in music?", "Ты интересуешься музыкой?", None),
    ("I'm not interested in politics.", "Я не интересуюсь политикой.", None),
    ("She is fond of reading.", "Она любит читать.", None),
    ("He is fond of chocolate.", "Он обожает шоколад.", None),
    ("I'm fond of the sea.", "Я люблю море.", None),
    ("She is proud of her son.", "Она гордится сыном.", None),
    ("He is proud of his work.", "Он гордится своей работой.", None),
    ("I'm proud of you.", "Я горжусь тобой.", None),
    ("I'm tired of waiting.", "Я устал ждать.", None),
    ("She is tired of his jokes.", "Ей надоели его шутки.", None),
    ("I'm sick of this weather.", "Меня достала эта погода.", None),
    ("He is famous for his films.", "Он известен своими фильмами.", None),
    ("This city is famous for its food.", "Этот город известен своей едой.", None),
    ("She is responsible for the project.", "Она отвечает за проект.", None),
    ("I'm worried about you.", "Я беспокоюсь о тебе.", None),
    ("She is worried about the exam.", "Она беспокоится об экзамене.", None),
    ("Don't worry about it.", "Не беспокойся об этом.", None),
    ("I'm angry with him.", "Я сержусь на него.", None),
    ("She is angry about the delay.", "Она злится из-за задержки.", None),
    ("I'm surprised at the news.", "Я удивлён этой новостью.", None),
    ("We were shocked at the price.", "Мы были шокированы ценой.", None),
    ("He is different from his brother.", "Он отличается от брата.", None),
    ("This is similar to that.", "Это похоже на то.", None),
    ("It depends on you.", "Это зависит от тебя.", None),
    ("I'm full of energy.", "Я полон энергии.", None),
    ("The room is full of people.", "Комната полна людей.", None),
    ("She is keen on photography.", "Она увлекается фотографией.", None),
    ("He is mad about football.", "Он помешан на футболе.", None),
    ("I'm sorry for being late.", "Извини за опоздание.", None),
    ("She is excited about the trip.", "Она в восторге от поездки.", None),
    ("I'm used to getting up early.", "Я привык рано вставать.", None),
]

B24 = [
    ("He said he was busy.", "Он сказал, что занят.", None),
    ("The room was cleaned yesterday.", "Комната была убрана вчера.", None),
    ("English is spoken here.", "Здесь говорят по-английски.", None),
    ("This bridge was built in 1900.", "Этот мост построен в 1900 году.", None),
    ("Nice weather, isn't it?", "Хорошая погода, не так ли?", None),
    ("You are from Russia, aren't you?", "Ты из России, не так ли?", None),
    ("I'm afraid of flying.", "Я боюсь летать.", None),
    ("She is good at cooking.", "Она хорошо готовит.", None),
    ("I'm interested in history.", "Я интересуюсь историей.", None),
    ("I'm proud of you.", "Я горжусь тобой.", None),
    ("She said she would come.", "Она сказала, что придёт.", None),
    ("He asked if I was ready.", "Он спросил, готов ли я.", None),
    ("Could you tell me where the station is?", "Не подскажете, где вокзал?", None),
    ("She told me to wait.", "Она велела мне подождать.", None),
    ("The window was broken.", "Окно было разбито.", None),
    ("The results will be announced tomorrow.", "Результаты будут объявлены завтра.", None),
    ("You know the answer, don't you?", "Ты знаешь ответ, не так ли?", None),
    ("It was good, wasn't it?", "Было хорошо, не так ли?", None),
    ("He is famous for his films.", "Он известен своими фильмами.", None),
    ("I'm tired of waiting.", "Я устал ждать.", None),
    ("He works here, doesn't he?", "Он работает здесь, не так ли?", None),
    ("The letter was sent last week.", "Письмо отправлено на прошлой неделе.", None),
    ("I was born in Moscow.", "Я родился в Москве.", None),
    ("Paper is made from wood.", "Бумагу делают из дерева.", None),
    ("You haven't seen my keys, have you?", "Ты не видел мои ключи?", None),
    ("It isn't raining, is it?", "Дождя нет, правда?", None),
    ("I'm worried about you.", "Я беспокоюсь о тебе.", None),
    ("She is fond of reading.", "Она любит читать.", None),
    ("He denied that he had said it.", "Он отрицал, что это говорил.", None),
    ("The car was stolen.", "Машину угнали.", None),
    ("Everything has been arranged.", "Всё устроено.", None),
    ("Do you know when the bus leaves?", "Вы знаете, когда отходит автобус?", None),
    ("He is different from his brother.", "Он отличается от брата.", None),
    ("She is excited about the trip.", "Она в восторге от поездки.", None),
    ("I wonder what he meant.", "Интересно, что он имел в виду.", None),
    ("The problem will be solved.", "Проблема будет решена.", None),
    ("He warned me to be careful.", "Он предупредил меня быть осторожным.", None),
    ("This book was written by a famous author.", "Эта книга написана известным автором.", None),
    ("Don't worry about it.", "Не беспокойся об этом.", None),
    ("She is angry about the delay.", "Она злится из-за задержки.", None),
    ("Let's go, shall we?", "Пойдём, хорошо?", None),
    ("Everyone came, didn't they?", "Все пришли, не так ли?", None),
    ("I don't know what to say.", "Не знаю, что сказать.", None),
    ("It is said that…", "Говорят, что…", None),
]

B25 = [
    ("Let's eat out tonight.", "Давай поужинаем вне дома сегодня.", None),
    ("We eat out every Friday.", "Мы едим вне дома каждую пятницу.", None),
    ("I don't feel like cooking — let's eat out.", "Не хочется готовить — пойдём в кафе.", None),
    ("I'm looking forward to the holidays.", "Я жду каникулы с нетерпением.", None),
    ("I'm looking forward to seeing them.", "Жду встречи с ними.", None),
    ("What are you looking forward to?", "Чего ты ждёшь с нетерпением?", None),
    ("We get along with each other.", "Мы ладим друг с другом.", None),
    ("Do you get along with your boss?", "Ты ладишь с начальником?", None),
    ("They get along like a house on fire.", "Они ладят на удивление хорошо.", None),
    ("We ran out of coffee.", "У нас закончился кофе.", None),
    ("I ran out of ideas.", "У меня закончились идеи.", None),
    ("We're running out of time.", "У нас кончается время.", None),
    ("Don't run out of patience.", "Не теряй терпение.", None),
    ("I'm fed up with the rain.", "Меня достал дождь.", None),
    ("I'm fed up with waiting.", "Я сыт по горло ожиданием.", None),
    ("She put up with a lot.", "Она многое вытерпела.", None),
    ("I can't put up with this noise.", "Я не могу терпеть этот шум.", None),
    ("He came up with a great idea.", "Ему пришла в голову отличная идея.", None),
    ("She came up with a solution.", "Она нашла решение.", None),
    ("I ended up staying at home.", "В итоге я остался дома.", None),
    ("We ended up in the wrong place.", "Мы оказались не в том месте.", None),
    ("How did it end up?", "Чем это закончилось?", None),
    ("I bumped into an old friend.", "Я случайно встретил старого друга.", None),
    ("I ran into my ex-boss.", "Я случайно встретил бывшего начальника.", None),
    ("I turned down the invitation.", "Я отклонил приглашение.", None),
    ("She turned down the job.", "Она отказалась от работы.", None),
    ("He came across an old photo.", "Ему попалось старое фото.", None),
    ("I came across this word today.", "Мне сегодня попалось это слово.", None),
    ("Take care of yourself.", "Береги себя.", None),
    ("Who takes care of the cat?", "Кто заботится о коте?", None),
    ("I don't care about it.", "Мне это безразлично.", None),
    ("Who cares?", "Кого это волнует?", None),
    ("As far as I know.", "Насколько я знаю.", None),
    ("As far as I'm concerned.", "Что касается меня.", None),
    ("To be honest.", "Честно говоря.", None),
    ("To tell the truth.", "По правде говоря.", None),
    ("In fact.", "На самом деле.", None),
    ("Actually.", "Вообще-то.", None),
    ("By the way.", "Кстати.", None),
    ("Anyway.", "В любом случае.", None),
    ("Whatever.", "Как хочешь.", None),
    ("It's up to you.", "Решать тебе.", None),
    ("I can't be bothered.", "Мне лень.", None),
    ("Long story short.", "Короче говоря.", None),
]

B26 = [
    ("You must stop.", "Вы должны остановиться.", None),
    ("I have to go.", "Мне нужно идти.", None),
    ("You should rest.", "Тебе следует отдохнуть.", None),
    ("You'd better hurry.", "Тебе лучше поторопиться.", None),
    ("You'd better stay in bed.", "Тебе лучше остаться в постели.", None),
    ("I'd better call a taxi.", "Мне лучше вызвать такси.", None),
    ("You'd better not be late.", "Тебе лучше не опаздывать.", None),
    ("We'd better leave now.", "Нам лучше уходить сейчас.", None),
    ("You must see a doctor.", "Вам обязательно нужно к врачу.", None),
    ("You have to wear a helmet.", "Ты должен носить шлем.", None),
    ("You should drink more water.", "Тебе следует пить больше воды.", None),
    ("You mustn't tell anyone.", "Тебе нельзя никому говорить.", None),
    ("You don't have to come.", "Тебе не обязательно приходить.", None),
    ("You shouldn't work so hard.", "Тебе не стоит так много работать.", None),
    ("I had to wait an hour.", "Мне пришлось ждать час.", None),
    ("I couldn't help it.", "Я не мог удержаться.", None),
    ("You could be right.", "Возможно, ты прав.", None),
    ("That can't be true.", "Не может быть, чтобы это было правдой.", None),
    ("It must be late.", "Должно быть, уже поздно.", None),
    ("She might come later.", "Она, возможно, придёт позже.", None),
    ("He may know the answer.", "Он, возможно, знает ответ.", None),
    ("You might need it.", "Это может тебе понадобиться.", None),
    ("It could rain.", "Может пойти дождь.", None),
    ("I would if I could.", "Я бы, если бы мог.", None),
    ("You should have called.", "Тебе следовало позвонить.", None),
    ("I should have known.", "Надо было догадаться.", None),
    ("You could have told me.", "Ты мог бы мне сказать.", None),
    ("I would have helped.", "Я бы помог.", None),
    ("You must have been tired.", "Ты, должно быть, устал.", None),
    ("She can't have forgotten.", "Не может быть, чтобы она забыла.", None),
    ("He might have missed the bus.", "Он, возможно, опоздал на автобус.", None),
    ("Is it necessary?", "Это необходимо?", None),
    ("Do I really need to?", "Мне правда нужно?", None),
    ("It's not worth it.", "Это того не стоит.", None),
    ("It's worth a try.", "Стоит попробовать.", None),
    ("What do you suggest?", "Что вы предлагаете?", None),
    ("What would you do?", "Что бы ты сделал?", None),
    ("If I were you, I'd wait.", "На твоём месте я бы подождал.", None),
    ("You'd better take an umbrella.", "Тебе лучше взять зонт.", None),
    ("You must be joking!", "Ты шутишь, что ли?", None),
    ("You can't be serious.", "Ты не можешь быть серьёзным.", None),
    ("Are you sure?", "Ты уверен?", None),
    ("Definitely.", "Определённо.", None),
    ("Absolutely.", "Абсолютно.", None),
]

B28 = [
    ("It's quite good.", "Это довольно хорошо.", None),
    ("It's quite difficult.", "Это довольно сложно.", None),
    ("She is quite beautiful.", "Она довольно красивая.", None),
    ("The food was quite delicious.", "Еда была довольно вкусной.", None),
    ("I quite like it.", "Мне это довольно нравится.", None),
    ("It's really interesting.", "Это действительно интересно.", None),
    ("She is really nice.", "Она действительно милая.", None),
    ("The film was really boring.", "Фильм был действительно скучным.", None),
    ("I really appreciate it.", "Я действительно это ценю.", None),
    ("Thank you so much.", "Большое спасибо.", None),
    ("It's a bit cold.", "Немного холодно.", None),
    ("I'm a bit tired.", "Я немного устал.", None),
    ("Could you wait a bit?", "Могли бы вы немного подождать?", None),
    ("It's a bit expensive.", "Это немного дорого.", None),
    ("I like it a lot.", "Мне это очень нравится.", None),
    ("I miss you very much.", "Я очень по тебе скучаю.", None),
    ("Thank you very much.", "Большое спасибо.", None),
    ("I very much doubt it.", "Я очень сомневаюсь в этом.", None),
    ("This is quite amazing.", "Это поразительно.", None),
    ("It was absolutely fantastic.", "Это было абсолютно фантастически.", None),
    ("The view is absolutely stunning.", "Вид абсолютно потрясающий.", None),
    ("I completely agree.", "Я полностью согласен.", None),
    ("I totally understand.", "Я прекрасно понимаю.", None),
    ("It's incredibly fast.", "Это невероятно быстро.", None),
    ("The weather is extremely hot.", "Погода невероятно жаркая.", None),
    ("This is extremely important.", "Это чрезвычайно важно.", None),
    ("She is incredibly talented.", "Она невероятно талантлива.", None),
    ("I'm so sorry about that.", "Мне очень жаль.", None),
    ("I'm terribly sorry.", "Мне очень жаль.", None),
    ("It's incredibly good.", "Это невероятно хорошо.", None),
    ("He drives too fast.", "Он водит слишком быстро.", None),
    ("She speaks too quietly.", "Она говорит слишком тихо.", None),
    ("It's far too early.", "Слишком рано.", None),
    ("This is by far the best.", "Это безусловно лучшее.", None),
    ("It's not good enough.", "Это недостаточно хорошо.", None),
    ("It's good enough for me.", "Мне этого достаточно.", None),
    ("He is not old enough.", "Он недостаточно взрослый.", None),
    ("It's rather cold.", "Довольно холодно.", None),
    ("It's rather strange.", "Довольно странно.", None),
    ("I rather like it.", "Мне это скорее нравится.", None),
    ("She sings pretty well.", "Она поёт довольно хорошо.", None),
    ("That's pretty amazing.", "Это довольно потрясающе.", None),
    ("It's not that bad.", "Не так уж и плохо.", None),
    ("It's not so difficult.", "Не так уж и сложно.", None),
    ("It's easier than I thought.", "Это проще, чем я думал.", None),
]

B29 = [
    ("It's quite good.", "Это довольно хорошо.", None),
    ("I'm a bit tired.", "Я немного устал.", None),
    ("I really appreciate it.", "Я действительно это ценю.", None),
    ("It's absolutely stunning.", "Это абсолютно потрясающе.", None),
    ("He drives too fast.", "Он водит слишком быстро.", None),
    ("It's not good enough.", "Это недостаточно хорошо.", None),
    ("It's rather strange.", "Довольно странно.", None),
    ("I quite like it.", "Мне это довольно нравится.", None),
    ("She is really nice.", "Она действительно милая.", None),
    ("This is by far the best.", "Это безусловно лучшее.", None),
    ("Let's eat out tonight.", "Давай поужинаем вне дома сегодня.", None),
    ("I'm looking forward to it.", "Я с нетерпением жду этого.", None),
    ("We ran out of time.", "У нас кончилось время.", None),
    ("I'm fed up with waiting.", "Я сыт по горло ожиданием.", None),
    ("He came up with a great idea.", "Ему пришла в голову отличная идея.", None),
    ("I bumped into an old friend.", "Я случайно встретил старого друга.", None),
    ("You'd better hurry.", "Тебе лучше поторопиться.", None),
    ("You must be joking!", "Ты шутишь, что ли?", None),
    ("It must be late.", "Должно быть, уже поздно.", None),
    ("She might come later.", "Она, возможно, придёт позже.", None),
    ("You should have called.", "Тебе следовало позвонить.", None),
    ("I would if I could.", "Я бы, если бы мог.", None),
    ("The room was cleaned yesterday.", "Комната была убрана вчера.", None),
    ("He said he was busy.", "Он сказал, что занят.", None),
    ("Nice weather, isn't it?", "Хорошая погода, не так ли?", None),
    ("I'm afraid of flying.", "Я боюсь летать.", None),
    ("She is good at cooking.", "Она хорошо готовит.", None),
    ("I'm interested in history.", "Я интересуюсь историей.", None),
    ("I'm proud of you.", "Я горжусь тобой.", None),
    ("The man who lives here is a doctor.", "Мужчина, который живёт здесь, — врач.", None),
    ("I enjoy reading.", "Я с удовольствием читаю.", None),
    ("I want to go home.", "Я хочу пойти домой.", None),
    ("We check in online.", "Мы регистрируемся онлайн.", None),
    ("The plane takes off at six.", "Самолёт взлетает в шесть.", None),
    ("I'll look it up.", "Я это посмотрю.", None),
    ("It turned out to be true.", "Это оказалось правдой.", None),
    ("Don't give up!", "Не сдавайся!", None),
    ("I have been learning English for two years.", "Я учу английский два года.", None),
    ("If I had more time, I would travel.", "Если бы у меня было больше времени, я бы путешествовал.", None),
    ("I used to live in London.", "Я раньше жил в Лондоне.", None),
    ("I have finished.", "Я закончил.", None),
    ("I had finished before you came.", "Я закончил до того, как ты пришёл.", None),
    ("How long have you been waiting?", "Как долго ты ждёшь?", None),
    ("Everything will be fine.", "Всё будет хорошо.", None),
    ("Long story short.", "Короче говоря.", None),
]

B30 = [
    ("I have finished my work.", "Я закончил работу.", None),
    ("I finished it yesterday.", "Я закончил это вчера.", None),
    ("I have been learning it for two years.", "Я учу его уже два года.", None),
    ("I had finished it before you came.", "Я закончил это до твоего прихода.", None),
    ("If it rains, I'll stay.", "Если пойдёт дождь, я останусь.", None),
    ("If I had time, I would travel.", "Если бы было время, я бы путешествовал.", None),
    ("I wish I were there.", "Жаль, что меня там нет.", None),
    ("I used to smoke.", "Я раньше курил.", None),
    ("I'm used to it.", "Я привык.", None),
    ("This bridge was built in 1900.", "Мост построен в 1900 году.", None),
    ("He said he was busy.", "Он сказал, что занят.", None),
    ("Nice weather, isn't it?", "Хорошая погода, не так ли?", None),
    ("I'm afraid of flying.", "Я боюсь летать.", None),
    ("She is good at cooking.", "Она хорошо готовит.", None),
    ("The man who lives here is a doctor.", "Мужчина, который здесь живёт, — врач.", None),
    ("I enjoy reading.", "Я с удовольствием читаю.", None),
    ("I want to go home.", "Я хочу пойти домой.", None),
    ("We check in online.", "Мы регистрируемся онлайн.", None),
    ("The plane takes off at six.", "Самолёт взлетает в шесть.", None),
    ("I'll look it up.", "Я это посмотрю.", None),
    ("It turned out to be true.", "Это оказалось правдой.", None),
    ("Don't give up!", "Не сдавайся!", None),
    ("We ran out of money.", "У нас кончились деньги.", None),
    ("I'm looking forward to it.", "Жду с нетерпением.", None),
    ("I get along with people.", "Я хорошо ладлю с людьми.", None),
    ("You'd better hurry.", "Тебе лучше поторопиться.", None),
    ("You must be joking!", "Ты шутишь!", None),
    ("It's quite good.", "Это довольно хорошо.", None),
    ("I really appreciate it.", "Я правда это ценю.", None),
    ("It's a bit cold.", "Немного холодно.", None),
    ("I have been to Paris.", "Я был в Париже.", None),
    ("I went to Paris last year.", "Я ездил в Париж в прошлом году.", None),
    ("Have you ever been abroad?", "Ты когда-нибудь был за границей?", None),
    ("What would you do?", "Что бы ты сделал?", None),
    ("Could you tell me where the station is?", "Не подскажете, где вокзал?", None),
    ("The results will be announced tomorrow.", "Результаты объявят завтра.", None),
    ("English is spoken here.", "Здесь говорят по-английски.", None),
    ("Let's eat out tonight.", "Давай поужинаем вне дома.", None),
    ("I bumped into an old friend.", "Я встретил старого друга.", None),
    ("He came up with a great idea.", "Ему пришла отличная идея.", None),
    ("Long story short.", "Короче говоря.", None),
    ("It's up to you.", "Решать тебе.", None),
    ("Everything will be fine.", "Всё будет хорошо.", None),
    ("This is by far the best.", "Это безусловно лучшее.", None),
]

RULE_B15 = """**Relative clauses: who / which / that.**
who — о людях: the man **who** lives here.
which/that — о вещах: the book **that** I read.
where — о местах: the town **where** I was born.
Можно опустить that/who, если это не подлежащее:
the book (that) I read — можно без that."""

RULE_B16 = """**Герундий vs инфинитив.**
Герундий (-ing) после: enjoy, finish, stop, give up:
I enjoy **reading**. Stop **talking**.
Инфинитив (to + V1) после: want, need, decide, hope, promise, plan:
I want **to go**. She decided **to stay**.
It's + прил. + to: It's important **to be** honest."""

RULE_B17 = """**Фразовые глаголы I: путешествия.**
check **in/out** — регистрироваться/выезжать
take **off** — взлетать; снимать (одежду)
get **on/off** — садиться/выходить (транспорт)
set **off** — отправляться
turn **on/off/up/down** — включить/выключить/громче/тише"""

RULE_B18 = """**Фразовые глаголы II: поиск и решения.**
look **up** — посмотреть (в словаре)
find **out** — узнать, выяснить
turn **out** — оказаться
give **up** — сдаваться, бросить
run **out of** — закончиться (запас)
look forward **to** — ждать с нетерпением
get **along** — ладить
work **out** — сложиться, получиться"""

RULE_B19 = """**Повторение №18: связные фразы.**
Relative clauses (who/which/that), герундий vs инфинитив,
фразовые глаголы I (check in, take off, get on) и II (look up, find out,
turn out, give up, run out of, look forward to)."""

RULE_B20 = """**Пассив: be + V3.**
**is/are made**, **was/were built**, **will be done**:
This bridge **was built** in 1900. English **is spoken** here.
Кто делает — не важно; важно — с кем/что делают:
by + исполнитель: written **by** a famous author."""

RULE_B21 = """**Косвенная речь.**
He said (that) he **was** busy. (was → было)
She said she **would** come. (will → would)
He said he **had** finished. (have → had)
Вопрос → if/whether + прямой порядок слов:
He asked **if I was** ready. (Нет do/does!)
Could you tell me where the station **is**? (не «where is»)"""

RULE_B22 = """**Разделительные вопросы (tag questions).**
+, −: You know, **don't you?** / It's cold, **isn't it?**
−, +: You don't smoke, **do you?** / It isn't raining, **is it?**
Правило: повторить be/auxiliary в противоположном знаке.
Let's go, **shall we?** — исключение."""

RULE_B23 = """**Предлоги после прилагательных.**
afraid **of**, good/bad **at**, interested **in**, fond **of**,
proud **of**, tired/sick **of**, famous **for**, worried **about**,
angry **with** (чел.) / **about** (о Situation), different **from**,
similar **to**, keen **on**, full **of**, used **to**."""

RULE_B24 = """**Повторение №19: чужая речь.**
Пассив, косвенная речь, разделительные вопросы,
предлоги после прилагательных.
Пунктуация: косвенный вопрос БЕЗ «?»: He asked if I was ready."""

RULE_B25 = """**Фразовые глаголы III: быт и отношения.**
eat **out** — есть вне дома; look forward **to** — ждать с нетерпением;
get **along** — ладить; run **out of** — закончиться;
be fed **up with** — быть сытым по горло; put **up with** — терпеть;
come **up with** — придумать; end **up** — оказаться в итоге;
bump **into** — случайно встретить; come **across** — наткнуться;
take **care of** — заботиться."""

RULE_B26 = """**Модальный микс.**
must (обязательно!) / have to (вынужден) / should (совет) /
'd better (лучше бы) / might (возможно) / can't be (не может быть!).
Уверенные догадки: must be late = «должно быть, поздно»;
can't be true = «не может быть правдой»."""

RULE_B28 = """**Наречия и усилители.**
quite = довольно; really = действительно; a bit = немного;
very much = очень; absolutely = абсолютно; completely = полностью;
too = слишком; enough = достаточно (ПОСЛЕ слова!);
rather = довольно; pretty = довольно (разг.); by far = несомненно."""

RULE_B29 = """**Повторение №20: весь ранг B.**
Фразовые глаголы III, модальный микс, усилители — плюс всё из B1–B4:
Present Perfect семья, условные/wish/used to, пассив, косвенная речь."""

RULE_B30 = """**Большое повторение перед Вратами A.**
ВСЁ ранга B: PP/PPC/Past Perfect, условные 0/1/2, wish, used to,
пассив, косвенная речь, tag questions, adj+prep, relative clauses,
герундий vs инфинитив, фразовые глаголы I–III, модальный микс,
усилители. Разговорник: все ситуации.
Врата A ждут, Охотник!"""

LESSONS_B3_B5 = [
    {
        "id": "les-b-15", "module": "mod-b-3",
        "title": "Relative clauses: who / which / that",
        "gp_id": "gp-b-15", "gp_title": "Придаточные определительные",
        "rule_md": RULE_B15,
        "phrases": B15,
        "rule_cloze": [
            ("The man ___ lives here is a doctor.", ["who", "that"]),
            ("The book ___ I read was great.", ["that", "which"]),
            ("This is the town ___ I was born.", ["where"]),
        ],
        "quotes": [("q-breaking-bad-0003", "who"), ("q-fma-fma-b-0018", "calling")],
        "trap_id": "trap-articles",
        "vocab_band": {"list": "ngsl-spoken", "from": 4601, "to": 4660},
        "phrasebook_topic": None,
        "quotes_topic": "relative",
        "bebris_video": None,
        "answer_question": [("Who is the man standing there?", "The man who lives here is a doctor.")],
        "find_error": [("The man which lives here is a doctor.", "The man who lives here is a doctor.")],
        "verb_tense": [
            ("The woman ___ called you is my sister.", "человек", ["who", "that"]),
            ("The café ___ is near the station is good.", "вещь", ["which", "that"]),
            ("This is the place ___ we first met.", "место", ["where"]),
        ],
    },
    {
        "id": "les-b-16", "module": "mod-b-3",
        "title": "Герундий vs инфинитив: enjoy doing / want to do",
        "gp_id": "gp-b-16", "gp_title": "Gerund or infinitive",
        "rule_md": RULE_B16,
        "phrases": B16,
        "rule_cloze": [
            ("I enjoy ___ books.", ["reading"]),
            ("I want ___ go home.", ["to"]),
            ("Stop ___! (разговаривать)", ["talking"]),
        ],
        "quotes": [("q-fma-fma-b-0001", "without"), ("q-supernatural-0011", "to")],
        "trap_id": "trap-want-that",
        "vocab_band": {"list": "ngsl-spoken", "from": 4661, "to": 4720},
        "phrasebook_topic": None,
        "quotes_topic": "grammar",
        "bebris_video": {"lesson": "2.96", "playlist_index": 647, "youtube_id": "UxX1Ca2w7iY", "title": None},
        "answer_question": [("Do you enjoy reading?", "I enjoy reading.")],
        "find_error": [("I enjoy to read.", "I enjoy reading.")],
        "verb_tense": [
            ("She enjoys ___.", "герундий", ["cooking"]),
            ("He decided ___ stay.", "заполни", ["to"]),
            ("I finished ___ the room.", "заполни", ["cleaning"]),
        ],
    },
    {
        "id": "les-b-17", "module": "mod-b-3",
        "title": "Фразовые глаголы I: путешествия",
        "gp_id": "gp-b-17", "gp_title": "Phrasal verbs: travel",
        "rule_md": RULE_B17,
        "phrases": B17,
        "rule_cloze": [
            ("We check ___ online.", ["in"]),
            ("The plane takes ___ at six.", ["off"]),
            ("Get ___ the bus. (садись)", ["on"]),
        ],
        "quotes": [("q-lord-of-the-rings-0001", "Fly"), ("q-the-100-0002", "meet")],
        "trap_id": "trap-articles",
        "vocab_band": {"list": "ngsl-spoken", "from": 4721, "to": 4780},
        "phrasebook_topic": "airport",
        "quotes_topic": "travel",
        "bebris_video": {"lesson": "2.336", "playlist_index": 887, "youtube_id": "fGxRBo8Prko", "title": None},
        "answer_question": [("What time does the plane take off?", "The plane takes off at six.")],
        "find_error": [("We check at online.", "We check in online.")],
        "verb_tense": [
            ("Get ___ at the next stop.", "выходить", ["off"]),
            ("Turn ___ the light.", "включить", ["on"]),
            ("We set ___ early.", "отправляться", ["off"]),
        ],
    },
    {
        "id": "les-b-18", "module": "mod-b-3",
        "title": "Фразовые глаголы II: поиск и решения",
        "gp_id": "gp-b-18", "gp_title": "Phrasal verbs: search & decisions",
        "rule_md": RULE_B18,
        "phrases": B18,
        "rule_cloze": [
            ("I'll look it ___ in the dictionary.", ["up"]),
            ("It turned ___ to be true.", ["out"]),
            ("Don't give ___!", ["up"]),
        ],
        "quotes": [("q-supernatural-0014", "Saving"), ("q-supernatural-0014", "hunting")],
        "trap_id": "trap-wait-for",
        "vocab_band": {"list": "ngsl-spoken", "from": 4781, "to": 4840},
        "phrasebook_topic": "directions",
        "quotes_topic": "phrasal",
        "bebris_video": {"lesson": "2.344", "playlist_index": 895, "youtube_id": "HkFu9dLvRfQ", "title": None},
        "answer_question": [("What did you find out?", "I found out the truth.")],
        "find_error": [("Don't give off!", "Don't give up!")],
        "verb_tense": [
            ("I found ___ the truth.", "выяснить", ["out"]),
            ("We ran ___ of money.", "закончиться", ["out"]),
            ("I'm looking forward ___ the trip.", "заполни", ["to"]),
        ],
    },
    {
        "id": "les-b-19", "module": "mod-b-3",
        "title": "Повторение №18",
        "gp_id": "gp-b-19", "gp_title": "Повторение модуля B3",
        "rule_md": RULE_B19,
        "phrases": B19,
        "rule_cloze": [
            ("I enjoy ___ books.", ["reading"]),
            ("The plane takes ___ at six.", ["off"]),
            ("Don't give ___!", ["up"]),
        ],
        "quotes": [("q-breaking-bad-0003", "who"), ("q-supernatural-0014", "family")],
        "trap_id": "trap-want-that",
        "vocab_band": {"list": "ngsl-spoken", "from": 4841, "to": 4900},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("Do you enjoy cooking?", "I enjoy reading books.")],
        "find_error": [("I enjoy to read books.", "I enjoy reading books.")],
        "verb_tense": [
            ("The man ___ lives here is a doctor.", "заполни", ["who", "that"]),
            ("We check ___ online.", "заполни", ["in"]),
            ("It turned ___ well.", "заполни", ["out"]),
        ],
    },
    {
        "id": "les-b-20", "module": "mod-b-4",
        "title": "Пассив: be + V3",
        "gp_id": "gp-b-20", "gp_title": "Passive voice базово",
        "rule_md": RULE_B20,
        "phrases": B20,
        "rule_cloze": [
            ("The bridge ___ built in 1900.", ["was"]),
            ("English is ___ here.", ["spoken"]),
            ("The results will be ___ tomorrow. (объявят)", ["announced"]),
        ],
        "quotes": [("q-memy-0006", "killed"), ("q-igry-0015", "died")],
        "trap_id": "trap-present-perfect",
        "vocab_band": {"list": "ngsl-spoken", "from": 4901, "to": 4960},
        "phrasebook_topic": None,
        "quotes_topic": "passive",
        "bebris_video": {"lesson": "2.216", "playlist_index": 767, "youtube_id": "lx-HhzfqGVM", "title": None},
        "answer_question": [("When was the bridge built?", "This bridge was built in 1900.")],
        "find_error": [("This bridge was build in 1900.", "This bridge was built in 1900.")],
        "verb_tense": [
            ("The room ___ cleaned yesterday.", "пассив прош.", ["was"]),
            ("English is ___ here.", "пассив, наст. время", ["spoken"]),
            ("The problem will be ___.", "пассив, буд. время", ["solved"]),
        ],
    },
    {
        "id": "les-b-21", "module": "mod-b-4",
        "title": "Косвенная речь: He said he was busy",
        "gp_id": "gp-b-21", "gp_title": "Reported speech",
        "rule_md": RULE_B21,
        "phrases": B21,
        "rule_cloze": [
            ("He said he ___ busy.", ["was"]),
            ("She said she ___ come.", ["would"]),
            ("He asked ___ I was ready.", ["if", "whether"]),
        ],
        "quotes": [("q-black-mirror-0010", "aren't"), ("q-stranger-things-0020", "thinking")],
        "trap_id": "trap-indirect-question",
        "vocab_band": {"list": "ngsl-spoken", "from": 4961, "to": 5020},
        "phrasebook_topic": "directions",
        "quotes_topic": "speech",
        "bebris_video": {"lesson": "2.256", "playlist_index": 807, "youtube_id": "62kfQH0uwIU", "title": None},
        "answer_question": [("What did he say?", "He said he was busy.")],
        "find_error": [("He asked where do I live.", "He asked where I lived.")],
        "verb_tense": [
            ("She said she ___ tired.", "косв. (is→)", ["was"]),
            ("He said he ___ finished.", "косв. (has→)", ["had"]),
            ("Could you tell me where the station ___?", "косв. (без ?)", ["is"]),
        ],
    },
    {
        "id": "les-b-22", "module": "mod-b-4",
        "title": "Разделительные вопросы: isn't it?",
        "gp_id": "gp-b-22", "gp_title": "Tag questions",
        "rule_md": RULE_B22,
        "phrases": B22,
        "rule_cloze": [
            ("It's cold, ___ it?", ["isn't"]),
            ("You don't smoke, ___ you?", ["do"]),
            ("Let's go, ___ we?", ["shall"]),
        ],
        "quotes": [("q-black-mirror-0010", "are"), ("q-star-wars-0014", "it")],
        "trap_id": "trap-question-word-order",
        "vocab_band": {"list": "ngsl-spoken", "from": 5021, "to": 5080},
        "phrasebook_topic": "smalltalk",
        "quotes_topic": "tags",
        "bebris_video": {"lesson": "2.266", "playlist_index": 817, "youtube_id": "HGwwoQB0BIA", "title": None},
        "answer_question": [("It's cold, isn't it?", "Yes, it is.")],
        "find_error": [("Nice weather, is it?", "Nice weather, isn't it?")],
        "verb_tense": [
            ("She works here, ___ she?", "хвостик", ["doesn't"]),
            ("You can swim, ___ you?", "хвостик", ["can't"]),
            ("They were late, ___ they?", "хвостик", ["weren't"]),
        ],
    },
    {
        "id": "les-b-23", "module": "mod-b-4",
        "title": "Предлоги после прилагательных: afraid of, good at",
        "gp_id": "gp-b-23", "gp_title": "Adjective + preposition",
        "rule_md": RULE_B23,
        "phrases": B23,
        "rule_cloze": [
            ("I'm afraid ___ flying.", ["of"]),
            ("She is good ___ cooking.", ["at"]),
            ("I'm interested ___ history.", ["in"]),
        ],
        "quotes": [("q-attack-on-titan-0002", "sacrifice"), ("q-lord-of-the-rings-0017", "decide")],
        "trap_id": "trap-wait-for",
        "vocab_band": {"list": "ngsl-spoken", "from": 5081, "to": 5140},
        "phrasebook_topic": "pharmacy",
        "quotes_topic": "feelings",
        "bebris_video": {"lesson": "2.269", "playlist_index": 820, "youtube_id": "qjb3rtyG8po", "title": None},
        "answer_question": [("What are you afraid of?", "I'm afraid of flying.")],
        "find_error": [("She is good in cooking.", "She is good at cooking.")],
        "verb_tense": [
            ("He is proud ___ his work.", "заполни", ["of"]),
            ("I'm tired ___ waiting.", "заполни", ["of"]),
            ("She is worried ___ the exam.", "предлог", ["about"]),
        ],
    },
    {
        "id": "les-b-24", "module": "mod-b-4",
        "title": "Повторение №19",
        "gp_id": "gp-b-24", "gp_title": "Повторение модуля B4",
        "rule_md": RULE_B24,
        "phrases": B24,
        "rule_cloze": [
            ("The room ___ cleaned yesterday.", ["was"]),
            ("He said he ___ busy.", ["was"]),
            ("It's cold, ___ it?", ["isn't"]),
        ],
        "quotes": [("q-memy-0006", "die"), ("q-black-mirror-0010", "aren't")],
        "trap_id": "trap-indirect-question",
        "vocab_band": {"list": "ngsl-spoken", "from": 5141, "to": 5200},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("What did she ask?", "She asked where I lived.")],
        "find_error": [("He asked where do I live.", "He asked where I lived.")],
        "verb_tense": [
            ("English is ___ here.", "пассив, наст. время", ["spoken"]),
            ("I'm afraid ___ flying.", "заполни", ["of"]),
            ("You know the answer, ___ you?", "хвостик", ["don't"]),
        ],
    },
    {
        "id": "les-b-25", "module": "mod-b-5",
        "title": "Фразовые глаголы III: быт и отношения",
        "gp_id": "gp-b-25", "gp_title": "Phrasal verbs: life & relationships",
        "rule_md": RULE_B25,
        "phrases": B25,
        "rule_cloze": [
            ("Let's eat ___ tonight.", ["out"]),
            ("I'm looking forward ___ it.", ["to"]),
            ("We ran ___ of money.", ["out"]),
        ],
        "quotes": [("q-supernatural-0018", "Family"), ("q-supernatural-0018", "don't")],
        "trap_id": "trap-wait-for",
        "vocab_band": {"list": "ngsl-spoken", "from": 5201, "to": 5260},
        "phrasebook_topic": "restaurant",
        "quotes_topic": "phrasal",
        "bebris_video": {"lesson": "2.379", "playlist_index": 930, "youtube_id": "dkBIfciHgew", "title": None},
        "answer_question": [("What are you looking forward to?", "I'm looking forward to the holidays.")],
        "find_error": [("I'm looking forward to see you.", "I'm looking forward to seeing you.")],
        "verb_tense": [
            ("We get ___ with each other.", "ладить", ["along"]),
            ("He came ___ with a great idea.", "придумать", ["up"]),
            ("I bumped ___ an old friend.", "встретить случайно", ["into"]),
        ],
    },
    {
        "id": "les-b-26", "module": "mod-b-5",
        "title": "Модальный микс: must / should / 'd better",
        "gp_id": "gp-b-26", "gp_title": "Modal verbs mix",
        "rule_md": RULE_B26,
        "phrases": B26,
        "rule_cloze": [
            ("You ___ stop. (обязательно)", ["must"]),
            ("You ___ rest. (совет)", ["should"]),
            ("You'd ___ hurry.", ["better"]),
        ],
        "quotes": [("q-game-of-thrones-0014", "win"), ("q-game-of-thrones-0014", "die")],
        "trap_id": "trap-if-will",
        "vocab_band": {"list": "ngsl-spoken", "from": 5261, "to": 5320},
        "phrasebook_topic": "pharmacy",
        "quotes_topic": "modals",
        "bebris_video": {"lesson": "2.300", "playlist_index": 851, "youtube_id": "H4-rXitQBN8", "title": None},
        "answer_question": [("What should I do?", "You should rest.")],
        "find_error": [("You must to stop.", "You must stop.")],
        "verb_tense": [
            ("I ___ to go.", "вынужден", ["have"]),
            ("It ___ be late.", "должно быть (догадка)", ["must"]),
            ("She ___ come later.", "возможно", ["might", "may"]),
        ],
    },
    {
        "id": "les-b-28", "module": "mod-b-5",
        "title": "Наречия и усилители: quite, really, a bit",
        "gp_id": "gp-b-28", "gp_title": "Adverbs and intensifiers",
        "rule_md": RULE_B28,
        "phrases": B28,
        "rule_cloze": [
            ("It's ___ good. (довольно)", ["quite", "rather"]),
            ("I'm a ___ tired.", ["bit", "little"]),
            ("He drives too ___.", ["fast"]),
        ],
        "quotes": [("q-star-wars-0013", "Never"), ("q-memy-0002", "simply")],
        "trap_id": "trap-very-like",
        "vocab_band": {"list": "ngsl-spoken", "from": 5321, "to": 5380},
        "phrasebook_topic": None,
        "quotes_topic": "degree",
        "bebris_video": {"lesson": "2.322", "playlist_index": 873, "youtube_id": "cTtcmycgs9o", "title": None},
        "answer_question": [("How is the food?", "It is quite good.")],
        "find_error": [("It's very good enough.", "It's good enough.")],
        "verb_tense": [
            ("It's ___ difficult.", "довольно", ["quite", "rather"]),
            ("She is ___ nice.", "действительно", ["really"]),
            ("It's ___ expensive.", "немного", ["a bit", "a little", "slightly"]),
        ],
    },
    {
        "id": "les-b-29", "module": "mod-b-5",
        "title": "Повторение №20 + диктант-микс",
        "gp_id": "gp-b-29", "gp_title": "Повторение: весь ранг B",
        "rule_md": RULE_B29,
        "phrases": B29,
        "rule_cloze": [
            ("It's quite ___. (хорошо)", ["good"]),
            ("You'd ___ hurry.", ["better"]),
            ("We ran ___ of time.", ["out"]),
        ],
        "quotes": [("q-memy-0006", "killed"), ("q-igry-0003", "used")],
        "trap_id": "trap-very-like",
        "vocab_band": {"list": "ngsl-spoken", "from": 5381, "to": 5440},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("How is it?", "It's absolutely stunning.")],
        "find_error": [("It's very good enough.", "It's good enough.")],
        "verb_tense": [
            ("I have been ___ English for two years.", "учить", ["learning"]),
            ("I ___ to live in London.", "раньше", ["used"]),
            ("He said he ___ busy.", "косв. речь", ["was"]),
        ],
    },
    {
        "id": "les-b-30", "module": "mod-b-5",
        "title": "Большое повторение перед Вратами A",
        "gp_id": "gp-b-30", "gp_title": "Сборка всего ранга B",
        "rule_md": RULE_B30,
        "phrases": B30,
        "rule_cloze": [
            ("I have ___ finished. (только что)", ["just"]),
            ("If I ___ time, I would travel.", ["had"]),
            ("The bridge ___ built in 1900.", ["was"]),
        ],
        "quotes": [("q-solo-leveling-0001", "Arise"), ("q-berserk-0002", "rather")],
        "trap_id": "trap-present-perfect",
        "vocab_band": {"list": "ngsl-spoken", "from": 5441, "to": 5500},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("Have you ever been abroad?", "I have been to Paris.")],
        "find_error": [("I have seen it yesterday.", "I saw it yesterday.")],
        "verb_tense": [
            ("I have been ___ for two years.", "учить (PPC)", ["learning"]),
            ("If it ___, I'll stay.", "условие 1", ["rains"]),
            ("English is ___ here.", "пассив, наст. время", ["spoken"]),
        ],
        "transform": [
            ("I finish my work.", "past", "I finished my work."),
            ("She goes home.", "past", "She went home."),
            ("They build a house.", "past", "They built a house."),
        ],
    },
]
