#!/usr/bin/env python3
"""Пулы уроков D3 «Количество» (D-11…D-15) и D4 «Вежливость» (D-16…D-20).

plan://M12#12.7. Импортируется build_d.py (LESSONS_D2). Программа — specs/01 §6.
"""

# --------------------------------------------------------------------------
# D3 «Количество»
# --------------------------------------------------------------------------
D11 = [
    ("I have some money.", "У меня есть немного денег.", None),
    ("I need some help.", "Мне нужна какая-нибудь помощь.", None),
    ("She has some questions.", "У неё есть несколько вопросов.", None),
    ("We bought some bread.", "Мы купили немного хлеба.", None),
    ("There are some apples on the table.", "На столе есть несколько яблок.", None),
    ("I want some water.", "Я хочу воды.", None),
    ("He needs some time.", "Ему нужно немного времени.", None),
    ("I see some people in the street.", "Я вижу на улице несколько людей.", None),
    ("Take some sugar.", "Возьми немного сахара.", None),
    ("I have some ideas.", "У меня есть несколько идей.", None),
    ("I don't have any money.", "У меня нет денег.", None),
    ("She doesn't need any help.", "Ей не нужна никакая помощь.", None),
    ("We don't have any bread.", "У нас нет хлеба.", None),
    ("There aren't any apples.", "Яблок нет.", None),
    ("I don't want any water.", "Я не хочу воды.", None),
    ("He doesn't have any questions.", "У него нет никаких вопросов.", None),
    ("I can't see any people.", "Я не вижу никого.", None),
    ("Do you have any money?", "У тебя есть деньги?", None),
    ("Do you need any help?", "Тебе нужна помощь?", None),
    ("Is there any bread?", "Есть хлеб?", None),
    ("Are there any apples?", "Есть яблоки?", None),
    ("Do you want any tea?", "Хочешь чаю?", None),
    ("Have you got any ideas?", "У тебя есть какие-нибудь идеи?", None),
    ("I have no money.", "У меня нет денег.", ["I don't have any money."]),
    ("She has no questions.", "У неё нет вопросов.", ["She doesn't have any questions."]),
    ("We have no bread.", "У нас нет хлеба.", ["We don't have any bread."]),
    ("I have no time.", "У меня нет времени.", ["I don't have any time."]),
    ("He has no ideas.", "У него нет идей.", ["He doesn't have any ideas."]),
    ("There is no sugar.", "Сахара нет.", ["There isn't any sugar."]),
    ("There are no people here.", "Здесь нет людей.", ["There aren't any people here."]),
    ("I know nothing about it.", "Я ничего об этом не знаю.", None),
    ("Nobody knows the answer.", "Никто не знает ответа.", None),
    ("I need something to eat.", "Мне нужно что-нибудь поесть.", None),
    ("Do you know anything about him?", "Ты что-нибудь знаешь о нём?", None),
    ("I want to tell you something.", "Я хочу тебе кое-что сказать.", None),
    ("Something is wrong.", "Что-то не так.", None),
    ("Is anything wrong?", "Что-нибудь не так?", None),
    ("Any ideas?", "Есть идеи?", None),
    ("Some tea or coffee?", "Чаю или кофе?", None),
    ("I can help with something.", "Я могу помочь с чем-нибудь.", None),
    ("We need some more milk.", "Нам нужно ещё немного молока.", None),
    ("Can I have some more, please?", "Можно ещё немного, пожалуйста?", None),
    ("I don't know anything about cars.", "Я ничего не понимаю в машинах.", None),
    ("Ask me anything.", "Спроси меня о чём угодно.", None),
]

D12 = [
    ("How much is this?", "Сколько это стоит?", None),
    ("How much is that shirt?", "Сколько стоит та рубашка?", None),
    ("How much are these shoes?", "Сколько стоят эти туфли?", None),
    ("How much does it cost?", "Сколько это стоит?", None),
    ("How much do you need?", "Сколько тебе нужно?", None),
    ("How much money do you have?", "Сколько у тебя денег?", None),
    ("How much time do we have?", "Сколько у нас времени?", None),
    ("How much is the ticket?", "Сколько стоит билет?", None),
    ("How much water do you want?", "Сколько воды ты хочешь?", None),
    ("How many people are there?", "Сколько там людей?", None),
    ("How many tickets do you need?", "Сколько билетов тебе нужно?", None),
    ("How many brothers do you have?", "Сколько у тебя братьев?", None),
    ("How many rooms are there?", "Сколько там комнат?", None),
    ("How many apples do we have?", "Сколько у нас яблок?", None),
    ("How many days is it?", "Сколько это дней?", None),
    ("I don't have much time.", "У меня не много времени.", None),
    ("We don't have much money.", "У нас не много денег.", None),
    ("There isn't much milk.", "Молока не много.", None),
    ("There are many shops here.", "Здесь много магазинов.", None),
    ("There aren't many tourists today.", "Сегодня не много туристов.", None),
    ("I have a lot of work.", "У меня много работы.", None),
    ("She has a lot of friends.", "У неё много друзей.", None),
    ("We have a lot of time.", "У нас много времени.", None),
    ("Thanks a lot.", "Большое спасибо.", None),
    ("It costs too much.", "Это стоит слишком дорого.", None),
    ("That's too much.", "Это слишком много.", None),
    ("It is not expensive.", "Это недорого.", None),
    ("It is cheap.", "Это дёшево.", None),
    ("It is a good price.", "Это хорошая цена.", None),
    ("Can you give me a better price?", "Можете сделать цену пониже?", None),
    ("I'll take it.", "Я возьму это.", None),
    ("I'll take two.", "Я возьму два.", None),
    ("Can I pay by card?", "Можно оплатить картой?", None),
    ("Cash or card?", "Наличные или карта?", None),
    ("Here is the money.", "Вот деньги.", None),
    ("Keep the change.", "Сдачи не надо.", None),
    ("Where can I buy this?", "Где я могу это купить?", None),
    ("Do you have a bigger one?", "У вас есть побольше?", None),
    ("Do you have a smaller one?", "У вас есть поменьше?", None),
    ("What size is it?", "Какой это размер?", None),
    ("Can I try it on?", "Можно примерить?", None),
    ("It fits.", "Оно подходит.", None),
    ("The bill, please.", "Счёт, пожалуйста.", None),
    ("How much altogether?", "Сколько всего?", None),
]

D13 = [
    ("I need advice.", "Мне нужен совет.", None),
    ("Can I give you some advice?", "Можно дам тебе совет?", None),
    ("That is good advice.", "Это хороший совет.", None),
    ("You need more information.", "Тебе нужно больше информации.", None),
    ("Can I ask for information?", "Могу я спросить информацию?", None),
    ("This is useful information.", "Это полезная информация.", None),
    ("I have no money.", "У меня нет денег.", None),
    ("Money is not a problem.", "Деньги — не проблема.", None),
    ("How much money do you need?", "Сколько денег тебе нужно?", None),
    ("Where is my luggage?", "Где мой багаж?", None),
    ("My luggage is heavy.", "Мой багаж тяжёлый.", None),
    ("My luggage is here.", "Мой багаж здесь.", None),
    ("I have two pieces of luggage.", "У меня два места багажа.", None),
    ("I need help with my luggage.", "Мне нужна помощь с багажом.", None),
    ("Water is important.", "Вода важна.", None),
    ("I drink a lot of water.", "Я пью много воды.", None),
    ("There is no water.", "Воды нет.", None),
    ("Do you have water?", "У вас есть вода?", None),
    ("I like music.", "Мне нравится музыка.", None),
    ("I listen to music every day.", "Я слушаю музыку каждый день.", None),
    ("What music do you like?", "Какая музыка тебе нравится?", None),
    ("Do you have children?", "У вас есть дети?", None),
    ("People are strange.", "Люди странные.", None),
    ("There are many people here.", "Здесь много людей.", None),
    ("How many people live here?", "Сколько людей здесь живёт?", None),
    ("I know these people.", "Я знаю этих людей.", None),
    ("Time is money.", "Время — деньги.", None),
    ("I don't have time.", "У меня нет времени.", None),
    ("We have time.", "У нас есть время.", None),
    ("The food is good here.", "Здесь хорошая еда.", None),
    ("Do you like the food?", "Тебе нравится еда?", None),
    ("The weather is fine.", "Погода хорошая.", None),
    ("The traffic is bad today.", "Сегодня сильное движение.", None),
    ("The news is good.", "Новости хорошие.", None),
    ("That is interesting news.", "Это интересные новости.", None),
    ("His work is difficult.", "Его работа тяжёлая.", None),
    ("I have a lot of work.", "У меня много работы.", None),
    ("I have two jobs.", "У меня две работы.", None),
    ("I have three children.", "У меня трое детей.", None),
    ("We have ten minutes.", "У нас десять минут.", None),
    ("I need two tickets.", "Мне нужно два билета.", None),
    ("Give me the money.", "Дай мне деньги.", None),
    ("I don't need many things.", "Мне не нужно много вещей.", None),
    ("Buy some bread and some apples.", "Купи немного хлеба и несколько яблок.", None),
    ("We need more information about the flight.", "Нам нужно больше информации о рейсе.", None),
]

D14 = [
    ("It is so cold today.", "Сегодня так холодно.", None),
    ("She is so kind.", "Она такая добрая.", None),
    ("This coffee is so good.", "Этот кофе такой вкусный.", None),
    ("I am so tired.", "Я такой усталый.", None),
    ("The film was so boring.", "Фильм был таким скучным.", None),
    ("You walk so slowly.", "Ты ходишь так медленно.", None),
    ("It is so far.", "Это так далеко.", None),
    ("I miss you so much.", "Я так по тебе скучаю.", None),
    ("Thank you so much.", "Большое тебе спасибо.", None),
    ("Sorry, I am so late.", "Извини, я так сильно опаздываю.", None),
    ("It is such a beautiful city.", "Это такой красивый город.", None),
    ("It is such a good idea.", "Это такая хорошая идея.", None),
    ("She is such a nice person.", "Она такой приятный человек.", None),
    ("It was such a long day.", "Это был такой долгий день.", None),
    ("That is such a mistake.", "Это такая ошибка.", None),
    ("He is such a good doctor.", "Он такой хороший врач.", None),
    ("This is such useful advice.", "Это такой полезный совет.", None),
    ("They are such good friends.", "Они такие хорошие друзья.", None),
    ("It was such bad weather.", "Была такая плохая погода.", None),
    ("That is such a pity.", "Какая жалость.", None),
    ("The city is very beautiful.", "Город очень красивый.", None),
    ("The weather is very good.", "Погода очень хорошая.", None),
    ("I am very happy.", "Я очень счастлив.", None),
    ("She is very angry.", "Она очень злая.", None),
    ("This bag is very heavy.", "Эта сумка очень тяжёлая.", None),
    ("He works very hard.", "Он очень усердно работает.", None),
    ("I like it very much.", "Мне это очень нравится.", None),
    ("I very much want to see it.", "Мне очень хочется это увидеть.", None),
    ("Thank you very much.", "Большое спасибо.", None),
    ("I like this song a lot.", "Мне очень нравится эта песня.", None),
    ("It helps a lot.", "Это очень помогает.", None),
    ("I read a lot.", "Я много читаю.", None),
    ("What a nice day!", "Какой хороший день!", None),
    ("What a surprise!", "Какой сюрприз!", None),
    ("What a good idea!", "Какая хорошая идея!", None),
    ("What a pity!", "Какая жалость!", None),
    ("The test was really easy.", "Тест был действительно лёгким.", None),
    ("The soup is too hot.", "Суп слишком горячий.", None),
    ("This shirt is too big.", "Эта рубашка слишком большая.", None),
    ("It is a bit expensive.", "Это немного дорого.", None),
    ("It is quite far.", "Это довольно далеко.", None),
    ("She is really nice.", "Она действительно милая.", None),
    ("Everything is so new.", "Всё такое новое.", None),
    ("Life is so strange.", "Жизнь такая странная.", None),
]

D15 = [
    ("I have some money.", "У меня есть немного денег.", None),
    ("I don't have any money.", "У меня нет денег.", None),
    ("Do you have any money?", "У тебя есть деньги?", None),
    ("I have no time.", "У меня нет времени.", None),
    ("There are some shops here.", "Здесь есть несколько магазинов.", None),
    ("There aren't any shops here.", "Здесь нет магазинов.", None),
    ("How much is this?", "Сколько это стоит?", None),
    ("How much does it cost?", "Сколько это стоит?", None),
    ("How many people are there?", "Сколько там людей?", None),
    ("How much time do we have?", "Сколько у нас времени?", None),
    ("It costs too much.", "Это стоит слишком дорого.", None),
    ("It is too big.", "Это слишком большое.", None),
    ("I'll take it.", "Я возьму это.", None),
    ("Can I pay by card?", "Можно оплатить картой?", None),
    ("Cash or card?", "Наличные или карта?", None),
    ("I need advice.", "Мне нужен совет.", None),
    ("We need more information.", "Нам нужно больше информации.", None),
    ("Where is my luggage?", "Где мой багаж?", None),
    ("There are many people here.", "Здесь много людей.", None),
    ("I listen to music a lot.", "Я много слушаю музыку.", None),
    ("It is such a beautiful city.", "Это такой красивый город.", None),
    ("She is so kind.", "Она такая добрая.", None),
    ("The coffee is very good.", "Кофе очень вкусный.", None),
    ("What a nice day!", "Какой хороший день!", None),
    ("This is such useful advice.", "Это такой полезный совет.", None),
    ("I like it very much.", "Мне это очень нравится.", None),
    ("I am so tired.", "Я такой усталый.", None),
    ("There is some water in the bottle.", "В бутылке есть немного воды.", None),
    ("Is there any milk?", "Есть молоко?", None),
    ("Buy some bread.", "Купи немного хлеба.", None),
    ("We need two tickets.", "Нам нужно два билета.", None),
    ("I have three questions.", "У меня три вопроса.", None),
    ("Something is wrong.", "Что-то не так.", None),
    ("Nothing is wrong.", "Всё в порядке.", None),
    ("Do you know anything about it?", "Ты что-нибудь знаешь об этом?", None),
    ("Nobody knows.", "Никто не знает.", None),
    ("Ask me anything.", "Спроси меня о чём угодно.", None),
    ("How much altogether?", "Сколько всего?", None),
    ("The bill, please.", "Счёт, пожалуйста.", None),
    ("Can I try it on?", "Можно примерить?", None),
    ("It fits.", "Оно подходит.", None),
    ("Do you have a bigger one?", "У вас есть побольше?", None),
    ("Keep the change.", "Сдачи не надо.", None),
    ("I don't need many things.", "Мне не нужно много вещей.", None),
]

# --------------------------------------------------------------------------
# D4 «Вежливость»
# --------------------------------------------------------------------------
D16 = [
    ("Who knows the answer?", "Кто знает ответ?", None),
    ("Who lives here?", "Кто здесь живёт?", None),
    ("Who wants tea?", "Кто хочет чаю?", None),
    ("Who helps you?", "Кто тебе помогает?", None),
    ("Who is that man?", "Кто тот человек?", None),
    ("Who is she?", "Кто она?", None),
    ("Who are they?", "Кто они?", None),
    ("Who is on duty today?", "Кто сегодня дежурный?", None),
    ("Who wants to go first?", "Кто хочет идти первым?", None),
    ("Who works here?", "Кто здесь работает?", None),
    ("He works here.", "Он здесь работает.", None),
    ("What helps you relax?", "Что помогает тебе расслабиться?", None),
    ("What makes you happy?", "Что делает тебя счастливым?", None),
    ("What happens next?", "Что происходит дальше?", None),
    ("What changed your life?", "Что изменило твою жизнь?", None),
    ("What time is it?", "Сколько времени?", None),
    ("It is five o'clock.", "Сейчас пять часов.", None),
    ("What day is it today?", "Какой сегодня день?", None),
    ("What is in the box?", "Что в коробке?", None),
    ("What is your name?", "Как тебя зовут?", None),
    ("What is the problem?", "В чём проблема?", None),
    ("What is the answer?", "Какой ответ?", None),
    ("Which is better?", "Что лучше?", None),
    ("Which way is shorter?", "Какой путь короче?", None),
    ("Which colour do you like?", "Какой цвет тебе нравится?", None),
    ("Whose bag is this?", "Чья это сумка?", None),
    ("Whose phone is ringing?", "Чей телефон звонит?", None),
    ("Whose idea was it?", "Чья это была идея?", None),
    ("Who called you?", "Кто тебе позвонил?", None),
    ("Who told you that?", "Кто тебе это сказал?", None),
    ("Who knows him better?", "Кто знает его лучше?", None),
    ("Who wants to help?", "Кто хочет помочь?", None),
    ("What grows in your garden?", "Что растёт в твоём саду?", None),
    ("What saves time?", "Что экономит время?", None),
    ("What works for you?", "Что работает у тебя?", None),
    ("Everybody knows it.", "Все это знают.", None),
    ("Nobody knows.", "Никто не знает.", None),
    ("Somebody wants to see you.", "Кто-то хочет тебя видеть.", None),
    ("Anybody can do it.", "Любой может это сделать.", None),
    ("Who is the best here?", "Кто здесь лучший?", None),
    ("What is the most important thing?", "Что самое важное?", None),
    ("Which of them is yours?", "Который из них твой?", None),
    ("Who broke the window?", "Кто разбил окно?", None),
    ("What made you smile?", "Что заставило тебя улыбнуться?", None),
    ("Who sings better?", "Кто поёт лучше?", None),
    ("Who is right?", "Кто прав?", None),
]

D17 = [
    ("I agree.", "Я согласен.", None),
    ("I agree with you.", "Я с тобой согласен.", None),
    ("I don't agree.", "Я не согласен.", None),
    ("I don't agree with you.", "Я с тобой не согласен.", None),
    ("I can't agree with that.", "С этим я не могу согласиться.", None),
    ("I think so.", "Я так думаю.", None),
    ("I don't think so.", "Я так не думаю.", None),
    ("That's right.", "Это верно.", None),
    ("That's not right.", "Это неверно.", None),
    ("Exactly.", "Именно.", None),
    ("You are right.", "Ты прав.", None),
    ("You are wrong.", "Ты не прав.", None),
    ("Maybe.", "Может быть.", None),
    ("Maybe you are right.", "Может, ты и прав.", None),
    ("Of course.", "Конечно.", None),
    ("Sure.", "Конечно.", None),
    ("No way.", "Ни за что.", None),
    ("It depends.", "Как посмотреть.", None),
    ("In my opinion, it is good.", "По моему мнению, это хорошо.", None),
    ("I think it is a bad idea.", "Думаю, это плохая идея.", None),
    ("What do you think?", "Что ты думаешь?", None),
    ("Do you agree?", "Вы согласны?", None),
    ("Do you agree with me?", "Ты со мной согласен?", None),
    ("I like it very much.", "Мне это очень нравится.", None),
    ("I like her very much.", "Она мне очень нравится.", None),
    ("I love this city a lot.", "Я очень люблю этот город.", None),
    ("It helps a lot.", "Это очень помогает.", None),
    ("I read a lot.", "Я много читаю.", None),
    ("We work a lot.", "Мы много работаем.", None),
    ("He talks too much.", "Он слишком много говорит.", None),
    ("She worries too much.", "Она слишком много волнуется.", None),
    ("I don't watch TV much.", "Я не много смотрю телевизор.", None),
    ("Do you travel much?", "Ты много путешествуешь?", None),
    ("I hardly know him.", "Я его едва знаю.", None),
    ("It is nearly ready.", "Это почти готово.", None),
    ("I almost forgot.", "Я чуть не забыл.", None),
    ("I completely agree.", "Я полностью согласен.", None),
    ("I quite like it.", "Мне это довольно нравится.", None),
    ("I really mean it.", "Я действительно серьёзно.", None),
    ("I totally understand.", "Я прекрасно понимаю.", None),
    ("Fair enough.", "Справедливо.", None),
    ("That makes sense.", "Это логично.", None),
    ("I see your point.", "Я понимаю твою мысль.", None),
    ("Let's agree to differ.", "Давай останемся каждый при своём.", None),
]

D18 = [
    ("He says nothing.", "Он ничего не говорит.", None),
    ("She says yes.", "Она говорит «да».", None),
    ("What does he say?", "Что он говорит?", None),
    ("Say it again, please.", "Скажи это снова, пожалуйста.", None),
    ("Say hello to your family.", "Передавай привет своей семье.", None),
    ("Don't say a word.", "Не говори ни слова.", None),
    ("Say the truth.", "Скажи правду.", None),
    ("How do you say it in English?", "Как это сказать по-английски?", None),
    ("Did you say anything?", "Ты что-то сказал?", None),
    ("He says that he is busy.", "Он говорит, что занят.", None),
    ("Tell me the truth.", "Скажи мне правду.", None),
    ("Tell me a story.", "Расскажи мне историю.", None),
    ("Tell me about your trip.", "Расскажи мне о своей поездке.", None),
    ("Tell him the news.", "Расскажи ему новости.", None),
    ("He told me the news.", "Он рассказал мне новости.", None),
    ("Don't tell her.", "Не говори ей.", None),
    ("Can you tell me the time?", "Можете сказать мне время?", None),
    ("I told you.", "Я тебе говорил.", None),
    ("She told me everything.", "Она рассказала мне всё.", None),
    ("Tell us your name.", "Скажите нам своё имя.", None),
    ("I will tell you later.", "Я скажу тебе позже.", None),
    ("Ask him.", "Спроси его.", None),
    ("Ask me anything.", "Спроси меня о чём угодно.", None),
    ("Ask the driver.", "Спросите водителя.", None),
    ("May I ask you something?", "Можно вас спросить?", None),
    ("She asks about you.", "Она спрашивает о тебе.", None),
    ("He asked for help.", "Он попросил помощи.", None),
    ("I asked her the question.", "Я задал ей вопрос.", None),
    ("Ask for the bill.", "Попросите счёт.", None),
    ("He said hello.", "Он поздоровался.", None),
    ("She said nothing.", "Она ничего не сказала.", None),
    ("What did he say?", "Что он сказал?", None),
    ("He said that he knows me.", "Он сказал, что знает меня.", None),
    ("He told me the answer.", "Он сказал мне ответ.", None),
    ("Don't ask me.", "Не спрашивай меня.", None),
    ("Ask her name.", "Спроси её имя.", None),
    ("Can I ask you a question?", "Можно задать вам вопрос?", None),
    ("She told a lie.", "Она солгала.", None),
    ("Never tell a lie.", "Никогда не лги.", None),
    ("Tell me why.", "Скажи мне почему.", None),
    ("Say it in English.", "Скажи это по-английски.", None),
    ("Speak slowly, please.", "Говорите медленно, пожалуйста.", None),
    ("Can you speak up?", "Можете говорить громче?", None),
    ("We talked about it.", "Мы об этом говорили.", None),
    ("They talked for an hour.", "Они разговаривали час.", None),
]

D19 = [
    ("How do you feel?", "Как ты себя чувствуешь?", None),
    ("I feel good.", "Я хорошо себя чувствую.", None),
    ("I feel bad.", "Я плохо себя чувствую.", None),
    ("I don't feel well.", "Мне нездоровится.", None),
    ("I feel sick.", "Меня тошнит.", None),
    ("She feels better today.", "Сегодня она чувствует себя лучше.", None),
    ("He feels worse.", "Ему хуже.", None),
    ("I feel tired.", "Я чувствую усталость.", None),
    ("I feel hungry.", "Я голоден.", None),
    ("Do you feel cold?", "Ты не замёрз?", None),
    ("It feels strange.", "Это ощущается странно.", None),
    ("I feel at home here.", "Я чувствую себя здесь как дома.", None),
    ("I'm waiting for you.", "Я жду тебя.", None),
    ("We are waiting for the bus.", "Мы ждём автобус.", None),
    ("She waited for an hour.", "Она ждала час.", None),
    ("Wait for me!", "Подожди меня!", None),
    ("Don't wait for me.", "Не жди меня.", None),
    ("What are you waiting for?", "Чего ты ждёшь?", None),
    ("I'm looking for my bag.", "Я ищу свою сумку.", None),
    ("He is looking for a job.", "Он ищет работу.", None),
    ("We looked for it everywhere.", "Мы искали это везде.", None),
    ("She is looking for you.", "Она тебя ищет.", None),
    ("I'm looking for a gift.", "Я ищу подарок.", None),
    ("Ask for help.", "Попроси помощи.", None),
    ("Thank you for your help.", "Спасибо за твою помощь.", None),
    ("Thanks for everything.", "Спасибо за всё.", None),
    ("Listen to me.", "Послушай меня.", None),
    ("I listen to the radio.", "Я слушаю радио.", None),
    ("Look at this.", "Посмотри на это.", None),
    ("Look at the sky.", "Посмотри на небо.", None),
    ("I think about it often.", "Я часто об этом думаю.", None),
    ("Dream about home.", "Мечтай о доме.", None),
    ("Pay for the ticket.", "Заплати за билет.", None),
    ("Can you pay for dinner?", "Можешь заплатить за ужин?", None),
    ("I paid ten dollars for it.", "Я заплатил за это десять долларов.", None),
    ("I don't feel well. I need a doctor.", "Мне нездоровится. Мне нужен врач.", None),
    ("Where is the nearest pharmacy?", "Где ближайшая аптека?", None),
    ("I need something for a headache.", "Мне нужно что-нибудь от головной боли.", None),
    ("Take this medicine twice a day.", "Принимайте это лекарство дважды в день.", None),
    ("Do you feel better now?", "Вам сейчас лучше?", None),
    ("I feel much better.", "Я чувствую себя гораздо лучше.", None),
    ("Call a doctor, please.", "Вызовите врача, пожалуйста.", None),
    ("I need a painkiller.", "Мне нужно обезболивающее.", None),
    ("Get well soon.", "Поправляйся.", None),
]

D20 = [
    ("Who knows the answer?", "Кто знает ответ?", None),
    ("Who is that man?", "Кто тот человек?", None),
    ("What makes you happy?", "Что делает тебя счастливым?", None),
    ("What is the problem?", "В чём проблема?", None),
    ("Whose bag is this?", "Чья это сумка?", None),
    ("Who called you?", "Кто тебе позвонил?", None),
    ("I agree with you.", "Я с тобой согласен.", None),
    ("I don't agree.", "Я не согласен.", None),
    ("I think so.", "Я так думаю.", None),
    ("You are right.", "Ты прав.", None),
    ("Maybe you are right.", "Может, ты и прав.", None),
    ("What do you think?", "Что ты думаешь?", None),
    ("I like it very much.", "Мне это очень нравится.", None),
    ("I read a lot.", "Я много читаю.", None),
    ("He talks too much.", "Он слишком много говорит.", None),
    ("Tell me the truth.", "Скажи мне правду.", None),
    ("She told me everything.", "Она рассказала мне всё.", None),
    ("Ask him.", "Спроси его.", None),
    ("He said that he knows me.", "Он сказал, что знает меня.", None),
    ("Say it in English.", "Скажи это по-английски.", None),
    ("How do you feel?", "Как ты себя чувствуешь?", None),
    ("I don't feel well.", "Мне нездоровится.", None),
    ("I feel much better.", "Я чувствую себя гораздо лучше.", None),
    ("I wait for you every day.", "Я жду тебя каждый день.", None),
    ("I'm waiting for you.", "Я жду тебя.", None),
    ("I'm looking for my bag.", "Я ищу свою сумку.", None),
    ("He is looking for a job.", "Он ищет работу.", None),
    ("Thank you for your help.", "Спасибо за твою помощь.", None),
    ("Listen to me.", "Послушай меня.", None),
    ("Look at this.", "Посмотри на это.", None),
    ("I need something for a headache.", "Мне нужно что-нибудь от головной боли.", None),
    ("There are some shops here.", "Здесь есть несколько магазинов.", None),
    ("How much is this?", "Сколько это стоит?", None),
    ("It costs too much.", "Это стоит слишком дорого.", None),
    ("Can I pay by card?", "Можно оплатить картой?", None),
    ("She is so kind.", "Она такая добрая.", None),
    ("It is such a beautiful city.", "Это такой красивый город.", None),
    ("Get well soon.", "Поправляйся.", None),
    ("Say hello to your family.", "Передавай привет своей семье.", None),
    ("I can help with something.", "Я могу помочь с чем-нибудь.", None),
    ("Nobody knows.", "Никто не знает.", None),
    ("Everybody knows it.", "Все это знают.", None),
    ("I totally understand.", "Я прекрасно понимаю.", None),
    ("That makes sense.", "Это логично.", None),
    ("It depends.", "Как посмотреть.", None),
]

RULE_D11 = """**some / any / no.**
Утверждение — **some**: I have **some** money.
Отрицание и вопрос — **any**: I don't have **any** money. / Do you have **any** money?
Усиленное отрицание — **no**: I have **no** money. (= not any)
some также в просьбах/предложениях: Can I have **some** more?"""

RULE_D12 = """**much / many / how much / how many.**
Неисчисляемые (money, time, water) — **much**: I don't have **much** time.
Исчисляемые (people, tickets, apples) — **many**: **Many** people live here.
Вопрос о количестве: **How much** is this? / **How much** money? / **How many** tickets?
Много обоих типов — **a lot of**: a lot of work, a lot of friends."""

RULE_D13 = """**Неисчисляемые существительные.**
advice, information, money, luggage, water, music, time, food, weather, news, work —
без -s, без a/an, с much/нет many: I need **advice**. ❌ advices
news — формально множественное, но глагол в ед.ч.: The news **is** good.
Счёт — через единицы: two **pieces of** luggage, three **bottles of** water.
⚠️ people = «люди», глагол во мн.ч.: There **are** many people."""

RULE_D14 = """**so / such / very / too / a lot.**
so + прилагательное/наречие: **so** cold, **so** good.
such + a/an + прилагательное + сущ.: **such a** beautiful city (сущ. есть — such!).
very — нейтральное усиление: very good; ⚠️ very НЕ перед глаголами (I like it **very much**).
too = «слишком»: too hot, too big. a lot = «сильно/много»: helps **a lot**.
What a + сущ.! = восклицание: **What a** nice day!"""

RULE_D15 = """**Повторение №7: количество.**
some → any в отрицании/вопросе; no = not any.
much/many по типу существительного; How much…? / How many…?
Неисчисляемые без -s: advice, money, information.
so + прилагательное, such + (a) + сущ."""

RULE_D16 = """**Вопрос к подлежащему.**
Who / What + глагол БЕЗ do/does: **Who knows**? **What helps** you?
❌ Who does know? Сравни: **Who knows** him? vs **Why does** he **know** it?
Глагол в 3-м лице ед.ч.: Who **wants** tea? Who **is** she?"""

RULE_D17 = """**Согласие и степень.**
agree — ГЛАГОЛ: I **agree** with you. ❌ I am agree.
Мнение: I think so. / I don't think so. / In my opinion…
Степень после глагола: I like it **very much** / **a lot** (не «very like»).
too much = «слишком много», quite/really/totally — оттенки усиления."""

RULE_D18 = """**say / tell / ask.**
**say** (что-то): say it, say hello, he says that…
**tell** (кому-то что-то): tell **me** the truth, tell **him** the news.
❌ say me → **tell me**.
**ask** (кому-то о чём-то): ask him, ask for help, ask a question."""

RULE_D19 = """**feel и глаголы с предлогами.**
feel + прилагательное/хорошо-плохо: I **feel** good. How do you **feel**?
❌ feel myself → **feel** well / **feel** good.
Предлоги: wait **for**, look **for** (искать), look **at** (смотреть на),
listen **to**, thank **for**, think **about**, pay **for**, ask **for**."""

RULE_D20 = """**Повторение №8: вежливость и предлоги.**
Вопрос к подлежащему: Who knows? What helps you?
agree как глагол: I (don't) agree with you.
say/tell/ask: tell ME the truth, say it again, ask him.
feel + предлоги глаголов: wait for, look for, listen to, pay for."""

LESSONS_D3_D4 = [
    {
        "id": "les-d-11", "module": "mod-d-3",
        "title": "some / any / no",
        "gp_id": "gp-d-11", "gp_title": "Квантификаторы some/any/no",
        "rule_md": RULE_D11,
        "phrases": D11,
        "rule_cloze": [
            ("I have ___ money.", ["some"]),
            ("I don't have ___ money.", ["any"]),
            ("I have ___ money. (= not any)", ["no"]),
        ],
        "quotes": [("q-attack-on-titan-0009", "some"), ("q-berserk-0005", "something")],
        "trap_id": "trap-articles",
        "vocab_band": {"list": "ngsl-spoken", "from": 881, "to": 940},
        "phrasebook_topic": None,
        "quotes_topic": "food",
        "bebris_video": {"lesson": "2.251", "playlist_index": 802, "youtube_id": "cpNfQQm8ppk", "title": None},
        "answer_question": [("Do you have any money?", "I have some money.")],
        "find_error": [("I don't have no money.", "I don't have any money.")],
        "verb_tense": [
            ("There are ___ apples on the table.", "утверждение", ["some"]),
            ("Is there ___ bread?", "вопрос", ["any"]),
            ("There is ___ sugar. (= not any)", "no", ["no"]),
        ],
    },
    {
        "id": "les-d-12", "module": "mod-d-3",
        "title": "much / many / How much is this?",
        "gp_id": "gp-d-12", "gp_title": "much/many, вопрос о цене",
        "rule_md": RULE_D12,
        "phrases": D12,
        "rule_cloze": [
            ("___ is this?", ["How much"]),
            ("___ people are there?", ["How many"]),
            ("I don't have ___ time.", ["much"]),
        ],
        "quotes": [("q-breaking-bad-0017", "more"), ("q-game-of-thrones-0020", "pay")],
        "trap_id": "trap-uncountable-plurals",
        "vocab_band": {"list": "ngsl-spoken", "from": 941, "to": 1000},
        "phrasebook_topic": "shop",
        "quotes_topic": "shopping",
        "bebris_video": {"lesson": "1.59", "playlist_index": 181, "youtube_id": "hUWh15C6Pqk", "title": None},
        "answer_question": [("How much is this?", "It costs too much.")],
        "find_error": [("How much money do you need? — How many money do you need?", "How much money do you need?")],
        "verb_tense": [
            ("___ does it cost?", "цена", ["How much"]),
            ("___ tickets do you need?", "количество (исчисл.)", ["How many"]),
            ("I have a ___ of work.", "много", ["lot"]),
        ],
    },
    {
        "id": "les-d-13", "module": "mod-d-3",
        "title": "Неисчисляемые: advice, money, information",
        "gp_id": "gp-d-13", "gp_title": "Неисчисляемые существительные",
        "rule_md": RULE_D13,
        "phrases": D13,
        "rule_cloze": [
            ("I need ___. (совет)", ["advice"]),
            ("The news ___ good.", ["is"]),
            ("There ___ many people here.", ["are"]),
        ],
        "quotes": [("q-star-wars-0017", "These"), ("q-solo-leveling-0007", "all")],
        "trap_id": "trap-uncountable-plurals",
        "vocab_band": {"list": "ngsl-spoken", "from": 1001, "to": 1060},
        "phrasebook_topic": "shop",
        "quotes_topic": "things",
        "bebris_video": None,
        "answer_question": [("Where is my luggage?", "My luggage is here.")],
        "find_error": [("I need an advice.", "I need advice.")],
        "verb_tense": [
            ("Give me two ___ of luggage.", "единица измерения", ["pieces"]),
            ("The news ___ bad.", "news = ед.ч.", ["is"]),
            ("___ are many people here.", "люди", ["There"]),
        ],
    },
    {
        "id": "les-d-14", "module": "mod-d-3",
        "title": "so / such: so cold, such a beautiful city",
        "gp_id": "gp-d-14", "gp_title": "so и such, восклицания",
        "rule_md": RULE_D14,
        "phrases": D14,
        "rule_cloze": [
            ("It is ___ cold today.", ["so"]),
            ("It is ___ a beautiful city.", ["such"]),
            ("___ a nice day!", ["What"]),
        ],
        "quotes": [("q-fma-fma-b-0010", "What"), ("q-attack-on-titan-0017", "beautiful")],
        "trap_id": "trap-very-like",
        "vocab_band": {"list": "ngsl-spoken", "from": 1061, "to": 1120},
        "phrasebook_topic": None,
        "quotes_topic": "emotions",
        "bebris_video": {"lesson": "1.28", "playlist_index": 74, "youtube_id": "3pvq0lHmLXM", "title": None},
        "answer_question": [("Do you like this coffee?", "I like it very much.")],
        "find_error": [("I very like this song.", "I like it very much.")],
        "verb_tense": [
            ("She is ___ kind.", "так (прил.)", ["so"]),
            ("He is ___ a good doctor.", "такой (a + сущ.)", ["such"]),
            ("I like it ___ much.", "очень (после глагола)", ["very"]),
        ],
    },
    {
        "id": "les-d-15", "module": "mod-d-3",
        "title": "Повторение №7: количество",
        "gp_id": "gp-d-15", "gp_title": "Повторение модуля D3 + контрольная",
        "rule_md": RULE_D15,
        "phrases": D15,
        "rule_cloze": [
            ("How ___ is this?", ["much"]),
            ("I don't have ___ money.", ["any"]),
            ("It is ___ a beautiful city.", ["such"]),
        ],
        "quotes": [("q-jujutsu-kaisen-0013", "people"), ("q-game-of-thrones-0023", "Fire")],
        "trap_id": "trap-third-person-s",
        "vocab_band": {"list": "ngsl-spoken", "from": 1121, "to": 1180},
        "phrasebook_topic": "shop",
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("Cash or card?", "Can I pay by card?")],
        "find_error": [("How many money do you have?", "How much money do you have?")],
        "verb_tense": [
            ("___ people are there?", "сколько (исчисл.)", ["How many"]),
            ("I have ___ time.", "немного (утв.)", ["some"]),
            ("It is ___ cold.", "так", ["so"]),
        ],
    },
    {
        "id": "les-d-16", "module": "mod-d-4",
        "title": "Вопрос к подлежащему: Who knows? What helps?",
        "gp_id": "gp-d-16", "gp_title": "Вопрос к подлежащему без do",
        "rule_md": RULE_D16,
        "phrases": D16,
        "rule_cloze": [
            ("___ knows the answer?", ["Who"]),
            ("___ makes you happy?", ["What"]),
            ("Who ___ tea? (3-е лицо)", ["wants"]),
        ],
        "quotes": [("q-attack-on-titan-0005", "Who's"), ("q-jujutsu-kaisen-0006", "What")],
        "trap_id": "trap-question-word-order",
        "vocab_band": {"list": "ngsl-spoken", "from": 1181, "to": 1240},
        "phrasebook_topic": "smalltalk",
        "quotes_topic": "people",
        "bebris_video": {"lesson": "1.21", "playlist_index": 48, "youtube_id": "mfsalx6Nojs", "title": None},
        "answer_question": [("Who is that man?", "He works here.")],
        "find_error": [("Who does know the answer?", "Who knows the answer?")],
        "verb_tense": [
            ("Who ___ here?", "жить (3 л.)", ["lives"]),
            ("___ helps you?", "что", ["What"]),
            ("Whose bag ___ this?", "быть", ["is"]),
        ],
    },
    {
        "id": "les-d-17", "module": "mod-d-4",
        "title": "agree и наречия степени: very much, a lot",
        "gp_id": "gp-d-17", "gp_title": "Согласие; very much / a lot",
        "rule_md": RULE_D17,
        "phrases": D17,
        "rule_cloze": [
            ("I ___ with you.", ["agree"]),
            ("I like it ___ much.", ["very"]),
            ("It helps a ___.", ["lot"]),
        ],
        "quotes": [("q-supernatural-0006", "matter"), ("q-breaking-bad-0010", "handle")],
        "trap_id": "trap-im-agree",
        "vocab_band": {"list": "ngsl-spoken", "from": 1241, "to": 1300},
        "phrasebook_topic": "smalltalk",
        "quotes_topic": "opinions",
        "bebris_video": None,
        "answer_question": [("Do you agree with me?", "I agree with you.")],
        "find_error": [("I am agree with you.", "I agree with you.")],
        "verb_tense": [
            ("I don't ___ with that.", "соглашаться", ["agree"]),
            ("He talks too ___.", "слишком много", ["much"]),
            ("I read a ___.", "много", ["lot"]),
        ],
    },
    {
        "id": "les-d-18", "module": "mod-d-4",
        "title": "say / tell / ask",
        "gp_id": "gp-d-18", "gp_title": "say, tell, ask",
        "rule_md": RULE_D18,
        "phrases": D18,
        "rule_cloze": [
            ("___ me the truth.", ["Tell"]),
            ("He ___ that he is busy.", ["says"]),
            ("___ him about the plan.", ["Ask"]),
        ],
        "quotes": [("q-game-of-thrones-0003", "say"), ("q-stranger-things-0011", "lie")],
        "trap_id": "trap-said-me",
        "vocab_band": {"list": "ngsl-spoken", "from": 1301, "to": 1360},
        "phrasebook_topic": None,
        "quotes_topic": "talk",
        "bebris_video": None,
        "answer_question": [("Can you tell me the time?", "It is five o'clock.")],
        "find_error": [("He said me the news.", "He told me the news.")],
        "verb_tense": [
            ("She ___ me everything.", "tell (прош.)", ["told"]),
            ("___ it again, please.", "сказать", ["Say"]),
            ("Ask ___ help.", "предлог", ["for"]),
        ],
    },
    {
        "id": "les-d-19", "module": "mod-d-4",
        "title": "feel; wait for, look for и другие предлоги",
        "gp_id": "gp-d-19", "gp_title": "feel + глаголы с предлогами",
        "rule_md": RULE_D19,
        "phrases": D19,
        "rule_cloze": [
            ("I don't feel ___.", ["well"]),
            ("I'm waiting ___ you.", ["for"]),
            ("Listen ___ me.", ["to"]),
        ],
        "quotes": [("q-fma-fma-b-0016", "feel"), ("q-fma-fma-b-0019", "feel")],
        "trap_id": "trap-feel-myself",
        "vocab_band": {"list": "ngsl-spoken", "from": 1361, "to": 1420},
        "phrasebook_topic": "pharmacy",
        "quotes_topic": "health",
        "bebris_video": {"lesson": "1.60", "playlist_index": 182, "youtube_id": "2bsDP-r-RGk", "title": None},
        "answer_question": [("How do you feel?", "I feel much better.")],
        "find_error": [("I feel myself bad.", "I feel bad.")],
        "verb_tense": [
            ("He is looking ___ a job.", "искать", ["for"]),
            ("Thank you ___ your help.", "за", ["for"]),
            ("Look ___ the sky.", "на", ["at"]),
        ],
    },
    {
        "id": "les-d-20", "module": "mod-d-4",
        "title": "Повторение №8: вежливость",
        "gp_id": "gp-d-20", "gp_title": "Повторение модуля D4",
        "rule_md": RULE_D20,
        "phrases": D20,
        "rule_cloze": [
            ("Who ___ the answer?", ["knows"]),
            ("I agree ___ you.", ["with"]),
            ("Tell ___ the truth.", ["me"]),
        ],
        "quotes": [("q-supernatural-0019", "stronger"), ("q-the-100-0011", "responsibility")],
        "trap_id": "trap-wait-for",
        "vocab_band": {"list": "ngsl-spoken", "from": 1421, "to": 1480},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("How do you feel?", "I feel good.")],
        "find_error": [("I wait you every day.", "I wait for you every day.")],
        "verb_tense": [
            ("___ makes you happy?", "что (подлежащее)", ["What"]),
            ("I'm looking ___ my bag.", "искать", ["for"]),
            ("He ___ me the news.", "tell (прош.)", ["told"]),
        ],
    },
]
