#!/usr/bin/env python3
"""Пулы уроков C1 «Прошлое» (C-01…C-10) — plan://M14#14.2.

Импортируется build_c.py. Программа — specs/01 §7: Past Simple
(правильные/неправильные I+II), was/were, didn't, Did…?, контраст
времён, вопрос к подлежащему в прошедшем, Повторения №10–11.
"""

C01 = [
    ("I visited London last year.", "Я посетил Лондон в прошлом году.", None),
    ("I usually visit my parents.", "Я обычно навещаю родителей.", None),
    ("We stayed at a small hotel.", "Мы остановились в маленьком отеле.", None),
    ("She booked the tickets online.", "Она забронировала билеты онлайн.", None),
    ("He walked to the station.", "Он дошёл до вокзала пешком.", None),
    ("They watched a film yesterday.", "Вчера они посмотрели фильм.", None),
    ("I worked all day.", "Я проработал весь день.", None),
    ("Yesterday I worked all day.", "Вчера я проработал весь день.", None),
    ("We talked for an hour.", "Мы разговаривали час.", None),
    ("She cooked dinner for us.", "Она приготовила нам ужин.", None),
    ("He cleaned the room.", "Он убрал комнату.", None),
    ("I finished the book.", "Я закончил книгу.", None),
    ("They played football on Sunday.", "В воскресенье они играли в футбол.", None),
    ("We listened to the music.", "Мы послушали музыку.", None),
    ("I asked him a question.", "Я задал ему вопрос.", None),
    ("She answered quickly.", "Она быстро ответила.", None),
    ("He opened the window.", "Он открыл окно.", None),
    ("I closed the door.", "Я закрыл дверь.", None),
    ("We walked in the park.", "Мы гуляли в парке.", None),
    ("They arrived at six.", "Они приехали в шесть.", None),
    ("The train stopped.", "Поезд остановился.", None),
    ("I called you yesterday.", "Я звонил тебе вчера.", None),
    ("We watched the news.", "Мы посмотрели новости.", None),
    ("She helped me a lot.", "Она мне сильно помогла.", None),
    ("He thanked us.", "Он нас поблагодарил.", None),
    ("I needed a rest.", "Мне нужен был отдых.", None),
    ("We planned the trip together.", "Мы спланировали поездку вместе.", None),
    ("They looked at the map.", "Они посмотрели на карту.", None),
    ("I parked the car near the bank.", "Я припарковал машину у банка.", None),
    ("She printed the tickets.", "Она распечатала билеты.", None),
    ("We packed our bags in the morning.", "Мы собрали сумки утром.", None),
    ("He checked the time.", "Он проверил время.", None),
    ("I washed my hands.", "Я вымыл руки.", None),
    ("They painted the walls.", "Они покрасили стены.", None),
    ("We crossed the street.", "Мы перешли дорогу.", None),
    ("I missed the bus.", "Я опоздал на автобус.", None),
    ("She followed the signs.", "Она шла по указателям.", None),
    ("He turned on the light.", "Он включил свет.", None),
    ("I turned off my phone.", "Я выключил телефон.", None),
    ("We ordered two coffees.", "Мы заказали два кофе.", None),
    ("The film started at eight.", "Фильм начался в восемь.", None),
    ("It rained all day.", "Весь день шёл дождь.", None),
    ("I liked the city very much.", "Город мне очень понравился.", None),
    ("We enjoyed the trip.", "Нам понравилась поездка.", None),
    ("The day ended well.", "День закончился хорошо.", None),
    ("I rested after the flight.", "Я отдохнул после перелёта.", None),
]

C02 = [
    ("I went to the shop.", "Я ходил в магазин.", None),
    ("We went by bus.", "Мы поехали на автобусе.", None),
    ("She went home early.", "Она ушла домой рано.", None),
    ("They went to Spain.", "Они ездили в Испанию.", None),
    ("He made coffee.", "Он приготовил кофе.", None),
    ("I made a mistake.", "Я сделал ошибку.", None),
    ("She made a call.", "Она позвонила.", None),
    ("We made a plan.", "Мы составили план.", None),
    ("I saw him yesterday.", "Я видел его вчера.", None),
    ("Did you see that?", "Ты это видел?", None),
    ("We saw the sea.", "Мы увидели море.", None),
    ("She saw the film.", "Она видела фильм.", None),
    ("I took a taxi.", "Я взял такси.", None),
    ("He took my pen.", "Он взял мою ручку.", None),
    ("We took the first train.", "Мы сели на первый поезд.", None),
    ("She took a photo.", "Она сделала фото.", None),
    ("I came home late.", "Я пришёл домой поздно.", None),
    ("He came to the party.", "Он пришёл на вечеринку.", None),
    ("They came by metro.", "Они приехали на метро.", None),
    ("The bus came on time.", "Автобус пришёл вовремя.", None),
    ("I got a message.", "Я получил сообщение.", None),
    ("She got a new job.", "Она получила новую работу.", None),
    ("We got lost.", "Мы заблудились.", None),
    ("He got tired.", "Он устал.", None),
    ("I had a good day.", "У меня был хороший день.", None),
    ("We had a great time.", "Мы отлично провели время.", None),
    ("She had a headache.", "У неё болела голова.", None),
    ("They had no money.", "У них не было денег.", None),
    ("I did my homework.", "Я сделал домашнее задание.", None),
    ("He did nothing.", "Он ничего не сделал.", None),
    ("We did it together.", "Мы сделали это вместе.", None),
    ("She did her best.", "Она старалась изо всех сил.", None),
    ("I said hello.", "Я поздоровался.", None),
    ("He said nothing.", "Он ничего не сказал.", None),
    ("She told me the news.", "Она рассказала мне новости.", None),
    ("I told you so.", "Я же тебе говорил.", None),
    ("We knew the answer.", "Мы знали ответ.", None),
    ("I knew him at school.", "Я знал его в школе.", None),
    ("She thought about it.", "Она об этом подумала.", None),
    ("I thought it was late.", "Я думал, что уже поздно.", None),
    ("He bought two tickets.", "Он купил два билета.", None),
    ("I bought it yesterday.", "Я купил это вчера.", None),
    ("We brought some food.", "Мы принесли еду.", None),
    ("She brought a friend.", "Она привела друга.", None),
]

C03 = [
    ("I lost my passport.", "Я потерял паспорт.", None),
    ("She lost her keys.", "Она потеряла ключи.", None),
    ("We lost the way.", "Мы потеряли дорогу.", None),
    ("He found the ticket.", "Он нашёл билет.", None),
    ("I found my phone.", "Я нашёл телефон.", None),
    ("She found a cheap hotel.", "Она нашла дешёвый отель.", None),
    ("They found the answer.", "Они нашли ответ.", None),
    ("I gave him the money.", "Я дал ему деньги.", None),
    ("She gave me a present.", "Она подарила мне подарок.", None),
    ("We gave them the keys.", "Мы отдали им ключи.", None),
    ("He took my seat.", "Он занял моё место.", None),
    ("I met her at the station.", "Я встретил её на вокзале.", None),
    ("We met in 2020.", "Мы познакомились в 2020-м.", None),
    ("She met an old friend.", "Она встретила старого друга.", None),
    ("I spoke to the manager.", "Я поговорил с менеджером.", None),
    ("He spoke slowly.", "Он говорил медленно.", None),
    ("We spoke about the plan.", "Мы поговорили о плане.", None),
    ("She left early.", "Она ушла рано.", None),
    ("The train left at seven.", "Поезд отправился в семь.", None),
    ("I left my bag in the taxi.", "Я оставил сумку в такси.", None),
    ("He left the hotel at noon.", "Он выехал из отеля в полдень.", None),
    ("I read the book in two days.", "Я прочитал книгу за два дня.", None),
    ("She read the message.", "Она прочитала сообщение.", None),
    ("We read about it online.", "Мы читали об этом онлайн.", None),
    ("I wrote a message.", "Я написал сообщение.", None),
    ("She wrote down the address.", "Она записала адрес.", None),
    ("He wrote a letter.", "Он написал письмо.", None),
    ("I ate too much.", "Я слишком много съел.", None),
    ("We ate at a small café.", "Мы поели в маленьком кафе.", None),
    ("She ate nothing.", "Она ничего не ела.", None),
    ("He drank all the coffee.", "Он выпил весь кофе.", None),
    ("I drank a lot of water.", "Я выпил много воды.", None),
    ("We drank tea and talked.", "Мы пили чай и разговаривали.", None),
    ("I slept badly.", "Я плохо спал.", None),
    ("She slept for ten hours.", "Она проспала десять часов.", None),
    ("He fell on the stairs.", "Он упал на лестнице.", None),
    ("The glass fell and broke.", "Стакан упал и разбился.", None),
    ("I felt bad yesterday.", "Вчера мне было плохо.", None),
    ("She felt much better.", "Она почувствовала себя гораздо лучше.", None),
    ("We felt at home.", "Мы чувствовали себя как дома.", None),
    ("I woke up at six.", "Я проснулся в шесть.", None),
    ("She woke up late.", "Она проснулась поздно.", None),
    ("They understood everything.", "Они всё поняли.", None),
    ("I understood you well.", "Я хорошо тебя понял.", None),
]

C04 = [
    ("I was at home all evening.", "Я был дома весь вечер.", None),
    ("I was at home.", "Я был дома.", None),
    ("She was at work.", "Она была на работе.", None),
    ("He was in the shower.", "Он был в душе.", None),
    ("We were at the airport.", "Мы были в аэропорту.", None),
    ("They were in Paris.", "Они были в Париже.", None),
    ("The room was small but clean.", "Номер был маленький, но чистый.", None),
    ("The room was dirty.", "Номер был грязный.", None),
    ("The weather was great.", "Погода была отличная.", None),
    ("The food was delicious.", "Еда была очень вкусной.", None),
    ("The flight was long.", "Перелёт был долгим.", None),
    ("The film was boring.", "Фильм был скучным.", None),
    ("The trip was amazing.", "Поездка была потрясающей.", None),
    ("My booking was for two nights.", "Моя бронь была на две ночи.", None),
    ("The meeting was at ten.", "Встреча была в десять.", None),
    ("It was late.", "Было поздно.", None),
    ("It was cold in the room.", "В номере было холодно.", None),
    ("The wifi was free.", "Вайфай был бесплатным.", None),
    ("The staff was friendly.", "Персонал был дружелюбным.", None),
    ("I was tired after the flight.", "Я устал после перелёта.", None),
    ("She was right.", "Она была права.", None),
    ("He was wrong.", "Он был неправ.", None),
    ("We were hungry.", "Мы были голодны.", None),
    ("They were ready to go.", "Они были готовы идти.", None),
    ("I wasn't at home.", "Меня не было дома.", None),
    ("She wasn't happy with the room.", "Она была недовольна номером.", None),
    ("The hotel wasn't full.", "Отель не был заполнен.", None),
    ("We weren't tired.", "Мы не устали.", None),
    ("They weren't late.", "Они не опоздали.", None),
    ("It wasn't expensive.", "Это было недорого.", None),
    ("The breakfast wasn't included.", "Завтрак не был включён.", None),
    ("Was the flight OK?", "Перелёт был нормальным?", None),
    ("Were you at the hotel?", "Ты был в отеле?", None),
    ("Was she at the meeting?", "Она была на встрече?", None),
    ("Were they at the party?", "Они были на вечеринке?", None),
    ("Where were you yesterday?", "Где ты был вчера?", None),
    ("How was your day?", "Как прошёл твой день?", None),
    ("How was the trip?", "Как прошла поездка?", None),
    ("How was the weather?", "Какая была погода?", None),
    ("What was the problem?", "В чём была проблема?", None),
    ("Why was he angry?", "Почему он был злой?", None),
    ("Yes, I was.", "Да.", None),
    ("No, I wasn't.", "Нет.", None),
    ("That was strange.", "Это было странно.", None),
    ("Those were the best days.", "Это были лучшие дни.", None),
]

C05 = [
    ("I visited Rome last spring.", "Я посетил Рим прошлой весной.", None),
    ("We went by plane.", "Мы полетели на самолёте.", None),
    ("She was tired in the evening.", "Вечером она устала.", None),
    ("They were at the museum.", "Они были в музее.", None),
    ("I saw an old friend.", "Я встретил старого друга.", None),
    ("He took my luggage.", "Он взял мой багаж.", None),
    ("We had dinner at seven.", "Мы ужинали в семь.", None),
    ("She made a cake.", "Она испекла торт.", None),
    ("I came back on Monday.", "Я вернулся в понедельник.", None),
    ("They left in the morning.", "Они уехали утром.", None),
    ("I didn't visit the museum.", "Я не ходил в музей.", None),
    ("We didn't go out.", "Мы не выходили из дома.", None),
    ("She didn't see the message.", "Она не увидела сообщение.", None),
    ("He didn't take the car.", "Он не взял машину.", None),
    ("They didn't have time.", "У них не было времени.", None),
    ("I didn't know that.", "Я этого не знал.", None),
    ("We didn't eat much.", "Мы мало ели.", None),
    ("She didn't feel well.", "Ей было нездорово.", None),
    ("I wasn't at work yesterday.", "Вчера меня не было на работе.", None),
    ("They weren't at home.", "Их не было дома.", None),
    ("Did you visit the old town?", "Ты ходил в старый город?", None),
    ("Did she go with you?", "Она пошла с тобой?", None),
    ("Did he like the hotel?", "Ему понравился отель?", None),
    ("Did they have a good time?", "Они хорошо провели время?", None),
    ("Did you see the sea?", "Ты видел море?", None),
    ("Were you tired?", "Ты устал?", None),
    ("Was the hotel good?", "Отель был хороший?", None),
    ("Were your friends there?", "Твои друзья были там?", None),
    ("What did you do yesterday?", "Что ты делал вчера?", None),
    ("Where did you go?", "Куда ты ходил?", None),
    ("Where did you stay?", "Где ты останавливался?", None),
    ("What did you eat?", "Что ты ел?", None),
    ("Who did you meet?", "Кого ты встретил?", None),
    ("How did you get there?", "Как ты туда добрался?", None),
    ("I stayed two nights.", "Я остановился на две ночи.", None),
    ("We booked a small room.", "Мы забронировали маленький номер.", None),
    ("The city was beautiful.", "Город был красивым.", None),
    ("Everything was fine.", "Всё было хорошо.", None),
    ("It was a long day.", "Это был долгий день.", None),
    ("I met a lot of people.", "Я встретил много людей.", None),
    ("We spoke English all day.", "Мы весь день говорили по-английски.", None),
    ("I understood almost everything.", "Я понял почти всё.", None),
    ("That was a good trip.", "Это была хорошая поездка.", None),
    ("I want to go back.", "Я хочу туда вернуться.", None),
]

C06 = [
    ("I didn't go to work.", "Я не пошёл на работу.", None),
    ("She didn't come to the party.", "Она не пришла на вечеринку.", None),
    ("I didn't go to the party.", "Я не пошёл на вечеринку.", None),
    ("He didn't call me.", "Он мне не позвонил.", None),
    ("We didn't like the film.", "Фильм нам не понравился.", None),
    ("They didn't understand the rule.", "Они не поняли правило.", None),
    ("I didn't see him.", "Я его не видел.", None),
    ("She didn't hear the question.", "Она не услышала вопрос.", None),
    ("He didn't take the money.", "Он не взял деньги.", None),
    ("We didn't have breakfast.", "Мы не завтракали.", None),
    ("They didn't know about it.", "Они не знали об этом.", None),
    ("I didn't say that.", "Я этого не говорил.", None),
    ("She didn't tell anyone.", "Она никому не сказала.", None),
    ("He didn't buy anything.", "Он ничего не купил.", None),
    ("We didn't eat at the hotel.", "Мы не ели в отеле.", None),
    ("They didn't stay long.", "Они долго не задержались.", None),
    ("I didn't sleep well.", "Я плохо спал.", None),
    ("She didn't feel any pain.", "Она не чувствовала никакой боли.", None),
    ("He didn't make mistakes.", "Он не делал ошибок.", None),
    ("I didn't want to leave.", "Я не хотел уезжать.", None),
    ("We didn't pay by card.", "Мы не платили картой.", None),
    ("I didn't work yesterday.", "Я не работал вчера.", None),
    ("She didn't answer my message.", "Она не ответила на моё сообщение.", None),
    ("The shop didn't open.", "Магазин не открылся.", None),
    ("He didn't find his keys.", "Он не нашёл ключи.", None),
    ("I didn't take a taxi.", "Я не взял такси.", None),
    ("We didn't watch TV.", "Мы не смотрели телевизор.", None),
    ("They didn't play well.", "Они играли плохо.", None),
    ("She didn't write to me.", "Она мне не написала.", None),
    ("It didn't rain.", "Дождя не было.", None),
    ("The bus didn't come.", "Автобус не пришёл.", None),
    ("I didn't need help.", "Мне не нужна была помощь.", None),
    ("He didn't speak to me.", "Он со мной не разговаривал.", None),
    ("We didn't wait long.", "Мы недолго ждали.", None),
    ("They didn't ask questions.", "Они не задавали вопросов.", None),
    ("I didn't know the way.", "Я не знал дорогу.", None),
    ("She didn't book the room.", "Она не забронировала номер.", None),
    ("He didn't like the food.", "Ему не понравилась еда.", None),
    ("I didn't do anything wrong.", "Я ничего плохого не сделал.", None),
    ("We didn't meet anyone.", "Мы никого не встретили.", None),
    ("They didn't tell us the truth.", "Они не сказали нам правду.", None),
    ("I didn't get your message.", "Я не получил твоё сообщение.", None),
    ("She didn't go out at all.", "Она вообще не выходила из дома.", None),
    ("Nothing happened.", "Ничего не случилось.", None),
    ("It didn't matter.", "Это не имело значения.", None),
]

C07 = [
    ("Did you see my bag?", "Ты не видел мою сумку?", None),
    ("Did you see the film?", "Ты видел фильм?", None),
    ("Did you check the room?", "Ты проверил номер?", None),
    ("Did you call the hotel?", "Ты позвонил в отель?", None),
    ("Did she like the city?", "Ей понравился город?", None),
    ("Did he find the keys?", "Он нашёл ключи?", None),
    ("Did they enjoy the trip?", "Им понравилась поездка?", None),
    ("Did you speak to the doctor?", "Ты поговорил с врачом?", None),
    ("Did she book the table?", "Она забронировала столик?", None),
    ("Did you pack everything?", "Ты всё собрал?", None),
    ("Did he pay for the room?", "Он заплатил за номер?", None),
    ("Where did you stay?", "Где ты останавливался?", None),
    ("Where did you eat?", "Где ты ел?", None),
    ("Where did she work?", "Где она работала?", None),
    ("What did you do?", "Что ты делал?", None),
    ("What did he say?", "Что он сказал?", None),
    ("What did they buy?", "Что они купили?", None),
    ("What time did you get up?", "Во сколько ты встал?", None),
    ("What did she tell you?", "Что она тебе сказала?", None),
    ("When did you arrive?", "Когда ты приехал?", None),
    ("When did the film start?", "Когда начался фильм?", None),
    ("When did they leave?", "Когда они уехали?", None),
    ("Why did you go there?", "Почему ты туда пошёл?", None),
    ("Why did she call me?", "Почему она мне звонила?", None),
    ("Why did he say that?", "Почему он это сказал?", None),
    ("How did you get there?", "Как ты туда добрался?", None),
    ("How did it happen?", "Как это случилось?", None),
    ("How much did it cost?", "Сколько это стоило?", None),
    ("How long did you stay?", "Как долго ты оставался?", None),
    ("Who did you see?", "Кого ты видел?", None),
    ("Who did you tell?", "Кому ты сказал?", None),
    ("Who did they invite?", "Кого они пригласили?", None),
    ("I saw your bag in the hall.", "Я видел твою сумку в коридоре.", None),
    ("I checked everything twice.", "Я всё проверил дважды.", None),
    ("She liked it a lot.", "Ей это очень понравилось.", None),
    ("He found them under the sofa.", "Он нашёл их под диваном.", None),
    ("We stayed at a guest house.", "Мы остановились в гостевом доме.", None),
    ("I spoke to him in the morning.", "Я поговорил с ним утром.", None),
    ("They arrived late at night.", "Они приехали поздно ночью.", None),
    ("I told you about it.", "Я тебе об этом говорил.", None),
    ("It happened two days ago.", "Это случилось два дня назад.", None),
    ("It cost twenty dollars.", "Это стоило двадцать долларов.", None),
    ("We got there by taxi.", "Мы добрались туда на такси.", None),
    ("I saw Anna at the café.", "Я видел Анну в кафе.", None),
    ("What happened next?", "Что было дальше?", None),
    ("And then what?", "И что потом?", None),
]

C08 = [
    ("I usually get up at seven, but yesterday I got up at nine.", "Обычно я встаю в семь, но вчера встал в девять.", None),
    ("She usually walks, but today she took a bus.", "Обычно она ходит пешком, но сегодня поехала на автобусе.", None),
    ("We often eat at home, but yesterday we ate out.", "Мы часто едим дома, но вчера поели в кафе.", None),
    ("He always drinks tea, but this morning he drank coffee.", "Он всегда пьёт чай, но сегодня утром выпил кофе.", None),
    ("I work every day.", "Я работаю каждый день.", None),
    ("I worked all day yesterday.", "Вчера я проработал весь день.", None),
    ("She goes to the gym on Mondays.", "Она ходит в зал по понедельникам.", None),
    ("She went to the gym yesterday.", "Вчера она сходила в зал.", None),
    ("We often travel by train.", "Мы часто ездим на поезде.", None),
    ("Last month we travelled by car.", "В прошлом месяце мы ездили на машине.", None),
    ("Do you often see them?", "Ты часто их видишь?", None),
    ("Did you see them yesterday?", "Ты видел их вчера?", None),
    ("Does he know the city?", "Он знает город?", None),
    ("Did he know the way?", "Он знал дорогу?", None),
    ("Yesterday I visited my parents.", "Вчера я навестил родителей.", None),
    ("Last week she was in Berlin.", "На прошлой неделе она была в Берлине.", None),
    ("Last year we went to Italy.", "В прошлом году мы ездили в Италию.", None),
    ("Two days ago it rained.", "Два дня назад шёл дождь.", None),
    ("A minute ago he was here.", "Минуту назад он был здесь.", None),
    ("In 2019 they moved to London.", "В 2019-м они переехали в Лондон.", None),
    ("When I was a child, I played outside a lot.", "В детстве я много играл на улице.", None),
    ("This morning I woke up early.", "Сегодня утром я проснулся рано.", None),
    ("Today I am busy.", "Сегодня я занят.", None),
    ("Tonight we are free.", "Сегодня вечером мы свободны.", None),
    ("Now I understand.", "Теперь я понимаю.", None),
    ("At that time I didn't understand.", "Тогда я не понимал.", None),
    ("He usually drives, but yesterday he walked.", "Обычно он водит машину, но вчера пошёл пешком.", None),
    ("I don't watch TV in the morning.", "Я не смотрю телевизор утром.", None),
    ("I didn't watch TV yesterday.", "Я не смотрел телевизор вчера.", None),
    ("What do you usually do on Sundays?", "Что ты обычно делаешь по воскресеньям?", None),
    ("What did you do last Sunday?", "Что ты делал в прошлое воскресенье?", None),
    ("Where do you work?", "Где ты работаешь?", None),
    ("Where did you work before?", "Где ты работал раньше?", None),
    ("I live in Moscow now.", "Сейчас я живу в Москве.", None),
    ("I lived in Rome for a year.", "Я год жил в Риме.", None),
    ("We know each other well.", "Мы хорошо знаем друг друга.", None),
    ("We met two years ago.", "Мы познакомились два года назад.", None),
    ("The shop opens at nine.", "Магазин открывается в девять.", None),
    ("The shop opened late yesterday.", "Вчера магазин открылся поздно.", None),
    ("She is often late.", "Она часто опаздывает.", None),
    ("She was late again.", "Она снова опоздала.", None),
    ("Time flies.", "Время летит.", None),
    ("Those days are gone.", "Те дни прошли.", None),
    ("Everything changes.", "Всё меняется.", None),
]

C09 = [
    ("What happened?", "Что случилось?", None),
    ("What happened next?", "Что случилось потом?", None),
    ("Who said that?", "Кто это сказал?", None),
    ("Who called you?", "Кто тебе звонил?", None),
    ("Who broke the window?", "Кто разбил окно?", None),
    ("Who took my pen?", "Кто взял мою ручку?", None),
    ("Who paid the bill?", "Кто оплатил счёт?", None),
    ("Who helped you?", "Кто тебе помог?", None),
    ("Who won the game?", "Кто выиграл игру?", None),
    ("Who knew about it?", "Кто знал об этом?", None),
    ("What changed your mind?", "Что изменило твоё решение?", None),
    ("What made you laugh?", "Что тебя рассмешило?", None),
    ("What went wrong?", "Что пошло не так?", None),
    ("What surprised you?", "Что тебя удивило?", None),
    ("What hurt him?", "Что причинило ему боль?", None),
    ("Who saw him last?", "Кто видел его последним?", None),
    ("Who told you the news?", "Кто рассказал тебе новость?", None),
    ("Who wrote this letter?", "Кто написал это письмо?", None),
    ("Who made this decision?", "Кто принял это решение?", None),
    ("Who lost the keys?", "Кто потерял ключи?", None),
    ("Nobody saw him.", "Никто его не видел.", None),
    ("Everyone knew the answer.", "Все знали ответ.", None),
    ("Something happened.", "Что-то случилось.", None),
    ("Nothing happened.", "Ничего не случилось.", None),
    ("I don't know what happened.", "Я не знаю, что случилось.", None),
    ("The car stopped.", "Машина остановилась.", None),
    ("The light went out.", "Свет погас.", None),
    ("The plane took off on time.", "Самолёт вылетел вовремя.", None),
    ("The show started at eight.", "Шоу началось в восемь.", None),
    ("It began to rain.", "Начался дождь.", None),
    ("He fell asleep.", "Он заснул.", None),
    ("She woke up at midnight.", "Она проснулась в полночь.", None),
    ("We ran to the bus.", "Мы побежали к автобусу.", None),
    ("They drove all night.", "Они ехали всю ночь.", None),
    ("I forgot her name.", "Я забыл её имя.", None),
    ("He remembered everything.", "Он всё вспомнил.", None),
    ("It took an hour.", "Это заняло час.", None),
    ("The door opened slowly.", "Дверь медленно открылась.", None),
    ("The phone rang again.", "Телефон снова зазвонил.", None),
    ("Everything went well.", "Всё прошло хорошо.", None),
    ("It could happen to anyone.", "Это могло случиться с кем угодно.", None),
    ("Then everything changed.", "А потом всё изменилось.", None),
    ("That was the best day.", "Это был лучший день.", None),
    ("It ended too soon.", "Это закончилось слишком быстро.", None),
]

C10 = [
    ("I visited my grandmother last weekend.", "Я навестил бабушку в прошлые выходные.", None),
    ("We went to the mountains by car.", "Мы поехали в горы на машине.", None),
    ("The weather was perfect.", "Погода была идеальной.", None),
    ("I didn't know the place.", "Я не знал это место.", None),
    ("She took a lot of photos.", "Она сделала много фото.", None),
    ("We had lunch at a small café.", "Мы пообедали в маленьком кафе.", None),
    ("He lost his phone on the way.", "Он потерял телефон по дороге.", None),
    ("I found it in my bag later.", "Позже я нашёл его в своей сумке.", None),
    ("Was the food good?", "Еда была хорошей?", None),
    ("Did you sleep well?", "Ты хорошо спал?", None),
    ("I wasn't hungry in the morning.", "Утром я не был голоден.", None),
    ("We weren't tired at all.", "Мы совсем не устали.", None),
    ("What did you do in the evening?", "Что вы делали вечером?", None),
    ("Where did you have dinner?", "Где вы ужинали?", None),
    ("Who drove the car?", "Кто вёл машину?", None),
    ("Who paid for the petrol?", "Кто заплатил за бензин?", None),
    ("I was born in a small town.", "Я родился в маленьком городе.", None),
    ("She was the best student in class.", "Она была лучшей ученицей в классе.", None),
    ("They were happy together.", "Они были счастливы вместе.", None),
    ("It was a long time ago.", "Это было давно.", None),
    ("I went, I saw, I liked.", "Я съездил, посмотрел, мне понравилось.", None),
    ("He came, he helped, he left.", "Он пришёл, помог и ушёл.", None),
    ("We didn't stay long.", "Мы долго не задержались.", None),
    ("She didn't say why.", "Она не сказала почему.", None),
    ("They didn't tell us the price.", "Они не сказали нам цену.", None),
    ("Did he like the gift?", "Ему понравился подарок?", None),
    ("Did it cost much?", "Это много стоило?", None),
    ("When did you get back?", "Когда ты вернулся?", None),
    ("How did you sleep?", "Как ты спал?", None),
    ("What was the hotel like?", "Каким был отель?", None),
    ("I met them at the station.", "Я встретил их на вокзале.", None),
    ("We spoke about old times.", "Мы говорили о старых временах.", None),
    ("The trip took three hours.", "Дорога заняла три часа.", None),
    ("It rained in the morning, but the sun came out later.", "Утром шёл дождь, но позже выглянуло солнце.", None),
    ("Everything went fine.", "Всё прошло хорошо.", None),
    ("I want to tell you about my trip.", "Я хочу рассказать тебе о своей поездке.", None),
    ("Last summer changed everything.", "Прошлое лето всё изменило.", None),
    ("We spent two weeks by the sea.", "Мы провели две недели у моря.", None),
    ("I bought nothing special.", "Я не купил ничего особенного.", None),
    ("She taught me a new word.", "Она научила меня новому слову.", None),
    ("He showed me the photos.", "Он показал мне фото.", None),
    ("The day started badly but ended well.", "День начался плохо, но закончился хорошо.", None),
    ("I kept the ticket as a memory.", "Я оставил билет на память.", None),
    ("Those were great days.", "Это были прекрасные дни.", None),
    ("I visit my grandmother.", "Я навещаю бабушку.", None),
    ("I visited my grandmother.", "Я навестил бабушку.", None),
    ("He goes to work by car.", "Он ездит на работу на машине.", None),
    ("He went to work by car.", "Он поехал на работу на машине.", None),
    ("We see them every day.", "Мы видим их каждый день.", None),
    ("We saw them every day.", "Мы видели их каждый день.", None),
]

# --------------------------------------------------------------------------
# C2 «Будущее» (C-11…C-15)
# --------------------------------------------------------------------------
C11 = [
    ("I will call you tomorrow.", "Я позвоню тебе завтра.", None),
    ("I will call you.", "Я тебе позвоню.", None),
    ("I will help you.", "Я тебе помогу.", None),
    ("I'll call you tomorrow.", "Я позвоню тебе завтра.", ["I will call you tomorrow."]),
    ("We will arrive at six.", "Мы приедем в шесть.", None),
    ("She will like the city.", "Город ей понравится.", None),
    ("He will help us.", "Он нам поможет.", None),
    ("They will come next week.", "Они приедут на следующей неделе.", None),
    ("I will be there on time.", "Я буду там вовремя.", None),
    ("I'll be back in five minutes.", "Я вернусь через пять минут.", ["I will be back in five minutes."]),
    ("The flight will be late.", "Рейс задержится.", None),
    ("The weather will be good.", "Погода будет хорошей.", None),
    ("It will be hot tomorrow.", "Завтра будет жарко.", None),
    ("Everything will be fine.", "Всё будет хорошо.", None),
    ("I will pay by card.", "Я заплачу картой.", None),
    ("I'll pay for dinner.", "Я заплачу за ужин.", ["I will pay for dinner."]),
    ("We will see.", "Посмотрим.", None),
    ("I will remember this day.", "Я запомню этот день.", None),
    ("You will love this film.", "Тебе понравится этот фильм.", None),
    ("She will understand everything.", "Она всё поймёт.", None),
    ("I will never forget it.", "Я этого никогда не забуду.", None),
    ("This will be interesting.", "Это будет интересно.", None),
    ("I'll take the Ring to Mordor.", "Я отнесу Кольцо в Мордор.", None),
    ("I will do it myself.", "Я сделаю это сам.", None),
    ("We will wait for you.", "Мы тебя подождём.", None),
    ("The taxi will be here soon.", "Такси скоро будет здесь.", None),
    ("I will send you the address.", "Я пришлю тебе адрес.", None),
    ("He will meet us at the airport.", "Он встретит нас в аэропорту.", None),
    ("I'll have the same.", "Мне то же самое.", ["I will have the same."]),
    ("The shop will open at nine.", "Магазин откроется в девять.", None),
    ("The meeting will start soon.", "Встреча скоро начнётся.", None),
    ("I will show you the city.", "Я покажу тебе город.", None),
    ("You will find the way.", "Ты найдёшь дорогу.", None),
    ("It won't take long.", "Это не займёт много времени.", ["It will not take long."]),
    ("I will always remember you.", "Я всегда буду тебя помнить.", None),
    ("The train will be full.", "Поезд будет полным.", None),
    ("We will be friends.", "Мы будем друзьями.", None),
    ("I promise I will be careful.", "Обещаю, я буду осторожен.", None),
    ("I'll never leave you.", "Я никогда тебя не оставлю.", ["I will never leave you."]),
    ("Time will tell.", "Время покажет.", None),
    ("This day will come.", "Этот день наступит.", None),
    ("I will try again tomorrow.", "Завтра я попробую снова.", None),
    ("We will never give up.", "Мы никогда не сдадимся.", None),
    ("Everything will change.", "Всё изменится.", None),
    ("It will be a great trip.", "Это будет отличная поездка.", None),
    ("See you tomorrow!", "До завтра!", None),
]

C12 = [
    ("I won't tell anyone.", "Я никому не скажу.", ["I will not tell anyone."]),
    ("He won't come today.", "Он не придёт сегодня.", ["He will not come today."]),
    ("She won't like it.", "Ей это не понравится.", None),
    ("We won't be late.", "Мы не опоздаем.", ["We will not be late."]),
    ("They won't wait for us.", "Они нас не дождутся.", None),
    ("It won't rain tomorrow.", "Завтра не будет дождя.", None),
    ("The flight won't be cheap.", "Перелёт не будет дешёвым.", None),
    ("I won't forget you.", "Я тебя не забуду.", None),
    ("He won't be a boy forever.", "Он не будет мальчиком вечно.", None),
    ("This won't happen again.", "Это больше не повторится.", None),
    ("Will you come with me?", "Ты пойдёшь со мной?", None),
    ("Will you help me?", "Ты мне поможешь?", None),
    ("Will you join us?", "Ты присоединишься к нам?", None),
    ("Will you wait a minute?", "Подождёшь минутку?", None),
    ("Will she like the gift?", "Ей понравится подарок?", None),
    ("Will he be at the party?", "Он будет на вечеринке?", None),
    ("Will they come tomorrow?", "Они приедут завтра?", None),
    ("Will it be open on Sunday?", "В воскресенье будет открыто?", None),
    ("Will the flight be on time?", "Рейс будет вовремя?", None),
    ("Will you be at home tonight?", "Ты будешь дома вечером?", None),
    ("Yes, I will.", "Да.", None),
    ("No, I won't.", "Нет, не буду.", None),
    ("Yes, we will.", "Да.", None),
    ("I hope so.", "Надеюсь.", None),
    ("I'm afraid not.", "Боюсь, что нет.", None),
    ("Where will you stay?", "Где вы остановитесь?", None),
    ("What will you do tomorrow?", "Что ты будешь делать завтра?", None),
    ("What time will you come?", "Во сколько ты придёшь?", None),
    ("When will they arrive?", "Когда они приедут?", None),
    ("How long will it take?", "Сколько это займёт?", None),
    ("How much will it cost?", "Сколько это будет стоить?", None),
    ("Who will win?", "Кто победит?", None),
    ("It will be cold at night.", "Ночью будет холодно.", None),
    ("The weather will be worse.", "Погода будет хуже.", None),
    ("I think it will be fine.", "Думаю, всё будет хорошо.", None),
    ("I don't think he will come.", "Не думаю, что он придёт.", None),
    ("Maybe we will see them later.", "Может, мы увидим их позже.", None),
    ("Probably she will call you.", "Вероятно, она тебе позвонит.", None),
    ("Sure, I will help you.", "Конечно, я тебе помогу.", None),
    ("Sorry, I won't be able to come.", "Извини, я не смогу прийти.", None),
    ("Let's see what happens.", "Посмотрим, что будет.", None),
    ("Winter is coming.", "Зима приближается.", None),
    ("Everything will be different.", "Всё будет иначе.", None),
    ("Nothing will change.", "Ничего не изменится.", None),
]

C13 = [
    ("When will you be free?", "Когда ты будешь свободен?", None),
    ("Where will we meet?", "Где мы встретимся?", None),
    ("What will we do there?", "Что мы там будем делать?", None),
    ("Which film will we watch?", "Какой фильм мы посмотрим?", None),
    ("Who will drive?", "Кто будет вести машину?", None),
    ("Who will pay?", "Кто будет платить?", None),
    ("Why will she say no?", "Почему она откажет?", None),
    ("How will we get there?", "Как мы туда доберёмся?", None),
    ("What time will the show start?", "Во сколько начнётся шоу?", None),
    ("How long will the flight take?", "Сколько займёт перелёт?", None),
    ("I will be able to help you tomorrow.", "Я смогу помочь тебе завтра.", None),
    ("Will you be able to come?", "Ты сможешь прийти?", None),
    ("She won't be able to work this week.", "На этой неделе она не сможет работать.", None),
    ("I can swim now, and I will be able to swim there too.", "Я умею плавать и там тоже смогу плавать.", None),
    ("I will be able to help you.", "Я смогу тебе помочь.", None),
    ("I won't be able to come.", "Я не смогу прийти.", None),
    ("He managed to find the hotel.", "Ему удалось найти отель.", None),
    ("We managed to catch the last train.", "Мы успели на последний поезд.", None),
    ("She managed to pass the exam.", "Ей удалось сдать экзамен.", None),
    ("I managed to open the door.", "Мне удалось открыть дверь.", None),
    ("They managed to escape.", "Им удалось сбежать.", None),
    ("He couldn't come, but he will come next time.", "Он не смог прийти, но в следующий раз придёт.", None),
    ("Tomorrow I will know the answer.", "Завтра я буду знать ответ.", None),
    ("You will see everything with your own eyes.", "Ты всё увидишь своими глазами.", None),
    ("Will it be easy?", "Это будет легко?", None),
    ("It will be difficult, but we will try.", "Это будет трудно, но мы попробуем.", None),
    ("Next year we will travel more.", "В следующем году мы будем путешествовать больше.", None),
    ("In an hour I will be free.", "Через час я освобожусь.", None),
    ("Soon everything will be clear.", "Скоро всё станет ясно.", None),
    ("One day you will understand me.", "Однажды ты меня поймёшь.", None),
    ("I will always be there for you.", "Я всегда буду рядом.", None),
    ("Will you marry me?", "Ты выйдешь за меня?", None),
    ("What will the future bring?", "Что принесёт будущее?", None),
    ("Nobody will know.", "Никто не узнает.", None),
    ("Everyone will hear about it.", "Все об этом услышат.", None),
    ("The world will change.", "Мир изменится.", None),
    ("We will see about that.", "Это мы ещё посмотрим.", None),
    ("I will never do it again.", "Я больше никогда так не сделаю.", None),
    ("You will regret it.", "Ты об этом пожалеешь.", None),
    ("It will be worth it.", "Это будет того стоить.", None),
    ("This will be our secret.", "Это будет наш секрет.", None),
    ("I will do my best.", "Я сделаю всё возможное.", None),
    ("We will find a way.", "Мы найдём выход.", None),
    ("Hope for the best.", "Надейся на лучшее.", None),
    ("Time will show.", "Время покажет.", None),
    ("The best is yet to come.", "Всё самое лучшее ещё впереди.", None),
]

C14 = [
    ("I'm going to travel this summer.", "Этим летом я собираюсь путешествовать.", None),
    ("We are going to visit Rome.", "Мы собираемся посетить Рим.", None),
    ("She is going to study English.", "Она собирается учить английский.", None),
    ("He is going to buy a car.", "Он собирается купить машину.", None),
    ("They are going to move to Berlin.", "Они собираются переехать в Берлин.", None),
    ("I'm going to call the police.", "Я вызову полицию.", ["I am going to call the police."]),
    ("What are you going to do?", "Что ты собираешься делать?", None),
    ("Where are you going to stay?", "Где вы собираетесь остановиться?", None),
    ("When are they going to leave?", "Когда они собираются уезжать?", None),
    ("What are we going to eat?", "Что мы будем есть?", None),
    ("It is going to rain.", "Собирается дождь.", None),
    ("The sky is dark — it's going to storm.", "Небо тёмное — будет гроза.", None),
    ("I'm not going to wait any longer.", "Я больше не собираюсь ждать.", None),
    ("We aren't going to pay twice.", "Мы не собираемся платить дважды.", None),
    ("She isn't going to like it.", "Ей это не понравится.", None),
    ("Are you going to finish it today?", "Ты собираешься закончить это сегодня?", None),
    ("Is he going to help us?", "Он собирается нам помочь?", None),
    ("Are they going to come?", "Они собираются прийти?", None),
    ("I'm going to be a hunter.", "Я стану охотником.", None),
    ("We're going to win.", "Мы победим.", ["We will win."]),
    ("I'm going to protect my family.", "Я защищу свою семью.", None),
    ("Look at the clouds!", "Посмотри на облака!", None),
    ("I'm going to try.", "Я попробую.", ["I'll try."]),
    ("What's going to happen?", "Что будет?", None),
    ("Nothing is going to stop me.", "Меня ничто не остановит.", ["Nothing will stop me."]),
    ("I'm going to say what I think.", "Я скажу, что думаю.", None),
    ("We are going to be late.", "Мы опоздаем.", None),
    ("The bus is going to leave.", "Автобус сейчас отойдёт.", None),
    ("I'm going to bed.", "Я иду спать.", None),
    ("Are you going to the party?", "Ты идёшь на вечеринку?", None),
    ("I was going to call you.", "Я собирался тебе позвонить.", None),
    ("She was going to tell him.", "Она собиралась ему сказать.", None),
    ("We were going to take a taxi.", "Мы собирались взять такси.", None),
    ("I'm going to do what's called a pro gamer move.", "Я сделаю то, что называется про-геймерским приёмом.", None),
    ("This is going to be great.", "Это будет здорово.", ["This will be great."]),
    ("It's not going to be easy.", "Это будет непросто.", ["It won't be easy."]),
    ("Who is going to help us?", "Кто нам поможет?", None),
    ("Everything is going to change.", "Всё изменится.", ["Everything will change."]),
    ("I'm going to remember this moment.", "Я запомню этот момент.", None),
    ("We're going to have a great time.", "Мы отлично проведём время.", ["We will have a great time."]),
    ("Plans are going to change.", "Планы изменятся.", None),
    ("I'm going to start next Monday.", "Я начну в следующий понедельник.", None),
    ("Nothing is going to happen.", "Ничего не случится.", None),
    ("Watch me.", "Ну смотри.", None),
]

C15 = [
    ("I will call you tomorrow.", "Я позвоню тебе завтра.", None),
    ("I will call you.", "Я тебе позвоню.", None),
    ("I will help you.", "Я тебе помогу.", None),
    ("I'm going to visit my aunt.", "Я собираюсь навестить тётю.", None),
    ("I think it will rain.", "Думаю, будет дождь.", None),
    ("It's going to rain — look at the sky.", "Будет дождь — посмотри на небо.", None),
    ("We will see.", "Посмотрим.", None),
    ("We are going to stay two nights.", "Мы остановимся на две ночи.", None),
    ("He won't come.", "Он не придёт.", None),
    ("She isn't going to wait.", "Она не собирается ждать.", None),
    ("Will you help me?", "Ты мне поможешь?", None),
    ("Are you going to eat now?", "Ты будешь есть сейчас?", None),
    ("I'll be back.", "Я вернусь.", None),
    ("I'm going to start a new job.", "Я собираюсь начать новую работу.", ["I will start a new job."]),
    ("The flight will be late.", "Рейс задержится.", None),
    ("The shop is going to close.", "Магазин сейчас закроется.", None),
    ("We won't be long.", "Мы ненадолго.", None),
    ("They're going to love this city.", "Им понравится этот город.", None),
    ("What will you do?", "Что ты будешь делать?", None),
    ("What are you going to buy?", "Что ты собираешься купить?", None),
    ("Where will you be?", "Где ты будешь?", None),
    ("Where are you going to work?", "Где ты собираешься работать?", None),
    ("I was in Rome last spring.", "Я был в Риме прошлой весной.", None),
    ("We went there by train.", "Мы поехали туда на поезде.", None),
    ("She didn't like the hotel.", "Ей не понравился отель.", None),
    ("Did you see the Colosseum?", "Ты видел Колизей?", None),
    ("What did you eat there?", "Что ты там ел?", None),
    ("I visited the museum yesterday.", "Вчера я ходил в музей.", None),
    ("He lost his camera.", "Он потерял камеру.", None),
    ("We found a great café.", "Мы нашли отличное кафе.", None),
    ("The trip was wonderful.", "Поездка была чудесной.", None),
    ("I was tired but happy.", "Я устал, но был счастлив.", None),
    ("I usually work on Saturdays.", "Обычно я работаю по субботам.", None),
    ("I worked last Saturday too.", "И в прошлую субботу я работал.", None),
    ("Who told you that?", "Кто тебе это сказал?", None),
    ("What happened at the end?", "Что случилось в конце?", None),
    ("I'll never forget those days.", "Я никогда не забуду те дни.", None),
    ("Everything is going to be fine.", "Всё будет хорошо.", ["Everything will be fine."]),
    ("I promise.", "Обещаю.", None),
    ("Trust me.", "Доверься мне.", None),
    ("Time will tell.", "Время покажет.", None),
    ("The best is yet to come.", "Всё самое лучшее ещё впереди.", None),
    ("I can do it now.", "Я могу сделать это сейчас.", None),
    ("I will be able to do it later.", "Потом я смогу это сделать.", None),
    ("We managed to see everything.", "Мы успели всё посмотреть.", None),
    ("She was going to stay, but she left.", "Она собиралась остаться, но ушла.", None),
    ("I call you tomorrow.", "Я позвоню тебе завтра.", None),
    ("I will call you tomorrow.", "Я позвоню тебе завтра.", ["I'll call you tomorrow."]),
    ("I visit my aunt.", "Я навещаю тётю.", None),
    ("I visited my aunt.", "Я навестил тётю.", None),
    ("We stay two nights.", "Мы останавливаемся на две ночи.", None),
    ("We will stay two nights.", "Мы остановимся на две ночи.", ["We'll stay two nights."]),
]

RULE_C01 = """**Past Simple: правильные глаголы (+).**
Действие закончилось в прошлом: visit → visit**ed**, stay → stay**ed**.
I **visited** London last year. She **cooked** dinner.
Маркеры: yesterday, last year/week, two days ago, in 2019."""

RULE_C02 = """**Past Simple: неправильные глаголы I (топ-20).**
Вторая форма — из таблицы: go→**went**, make→**made**, see→**saw**,
take→**took**, come→**came**, get→**got**, have→**had**, do→**did**,
say→**said**, tell→**told**, know→**knew**, think→**thought**, buy→**bought**.
I **went** to the shop. He **bought** two tickets."""

RULE_C03 = """**Past Simple: неправильные глаголы II (топ-21–50).**
lose→**lost**, find→**found**, give→**gave**, meet→**met**, speak→**spoke**,
leave→**left**, read→**read**, write→**wrote**, eat→**ate**, drink→**drank**,
sleep→**slept**, fall→**fell**, feel→**felt**, wake→**woke**, understand→**understood**.
I **lost** my passport. We **met** in 2020."""

RULE_C04 = """**was / were: +/−/?.**
I/he/she/it → **was**; you/we/they → **were**.
I **was** at home. They **were** in Paris.
−: I **wasn't** at home. ?: **Were** you at the hotel?
How **was** your day? — It was great!"""

RULE_C05 = """**Повторение №10: прошлое.**
Правильные -ed и неправильные формы; was/were ±?;
Спецвопросы: What/Where/How **did** you…? (did + 1-я форма!)
didn't + 1-я форма: I **didn't go** (не «didn't went»)."""

RULE_C06 = """**Past Simple: отрицание didn't.**
didn't + первая форма: I **didn't go**. She **didn't come**.
❌ I didn't went (после didn't — 1-я форма!).
⚠️ Ловушка: «Я не пошёл» = I didn't go, НЕ «I not went»."""

RULE_C07 = """**Past Simple: вопросы Did…?**
**Did** + подлежащее + 1-я форма: **Did** you **see** my bag?
Спецвопросы: Where **did** you **stay**? What **did** he **say**?
❌ Did you saw? (после did — 1-я форма)."""

RULE_C08 = """**Past Simple vs Present Simple.**
Обычно (каждый день) → Present: I **work** every day.
Закончилось (yesterday, last week) → Past: I **worked** yesterday.
Сравни: Where **do** you work? / Where **did** you work before?"""

RULE_C09 = """**Вопрос к подлежащему в прошедшем.**
Who/What + 2-я форма БЕЗ did: **Who said** that? **What happened**?
❌ Who did say? Сравни: **Who won**? vs **Why did** he **win**?"""

RULE_C10 = """**Повторение №11: прошедшее время.**
Past Simple ±? + was/were + вопросы к подлежащему.
Контрольная: найди ошибку, поставь форму, трансформация в прошедшее.
Маркеры прошедшего: yesterday, ago, last…, in 2019."""

RULE_C11 = """**Future Simple: will (+).**
will + 1-я форма: I **will call** you tomorrow. = I'**ll call**.
Обещания и прогнозы: Everything **will** be fine. I **won't** forget.
will одинаков для всех лиц: he will, they will."""

RULE_C12 = """**will: − и ?.**
Отрицание: I **won't** tell anyone. (= will not)
Вопрос: **Will** you help me? — Yes, I will. / No, I won't.
Спецвопросы: What **will** you do tomorrow? Where **will** you stay?"""

RULE_C13 = """**will: спецвопросы; be able to / manage to.**
How long **will** it take? Who **will** win?
**will be able to** = «смогу» в будущем: I **will be able to** help tomorrow.
**managed to** = «смог/удалось» в прошлом: We **managed to catch** the train."""

RULE_C14 = """**be going to: планы и намерения.**
am/is/are going to + 1-я форма: I'**m going to travel** this summer.
План заранее: We **are going to visit** Rome.
Очевидное будущее: It **is going to** rain (небо тёмное).
will — решение сейчас; going to — план заранее.
⚠️ Ловушка: I'm going **to bed** — это настоящее время («иду спать»), не план!"""

RULE_C15 = """**Повторение №12: будущее и прошедшее.**
will vs be going to: решение vs план; won't, Will you…?
Past Simple маркеры: yesterday, ago, last…; did + 1-я форма.
Контрольная: трансформации будущее/прошедшее, was/were, спецвопросы."""

LESSONS_C1_C2 = [
    {
        "id": "les-c-01", "module": "mod-c-1",
        "title": "Past Simple: правильные глаголы (-ed)",
        "gp_id": "gp-c-01", "gp_title": "Прошедшее: правильные глаголы",
        "rule_md": RULE_C01,
        "phrases": C01,
        "rule_cloze": [
            ("I ___ London last year.", ["visited"]),
            ("She ___ dinner for us.", ["cooked"]),
            ("They ___ a film yesterday.", ["watched"]),
        ],
        "quotes": [("q-attack-on-titan-0012", "received"), ("q-the-100-0010", "dropped")],
        "trap_id": "trap-didnt-past",
        "vocab_band": {"list": "ngsl-spoken", "from": 1961, "to": 2020},
        "phrasebook_topic": None,
        "quotes_topic": "past",
        "bebris_video": {"lesson": "1.64", "playlist_index": 209, "youtube_id": "oE0epGjQEyc", "title": None},
        "answer_question": [("Did you visit London?", "I visited London last year.")],
        "find_error": [("I visit London last year.", "I visited London last year.")],
        "verb_tense": [
            ("We ___ at a small hotel.", "yesterday", ["stayed"]),
            ("He ___ to the station.", "last night", ["walked"]),
            ("She ___ the tickets online.", "last week", ["booked"]),
        ],
    },
    {
        "id": "les-c-02", "module": "mod-c-1",
        "title": "Past Simple: неправильные глаголы I (топ-20)",
        "gp_id": "gp-c-02", "gp_title": "Топ-20 неправильных глаголов",
        "rule_md": RULE_C02,
        "phrases": C02,
        "rule_cloze": [
            ("I ___ to the shop.", ["went"]),
            ("He ___ two tickets.", ["bought"]),
            ("We ___ a great time.", ["had"]),
        ],
        "quotes": [("q-breaking-bad-0006", "won"), ("q-breaking-bad-0007", "was")],
        "trap_id": "trap-didnt-past",
        "vocab_band": {"list": "ngsl-spoken", "from": 2021, "to": 2080},
        "phrasebook_topic": None,
        "quotes_topic": "past",
        "bebris_video": {"lesson": "1.79", "playlist_index": 251, "youtube_id": "oAziZ0eLy68", "title": None},
        "answer_question": [("Did you see him yesterday?", "I saw him yesterday.")],
        "find_error": [("He maked coffee.", "He made coffee.")],
        "verb_tense": [
            ("She ___ home early.", "go", ["went", "came"]),
            ("I ___ a message.", "last night", ["got"]),
            ("He ___ a mistake.", "last week", ["made"]),
        ],
    },
    {
        "id": "les-c-03", "module": "mod-c-1",
        "title": "Past Simple: неправильные глаголы II (топ-21–50)",
        "gp_id": "gp-c-03", "gp_title": "Топ-21–50 неправильных глаголов",
        "rule_md": RULE_C03,
        "phrases": C03,
        "rule_cloze": [
            ("I ___ my passport.", ["lost"]),
            ("He ___ the ticket.", ["found"]),
            ("We ___ in 2020.", ["met"]),
        ],
        "quotes": [("q-game-of-thrones-0012", "send"), ("q-attack-on-titan-0015", "were")],
        "trap_id": "trap-didnt-past",
        "vocab_band": {"list": "ngsl-spoken", "from": 2081, "to": 2140},
        "phrasebook_topic": "emergency",
        "quotes_topic": "past",
        "bebris_video": {"lesson": "1.80", "playlist_index": 253, "youtube_id": "sxmNTfmhs9k", "title": None},
        "answer_question": [("Did you find your phone?", "I found my phone.")],
        "find_error": [("She loss her keys.", "She lost her keys.")],
        "verb_tense": [
            ("I ___ a message.", "yesterday", ["wrote"]),
            ("She ___ nothing.", "at dinner", ["ate"]),
            ("He ___ badly.", "last night", ["slept"]),
        ],
    },
    {
        "id": "les-c-04", "module": "mod-c-1",
        "title": "was / were: +/−/?",
        "gp_id": "gp-c-04", "gp_title": "was/were в прошедшем",
        "rule_md": RULE_C04,
        "phrases": C04,
        "rule_cloze": [
            ("I ___ at home all evening.", ["was"]),
            ("They ___ in Paris.", ["were"]),
            ("___ you at the hotel?", ["Were"]),
        ],
        "quotes": [("q-attack-on-titan-0003", "was"), ("q-attack-on-titan-0004", "was")],
        "trap_id": "trap-no-to-be",
        "vocab_band": {"list": "ngsl-spoken", "from": 2141, "to": 2200},
        "phrasebook_topic": "hotel",
        "quotes_topic": "past",
        "bebris_video": {"lesson": "1.97", "playlist_index": 297, "youtube_id": "073mRqaAExA", "title": None},
        "answer_question": [("Was the flight OK?", "The flight was long.")],
        "find_error": [("I were at home.", "I was at home.")],
        "verb_tense": [
            ("She ___ at work.", "yesterday", ["was"]),
            ("We ___ at the airport.", "at 6", ["were"]),
            ("It ___ cold in the room.", "that night", ["was"]),
        ],
    },
    {
        "id": "les-c-05", "module": "mod-c-1",
        "title": "Повторение №10: прошлое",
        "gp_id": "gp-c-05", "gp_title": "Повторение: Past Simple + was/were",
        "rule_md": RULE_C05,
        "phrases": C05,
        "rule_cloze": [
            ("___ did you do yesterday?", ["What"]),
            ("I ___ at work yesterday.", ["wasn't", "was not"]),
            ("She didn't ___ the message.", ["see", "read"]),
        ],
        "quotes": [("q-igry-0003", "took"), ("q-igry-0014", "died")],
        "trap_id": "trap-didnt-past",
        "vocab_band": {"list": "ngsl-spoken", "from": 2201, "to": 2260},
        "phrasebook_topic": None,
        "quotes_topic": "past",
        "bebris_video": None,
        "answer_question": [("Did you have a good time?", "We had a great time.")],
        "find_error": [("I didn't went to work.", "I didn't go to work.")],
        "verb_tense": [
            ("I ___ an old friend.", "yesterday", ["met", "saw"]),
            ("They ___ at the museum.", "last week", ["were"]),
            ("___ you like the hotel?", "вопрос (прош.)", ["Did"]),
        ],
    },
    {
        "id": "les-c-06", "module": "mod-c-1",
        "title": "Past Simple: отрицание didn't",
        "gp_id": "gp-c-06", "gp_title": "didn't + первая форма",
        "rule_md": RULE_C06,
        "phrases": C06,
        "rule_cloze": [
            ("I ___ go to work.", ["didn't", "did not"]),
            ("He ___ call me.", ["didn't", "did not"]),
            ("We didn't ___ breakfast.", ["have", "eat"]),
        ],
        "quotes": [("q-memy-0010", "pay"), ("q-igry-0008", "still")],
        "trap_id": "trap-didnt-past",
        "vocab_band": {"list": "ngsl-spoken", "from": 2261, "to": 2320},
        "phrasebook_topic": None,
        "quotes_topic": "negation",
        "bebris_video": {"lesson": "1.94", "playlist_index": 291, "youtube_id": "g8ZbFeoUhb0", "title": None},
        "answer_question": [("Did you go to the party?", "I didn't go to the party.")],
        "find_error": [("She didn't came to the party.", "She didn't come to the party.")],
        "verb_tense": [
            ("They didn't ___ about it.", "знать", ["know"]),
            ("I didn't ___ well.", "спать", ["sleep"]),
            ("He didn't ___ anything.", "покупать", ["buy"]),
            ("We didn't ___ breakfast.", "еда", ["have", "eat"]),
        ],
    },
    {
        "id": "les-c-07", "module": "mod-c-1",
        "title": "Past Simple: вопрос Did…? и спецвопросы",
        "gp_id": "gp-c-07", "gp_title": "Вопросы в прошедшем",
        "rule_md": RULE_C07,
        "phrases": C07,
        "rule_cloze": [
            ("___ you see my bag?", ["Did"]),
            ("What ___ he say?", ["did"]),
            ("Where ___ you stay?", ["did"]),
        ],
        "quotes": [("q-attack-on-titan-0004", "was"), ("q-lord-of-the-rings-0003", "had")],
        "trap_id": "trap-question-word-order",
        "vocab_band": {"list": "ngsl-spoken", "from": 2321, "to": 2380},
        "phrasebook_topic": "emergency",
        "quotes_topic": "questions",
        "bebris_video": {"lesson": "1.95", "playlist_index": 293, "youtube_id": "MzvC6xfF4i0", "title": None},
        "answer_question": [("Did you see my bag?", "I saw your bag in the hall.")],
        "find_error": [("Did you saw the film?", "Did you see the film?")],
        "verb_tense": [
            ("___ she like the city?", "вопрос", ["Did"]),
            ("How much ___ it cost?", "сколько стоило", ["did"]),
            ("What time ___ you get up?", "вопрос", ["did"]),
        ],
    },
    {
        "id": "les-c-08", "module": "mod-c-1",
        "title": "Past Simple vs Present Simple: yesterday / usually",
        "gp_id": "gp-c-08", "gp_title": "Контраст времён",
        "rule_md": RULE_C08,
        "phrases": C08,
        "rule_cloze": [
            ("I usually ___ up at seven.", ["get"]),
            ("Yesterday I ___ up at nine.", ["got"]),
            ("Last week we ___ by car.", ["travelled", "went"]),
        ],
        "quotes": [("q-lord-of-the-rings-0003", "had"), ("q-stranger-things-0013", "are")],
        "trap_id": "trap-third-person-s",
        "vocab_band": {"list": "ngsl-spoken", "from": 2381, "to": 2440},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": {"lesson": "1.104", "playlist_index": 311, "youtube_id": "Ol4La1-di8o", "title": None},
        "answer_question": [("What do you usually do on Sundays?", "I usually visit my parents.")],
        "find_error": [("Yesterday I work all day.", "Yesterday I worked all day.")],
        "verb_tense": [
            ("He always ___ tea.", "обычно", ["drinks"]),
            ("This morning he ___ coffee.", "прош.", ["drank"]),
            ("We ___ to Italy last year.", "прош.", ["went", "travelled"]),
        ],
    },
    {
        "id": "les-c-09", "module": "mod-c-1",
        "title": "Вопрос к подлежащему в прошедшем: What happened?",
        "gp_id": "gp-c-09", "gp_title": "Who said? What happened?",
        "rule_md": RULE_C09,
        "phrases": C09,
        "rule_cloze": [
            ("What ___?", ["happened"]),
            ("Who ___ that?", ["said", "did", "made"]),
            ("Who ___ my pen?", ["took"]),
        ],
        "quotes": [("q-igry-0014", "died"), ("q-igry-0003", "took")],
        "trap_id": "trap-question-word-order",
        "vocab_band": {"list": "ngsl-spoken", "from": 2441, "to": 2500},
        "phrasebook_topic": None,
        "quotes_topic": "questions",
        "bebris_video": {"lesson": "1.106", "playlist_index": 313, "youtube_id": "T2rNu1NNnzU", "title": None},
        "answer_question": [("What happened?", "Nothing happened.")],
        "find_error": [("Who did say that?", "Who said that?")],
        "verb_tense": [
            ("Who ___ the game?", "прош. (кто победил)", ["won"]),
            ("What ___ next?", "прош.", ["happened"]),
            ("Who ___ the bill?", "прош.", ["paid"]),
        ],
    },
    {
        "id": "les-c-10", "module": "mod-c-1",
        "title": "Повторение №11: контрольная-тренировка",
        "gp_id": "gp-c-10", "gp_title": "Контрольная: прошедшее время",
        "rule_md": RULE_C10,
        "phrases": C10,
        "rule_cloze": [
            ("The weather ___ perfect.", ["was"]),
            ("___ did you have dinner?", ["Where", "When"]),
            ("He ___ his phone on the way.", ["lost", "found"]),
        ],
        "quotes": [("q-berserk-0003", "is"), ("q-supernatural-0018", "don't")],
        "trap_id": "trap-didnt-past",
        "vocab_band": {"list": "ngsl-spoken", "from": 2501, "to": 2560},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("How did you sleep?", "I slept badly.")],
        "find_error": [("Who did break the window?", "Who broke the window?")],
        "verb_tense": [
            ("I ___ my grandmother.", "last weekend", ["visited"]),
            ("They ___ by car.", "yesterday", ["went"]),
            ("She ___ a lot of photos.", "last trip", ["took"]),
        ],
        "transform": [
            ("I visit my grandmother.", "past", "I visited my grandmother."),
            ("He goes to work by car.", "past", "He went to work by car."),
            ("We see them every day.", "past", "We saw them every day."),
        ],
    },
    {
        "id": "les-c-11", "module": "mod-c-2",
        "title": "Future Simple: will (+), I'll",
        "gp_id": "gp-c-11", "gp_title": "will: обещания и прогнозы",
        "rule_md": RULE_C11,
        "phrases": C11,
        "rule_cloze": [
            ("I ___ call you tomorrow.", ["will", "'ll"]),
            ("The flight ___ be late.", ["will"]),
            ("Everything ___ be fine.", ["will", "'ll"]),
        ],
        "quotes": [("q-lord-of-the-rings-0002", "will"), ("q-attack-on-titan-0011", "I'll")],
        "trap_id": "trap-if-will",
        "vocab_band": {"list": "ngsl-spoken", "from": 2561, "to": 2620},
        "phrasebook_topic": "airport",
        "quotes_topic": "future",
        "bebris_video": {"lesson": "1.49", "playlist_index": 163, "youtube_id": "4Tt_XQw5Q9k", "title": None},
        "answer_question": [("Will you help me?", "I will help you.")],
        "find_error": [("I will to call you.", "I will call you.")],
        "verb_tense": [
            ("She ___ like the city.", "прогноз", ["will", "'ll"]),
            ("They ___ come next week.", "обещание", ["will", "'ll"]),
            ("I ___ be back in five minutes.", "сокращение", ["'ll", "will"]),
        ],
    },
    {
        "id": "les-c-12", "module": "mod-c-2",
        "title": "will: − и ? (won't, Will you…?)",
        "gp_id": "gp-c-12", "gp_title": "won't и вопросы с will",
        "rule_md": RULE_C12,
        "phrases": C12,
        "rule_cloze": [
            ("I ___ tell anyone.", ["won't", "will not"]),
            ("___ you help me tomorrow?", ["Will"]),
            ("___ will you stay?", ["Where"]),
        ],
        "quotes": [("q-game-of-thrones-0001", "won't"), ("q-berserk-0017", "get")],
        "trap_id": "trap-if-will",
        "vocab_band": {"list": "ngsl-spoken", "from": 2621, "to": 2680},
        "phrasebook_topic": "smalltalk",
        "quotes_topic": "future",
        "bebris_video": {"lesson": "1.51", "playlist_index": 167, "youtube_id": "aWv9LlHCdhQ", "title": None},
        "answer_question": [("Will you join us?", "Yes, I will.")],
        "find_error": [("I won't to tell anyone.", "I won't tell anyone.")],
        "verb_tense": [
            ("He ___ come today.", "отказ", ["won't", "will not"]),
            ("___ it be open on Sunday?", "вопрос", ["Will"]),
            ("What ___ you do tomorrow?", "спецвопрос", ["will"]),
        ],
    },
    {
        "id": "les-c-13", "module": "mod-c-2",
        "title": "will: спецвопросы; be able to / manage to",
        "gp_id": "gp-c-13", "gp_title": "Возможности: will be able to, managed to",
        "rule_md": RULE_C13,
        "phrases": C13,
        "rule_cloze": [
            ("How long ___ it take?", ["will"]),
            ("I will ___ able to help you.", ["be"]),
            ("We ___ to catch the last train.", ["managed"]),
        ],
        "quotes": [("q-star-wars-0013", "tell"), ("q-lord-of-the-rings-0017", "decide")],
        "trap_id": "trap-if-will",
        "vocab_band": {"list": "ngsl-spoken", "from": 2681, "to": 2740},
        "phrasebook_topic": None,
        "quotes_topic": "future",
        "bebris_video": {"lesson": "1.55", "playlist_index": 175, "youtube_id": "TNpl9twtT_Q", "title": None},
        "answer_question": [("Will you be able to come?", "I won't be able to come.")],
        "find_error": [("I will can help you.", "I will be able to help you.")],
        "verb_tense": [
            ("Where ___ we meet?", "будущее", ["will"]),
            ("She ___ to pass the exam.", "удалось", ["managed"]),
            ("___ you be able to come?", "вопрос", ["Will"]),
        ],
    },
    {
        "id": "les-c-14", "module": "mod-c-2",
        "title": "be going to: планы и намерения",
        "gp_id": "gp-c-14", "gp_title": "going to vs will",
        "rule_md": RULE_C14,
        "phrases": C14,
        "rule_cloze": [
            ("I'm ___ to travel this summer.", ["going"]),
            ("It is ___ to rain.", ["going"]),
            ("What are you ___ to do?", ["going"]),
        ],
        "quotes": [("q-memy-0003", "gonna", ["going to"]), ("q-solo-leveling-0009", "going")],
        "trap_id": "trap-want-that",
        "vocab_band": {"list": "ngsl-spoken", "from": 2741, "to": 2800},
        "phrasebook_topic": "emergency",
        "quotes_topic": "future",
        "bebris_video": None,
        "answer_question": [("What are you going to do?", "I'm going to travel this summer.")],
        "find_error": [("I'm going travel this summer.", "I'm going to travel this summer.")],
        "verb_tense": [
            ("We are ___ to visit Rome.", "план", ["going"]),
            ("She is going to ___ English.", "учить", ["study"]),
            ("I was ___ to call you.", "собирался", ["going"]),
        ],
    },
    {
        "id": "les-c-15", "module": "mod-c-2",
        "title": "Повторение №12: будущее и прошедшее",
        "gp_id": "gp-c-15", "gp_title": "Контрольная: will/going to + Past Simple",
        "rule_md": RULE_C15,
        "phrases": C15,
        "rule_cloze": [
            ("I think it ___ rain.", ["will"]),
            ("It's ___ to rain — look at the sky.", ["going"]),
            ("We ___ there by train.", ["went"]),
        ],
        "quotes": [("q-solo-leveling-0012", "Will"), ("q-memy-0002", "walk")],
        "trap_id": "trap-didnt-past",
        "vocab_band": {"list": "ngsl-spoken", "from": 2801, "to": 2860},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("What will you do tomorrow?", "I'll call you tomorrow.")],
        "find_error": [("I will to call you tomorrow.", "I will call you tomorrow.")],
        "verb_tense": [
            ("I'm ___ to start a new job.", "план", ["going"]),
            ("He ___ come.", "отказ (буд.)", ["won't", "will not"]),
            ("___ you see the Colosseum?", "прош. вопрос", ["Did"]),
        ],
        "transform": [
            ("I call you tomorrow.", "future", "I will call you tomorrow."),
            ("I visit my aunt.", "past", "I visited my aunt."),
            ("We stay two nights.", "future", "We will stay two nights."),
        ],
    },
]
