#!/usr/bin/env python3
"""Пулы уроков C3 «Должен и могу» (C-16…C-20), C4 «Сравнения и процесс»
(C-21…C-25) и C5 «В пути» (C-26…C-30) — plan://M14#14.7. specs/01 §7.
"""

# --------------------------------------------------------------------------
# C3 «Должен и могу»
# --------------------------------------------------------------------------
C16 = [
    ("I must go.", "Я должен идти.", None),
    ("You must stop.", "Вы должны остановиться.", None),
    ("She must rest.", "Ей нужно отдохнуть.", None),
    ("We must be careful.", "Мы должны быть осторожны.", None),
    ("I must say it.", "Я должен это сказать.", None),
    ("You must see this film.", "Ты обязательно должен посмотреть этот фильм.", None),
    ("I have to work tomorrow.", "Мне нужно работать завтра.", None),
    ("You have to hurry.", "Тебе нужно поторопиться.", None),
    ("She has to study.", "Ей нужно учиться.", None),
    ("He has to leave early.", "Ему нужно уйти рано.", None),
    ("We have to change trains.", "Нам нужно пересесть на другой поезд.", None),
    ("They have to pay extra.", "Им нужно доплатить.", None),
    ("Do I have to fill in this form?", "Мне нужно заполнить эту форму?", None),
    ("You have to fill in this form.", "Вы должны заполнить эту форму.", ["You must fill in this form."]),
    ("Do you have to go now?", "Тебе нужно идти сейчас?", None),
    ("Does she have to come?", "Ей нужно приходить?", None),
    ("What do I have to do?", "Что я должен сделать?", None),
    ("Where do I have to sign?", "Где я должен подписать?", None),
    ("I don't have to work on Sundays.", "Мне не нужно работать по воскресеньям.", None),
    ("You don't have to wait.", "Тебе не нужно ждать.", None),
    ("She doesn't have to wear a uniform.", "Ей не нужно носить форму.", None),
    ("You mustn't smoke here.", "Здесь нельзя курить.", ["You can't smoke here."]),
    ("You mustn't open this door.", "Нельзя открывать эту дверь.", None),
    ("Passengers must wear seat belts.", "Пассажиры должны пристегнуть ремни.", None),
    ("You must show your passport.", "Вы должны показать паспорт.", None),
    ("Everyone must pass security.", "Все должны пройти контроль безопасности.", None),
    ("I had to wait two hours.", "Мне пришлось ждать два часа.", None),
    ("We had to pay in cash.", "Нам пришлось платить наличными.", None),
    ("He had to show his ticket.", "Ему пришлось показать билет.", None),
    ("Do I need a visa?", "Мне нужна виза?", None),
    ("You need a ticket for the metro.", "Для метро нужен билет.", None),
    ("This is forbidden.", "Это запрещено.", None),
    ("This is allowed.", "Это разрешено.", None),
    ("No parking here.", "Здесь нельзя парковаться.", None),
    ("Can I bring luggage?", "Можно привезти багаж?", None),
    ("What is the purpose of your visit?", "Какова цель вашего визита?", None),
    ("Tourism.", "Туризм.", None),
    ("Business.", "Бизнес.", None),
    ("I'm here for a week.", "Я здесь на неделю.", None),
    ("How long will you stay?", "Как долго вы пробудете?", None),
    ("Anything to declare?", "Есть что декларировать?", None),
    ("Nothing to declare.", "Нечего декларировать.", None),
    ("Open your bag, please.", "Откройте сумку, пожалуйста.", None),
    ("That's all, thank you.", "Это всё, спасибо.", None),
    ("Welcome to the country.", "Добро пожаловать в страну.", None),
]

C17 = [
    ("You should see a doctor.", "Вам следует показаться врачу.", None),
    ("You should rest.", "Тебе следует отдохнуть.", None),
    ("You should drink more water.", "Тебе следует пить больше воды.", None),
    ("You should sleep more.", "Тебе следует больше спать.", None),
    ("She should take a taxi.", "Ей следует взять такси.", None),
    ("He should call her.", "Ему следует ей позвонить.", None),
    ("We should book the tickets.", "Нам следует забронировать билеты.", None),
    ("You should try local food.", "Тебе стоит попробовать местную еду.", None),
    ("You shouldn't eat so fast.", "Тебе не стоит есть так быстро.", None),
    ("You shouldn't drink coffee at night.", "Не стоит пить кофе на ночь.", None),
    ("She shouldn't work so much.", "Ей не стоит так много работать.", None),
    ("You shouldn't go alone.", "Тебе не стоит идти одному.", None),
    ("You shouldn't miss this museum.", "Не пропускай этот музей.", ["Don't miss this museum."]),
    ("What should I do?", "Что мне делать?", None),
    ("Where should we eat?", "Где нам поесть?", None),
    ("What time should we leave?", "Во сколько нам выходить?", None),
    ("Which bus should I take?", "На какой автобус мне сесть?", None),
    ("Should I call a doctor?", "Мне вызвать врача?", None),
    ("I don't feel well.", "Мне нездоровится.", None),
    ("I have a headache.", "У меня болит голова.", None),
    ("I have a sore throat.", "У меня болит горло.", None),
    ("I have a temperature.", "У меня температура.", None),
    ("I have a bad cough.", "У меня сильный кашель.", None),
    ("My stomach hurts.", "У меня болит живот.", None),
    ("My back hurts.", "У меня болит спина.", None),
    ("I feel dizzy.", "У меня кружится голова.", None),
    ("How long have you had this pain?", "Как давно у вас эта боль?", None),
    ("Since yesterday.", "Со вчерашнего дня.", None),
    ("It hurts here.", "Здесь болит.", None),
    ("Take this medicine twice a day.", "Принимайте это лекарство дважды в день.", None),
    ("You'll feel better soon.", "Скоро вам станет лучше.", None),
    ("It's nothing serious.", "Ничего серьёзного.", None),
    ("Do I have to stay in bed?", "Нужно ли мне соблюдать постельный режим?", None),
    ("Drink warm tea with honey.", "Пейте тёплый чай с мёдом.", None),
    ("Get well soon!", "Поправляйтесь!", None),
    ("You look tired.", "Ты выглядишь усталым.", None),
    ("You look pale.", "Ты выглядишь бледным.", None),
    ("Maybe you should stay at home.", "Может, тебе стоит остаться дома.", None),
    ("I think you should apologize.", "Думаю, тебе стоит извиниться.", None),
    ("You'd better see a dentist.", "Лучше бы тебе сходить к стоматологу.", None),
    ("You'd better hurry.", "Тебе лучше поторопиться.", None),
    ("That's a good idea.", "Это хорошая мысль.", None),
    ("Thanks for the advice.", "Спасибо за совет.", None),
    ("I'll do that.", "Я так и сделаю.", None),
    ("I can help you.", "Я могу тебе помочь.", None),
    ("I could help you.", "Я мог тебе помочь.", None),
    ("I had to go.", "Мне пришлось идти.", None),
]
C18 = [
    ("Could I have the menu, please?", "Можно меню, пожалуйста?", None),
    ("Could I have the bill?", "Можно счёт?", None),
    ("Could I have some water?", "Можно воды?", None),
    ("Could you help me, please?", "Не могли бы вы мне помочь?", None),
    ("Could you help me?", "Не могли бы вы помочь?", None),
    ("Could you repeat that?", "Не могли бы вы повторить?", None),
    ("Could you speak slowly?", "Не могли бы вы говорить медленнее?", None),
    ("Could you open the window?", "Не могли бы вы открыть окно?", None),
    ("Could you pass the salt?", "Передадите соль?", None),
    ("Could you call a taxi?", "Не могли бы вы вызвать такси?", None),
    ("Could you take a photo of us?", "Не могли бы вы нас сфотографировать?", None),
    ("Could I pay by card?", "Можно заплатить картой?", None),
    ("Could I sit here?", "Можно здесь сесть?", None),
    ("Could I ask you something?", "Можно вас кое о чём спросить?", None),
    ("Could you tell me the time?", "Подскажете время?", None),
    ("Could I have a room for two nights?", "Можно номер на две ночи?", None),
    ("Of course.", "Конечно.", None),
    ("Sure, no problem.", "Конечно, без проблем.", None),
    ("Certainly.", "Разумеется.", None),
    ("I'm sorry, we're full.", "Извините, у нас всё занято.", None),
    ("When I was young, I could run fast.", "В молодости я мог быстро бегать.", None),
    ("She could swim when she was five.", "Она умела плавать в пять лет.", None),
    ("He could speak three languages.", "Он умел говорить на трёх языках.", None),
    ("I could see the sea from my window.", "Я мог видеть море из окна.", None),
    ("I couldn't sleep.", "Я не мог уснуть.", None),
    ("She couldn't come.", "Она не смогла прийти.", None),
    ("We couldn't find the hotel.", "Мы не смогли найти отель.", None),
    ("He couldn't understand me.", "Он не мог меня понять.", None),
    ("I couldn't believe my eyes.", "Я не мог поверить своим глазам.", None),
    ("Could you help me with my bags?", "Поможете мне с сумками?", None),
    ("That would be great.", "Было бы здорово.", None),
    ("Would you like something to drink?", "Что-нибудь выпьете?", None),
    ("I'd like a coffee, please.", "Кофе, пожалуйста.", None),
    ("Anything for you?", "Что-нибудь для вас?", None),
    ("The soup of the day is tomato.", "Суп дня — томатный.", None),
    ("I'll have the fish.", "Я возьму рыбу.", None),
    ("How would you like your steak?", "Как прожарить стейк?", None),
    ("Are you ready to order?", "Вы готовы сделать заказ?", None),
    ("Is everything OK with your meal?", "Всё в порядке с блюдом?", None),
    ("It was delicious.", "Было очень вкусно.", None),
    ("Can I get you anything else?", "Принести что-нибудь ещё?", None),
    ("Just the bill, please.", "Только счёт, пожалуйста.", None),
    ("Service was excellent.", "Обслуживание было отличным.", None),
    ("I could never hate you.", "Я никогда бы не смог тебя ненавидеть.", None),
    ("Enjoy your meal!", "Приятного аппетита!", None),
]

C19 = [
    ("I like reading.", "Я люблю читать.", None),
    ("She likes cooking.", "Она любит готовить.", None),
    ("He likes travelling.", "Он любит путешествовать.", None),
    ("We like walking in the park.", "Мы любим гулять в парке.", None),
    ("They like swimming.", "Они любят плавать.", None),
    ("I like listening to music.", "Я люблю слушать музыку.", None),
    ("Do you like dancing?", "Ты любишь танцевать?", None),
    ("I don't like waiting.", "Я не люблю ждать.", None),
    ("She doesn't like flying.", "Она не любит летать.", None),
    ("I hate getting up early.", "Ненавижу рано вставать.", None),
    ("I love learning English.", "Обожаю учить английский.", None),
    ("I enjoy watching films.", "Мне нравится смотреть фильмы.", None),
    ("I want you to understand.", "Я хочу, чтобы ты понял.", None),
    ("I want him to come.", "Я хочу, чтобы он пришёл.", None),
    ("I want her to stay.", "Я хочу, чтобы она осталась.", None),
    ("She wants me to help.", "Она хочет, чтобы я помог.", None),
    ("He wants us to wait.", "Он хочет, чтобы мы подождали.", None),
    ("They want me to decide.", "Они хотят, чтобы я решил.", None),
    ("I want you to be happy.", "Я хочу, чтобы ты был счастлив.", None),
    ("I don't want you to go.", "Я не хочу, чтобы ты уходил.", None),
    ("I don't want him to know.", "Я не хочу, чтобы он знал.", None),
    ("She doesn't want us to be late.", "Она не хочет, чтобы мы опоздали.", None),
    ("I'd like you to try it.", "Я бы хотел, чтобы ты это попробовал.", None),
    ("I need you to listen.", "Мне нужно, чтобы ты слушал.", None),
    ("I expect you to be on time.", "Я рассчитываю, что ты будешь вовремя.", None),
    ("I asked him to help.", "Я попросил его помочь.", None),
    ("She told me to wait.", "Она сказала мне подождать.", None),
    ("He told us to follow him.", "Он велел нам следовать за ним.", None),
    ("They asked me to stop.", "Они попросили меня остановиться.", None),
    ("The doctor told me to rest.", "Врач велел мне отдохнуть.", None),
    ("I'm allergic to nuts.", "У меня аллергия на орехи.", None),
    ("I don't eat meat.", "Я не ем мясо.", None),
    ("Is this vegetarian?", "Это вегетарианское?", None),
    ("Without onion, please.", "Без лука, пожалуйста.", None),
    ("I can't eat spicy food.", "Я не могу есть острую еду.", None),
    ("Does it contain milk?", "Это содержит молоко?", None),
    ("What do you recommend?", "Что вы посоветуете?", None),
    ("It's my favourite dish.", "Это моё любимое блюдо.", None),
    ("I prefer tea to coffee.", "Я предпочитаю чай кофе.", None),
    ("I'd rather stay at home.", "Я бы лучше остался дома.", None),
    ("It's up to you.", "Решать тебе.", None),
    ("I just want you to understand.", "Я просто хочу, чтобы ты понял.", None),
    ("That's all I want.", "Вот всё, чего я хочу.", None),
    ("Trust me on this.", "Поверь мне в этом.", None),
]

C20 = [
    ("You should see a doctor.", "Вам следует показаться врачу.", None),
    ("You shouldn't work so much.", "Не стоит так много работать.", None),
    ("Do I have to fill in this form?", "Мне нужно заполнить эту форму?", None),
    ("You have to fill in this form.", "Вы должны заполнить эту форму.", ["You must fill in this form."]),
    ("I have to work tomorrow.", "Мне нужно работать завтра.", None),
    ("You mustn't smoke here.", "Здесь нельзя курить.", ["You can't smoke here."]),
    ("Could you help me, please?", "Не могли бы вы мне помочь?", None),
    ("Could you help me?", "Не могли бы вы помочь?", None),
    ("Could I have the menu?", "Можно меню?", None),
    ("I couldn't sleep.", "Я не мог уснуть.", None),
    ("I like reading.", "Я люблю читать.", None),
    ("She doesn't like flying.", "Она не любит летать.", None),
    ("I want you to understand.", "Я хочу, чтобы ты понял.", None),
    ("I don't want him to go.", "Я не хочу, чтобы он уходил.", None),
    ("She told me to wait.", "Она сказала мне подождать.", None),
    ("I have a headache.", "У меня болит голова.", None),
    ("You should drink more water.", "Тебе следует пить больше воды.", None),
    ("Get well soon!", "Поправляйтесь!", None),
    ("I'm allergic to nuts.", "У меня аллергия на орехи.", None),
    ("I don't eat meat.", "Я не ем мясо.", None),
    ("What do you recommend?", "Что вы посоветуете?", None),
    ("Anything to declare?", "Есть что декларировать?", None),
    ("Nothing to declare.", "Нечего декларировать.", None),
    ("What is the purpose of your visit?", "Какова цель вашего визита?", None),
    ("I'm here for a week.", "Я здесь на неделю.", None),
    ("You must show your passport.", "Вы должны показать паспорт.", None),
    ("It was delicious.", "Было очень вкусно.", None),
    ("I'd like a coffee, please.", "Кофе, пожалуйста.", None),
    ("Are you ready to order?", "Вы готовы сделать заказ?", None),
    ("Could you repeat that?", "Не могли бы вы повторить?", None),
    ("Should I call a doctor?", "Мне вызвать врача?", None),
    ("You'd better hurry.", "Тебе лучше поторопиться.", None),
    ("I had to wait two hours.", "Мне пришлось ждать два часа.", None),
    ("We couldn't find the hotel.", "Мы не смогли найти отель.", None),
    ("I enjoy watching films.", "Мне нравится смотреть фильмы.", None),
    ("He wants us to wait.", "Он хочет, чтобы мы подождали.", None),
    ("I asked him to help.", "Я попросил его помочь.", None),
    ("I'll have the fish.", "Я возьму рыбу.", None),
    ("Can I get you anything else?", "Принести что-нибудь ещё?", None),
    ("Just the bill, please.", "Только счёт, пожалуйста.", None),
    ("That would be great.", "Было бы здорово.", None),
    ("It's up to you.", "Решать тебе.", None),
    ("Thanks for the advice.", "Спасибо за совет.", None),
    ("I'll do that.", "Я так и сделаю.", None),
    ("I can help you.", "Я могу тебе помочь.", None),
    ("I could help you.", "Я мог тебе помочь.", None),
    ("I had to go.", "Мне пришлось идти.", None),
    ("Welcome to the country.", "Добро пожаловать в страну.", None),
    ("Enjoy your meal!", "Приятного аппетита!", None),
]

# --------------------------------------------------------------------------
# C4 «Сравнения и процесс»
# --------------------------------------------------------------------------
C21 = [
    ("This room is bigger.", "Этот номер больше.", None),
    ("It is bigger.", "Он больше.", None),
    ("That room is smaller.", "Тот номер меньше.", None),
    ("My bag is heavier than yours.", "Моя сумка тяжелее твоей.", None),
    ("The bus is cheaper than the train.", "Автобус дешевле поезда.", None),
    ("The train is faster.", "Поезд быстрее.", None),
    ("This hotel is better.", "Этот отель лучше.", None),
    ("That café is worse.", "То кафе хуже.", None),
    ("Today is hotter than yesterday.", "Сегодня жарче, чем вчера.", None),
    ("The morning is colder.", "Утро холоднее.", None),
    ("This street is quieter.", "Эта улица тише.", None),
    ("The city is noisier at night.", "Город шумнее ночью.", None),
    ("My phone is newer.", "Мой телефон новее.", None),
    ("This book is more interesting.", "Эта книга интереснее.", None),
    ("The film was more exciting.", "Фильм был более захватывающим.", None),
    ("This way is more difficult.", "Этот путь сложнее.", None),
    ("The soup is more delicious.", "Суп вкуснее.", None),
    ("It is the biggest city in Europe.", "Это самый большой город в Европе.", None),
    ("It is the best day of my life.", "Это лучший день в моей жизни.", None),
    ("This is the worst weather.", "Это худшая погода.", None),
    ("It is the most beautiful place.", "Это самое красивое место.", None),
    ("It is the most famous museum.", "Это самый известный музей.", None),
    ("That was the most expensive hotel.", "Это был самый дорогой отель.", None),
    ("The longest day.", "Самый длинный день.", None),
    ("The shortest way.", "Самый короткий путь.", None),
    ("Do you have a bigger room?", "У вас есть номер побольше?", None),
    ("Do you have a cheaper one?", "Есть что-нибудь подешевле?", None),
    ("Is there a faster way?", "Есть путь быстрее?", None),
    ("Which is better?", "Что лучше?", None),
    ("Which is more important?", "Что важнее?", None),
    ("What is the nearest metro station?", "Какая станция метро ближайшая?", None),
    ("Where is the closest pharmacy?", "Где ближайшая аптека?", None),
    ("Two rooms, please — the quieter one for me.", "Два номера, пожалуйста — мне номер потише.", None),
    ("The more, the better.", "Чем больше, тем лучше.", None),
    ("Better late than never.", "Лучше поздно, чем никогда.", None),
    ("It's getting darker.", "Становится темнее.", None),
    ("It's getting colder.", "Становится холоднее.", None),
    ("Prices are getting higher.", "Цены становятся выше.", None),
    ("My English is getting better.", "Мой английский становится лучше.", None),
    ("Older and wiser.", "Старше и мудрее.", None),
    ("The older, the wiser.", "Кто старше, тот мудрее.", None),
    ("Bigger is not always better.", "Больше — не всегда лучше.", None),
    ("This one or that one?", "Этот или тот?", None),
    ("The second option is cheaper.", "Второй вариант дешевле.", None),
    ("Good, better, the best.", "Хорошо, лучше, наилучшее.", None),
]

C22 = [
    ("He is as tall as his brother.", "Он такой же высокий, как его брат.", None),
    ("She is as busy as me.", "Она так же занята, как и я.", None),
    ("This hotel is as good as that one.", "Этот отель такой же хороший, как тот.", None),
    ("The food is as delicious as at home.", "Еда такая же вкусная, как дома.", None),
    ("It is not as cold as yesterday.", "Сегодня не так холодно, как вчера.", None),
    ("He is not as strong as you.", "Он не такой сильный, как ты.", None),
    ("The bus is not as fast as the train.", "Автобус не такой быстрый, как поезд.", None),
    ("It's not as difficult as it looks.", "Это не так сложно, как кажется.", None),
    ("As soon as possible.", "Как можно скорее.", None),
    ("As fast as you can.", "Так быстро, как сможешь.", None),
    ("Twice as expensive.", "Вдвое дороже.", None),
    ("This coffee is too hot.", "Этот кофе слишком горячий.", None),
    ("This shirt is too small.", "Эта рубашка слишком мала.", None),
    ("It is too late.", "Уже слишком поздно.", None),
    ("It is too far to walk.", "Слишком далеко, чтобы идти пешком.", None),
    ("The music is too loud.", "Музыка слишком громкая.", None),
    ("He talks too fast.", "Он говорит слишком быстро.", None),
    ("Too much salt.", "Слишком много соли.", None),
    ("Too many people.", "Слишком много людей.", None),
    ("This room is big enough.", "Этот номер достаточно большой.", None),
    ("The water is warm enough.", "Вода достаточно тёплая.", None),
    ("I'm not tall enough.", "Я недостаточно высокий.", None),
    ("It's not good enough.", "Это недостаточно хорошо.", None),
    ("We don't have enough time.", "У нас недостаточно времени.", None),
    ("I have enough money.", "У меня достаточно денег.", None),
    ("Is the room quiet enough for you?", "Номер для вас достаточно тихий?", None),
    ("Strong enough for both.", "Достаточно сильный для обоих.", None),
    ("We're the strongest.", "Мы сильнейшие.", None),
    ("It's warm enough to swim.", "Достаточно тепло, чтобы плавать.", None),
    ("I'm too tired to walk.", "Я слишком устал, чтобы идти.", None),
    ("She is old enough to decide.", "Она достаточно взрослая, чтобы решать.", None),
    ("This bag is too heavy to carry.", "Эта сумка слишком тяжёлая, чтобы нести.", None),
    ("Just right.", "В самый раз.", None),
    ("Perfect!", "Идеально!", None),
    ("Not bad at all.", "Совсем неплохо.", None),
    ("It could be worse.", "Могло быть и хуже.", None),
    ("It's just perfect.", "Это просто идеально.", None),
    ("Almost perfect.", "Почти идеально.", None),
    ("Comfortable enough.", "Достаточно удобно.", None),
    ("The bed is too hard.", "Кровать слишком жёсткая.", None),
    ("Could I have an extra blanket?", "Можно дополнительное одеяло?", None),
    ("The pillow is too soft.", "Подушка слишком мягкая.", None),
    ("Just what I needed.", "Как раз то, что мне нужно.", None),
    ("Same as always.", "Как обычно.", None),
]

C23 = [
    ("Can I pay for the ticket by card?", "Можно заплатить за билет картой?", None),
    ("I'll pay for dinner.", "Я заплачу за ужин.", None),
    ("Who pays for the trip?", "Кто платит за поездку?", None),
    ("He paid for the coffee.", "Он заплатил за кофе.", None),
    ("Don't pay for me.", "Не платите за меня.", None),
    ("It depends on the weather.", "Это зависит от погоды.", None),
    ("It depends on the price.", "Это зависит от цены.", None),
    ("It depends on you.", "Это зависит от тебя.", None),
    ("Everything depends on time.", "Всё зависит от времени.", None),
    ("Success depends on you.", "Успех зависит от тебя.", None),
    ("I'm looking for my keys.", "Я ищу свои ключи.", None),
    ("She is looking for a job.", "Она ищет работу.", None),
    ("What are you looking for?", "Что ты ищешь?", None),
    ("I looked for it everywhere.", "Я искал это везде.", None),
    ("He is looking for you.", "Он тебя ищет.", None),
    ("I'm waiting for the bus.", "Я жду автобус.", None),
    ("We waited for an hour.", "Мы ждали час.", None),
    ("Who are you waiting for?", "Кого ты ждёшь?", None),
    ("Don't wait for me.", "Не жди меня.", None),
    ("She asked for the bill.", "Она попросила счёт.", None),
    ("He asked for help.", "Он попросил помощи.", None),
    ("Can I ask for a favour?", "Можно попросить об услуге?", None),
    ("Listen to me.", "Послушай меня.", None),
    ("I listen to podcasts.", "Я слушаю подкасты.", None),
    ("Look at this photo.", "Посмотри на это фото.", None),
    ("Look at the map.", "Посмотри на карту.", None),
    ("Thank you for everything.", "Спасибо за всё.", None),
    ("Thanks for the help.", "Спасибо за помощь.", None),
    ("I think about it.", "Я думаю об этом.", None),
    ("Dream about the sea.", "Мечтай о море.", None),
    ("Talk to him.", "Поговори с ним.", None),
    ("Speak to the manager.", "Поговорите с менеджером.", None),
    ("Agree with me.", "Согласись со мной.", None),
    ("I agree with you.", "Я согласен с тобой.", None),
    ("Believe in yourself.", "Верь в себя.", None),
    ("He believes in luck.", "Он верит в удачу.", None),
    ("Apologize for being late.", "Извини за опоздание.", None),
    ("Sorry for the delay.", "Извините за задержку.", None),
    ("The driver was driving too fast.", "Водитель ехал слишком быстро.", None),
    ("Can you stop at the corner?", "Остановитесь на углу?", None),
    ("Drop me here, please.", "Высадите меня здесь.", None),
    ("Keep the change.", "Сдачи не надо.", None),
    ("It was a nice ride.", "Поездка была приятной.", None),
    ("How much do I owe you?", "Сколько я вам должен?", None),
]

C24 = [
    ("I was waiting for the bus.", "Я ждал автобус.", None),
    ("She was reading a book.", "Она читала книгу.", None),
    ("I was reading a book.", "Я читал книгу.", None),
    ("He was sleeping.", "Он спал.", None),
    ("We were watching TV.", "Мы смотрели телевизор.", None),
    ("They were playing outside.", "Они играли на улице.", None),
    ("It was raining.", "Шёл дождь.", None),
    ("The sun was shining.", "Светило солнце.", None),
    ("I was cooking dinner.", "Я готовил ужин.", None),
    ("She was working on her English.", "Она работала над своим английским.", None),
    ("The driver was driving too fast.", "Водитель ехал слишком быстро.", None),
    ("I wasn't sleeping.", "Я не спал.", None),
    ("She wasn't listening.", "Она не слушала.", None),
    ("We weren't in a hurry.", "Мы не спешили.", None),
    ("They weren't watching the road.", "Они не смотрели на дорогу.", None),
    ("Were you waiting for me?", "Ты ждал меня?", None),
    ("Was she crying?", "Она плакала?", None),
    ("What were you doing at eight?", "Что ты делал в восемь?", None),
    ("Where were you going?", "Куда ты шёл?", None),
    ("Why were they laughing?", "Почему они смеялись?", None),
    ("I was waiting when he came.", "Я ждал, когда он пришёл.", None),
    ("She was reading when I called.", "Она читала, когда я позвонил.", None),
    ("We were eating when the phone rang.", "Мы ели, когда зазвонил телефон.", None),
    ("He was sleeping when the alarm went off.", "Он спал, когда сработал будильник.", None),
    ("It was raining when we left.", "Шёл дождь, когда мы вышли.", None),
    ("I was walking home when I saw him.", "Я шёл домой, когда увидел его.", None),
    ("They were talking when the teacher came in.", "Они разговаривали, когда вошёл учитель.", None),
    ("While I was cooking, she was cleaning.", "Пока я готовил, она убиралась.", None),
    ("While we were waiting, it started to rain.", "Пока мы ждали, начался дождь.", None),
    ("While he was driving, he was listening to the radio.", "Пока он ехал, он слушал радио.", None),
    ("The phone rang while I was sleeping.", "Телефон зазвонил, пока я спал.", None),
    ("He broke his leg while he was skiing.", "Он сломал ногу, катаясь на лыжах.", None),
    ("I saw her while I was walking to work.", "Я увидел её по дороге на работу.", ["I saw her on my way to work."]),
    ("Suddenly everything went quiet.", "Внезапно всё стихло.", None),
    ("At that moment I understood.", "В тот момент я понял.", None),
    ("At six o'clock I was still sleeping.", "В шесть часов я ещё спал.", None),
    ("All day yesterday I was travelling.", "Весь вчерашний день я был в пути.", None),
    ("The whole evening we were talking.", "Весь вечер мы разговаривали.", None),
    ("It happened while I wasn't looking.", "Это случилось, когда я не смотрел.", None),
    ("You weren't listening again.", "Ты снова не слушал.", None),
    ("What happened while I was away?", "Что случилось, пока меня не было?", None),
    ("I was thinking about you.", "Я думал о тебе.", None),
    ("She was making tea in the kitchen.", "Она готовила чай на кухне.", None),
    ("We were late because the traffic was terrible.", "Мы опоздали, потому что были ужасные пробки.", None),
    ("It was getting dark.", "Начинало темнеть.", None),
]

C25 = [
    ("This room is bigger than that one.", "Этот номер больше того.", None),
    ("It is the best hotel in the city.", "Это лучший отель в городе.", None),
    ("He is as tall as me.", "Он такого же роста, как я.", None),
    ("It's not as cold as yesterday.", "Сегодня не так холодно, как вчера.", None),
    ("This coffee is too hot.", "Этот кофе слишком горячий.", None),
    ("The room is big enough.", "Номер достаточно большой.", None),
    ("I'm too tired to walk.", "Я слишком устал, чтобы идти.", None),
    ("I was waiting for the bus.", "Я ждал автобус.", None),
    ("She was reading when I called.", "Она читала, когда я позвонил.", None),
    ("We were eating when he arrived.", "Мы ели, когда он приехал.", None),
    ("What were you doing at nine?", "Что ты делал в девять?", None),
    ("While I was cooking, she was cleaning.", "Пока я готовил, она убиралась.", None),
    ("Can I pay for the ticket by card?", "Можно заплатить за билет картой?", None),
    ("It depends on the weather.", "Это зависит от погоды.", None),
    ("I'm looking for my keys.", "Я ищу свои ключи.", None),
    ("I'm waiting for the bus.", "Я жду автобус.", None),
    ("Listen to me.", "Послушай меня.", None),
    ("Thank you for everything.", "Спасибо за всё.", None),
    ("I agree with you.", "Я согласен с тобой.", None),
    ("However, there is one problem.", "Однако есть одна проблема.", None),
    ("Unfortunately, we were full.", "К сожалению, у нас всё было занято.", None),
    ("To be honest, I didn't like it.", "Честно говоря, мне это не понравилось.", None),
    ("By the way, where is the exit?", "Кстати, где выход?", None),
    ("In fact, it was cheaper.", "На самом деле это было дешевле.", None),
    ("Of course, I remember.", "Конечно, я помню.", None),
    ("First of all, check your bag.", "Прежде всего проверь свою сумку.", None),
    ("Do you have a bigger room?", "У вас есть номер побольше?", None),
    ("Which is more important?", "Что важнее?", None),
    ("The more, the better.", "Чем больше, тем лучше.", None),
    ("Better late than never.", "Лучше поздно, чем никогда.", None),
    ("You should see a doctor.", "Вам следует показаться врачу.", None),
    ("I want you to understand.", "Я хочу, чтобы ты понял.", None),
    ("She couldn't find the hotel.", "Она не смогла найти отель.", None),
    ("Could you help me, please?", "Не могли бы вы мне помочь?", None),
    ("Could you help me?", "Не могли бы вы помочь?", None),
    ("I had to wait two hours.", "Мне пришлось ждать два часа.", None),
    ("I like travelling.", "Я люблю путешествовать.", None),
    ("The city was getting quieter.", "Город становился тише.", None),
    ("It was getting dark.", "Начинало темнеть.", None),
    ("Everything depends on you.", "Всё зависит от тебя.", None),
    ("While we were waiting, it started to rain.", "Пока мы ждали, начался дождь.", None),
    ("As soon as possible.", "Как можно скорее.", None),
    ("Just what I needed.", "Как раз то, что мне нужно.", None),
    ("It could be worse.", "Могло быть и хуже.", None),
    ("In the end, everything was fine.", "В конце концов всё было хорошо.", None),
]

# --------------------------------------------------------------------------
# C5 «В пути» — разговорник-интенсив (обычные уроки с тематической лексикой)
# --------------------------------------------------------------------------
C26 = [
    ("Where is the check-in desk?", "Где стойка регистрации?", None),
    ("Which gate is my flight?", "Какой выход у моего рейса?", None),
    ("What time does boarding start?", "Во сколько начинается посадка?", None),
    ("Is the flight on time?", "Рейс по расписанию?", None),
    ("The flight is delayed by an hour.", "Рейс задержали на час.", None),
    ("The flight is cancelled.", "Рейс отменён.", None),
    ("Put your bag on the belt.", "Положите сумку на ленту.", None),
    ("Take out your liquids.", "Достаньте жидкости.", None),
    ("Empty your pockets.", "Выложите содержимое карманов.", None),
    ("Step through the scanner, please.", "Пройдите через сканер, пожалуйста.", None),
    ("Do you have any liquids?", "У вас есть жидкости?", None),
    ("Laptop in a separate tray.", "Ноутбук в отдельный лоток.", None),
    ("Any sharp objects?", "Есть острые предметы?", None),
    ("It's just a souvenir.", "Это просто сувенир.", None),
    ("Gate 12 is this way.", "Выход 12 в эту сторону.", None),
    ("Follow the signs to gate 5.", "Следуйте за указателями к выходу 5.", None),
    ("Boarding starts in twenty minutes.", "Посадка начнётся через двадцать минут.", None),
    ("Final call for flight 447.", "Последний вызов на рейс 447.", None),
    ("We are now boarding.", "Начинаем посадку.", None),
    ("Window or aisle seat?", "У окна или у прохода?", None),
    ("Here is your boarding pass.", "Вот ваша посадочная карта.", None),
    ("Have a nice flight!", "Хорошего полёта!", None),
    ("Welcome aboard.", "Добро пожаловать на борт.", None),
    ("Please take your seats.", "Займите свои места, пожалуйста.", None),
    ("Fasten your seat belts.", "Пристегните ремни.", None),
    ("Turn off your phone.", "Выключите телефон.", None),
    ("The plane is taking off.", "Самолёт взлетает.", None),
    ("We are landing in ten minutes.", "Мы приземлимся через десять минут.", None),
    ("Where is the baggage claim?", "Где выдача багажа?", None),
    ("My luggage is missing.", "Мой багаж потерялся.", None),
    ("Here is my baggage tag.", "Вот моя багажная бирка.", None),
    ("Fill in this form, please.", "Заполните эту форму, пожалуйста.", None),
    ("We will find it and send it to your hotel.", "Мы найдём его и доставим в ваш отель.", None),
    ("Is there anything to declare?", "Есть что декларировать?", None),
    ("Where is the exit?", "Где выход?", None),
    ("Where can I get a taxi?", "Где мне взять такси?", None),
    ("The information desk is over there.", "Стойка информации вон там.", None),
    ("Excuse me, where is gate 5?", "Извините, где выход 5?", None),
    ("Is this the right gate for Rome?", "Это правильный выход на Рим?", None),
    ("Where is the check-in desk for the Rome flight?", "Где стойка регистрации на рейс в Рим?", None),
    ("How do I get to the departure hall?", "Как мне попасть в зал вылета?", None),
    ("First class or economy?", "Первый класс или эконом?", None),
    ("Check-in closes at six.", "Регистрация закрывается в шесть.", None),
    ("I only have hand luggage.", "У меня только ручная кладь.", None),
    ("Enjoy your trip!", "Приятного путешествия!", None),
]

C27 = [
    ("Passport, please.", "Паспорт, пожалуйста.", None),
    ("Here is my passport.", "Вот мой паспорт.", None),
    ("What is the purpose of your visit?", "Какова цель вашего визита?", None),
    ("I'm here on holiday.", "Я здесь в отпуске.", None),
    ("I'm here on business.", "Я здесь в командировке.", None),
    ("I'm visiting friends.", "Я в гостях у друзей.", None),
    ("I'm transiting to Tokyo.", "Я транзитом в Токио.", None),
    ("How long will you stay?", "Как долго вы пробудете?", None),
    ("Two weeks.", "Две недели.", None),
    ("Until Friday.", "До пятницы.", None),
    ("Where will you stay?", "Где вы остановитесь?", None),
    ("At the Grand Hotel.", "В «Гранд-отеле».", None),
    ("With friends.", "У друзей.", None),
    ("Do you have a return ticket?", "У вас есть обратный билет?", None),
    ("Yes, here it is.", "Да, вот он.", None),
    ("Is this your first visit?", "Это ваш первый визит?", None),
    ("Yes, the first.", "Да, первый.", None),
    ("I was here two years ago.", "Я был здесь два года назад.", None),
    ("Do you have money for your stay?", "У вас есть деньги на проживание?", None),
    ("Yes, I have a credit card.", "Да, у меня есть кредитка.", None),
    ("May I see your visa?", "Можно вашу визу?", None),
    ("My visa is in the passport.", "Моя виза в паспорте.", None),
    ("Everything is in order.", "Всё в порядке.", None),
    ("Welcome. Enjoy your stay.", "Добро пожаловать. Приятного пребывания.", None),
    ("Anything to declare?", "Есть что декларировать?", None),
    ("Nothing to declare.", "Нечего декларировать.", None),
    ("Open your suitcase, please.", "Откройте чемодан, пожалуйста.", None),
    ("Sure, no problem.", "Конечно, без проблем.", None),
    ("What is in this box?", "Что в этой коробке?", None),
    ("It's tea, a gift.", "Это чай, подарок.", None),
    ("How much money do you have?", "Сколько у вас денег?", None),
    ("About a thousand euros.", "Около тысячи евро.", None),
    ("These are for personal use.", "Это для личного пользования.", None),
    ("You are over the limit.", "У вас больше лимита.", None),
    ("You have to pay duty on this.", "За это нужно заплатить пошлину.", None),
    ("I didn't know about the limit.", "Я не знал о лимите.", None),
    ("It was a mistake, sorry.", "Это была ошибка, извините.", None),
    ("Have a good trip.", "Хорошей поездки.", None),
    ("Go through the green channel.", "Проходите через зелёный коридор.", None),
    ("Next, please.", "Следующий, пожалуйста.", None),
    ("Have a nice day.", "Хорошего дня.", None),
    ("Thank you. Goodbye.", "Спасибо. До свидания.", None),
    ("That went well.", "Прошло хорошо.", None),
    ("That was easier than I thought.", "Это было проще, чем я думал.", None),
]

C28 = [
    ("I have a reservation.", "У меня бронь.", None),
    ("The name is Ivanov.", "Фамилия Иванов.", None),
    ("I booked a double room.", "Я забронировал двухместный номер.", None),
    ("For how many nights?", "На сколько ночей?", None),
    ("For three nights.", "На три ночи.", None),
    ("Breakfast is included.", "Завтрак включён.", None),
    ("What time is breakfast?", "Во сколько завтрак?", None),
    ("From seven to ten.", "С семи до десяти.", None),
    ("What time is check-out?", "Во сколько выезд?", None),
    ("Check-out is at noon.", "Выезд в полдень.", None),
    ("Can I have a late check-out?", "Можно поздний выезд?", None),
    ("The room is too noisy.", "Номер слишком шумный.", None),
    ("The air conditioning doesn't work.", "Кондиционер не работает.", None),
    ("There is no hot water.", "Нет горячей воды.", None),
    ("The TV doesn't work.", "Телевизор не работает.", None),
    ("Could you send someone to fix it?", "Можете прислать кого-нибудь починить?", None),
    ("Could you send someone?", "Можете прислать кого-нибудь?", None),
    ("Could I change rooms?", "Можно сменить номер?", None),
    ("Could I have an extra pillow?", "Можно дополнительную подушку?", None),
    ("Could I have a wake-up call at six?", "Разбудите меня в шесть?", None),
    ("Is there a safe in the room?", "В номере есть сейф?", None),
    ("Where is the lift?", "Где лифт?", None),
    ("What is the wifi password?", "Какой пароль от вайфая?", None),
    ("Is there a gym in the hotel?", "В отеле есть спортзал?", None),
    ("The gym is on the second floor.", "Спортзал на втором этаже.", None),
    ("Do you need a taxi?", "Вам нужно такси?", None),
    ("Could you call a taxi for me?", "Вызовите мне такси, пожалуйста.", None),
    ("I'm checking out.", "Я выезжаю.", None),
    ("Here is my key.", "Вот мой ключ.", None),
    ("Could I have the bill?", "Можно счёт?", None),
    ("I'd like to pay by card.", "Я хотел бы заплатить картой.", None),
    ("Everything was fine, thank you.", "Всё было хорошо, спасибо.", None),
    ("We enjoyed our stay.", "Нам понравилось у вас.", None),
    ("I left something in the room.", "Я кое-что оставил в номере.", None),
    ("Can you check room 305?", "Проверьте, пожалуйста, номер 305.", None),
    ("We found your charger.", "Мы нашли ваше зарядное устройство.", None),
    ("Can you keep my luggage until the evening?", "Можете держать мой багаж до вечера?", None),
    ("Of course, we have a storage room.", "Конечно, у нас есть камера хранения.", None),
    ("One moment, please.", "Одну минуту, пожалуйста.", None),
    ("Your room is ready.", "Ваш номер готов.", None),
    ("Room 405, fourth floor.", "Номер 405, четвёртый этаж.", None),
    ("Enjoy your stay!", "Приятного пребывания!", None),
    ("See you again.", "До новых встреч.", None),
    ("It was a pleasure.", "Было приятно.", None),
    ("Have a safe trip home.", "Доброго пути домой.", None),
]

C29 = [
    ("A table for two, please.", "Столик на двоих, пожалуйста.", None),
    ("A table for two people.", "Столик на двоих.", None),
    ("Do you have a reservation?", "У вас есть бронь?", None),
    ("We didn't book.", "Мы не бронировали.", None),
    ("I'll wait for a table.", "Я подожду столик.", None),
    ("Could I see the menu?", "Можно посмотреть меню?", None),
    ("What do you recommend?", "Что вы посоветуете?", None),
    ("The special of the day is fish.", "Блюдо дня — рыба.", None),
    ("I'll have the soup to start.", "Сначала возьму суп.", None),
    ("I'll have the steak.", "Я возьму стейк.", None),
    ("Same for me, please.", "Мне то же самое.", None),
    ("Anything to drink?", "Что будете пить?", None),
    ("Sparkling water, please.", "Воду с газом, пожалуйста.", None),
    ("A glass of red wine.", "Бокал красного вина.", None),
    ("No ice, please.", "Без льда, пожалуйста.", None),
    ("I'm allergic to nuts.", "У меня аллергия на орехи.", None),
    ("Does it contain gluten?", "Это содержит глютен?", None),
    ("I don't eat pork.", "Я не ем свинину.", None),
    ("Is it spicy?", "Это острое?", None),
    ("Not too spicy, please.", "Не слишком остро, пожалуйста.", None),
    ("Everything was delicious.", "Всё было очень вкусно.", None),
    ("The food was excellent.", "Еда была превосходной.", None),
    ("Could we have the bill?", "Можно нам счёт?", None),
    ("Separate bills, please.", "Раздельные счёта, пожалуйста.", None),
    ("Together, on me.", "Вместе, за мой счёт.", None),
    ("Keep the change.", "Сдачи не надо.", None),
    ("How often should I take it?", "Как часто это принимать?", None),
    ("Twice a day, after meals.", "Дважды в день после еды.", None),
    ("Before or after food?", "До или после еды?", None),
    ("One tablet in the morning.", "Одна таблетка утром.", None),
    ("For how many days?", "Сколько дней?", None),
    ("For five days.", "Пять дней.", None),
    ("Do you have something for a cold?", "У вас есть что-нибудь от простуды?", None),
    ("Something for a cough.", "Что-нибудь от кашля.", None),
    ("Do I need a prescription?", "Нужен рецепт?", None),
    ("No, it's over the counter.", "Нет, это продаётся без рецепта.", None),
    ("Any side effects?", "Есть побочные эффекты?", None),
    ("It may make you sleepy.", "Может клонить в сон.", None),
    ("Don't drive after taking it.", "Не водите машину после приёма.", None),
    ("Where are the plasters?", "Где пластыри?", None),
    ("Something for sunburn.", "Что-нибудь от солнечного ожога.", None),
    ("How much is it?", "Сколько это стоит?", None),
    ("Here you are.", "Пожалуйста.", None),
    ("Get well soon!", "Поправляйтесь!", None),
    ("Thank you for your help.", "Спасибо за помощь.", None),
]

C30 = [
    ("Where is the check-in desk?", "Где стойка регистрации?", None),
    ("My flight is delayed.", "Мой рейс задержан.", None),
    ("Passport, please.", "Паспорт, пожалуйста.", None),
    ("What is the purpose of your visit?", "Какова цель вашего визита?", None),
    ("I'm here on holiday.", "Я здесь в отпуске.", None),
    ("Nothing to declare.", "Нечего декларировать.", None),
    ("I have a reservation.", "У меня бронь.", None),
    ("For three nights.", "На три ночи.", None),
    ("The room is too noisy.", "Номер слишком шумный.", None),
    ("Could you send someone to fix it?", "Можете прислать кого-нибудь починить?", None),
    ("Could you send someone?", "Можете прислать кого-нибудь?", None),
    ("I'm checking out.", "Я выезжаю.", None),
    ("A table for two, please.", "Столик на двоих, пожалуйста.", None),
    ("A table for two people.", "Столик на двоих.", None),
    ("What do you recommend?", "Что вы посоветуете?", None),
    ("I'll have the fish.", "Я возьму рыбу.", None),
    ("Could we have the bill?", "Можно нам счёт?", None),
    ("How often should I take it?", "Как часто это принимать?", None),
    ("Twice a day, after meals.", "Дважды в день после еды.", None),
    ("I was waiting for the bus.", "Я ждал автобус.", None),
    ("She was reading when I called.", "Она читала, когда я позвонил.", None),
    ("While we were waiting, it started to rain.", "Пока мы ждали, начался дождь.", None),
    ("This room is bigger.", "Этот номер больше.", None),
    ("It is bigger.", "Он больше.", None),
    ("It is the best day of my life.", "Это лучший день в моей жизни.", None),
    ("He is as tall as his brother.", "Он такой же высокий, как его брат.", None),
    ("This coffee is too hot.", "Этот кофе слишком горячий.", None),
    ("The room is big enough.", "Номер достаточно большой.", None),
    ("You should see a doctor.", "Вам следует показаться врачу.", None),
    ("I want you to understand.", "Я хочу, чтобы ты понял.", None),
    ("Could you help me, please?", "Не могли бы вы мне помочь?", None),
    ("Could you help me?", "Не могли бы вы помочь?", None),
    ("I couldn't sleep.", "Я не мог уснуть.", None),
    ("I have to work tomorrow.", "Мне нужно работать завтра.", None),
    ("Do I have to fill in this form?", "Мне нужно заполнить эту форму?", None),
    ("You have to fill in this form.", "Вы должны заполнить эту форму.", ["You must fill in this form."]),
    ("It depends on the weather.", "Это зависит от погоды.", None),
    ("Can I pay for the ticket by card?", "Можно заплатить за билет картой?", None),
    ("I'm looking for my keys.", "Я ищу свои ключи.", None),
    ("I will call you tomorrow.", "Я позвоню тебе завтра.", None),
    ("I'm going to travel this summer.", "Этим летом я собираюсь путешествовать.", None),
    ("Will you join us?", "Ты присоединишься к нам?", None),
    ("I visited Rome last year.", "Я посетил Рим в прошлом году.", None),
    ("What happened?", "Что случилось?", None),
    ("Who said that?", "Кто это сказал?", None),
    ("Where did you stay?", "Где вы останавливались?", None),
    ("The weather was great.", "Погода была отличная.", None),
    ("Everything will be fine.", "Всё будет хорошо.", None),
    ("Good luck!", "Удачи!", None),
]

RULE_C16 = """**must / have to.**
must — сильная необходимость (правило, закон): You **must** show your passport.
have to — вынужденная необходимость: I **have to** work tomorrow.
? только have to: **Do** you **have to** go?
mustn't = «запрещено» ≠ don't have to = «не нужно»."""

RULE_C17 = """**should — совет.**
should + 1-я форма: You **should** see a doctor. You **shouldn't** eat so fast.
Спрашиваем совет: What **should** I do?
had to — «пришлось» в прошлом: I **had to** wait two hours."""

RULE_C18 = """**could — прошедшее и вежливость.**
Прошлое (умел/мог): When I was young, I **could** run fast. I **couldn't** sleep.
Вежливая просьба: **Could** you help me, please? **Could** I have the menu?
could вежливее can — используй с незнакомыми."""

RULE_C19 = """**like + -ing; want + object + to.**
like/enjoy/hate + -ing: I like **reading**. She doesn't like **flying**.
want + кого + to: I want **you to understand**. She wants **me to help**.
❌ I want that you… tell + to: She told me **to wait**.
ask + to: I asked him **to help**."""

RULE_C20 = """**Повторение №13: должен и могу.**
must/have to (mustn't = нельзя!), should (совет), could (умел/вежливо),
like + -ing, want + object + to, told/asked + to.
Контрольная: найди ошибку, поставь форму, выбери вариант."""

RULE_C21 = """**Сравнения: bigger / the biggest.**
Короткие: big → **bigger** → **the biggest**; hot → hotter → the hottest.
Длинные (3+ слога): interesting → **more** interesting → **the most** interesting.
good → better → the best; bad → worse → the worst.
X is bigger **than** Y."""

RULE_C22 = """**as … as; too / enough.**
Равенство: **as** tall **as**: He is as tall as his brother.
Отрицание: not as fast as = «не такой быстрый, как».
**too** = «слишком» (too hot, too expensive) — ПЕРЕД словом.
**enough** = «достаточно» (big enough, warm enough) — ПОСЛЕ слова.
too + прил. + to: too tired **to walk**."""

RULE_C23 = """**Глаголы с предлогами.**
pay **for**, depend **on**, look **for** (искать), look **at** (смотреть на),
wait **for**, ask **for**, listen **to**, thank **for**, think **about**,
talk **to**, agree **with**, believe **in**, apologize **for**.
⚠️ Русское «ждать автобус» = wait **for** the bus (не «wait the bus»)."""

RULE_C24 = """**Past Continuous: процесс в прошлом.**
was/were + -ing: I **was waiting** for the bus. It **was raining**.
Фон + событие: I was waiting **when he came** (процесс — Past Cont.,
событие — Past Simple). While I was cooking, she was cleaning.
−: I wasn't sleeping. ?: What **were** you **doing** at eight?"""

RULE_C25 = """**Повторение №14: сравнения и процесс.**
bigger/the biggest, as…as, too/enough; Past Continuous vs Past Simple
(процесс-фон + событие); глаголы с предлогами.
Пунктуация: **However,** … — запятая после вводного слова;
кавычки в английском: “ ” (не « »)."""

RULE_C26 = """**Аэропорт: сквозная сценка.**
check-in → security → gate → boarding. Полезные вопросы:
Where is the check-in desk? Which gate is my flight?
Is the flight on time? The flight is delayed.
Регистрация: window or aisle seat? Here is your boarding pass.
Безопасность: take out your liquids, empty your pockets."""

RULE_C27 = """**Паспортный контроль и таможня.**
Цель визита: What is the purpose of your visit? — Tourism / Business.
Сколько: How long will you stay? — Two weeks.
Бронь/билеты: Do you have a return ticket?
Таможня: Anything to declare? — Nothing to declare.
green channel — без декларации, red — с декларацией."""

RULE_C28 = """**Отель: заезд, проблемы, выезд.**
Заезд: I have a reservation. For three nights. Breakfast is included.
Проблемы: The room is too noisy. The air conditioning doesn't work.
Could you send someone to fix it? Could I change rooms?
Выезд: What time is check-out? I'm checking out. Could I have the bill?"""

RULE_C29 = """**Ресторан и аптека.**
Ресторан: A table for two. What do you recommend? I'll have the fish.
I'm allergic to nuts. Could we have the bill? Keep the change.
Аптека: How often should I take it? — Twice a day, after meals.
Do I need a prescription? Do you have something for a cold?"""

RULE_C30 = """**Большое повторение перед Вратами B.**
Всё ранга C: Past Simple ±? и was/were, will/going to, must/have to/
should/could, like + -ing, want + object + to, сравнения, as…as,
too/enough, глаголы с предлогами, Past Continuous.
Разговорник: аэропорт, паспорт, отель, ресторан, аптека.
Вперёд, Охотник — Врата B ждут!"""

LESSONS_C3_C5 = [
    {
        "id": "les-c-16", "module": "mod-c-3",
        "title": "must / have to: необходимость",
        "gp_id": "gp-c-16", "gp_title": "must и have to",
        "rule_md": RULE_C16,
        "phrases": C16,
        "rule_cloze": [
            ("You ___ show your passport.", ["must", "have to"]),
            ("I ___ to work tomorrow. (вынужден)", ["have"]),
            ("___ I have to fill in this form?", ["Do"]),
        ],
        "quotes": [("q-lord-of-the-rings-0017", "decide"), ("q-star-wars-0014", "know")],
        "trap_id": "trap-if-will",
        "vocab_band": {"list": "ngsl-spoken", "from": 2861, "to": 2920},
        "phrasebook_topic": "passport",
        "quotes_topic": "rules",
        "bebris_video": {"lesson": "2.300", "playlist_index": 851, "youtube_id": "H4-rXitQBN8", "title": None},
        "answer_question": [("Do I have to fill in this form?", "You have to fill in this form.")],
        "find_error": [("You must to stop.", "You must stop.")],
        "verb_tense": [
            ("She ___ to study.", "вынуждена", ["has"]),
            ("___ she have to come?", "вопрос", ["Does"]),
            ("We ___ change trains.", "необходимость", ["have to", "must"]),
        ],
    },
    {
        "id": "les-c-17", "module": "mod-c-3",
        "title": "should: совет (здоровье)",
        "gp_id": "gp-c-17", "gp_title": "should для советов",
        "rule_md": RULE_C17,
        "phrases": C17,
        "rule_cloze": [
            ("You ___ see a doctor. (совет)", ["should"]),
            ("You ___ eat so fast. (запрет-совет)", ["shouldn't", "should not"]),
            ("What ___ I do? (совет)", ["should"]),
        ],
        "quotes": [("q-supernatural-0025", "keep"), ("q-berserk-0016", "are")],
        "trap_id": "trap-im-agree",
        "vocab_band": {"list": "ngsl-spoken", "from": 2921, "to": 2980},
        "phrasebook_topic": "pharmacy",
        "quotes_topic": "health",
        "bebris_video": {"lesson": "2.300", "playlist_index": 851, "youtube_id": "H4-rXitQBN8", "title": None},
        "answer_question": [("Should I call a doctor?", "You should see a doctor.")],
        "find_error": [("You should to rest.", "You should rest.")],
        "verb_tense": [
            ("He ___ call her.", "совет", ["should"]),
            ("She ___ work so much. (не стоит)", "совет-запрет", ["shouldn't", "should not"]),
            ("I ___ to wait two hours.", "вчера", ["had"]),
        ],
    },
    {
        "id": "les-c-18", "module": "mod-c-3",
        "title": "could: прошедшее и вежливая просьба",
        "gp_id": "gp-c-18", "gp_title": "could: умел и вежливость",
        "rule_md": RULE_C18,
        "phrases": C18,
        "rule_cloze": [
            ("___ you help me, please? (вежливо)", ["Could", "Would", "Can"]),
            ("I ___ sleep yesterday. (не мог)", ["couldn't", "could not", "didn't"]),
            ("She ___ swim when she was five.", ["could"]),
        ],
        "quotes": [("q-fma-fma-b-0007", "could"), ("q-black-mirror-0010", "aren't")],
        "trap_id": "trap-said-me",
        "vocab_band": {"list": "ngsl-spoken", "from": 2981, "to": 3040},
        "phrasebook_topic": "restaurant",
        "quotes_topic": "requests",
        "bebris_video": {"lesson": "2.294", "playlist_index": 845, "youtube_id": "y8pcQGaMKI0", "title": None},
        "answer_question": [("Could you help me?", "Sure, no problem.")],
        "find_error": [("Could you to help me?", "Could you help me?")],
        "verb_tense": [
            ("___ I have the menu?", "вежливо", ["Could"]),
            ("We ___ find the hotel.", "в тот раз", ["couldn't", "could not"]),
            ("He ___ speak three languages.", "раньше", ["could"]),
        ],
    },
    {
        "id": "les-c-19", "module": "mod-c-3",
        "title": "like + -ing; want + object + to",
        "gp_id": "gp-c-19", "gp_title": "Герундий и инфинитивные конструкции",
        "rule_md": RULE_C19,
        "phrases": C19,
        "rule_cloze": [
            ("I like ___. (читать)", ["reading"]),
            ("I want you ___ understand.", ["to"]),
            ("She told me ___ wait.", ["to"]),
        ],
        "quotes": [("q-supernatural-0011", "want"), ("q-jujutsu-kaisen-0003", "is")],
        "trap_id": "trap-want-that",
        "vocab_band": {"list": "ngsl-spoken", "from": 3041, "to": 3100},
        "phrasebook_topic": "restaurant",
        "quotes_topic": "preferences",
        "bebris_video": {"lesson": "2.96", "playlist_index": 647, "youtube_id": "UxX1Ca2w7iY", "title": None},
        "answer_question": [("Do you like dancing?", "I like reading.")],
        "find_error": [("I want that you understand.", "I want you to understand.")],
        "verb_tense": [
            ("She doesn't like ___. (летать)", "герундий", ["flying"]),
            ("He wants us ___ wait.", "инфинитив", ["to"]),
            ("They asked me ___ stop.", "инфинитив", ["to"]),
        ],
    },
    {
        "id": "les-c-20", "module": "mod-c-3",
        "title": "Повторение №13: контрольная-тренировка",
        "gp_id": "gp-c-20", "gp_title": "Контрольная: должен и могу",
        "rule_md": RULE_C20,
        "phrases": C20,
        "rule_cloze": [
            ("You ___ smoke here. (запрещено)", ["mustn't", "must not"]),
            ("I ___ you to understand. (хочу)", ["want"]),
            ("___ you help me, please? (вежливо)", ["Could", "Would", "Can"]),
        ],
        "quotes": [("q-supernatural-0024", "picks"), ("q-supernatural-0020", "ain't")],
        "trap_id": "trap-want-that",
        "vocab_band": {"list": "ngsl-spoken", "from": 3101, "to": 3160},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("Should I call a doctor?", "You should see a doctor.")],
        "find_error": [("I want that he comes.", "I want him to come.")],
        "verb_tense": [
            ("You ___ to hurry.", "необходимость", ["have"]),
            ("I couldn't ___ last night.", "отдых", ["sleep"]),
            ("She likes ___. (готовить)", "герундий", ["cooking"]),
        ],
        "transform": [
            ("I can help you.", "past", "I could help you."),
            ("I must go.", "past", "I had to go."),
        ],
    },
    {
        "id": "les-c-21", "module": "mod-c-4",
        "title": "Сравнения: bigger / the biggest",
        "gp_id": "gp-c-21", "gp_title": "Сравнительная и превосходная степень",
        "rule_md": RULE_C21,
        "phrases": C21,
        "rule_cloze": [
            ("This room is ___. (больше)", ["bigger"]),
            ("It is ___ best day of my life.", ["the"]),
            ("This book is ___ interesting.", ["more"]),
        ],
        "quotes": [("q-berserk-0019", "strongest"), ("q-solo-leveling-0010", "alone")],
        "trap_id": "trap-very-like",
        "vocab_band": {"list": "ngsl-spoken", "from": 3161, "to": 3220},
        "phrasebook_topic": "hotel",
        "quotes_topic": "comparison",
        "bebris_video": {"lesson": "2.66", "playlist_index": 617, "youtube_id": "LBnXzY3pz6g", "title": None},
        "answer_question": [("Do you have a bigger room?", "It is bigger.")],
        "find_error": [("It is more bigger.", "It is bigger.")],
        "verb_tense": [
            ("The train is ___ than the bus.", "сравнение", ["faster", "cheaper"]),
            ("It is ___ city in Europe.", "самый большой", ["the biggest"]),
            ("Yesterday was ___ than today.", "жарче", ["hotter"]),
        ],
    },
    {
        "id": "les-c-22", "module": "mod-c-4",
        "title": "as … as; too / enough",
        "gp_id": "gp-c-22", "gp_title": "Равенство и достаточность",
        "rule_md": RULE_C22,
        "phrases": C22,
        "rule_cloze": [
            ("He is ___ tall as his brother.", ["as"]),
            ("This coffee is ___ hot. (слишком)", ["too"]),
            ("The room is big ___.", ["enough"]),
        ],
        "quotes": [("q-jujutsu-kaisen-0016", "your"), ("q-jujutsu-kaisen-0009", "don't")],
        "trap_id": "trap-very-like",
        "vocab_band": {"list": "ngsl-spoken", "from": 3221, "to": 3280},
        "phrasebook_topic": None,
        "quotes_topic": "comparison",
        "bebris_video": {"lesson": "2.66", "playlist_index": 617, "youtube_id": "LBnXzY3pz6g", "title": None},
        "answer_question": [("Is the room quiet enough?", "The room is too noisy.")],
        "find_error": [("He is too tall as me.", "He is as tall as me.")],
        "verb_tense": [
            ("It is not ___ cold as yesterday.", "равенство", ["as"]),
            ("The bag is ___ heavy to carry.", "слишком", ["too"]),
            ("I'm not old ___ to decide.", "достаточно", ["enough"]),
        ],
    },
    {
        "id": "les-c-23", "module": "mod-c-4",
        "title": "Глаголы с предлогами: pay for, depend on…",
        "gp_id": "gp-c-23", "gp_title": "Предлоги глаголов (закрепление)",
        "rule_md": RULE_C23,
        "phrases": C23,
        "rule_cloze": [
            ("Can I pay ___ the ticket by card?", ["for"]),
            ("It depends ___ the weather.", ["on"]),
            ("I'm looking ___ my keys.", ["for"]),
        ],
        "quotes": [("q-star-wars-0018", "lack"), ("q-berserk-0012", "belongs")],
        "trap_id": "trap-wait-for",
        "vocab_band": {"list": "ngsl-spoken", "from": 3281, "to": 3340},
        "phrasebook_topic": "taxi",
        "quotes_topic": "prepositions",
        "bebris_video": {"lesson": "1.60", "playlist_index": 182, "youtube_id": "2bsDP-r-RGk", "title": None},
        "answer_question": [("What are you looking for?", "I'm looking for my keys.")],
        "find_error": [("I'm waiting the bus.", "I'm waiting for the bus.")],
        "verb_tense": [
            ("Listen ___ me.", "кому", ["to"]),
            ("Thank you ___ everything.", "за", ["for"]),
            ("I agree ___ you.", "с", ["with"]),
        ],
    },
    {
        "id": "les-c-24", "module": "mod-c-4",
        "title": "Past Continuous: процесс в прошлом",
        "gp_id": "gp-c-24", "gp_title": "Past Continuous vs Past Simple",
        "rule_md": RULE_C24,
        "phrases": C24,
        "rule_cloze": [
            ("I ___ waiting for the bus.", ["was"]),
            ("They ___ playing outside.", ["were"]),
            ("She was reading when I ___. (позвонил)", ["called"]),
        ],
        "quotes": [("q-jujutsu-kaisen-0008", "got"), ("q-black-mirror-0014", "happen")],
        "trap_id": "trap-didnt-past",
        "vocab_band": {"list": "ngsl-spoken", "from": 3341, "to": 3400},
        "phrasebook_topic": "taxi",
        "quotes_topic": "past",
        "bebris_video": {"lesson": "2.36", "playlist_index": 587, "youtube_id": "nag2dLag6Mw", "title": None},
        "answer_question": [("What were you doing at eight?", "I was cooking dinner.")],
        "find_error": [("I was wait for the bus.", "I was waiting for the bus.")],
        "verb_tense": [
            ("The driver ___ driving too fast.", "процесс (прош.)", ["was"]),
            ("We ___ eating when he arrived.", "процесс (прош.)", ["were"]),
            ("It was raining when we ___. (вышли)", "событие (прош.)", ["left"]),
        ],
    },
    {
        "id": "les-c-25", "module": "mod-c-4",
        "title": "Повторение №14: сравнения и процесс",
        "gp_id": "gp-c-25", "gp_title": "Повторение модуля C4",
        "rule_md": RULE_C25,
        "phrases": C25,
        "rule_cloze": [
            ("He is ___ tall as me.", ["as"]),
            ("I ___ waiting for the bus.", ["was"]),
            ("However, ___ is one problem.", ["there"]),
        ],
        "quotes": [("q-memy-0009", "your"), ("q-lord-of-the-rings-0008", "smallest")],
        "trap_id": "trap-wait-for",
        "vocab_band": {"list": "ngsl-spoken", "from": 3401, "to": 3460},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("What were you doing at nine?", "I was reading a book.")],
        "find_error": [("I was waiting the bus.", "I was waiting for the bus.")],
        "verb_tense": [
            ("This coffee is ___ hot.", "слишком", ["too"]),
            ("She was ___ when I called.", "читать (процесс)", ["reading"]),
            ("It is ___ interesting book. (самая)", "superlative", ["the most"]),
        ],
    },
    {
        "id": "les-c-26", "module": "mod-c-5",
        "title": "Аэропорт: сквозная сценка",
        "gp_id": "gp-c-26", "gp_title": "Аэропорт: от регистрации до посадки",
        "rule_md": RULE_C26,
        "phrases": C26,
        "rule_cloze": [
            ("Where is the check-in ___?", ["desk"]),
            ("The flight is ___ by an hour.", ["delayed"]),
            ("Fasten your ___ belts.", ["seat"]),
        ],
        "quotes": [("q-igry-0010", "Praise"), ("q-igry-0012", "Do")],
        "trap_id": "trap-articles",
        "vocab_band": {"list": "ngsl-spoken", "from": 3461, "to": 3520},
        "phrasebook_topic": "airport",
        "quotes_topic": "travel",
        "bebris_video": None,
        "answer_question": [("Is the flight on time?", "The flight is delayed by an hour.")],
        "find_error": [("Where is the check-in desk for Rome flight?", "Where is the check-in desk for the Rome flight?")],
        "verb_tense": [
            ("What time ___ boarding start?", "расписание", ["does"]),
            ("Put your bag ___ the belt.", "на", ["on"]),
            ("Boarding starts ___ twenty minutes.", "через", ["in"]),
        ],
    },
    {
        "id": "les-c-27", "module": "mod-c-5",
        "title": "Паспортный контроль и таможня",
        "gp_id": "gp-c-27", "gp_title": "Паспортный контроль: типовые вопросы",
        "rule_md": RULE_C27,
        "phrases": C27,
        "rule_cloze": [
            ("What is the ___ of your visit?", ["purpose"]),
            ("How ___ will you stay?", ["long"]),
            ("Do you have a ___ ticket?", ["return"]),
        ],
        "quotes": [("q-attack-on-titan-0016", "met"), ("q-stranger-things-0020", "thinking")],
        "trap_id": "trap-question-word-order",
        "vocab_band": {"list": "ngsl-spoken", "from": 3521, "to": 3580},
        "phrasebook_topic": "passport",
        "quotes_topic": "travel",
        "bebris_video": None,
        "answer_question": [("How long will you stay?", "I'm here for a week.")],
        "find_error": [("What is purpose of your visit?", "What is the purpose of your visit?")],
        "verb_tense": [
            ("I'm here ___ holiday.", "в отпуске", ["on"]),
            ("Anything ___ declare?", "что декларировать", ["to"]),
            ("It's ___ personal use.", "для", ["for"]),
        ],
    },
    {
        "id": "les-c-28", "module": "mod-c-5",
        "title": "Отель: заезд, проблемы, выезд",
        "gp_id": "gp-c-28", "gp_title": "Отель: полный цикл",
        "rule_md": RULE_C28,
        "phrases": C28,
        "rule_cloze": [
            ("I ___ a reservation.", ["have"]),
            ("The air conditioning doesn't ___.", ["work"]),
            ("What time is ___-out?", ["check"]),
        ],
        "quotes": [("q-star-wars-0019", "matters"), ("q-memy-0002", "simply")],
        "trap_id": "trap-articles",
        "vocab_band": {"list": "ngsl-spoken", "from": 3581, "to": 3640},
        "phrasebook_topic": "hotel",
        "quotes_topic": "travel",
        "bebris_video": None,
        "answer_question": [("What time is check-out?", "Check-out is at noon.")],
        "find_error": [("Could you to send someone?", "Could you send someone?")],
        "verb_tense": [
            ("Breakfast is ___.", "включено", ["included"]),
            ("Could I have ___ extra pillow?", "дополнительную", ["an"]),
            ("The tv doesn't ___.", "работать", ["work"]),
        ],
    },
    {
        "id": "les-c-29", "module": "mod-c-5",
        "title": "Ресторан и аптека",
        "gp_id": "gp-c-29", "gp_title": "Ресторан: заказ; аптека: лекарства",
        "rule_md": RULE_C29,
        "phrases": C29,
        "rule_cloze": [
            ("A ___ for two, please.", ["table"]),
            ("How ___ should I take it?", ["often"]),
            ("Twice a day, ___ meals.", ["after"]),
        ],
        "quotes": [("q-igry-0008", "still"), ("q-star-wars-0014", "your")],
        "trap_id": "trap-articles",
        "vocab_band": {"list": "ngsl-spoken", "from": 3641, "to": 3700},
        "phrasebook_topic": "restaurant",
        "quotes_topic": "food",
        "bebris_video": None,
        "answer_question": [("What do you recommend?", "The special of the day is fish.")],
        "find_error": [("A table for two person.", "A table for two people.")],
        "verb_tense": [
            ("___ I have the menu?", "вежливо", ["Could", "May", "Can"]),
            ("How ___ should I take it?", "частота", ["often"]),
            ("One ___ in the morning.", "таблетка", ["tablet"]),
        ],
    },
    {
        "id": "les-c-30", "module": "mod-c-5",
        "title": "Большое повторение перед Вратами B",
        "gp_id": "gp-c-30", "gp_title": "Сборка всего ранга C",
        "rule_md": RULE_C30,
        "phrases": C30,
        "rule_cloze": [
            ("The flight is ___.", ["delayed"]),
            ("I ___ waiting for the bus.", ["was"]),
            ("He is ___ tall as his brother.", ["as"]),
        ],
        "quotes": [("q-solo-leveling-0001", "Arise"), ("q-star-wars-0013", "Never")],
        "trap_id": "trap-want-that",
        "vocab_band": {"list": "ngsl-spoken", "from": 3701, "to": 3760},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("Will everything be OK?", "Everything will be fine.")],
        "find_error": [("I am agree with you.", "I agree with you.")],
        "verb_tense": [
            ("I ___ call you tomorrow.", "будущее", ["will", "'ll"]),
            ("I'm going ___ travel this summer.", "инфинитив", ["to"]),
            ("Where ___ you stay last year?", "прош.", ["did"]),
        ],
    },
]
