#!/usr/bin/env python3
"""Пулы уроков B1 «Совершенное» (B-01…B-09) и B2 «Если и когда» (B-10…B-14)
— plan://M15#15.1–15.2. specs/01 §8: Present Perfect (введение, маркеры,
vs Past Simple, PPC, Past Perfect), условные 0/1/2, wish, used to.
"""

B01 = [
    ("I have finished.", "Я закончил.", None),
    ("She has arrived.", "Она приехала.", None),
    ("He has left.", "Он уехал.", None),
    ("We have started.", "Мы начали.", None),
    ("They have stopped.", "Они остановились.", None),
    ("I have seen this film.", "Я видел этот фильм.", None),
    ("She has read the book.", "Она прочитала книгу.", None),
    ("He has written a letter.", "Он написал письмо.", None),
    ("We have eaten.", "Мы поели.", None),
    ("They have gone home.", "Они ушли домой.", None),
    ("I have done it.", "Я это сделал.", None),
    ("She has made tea.", "Она приготовила чай.", None),
    ("He has taken my pen.", "Он взял мою ручку.", None),
    ("We have had lunch.", "Мы пообедали.", None),
    ("I have lost my keys.", "Я потерял ключи.", None),
    ("She has found the answer.", "Она нашла ответ.", None),
    ("He has broken the glass.", "Он разбил стакан.", None),
    ("The plane has landed.", "Самолёт приземлился.", None),
    ("The bus has come.", "Автобус пришёл.", None),
    ("The film has begun.", "Фильм начался.", None),
    ("I haven't finished yet.", "Я ещё не закончил.", None),
    ("She hasn't arrived.", "Она ещё не приехала.", None),
    ("He hasn't called.", "Он так и не позвонил.", None),
    ("We haven't decided.", "Мы ещё не решили.", None),
    ("Have you finished?", "Ты закончил?", None),
    ("Has she arrived?", "Она приехала?", None),
    ("Has he seen the film?", "Он видел фильм?", None),
    ("What have you done?", "Что ты сделал?", None),
    ("Where has he gone?", "Куда он ушёл?", None),
    ("I have never been to Japan.", "Я никогда не был в Японии.", None),
    ("She has been to Paris twice.", "Она была в Париже дважды.", None),
    ("We have known him for years.", "Мы знаем его много лет.", None),
    ("I have lived here since 2019.", "Я живу здесь с 2019-го.", None),
    ("She has worked here for five years.", "Она работает здесь пять лет.", None),
    ("He has changed a lot.", "Он сильно изменился.", None),
    ("The city has grown.", "Город вырос.", None),
    ("I have forgotten the word.", "Я забыл слово.", None),
    ("She has forgotten her umbrella.", "Она забыла зонт.", None),
    ("I have bought the tickets.", "Я купил билеты.", None),
    ("We have chosen the hotel.", "Мы выбрали отель.", None),
    ("The results are out.", "Результаты опубликованы.", None),
    ("It has started to rain.", "Начался дождь.", None),
    ("The shop has opened.", "Магазин открылся.", None),
    ("You have grown so much!", "Ты так вырос!", None),
    ("That was fast!", "Быстро однако!", None),
    ("I finish.", "Я заканчиваю.", None),
    ("She arrives.", "Она приезжает.", None),
    ("He left before I came.", "Он ушёл до того, как я пришёл.", None),
    ("If it rains, I'll stay at home.", "Если пойдёт дождь, я останусь дома.", None),
    ("I'll stay at home.", "Я останусь дома.", None),
    ("If I won the lottery, I would travel the world.", "Если бы я выиграл в лотерею, я бы объехал мир.", None),
    ("I stay at home.", "Я остаюсь дома.", None),
    ("I travel the world.", "Я путешествую по миру.", None),
]

B02 = [
    ("I have already eaten.", "Я уже поел.", None),
    ("She has already left.", "Она уже ушла.", None),
    ("He has already finished.", "Он уже закончил.", None),
    ("We have already seen it.", "Мы уже это видели.", None),
    ("They have already arrived.", "Они уже приехали.", None),
    ("I have already paid.", "Я уже заплатил.", None),
    ("I have never been to London.", "Я никогда не был в Лондоне.", None),
    ("She has never tried sushi.", "Она никогда не пробовала суши.", None),
    ("He has never smoked.", "Он никогда не курил.", None),
    ("We have never eaten there.", "Мы никогда там не ели.", None),
    ("I have never seen snow.", "Я никогда не видел снега.", None),
    ("She has never flown.", "Она никогда не летала на самолёте.", None),
    ("Have you ever been to Italy?", "Ты когда-нибудь был в Италии?", None),
    ("Have you ever tried Korean food?", "Ты когда-нибудь пробовал корейскую еду?", None),
    ("Have you ever seen this film?", "Ты когда-нибудь видел этот фильм?", None),
    ("Have you ever flown at night?", "Ты когда-нибудь летал ночью?", None),
    ("Has she ever been abroad?", "Она когда-нибудь была за границей?", None),
    ("Has he ever won anything?", "Он когда-нибудь что-нибудь выигрывал?", None),
    ("Yes, I have.", "Да.", None),
    ("No, never.", "Нет, никогда.", None),
    ("No, not yet.", "Нет, ещё нет.", None),
    ("I have been to three countries.", "Я был в трёх странах.", None),
    ("She has visited six cities.", "Она посетила шесть городов.", None),
    ("I have tried it once.", "Я пробовал это один раз.", None),
    ("Twice.", "Дважды.", None),
    ("Many times.", "Много раз.", None),
    ("Which countries have you visited?", "Какие страны ты посетил?", None),
    ("I have been abroad twice.", "Я дважды был за границей.", None),
    ("Have you ever been on a boat?", "Ты когда-нибудь был на лодке?", None),
    ("Have you ever missed a flight?", "Ты когда-нибудь опаздывал на рейс?", None),
    ("I have missed one, in 2022.", "Я опоздал на один, в 2022-м.", None),
    ("Have you ever lost your luggage?", "Ты когда-нибудь терял багаж?", None),
    ("Never, luckily.", "Никогда, к счастью.", None),
    ("I have never travelled alone.", "Я никогда не путешествовал один.", None),
    ("She has already packed.", "Она уже собрала вещи.", None),
    ("I have never thought about it.", "Я никогда об этом не думал.", None),
    ("What about you?", "А ты?", None),
    ("Me too.", "Я тоже.", None),
    ("Me neither.", "Я тоже нет.", None),
    ("Neither have I.", "И я нет.", None),
    ("So have I.", "И я.", None),
    ("Have you ever won a prize?", "Ты когда-нибудь выигрывал приз?", None),
    ("That sounds interesting.", "Звучит интересно.", None),
    ("What was it like?", "Как это было?", None),
]

B03 = [
    ("I have just finished.", "Я только что закончил.", None),
    ("She has just left.", "Она только что ушла.", None),
    ("He has just called.", "Он только что позвонил.", None),
    ("The film has just started.", "Фильм только что начался.", None),
    ("We have just arrived.", "Мы только что приехали.", None),
    ("I have just woken up.", "Я только что проснулся.", None),
    ("She has just cooked dinner.", "Она только что приготовила ужин.", None),
    ("The train has just left.", "Поезд только что отошёл.", None),
    ("I have just seen him.", "Я только что его видел.", None),
    ("They have just moved in.", "Они только что переехали.", None),
    ("I haven't finished yet.", "Я ещё не закончил.", None),
    ("She hasn't called yet.", "Она ещё не позвонила.", None),
    ("He hasn't arrived yet.", "Он ещё не приехал.", None),
    ("We haven't decided yet.", "Мы ещё не решили.", None),
    ("They haven't paid yet.", "Они ещё не заплатили.", None),
    ("I haven't eaten yet.", "Я ещё не ел.", None),
    ("Has she come yet?", "Она уже пришла?", None),
    ("Have you finished yet?", "Ты уже закончил?", None),
    ("Has the flight landed yet?", "Рейс уже приземлился?", None),
    ("Not yet.", "Ещё нет.", None),
    ("I have recently changed my job.", "Недавно я сменил работу.", None),
    ("She has recently moved to Berlin.", "Недавно она переехала в Берлин.", None),
    ("He has recently started learning English.", "Он недавно начал учить английский.", None),
    ("We have recently bought a car.", "Мы недавно купили машину.", None),
    ("I have just had lunch.", "Я только что пообедал.", None),
    ("The meeting has just ended.", "Встреча только что закончилась.", None),
    ("I have just sent it.", "Я только что отправил.", None),
    ("She has just texted me.", "Она только что написала мне.", None),
    ("Dinner is not ready yet.", "Ужин ещё не готов.", None),
    ("I'm still waiting.", "Я всё ещё жду.", None),
    ("Are you ready yet?", "Ты уже готов?", None),
    ("Almost.", "Почти.", None),
    ("Nearly there.", "Почти готово.", None),
    ("Just a second.", "Одну секунду.", None),
    ("I have already told you.", "Я тебе уже говорил.", None),
    ("I told you just now.", "Я говорил тебе только что.", None),
    ("What have you done lately?", "Чем ты занимался в последнее время?", None),
    ("I have been busy recently.", "В последнее время я был занят.", None),
    ("Nothing much.", "Ничего особенного.", None),
    ("Same as always.", "Как обычно.", None),
    ("I haven't seen you for ages!", "Я тебя сто лет не видел!", None),
    ("Where have you been?", "Где ты был?", None),
    ("I have been away.", "Я был в отъезде.", None),
    ("Good to see you!", "Рад тебя видеть!", None),
]

B04 = [
    ("be — was — been", "быть — был — был (V3)", None),
    ("go — went — gone", "идти — шёл — ушедший (V3)", None),
    ("see — saw — seen", "видеть — видел — виденный (V3)", None),
    ("do — did — done", "делать — делал — сделанный (V3)", None),
    ("have — had — had", "иметь — имел — имевший (V3)", None),
    ("make — made — made", "делать — делал — сделанный (V3)", None),
    ("take — took — taken", "брать — брал — взятый (V3)", None),
    ("come — came — come", "приходить — пришёл — пришедший (V3)", None),
    ("get — got — got", "получать — получил — полученный (V3)", None),
    ("say — said — said", "говорить — сказал — сказанный (V3)", None),
    ("tell — told — told", "рассказывать — рассказал — рассказанный (V3)", None),
    ("know — knew — known", "знать — знал — известный (V3)", None),
    ("think — thought — thought", "думать — думал — продуманный (V3)", None),
    ("buy — bought — bought", "покупать — купил — купленный (V3)", None),
    ("bring — brought — brought", "приносить — принёс — принесённый (V3)", None),
    ("write — wrote — written", "писать — писал — написанный (V3)", None),
    ("read — read — read", "читать — читал — прочитанный (V3)", None),
    ("eat — ate — eaten", "есть — ел — съеденный (V3)", None),
    ("drink — drank — drunk", "пить — пил — выпитый (V3)", None),
    ("speak — spoke — spoken", "говорить — говорил — говорённый (V3)", None),
    ("leave — left — left", "уходить — ушёл — ушедший (V3)", None),
    ("meet — met — met", "встречать — встретил — встреченный (V3)", None),
    ("find — found — found", "находить — нашёл — найденный (V3)", None),
    ("give — gave — given", "давать — дал — данный (V3)", None),
    ("lose — lost — lost", "терять — потерял — потерянный (V3)", None),
    ("feel — felt — felt", "чувствовать — чувствовал — почувствованный (V3)", None),
    ("sleep — slept — slept", "спать — спал — спавший (V3)", None),
    ("fall — fell — fallen", "падать — упал — упавший (V3)", None),
    ("wake — woke — woken", "просыпаться — проснулся — проснувшийся (V3)", None),
    ("understand — understood — understood", "понимать — понял — понятый (V3)", None),
    ("forget — forgot — forgotten", "забывать — забыл — забытый (V3)", None),
    ("break — broke — broken", "ломать — сломал — сломанный (V3)", None),
    ("drive — drove — driven", "водить — водил — водивший (V3)", None),
    ("fly — flew — flown", "летать — летал — летавший (V3)", None),
    ("grow — grew — grown", "расти — рос — выросший (V3)", None),
    ("wear — wore — worn", "носить — носил — ношеный (V3)", None),
    ("choose — chose — chosen", "выбирать — выбрал — выбранный (V3)", None),
    ("begin — began — begun", "начинать — начал — начатый (V3)", None),
    ("sit — sat — sat", "сидеть — сидел — сидевший (V3)", None),
    ("stand — stood — stood", "стоять — стоял — стоявший (V3)", None),
    ("win — won — won", "побеждать — победил — победивший (V3)", None),
    ("build — built — built", "строить — строил — построенный (V3)", None),
    ("He has already gone.", "Он уже ушёл.", None),
    ("She has written a book.", "Она написала книгу.", None),
    ("They have built a house.", "Они построили дом.", None),
    ("I have read the article.", "Я прочитал статью.", None),
    ("She has forgotten the word.", "Она забыла слово.", None),
    ("I have brought some water.", "Я принёс воды.", None),
    ("We have sold the flat.", "Мы продали квартиру.", None),
    ("He has lost his wallet.", "Он потерял кошелёк.", None),
    ("They have begun the race.", "Они начали гонку.", None),
    ("She has won.", "Она победила.", None),
    ("He has fallen.", "Он упал.", None),
    ("We have sat down.", "Мы сели.", None),
    ("I have stood up.", "Я встал.", None),
    ("The city has grown.", "Город вырос.", None),
    ("We have chosen a plan.", "Мы выбрали план.", None),
    ("He has driven all night.", "Он ехал всю ночь.", None),
    ("She has worn it once.", "Она надевала это один раз.", None),
    ("He has gone.", "Он ушёл.", None),
    ("I have never flown.", "Я никогда не летал.", None),
]

B05 = [
    ("I have finished the book.", "Я закончил книгу.", None),
    ("She has never been abroad.", "Она никогда не была за границей.", None),
    ("Have you ever tried Indian food?", "Ты когда-нибудь пробовал индийскую еду?", None),
    ("He has just left.", "Он только что ушёл.", None),
    ("I haven't seen it yet.", "Я это ещё не видел.", None),
    ("I have already paid.", "Я уже заплатил.", None),
    ("We have known each other for years.", "Мы знаем друг друга много лет.", None),
    ("She has recently changed her hair.", "Недавно она сменила причёску.", None),
    ("They have moved to a new house.", "Они переехали в новый дом.", None),
    ("I have lost my phone.", "Я потерял телефон.", None),
    ("He has broken his leg.", "Он сломал ногу.", None),
    ("The film has already started.", "Фильм уже начался.", None),
    ("Have you finished your homework yet?", "Ты уже сделал домашнее задание?", None),
    ("I have never seen such a beautiful place.", "Я никогда не видел такого красивого места.", None),
    ("I have seen it.", "Я это видел.", None),
    ("She has just called me.", "Она только что мне позвонила.", None),
    ("We haven't decided yet.", "Мы ещё не решили.", None),
    ("He has grown a beard.", "Он отрастил бороду.", None),
    ("I have forgotten her name.", "Я забыл её имя.", None),
    ("They have sold their car.", "Они продали машину.", None),
    ("She has written three books.", "Она написала три книги.", None),
    ("I have read it twice.", "Я читал это дважды.", None),
    ("He has chosen the red one.", "Он выбрал красный.", None),
    ("We have taken a taxi.", "Мы взяли такси.", None),
    ("I have brought some food.", "Я принёс еду.", None),
    ("She has told me everything.", "Она рассказала мне всё.", None),
    ("The weather has changed.", "Погода изменилась.", None),
    ("Prices have gone up.", "Цены выросли.", None),
    ("Everything has become expensive.", "Всё стало дорогим.", None),
    ("I have done my best.", "Я сделал всё возможное.", None),
    ("Have you ever driven at night?", "Ты когда-нибудь водил ночью?", None),
    ("She has worn this dress once.", "Она надевала это платье один раз.", None),
    ("I have met him before.", "Я уже встречал его раньше.", None),
    ("Where have you been all day?", "Где ты был весь день?", None),
    ("What have you done today?", "Что ты сделал сегодня?", None),
    ("I have been busy.", "Я был занят.", None),
    ("Nothing special.", "Ничего особенного.", None),
    ("The usual.", "Как обычно.", None),
    ("I haven't done much.", "Я мало что сделал.", None),
    ("You have changed so much!", "Ты так изменился!", None),
    ("I haven't seen you for a long time.", "Давно тебя не видел.", None),
    ("How have you been?", "Как ты поживаешь?", None),
    ("I have been fine, thanks.", "Нормально, спасибо.", None),
    ("Everything is fine.", "Всё хорошо.", None),
    ("Long time no see!", "Давно не виделись!", None),
]

B06 = [
    ("I have seen the film.", "Я видел фильм.", None),
    ("I saw the film yesterday.", "Я смотрел фильм вчера.", None),
    ("She has been to Paris.", "Она была в Париже.", None),
    ("She went to Paris last year.", "Она ездила в Париж в прошлом году.", None),
    ("He has finished the work.", "Он закончил работу.", None),
    ("He finished the work at five.", "Он закончил работу в пять.", None),
    ("We have arrived.", "Мы приехали.", None),
    ("We arrived an hour ago.", "Мы приехали час назад.", None),
    ("They have left.", "Они уехали.", None),
    ("They left on Monday.", "Они уехали в понедельник.", None),
    ("I have just eaten.", "Я только что поел.", None),
    ("I ate at noon.", "Я поел в полдень.", None),
    ("I have done it.", "Я это сделал.", None),
    ("I did it last week.", "Я сделал это на прошлой неделе.", None),
    ("She has called me.", "Она мне позвонила.", None),
    ("She called me this morning.", "Она позвонила мне сегодня утром.", None),
    ("When did you see him?", "Когда ты его видел?", None),
    ("When have you seen him?", "Когда ты его видел?", None),
    ("I saw him two days ago.", "Я видел его два дня назад.", None),
    ("I saw him yesterday.", "Я видел его вчера.", None),
    ("I saw it two days ago.", "Я видел это два дня назад.", None),
    ("Did you watch the game?", "Ты смотрел игру?", None),
    ("Yes, I watched it yesterday.", "Да, я смотрел её вчера.", None),
    ("Have you watched the new episode?", "Ты смотрел новую серию?", None),
    ("Not yet.", "Ещё нет.", None),
    ("I have never watched it.", "Я никогда её не смотрел.", None),
    ("I was in London in 2022.", "Я был в Лондоне в 2022-м.", None),
    ("I have been to London twice.", "Я был в Лондоне дважды.", None),
    ("When were you there?", "Когда ты там был?", None),
    ("Last spring.", "Прошлой весной.", None),
    ("I liked it a lot.", "Мне очень понравилось.", None),
    ("What did you like most?", "Что понравилось больше всего?", None),
    ("I did it for me.", "Я сделал это для себя.", None),
    ("I liked it.", "Мне это нравилось.", None),
    ("I was good at it.", "Я был в этом хорош.", None),
    ("I have read the book.", "Я прочитал книгу.", None),
    ("I read the book last month.", "Я прочитал книгу в прошлом месяце.", None),
    ("She has lived here since childhood.", "Она живёт здесь с детства.", None),
    ("She lived here as a child.", "Она жила здесь в детстве.", None),
    ("He has worked there for a year.", "Он работает там уже год.", None),
    ("He worked there a year ago.", "Он работал там год назад.", None),
    ("I have never said that.", "Я никогда этого не говорил.", None),
    ("I said nothing.", "Я ничего не сказал.", None),
    ("Yesterday is gone.", "Вчера ушло.", None),
    ("Today is a new day.", "Сегодня новый день.", None),
    ("Move on.", "Двигайся дальше.", None),
]

B07 = [
    ("How long have you been learning English?", "Как долго ты учишь английский?", None),
    ("I have been learning English for two years.", "Я учу английский два года.", None),
    ("I have been learning English since January.", "Я учу английский с января.", None),
    ("How long have you been living here?", "Как долго ты здесь живёшь?", None),
    ("I have been living here for ten years.", "Я живу здесь десять лет.", None),
    ("She has been working all day.", "Она работает весь день.", None),
    ("He has been waiting for two hours.", "Он ждёт уже два часа.", None),
    ("We have been travelling since morning.", "Мы в пути с утра.", None),
    ("They have been talking for an hour.", "Они разговаривают уже час.", None),
    ("I have been reading this book all week.", "Я читаю эту книгу всю неделю.", None),
    ("It has been raining all day.", "Весь день идёт дождь.", None),
    ("The sun has been shining since morning.", "Солнце светит с утра.", None),
    ("She has been cooking for three hours.", "Она готовит уже три часа.", None),
    ("He has been playing football since childhood.", "Он играет в футбол с детства.", None),
    ("I have been thinking about it.", "Я думаю об этом.", None),
    ("We have been looking for a flat.", "Мы ищем квартиру.", None),
    ("She has been studying hard.", "Она усердно занимается.", None),
    ("How long have you been waiting?", "Как долго ты ждёшь?", None),
    ("I have been waiting for twenty minutes.", "Я жду двадцать минут.", None),
    ("He has been driving all night.", "Он ехал всю ночь.", None),
    ("It has been snowing since Friday.", "Снег идёт с пятницы.", None),
    ("My back hurts — I have been sitting too long.", "У меня болит спина — я слишком долго сидел.", None),
    ("I'm tired — I have been running.", "Я устал — я бегал.", None),
    ("She is out of breath — she has been climbing.", "Она запыхалась — она поднималась в гору.", None),
    ("Why are your eyes red? — I have been crying.", "Почему у тебя красные глаза? — Я плакала.", None),
    ("What have you been doing?", "Чем ты занимался?", None),
    ("I have been cleaning the house.", "Я убирался в доме.", None),
    ("We have been watching a series.", "Мы смотрели сериал.", None),
    ("I have been trying to call you.", "Я пытался тебе дозвониться.", None),
    ("How long have you been married?", "Как долго вы женаты?", None),
    ("For five years.", "Пять лет.", None),
    ("We have been together since 2020.", "Мы вместе с 2020-го.", None),
    ("I have been levelling up this whole time.", "Я всё это время прокачивался.", None),
    ("You have been improving.", "Ты прогрессируешь.", None),
    ("Your English is getting better and better.", "Твой английский становится всё лучше.", None),
    ("I have been practising every day.", "Я практикуюсь каждый день.", None),
    ("Keep going!", "Продолжай!", None),
    ("Don't give up.", "Не сдавайся.", None),
    ("It pays off.", "Это окупается.", None),
    ("How long has it been going on?", "Как давно это продолжается?", None),
    ("It started a week ago.", "Это началось неделю назад.", None),
    ("How long have you known each other?", "Как давно вы знакомы?", None),
    ("Since school.", "Со школы.", None),
    ("That's a long time.", "Это долго.", None),
]

B08 = [
    ("I had finished before you came.", "Я закончил до того, как ты пришёл.", None),
    ("She had left when I arrived.", "Она уже ушла, когда я приехал.", None),
    ("He had eaten before the trip.", "Он поел до поездки.", None),
    ("We had booked the tickets in advance.", "Мы забронировали билеты заранее.", None),
    ("They had sold out by noon.", "Всё было распродано к полудню.", None),
    ("The film had already started.", "Фильм уже начался.", None),
    ("I had never seen it before.", "Я никогда раньше этого не видел.", None),
    ("She had never been there before that trip.", "Она никогда раньше не была там до той поездки.", None),
    ("He had forgotten his wallet.", "Он забыл кошелёк.", None),
    ("I had lost the address.", "Я потерял адрес.", None),
    ("We had no money — I had spent it all.", "У нас не было денег — я всё потратил.", None),
    ("The bus had gone when we got there.", "Автобус ушёл, когда мы туда добрались.", None),
    ("I realized I had made a mistake.", "Я понял, что сделал ошибку.", None),
    ("She said she had already eaten.", "Она сказала, что уже поела.", None),
    ("He told me he had finished.", "Он сказал мне, что закончил.", None),
    ("I thought I had seen him before.", "Я подумал, что уже видел его раньше.", None),
    ("It was too late — the shop had closed.", "Было слишком поздно — магазин закрылся.", None),
    ("The plane had taken off.", "Самолёт взлетел.", None),
    ("When I got home, she had already gone to bed.", "Когда я пришёл домой, она уже легла спать.", None),
    ("By the time we arrived, the party had ended.", "К моменту нашего приезда вечеринка закончилась.", None),
    ("After I had finished, I went for a walk.", "После того как я закончил, я пошёл гулять.", None),
    ("After she had said it, she regretted.", "После того как она это сказала, она пожалела.", None),
    ("I had never heard it before that day.", "Я никогда не слышал этого до того дня.", None),
    ("The city had changed a lot.", "Город сильно изменился.", None),
    ("Everything had gone wrong.", "Всё пошло не так.", None),
    ("I had a dream.", "У меня была мечта.", None),
    ("A dream is something you do for yourself.", "Мечта — это то, что ты делаешь для себя.", None),
    ("It had taken years.", "Это заняло годы.", None),
    ("Nobody had believed in him.", "Никто в него не верил.", None),
    ("He had kept his promise.", "Он сдержал обещание.", None),
    ("They had won the war.", "Они выиграли войну.", None),
    ("She had found the key at last.", "Она наконец нашла ключ.", None),
    ("The train had left without us.", "Поезд ушёл без нас.", None),
    ("I had missed my chance.", "Я упустил свой шанс.", None),
    ("It had all happened before.", "Это всё уже случалось раньше.", None),
    ("I didn't know what had happened.", "Я не знал, что случилось.", None),
    ("What had gone wrong?", "Что пошло не так?", None),
    ("By then, everything had changed.", "К тому времени всё изменилось.", None),
    ("I wish I had known.", "Жаль, что я не знал.", None),
    ("If only I had listened.", "Если бы я только слушал.", None),
    ("Hindsight is a wonderful thing.", "Задним умом все крепки.", None),
    ("It was bound to happen.", "Это должно было случиться.", None),
    ("The past is the past.", "Прошлое остаётся прошлым.", None),
    ("What's done is done.", "Сделанного не воротишь.", None),
]

B09 = [
    ("I have finished.", "Я закончил.", None),
    ("I have been waiting for an hour.", "Я жду уже час.", None),
    ("I had finished before you came.", "Я закончил до того, как ты пришёл.", None),
    ("She has just left.", "Она только что ушла.", None),
    ("He had already gone.", "Он уже ушёл.", None),
    ("Have you ever been to Rome?", "Ты когда-нибудь был в Риме?", None),
    ("I went to Rome last year.", "Я ездил в Рим в прошлом году.", None),
    ("I have been learning for two years.", "Я учусь уже два года.", None),
    ("She has never flown.", "Она никогда не летала.", None),
    ("We hadn't booked — everything was full.", "Мы не забронировали — всё было занято.", None),
    ("I haven't eaten yet.", "Я ещё не ел.", None),
    ("The film had started when we arrived.", "Фильм начался, когда мы приехали.", None),
    ("He has been working since morning.", "Он работает с утра.", None),
    ("They had sold out by noon.", "К полудню всё распродали.", None),
    ("I have just seen him.", "Я только что его видел.", None),
    ("She had lost the keys.", "Она потеряла ключи.", None),
    ("I have known him for years.", "Я знаю его много лет.", None),
    ("What have you been doing?", "Чем ты занимался?", None),
    ("How long have you been waiting?", "Как долго ты ждёшь?", None),
    ("I had no idea.", "Я и не догадывался.", None),
    ("I have already told you.", "Я тебе уже говорил.", None),
    ("He said he had finished.", "Он сказал, что закончил.", None),
    ("We have moved.", "Мы переехали.", None),
    ("They had never met before.", "Они никогда раньше не встречались.", None),
    ("She has been cooking all morning.", "Она готовит всё утро.", None),
    ("The train had already left.", "Поезд уже ушёл.", None),
    ("I have never tried it.", "Я никогда это не пробовал.", None),
    ("He had broken the window.", "Он разбил окно.", None),
    ("I have bought the tickets.", "Я купил билеты.", None),
    ("We had paid in advance.", "Мы заплатили заранее.", None),
    ("She has just called.", "Она только что позвонила.", None),
    ("I had never seen snow before.", "Я никогда раньше не видел снега.", None),
    ("It has been raining all day.", "Весь день идёт дождь.", None),
    ("He had kept it secret.", "Он держал это в секрете.", None),
    ("I have done my best.", "Я сделал всё возможное.", None),
    ("Everything had gone well.", "Всё прошло хорошо.", None),
    ("Have you finished yet?", "Ты уже закончил?", None),
    ("What had happened?", "Что случилось?", None),
    ("She has changed her mind.", "Она передумала.", None),
    ("I had thought it was easy.", "Я думал, это легко.", None),
    ("We have decided.", "Мы решили.", None),
    ("They had warned us.", "Они нас предупреждали.", None),
    ("It has stopped raining.", "Дождь прекратился.", None),
    ("Good riddance.", "И слава богу.", None),
    ("He left.", "Он ушёл.", None),
    ("He had left.", "Он уже ушёл (до).", None),
]

# --------------------------------------------------------------------------
# B2 «Если и когда» (B-10…B-14)
# --------------------------------------------------------------------------
B10 = [
    ("If it rains, I'll stay at home.", "Если пойдёт дождь, я останусь дома.", None),
    ("I'll stay at home.", "Я останусь дома.", None),
    ("If you help me, I'll finish faster.", "Если ты поможешь, я закончу быстрее.", None),
    ("If she calls, tell her I'm busy.", "Если она позвонит, скажи, что я занят.", None),
    ("If we miss the bus, we'll take a taxi.", "Если мы опоздаем на автобус, возьмём такси.", None),
    ("If you don't hurry, you'll be late.", "Если не поторопишься, опоздаешь.", None),
    ("If he asks, I'll say yes.", "Если он спросит, я скажу «да».", None),
    ("If the weather is good, we'll go out.", "Если погода будет хорошей, мы пойдём гулять.", None),
    ("If I have time, I'll call you.", "Если будет время, я позвоню.", None),
    ("If you need anything, just ask.", "Если что-нибудь понадобится — просто скажи.", None),
    ("If it gets cold, take a jacket.", "Если похолодает, возьми куртку.", None),
    ("If you heat water, it boils.", "Если нагреть воду, она кипит.", None),
    ("If you press this button, the light comes on.", "Если нажать эту кнопку, включается свет.", None),
    ("Ice melts if you heat it.", "Лёд тает, если его нагреть.", None),
    ("Plants die if you don't water them.", "Растения погибают, если их не поливать.", None),
    ("If I wake up early, I go for a walk.", "Если я встаю рано, я иду гулять.", None),
    ("If you mix blue and yellow, you get green.", "Если смешать синий и жёлтый, получится зелёный.", None),
    ("I'll do it if you want.", "Я сделаю это, если хочешь.", None),
    ("We'll leave if you're ready.", "Мы поедем, если ты готов.", None),
    ("I won't go if it rains.", "Я не пойду, если будет дождь.", None),
    ("She won't come if she's busy.", "Она не придёт, если будет занята.", None),
    ("Will you help me if I ask?", "Ты поможешь, если я попрошу?", None),
    ("What will you do if it snows?", "Что ты будешь делать, если пойдёт снег?", None),
    ("What happens if I press this?", "Что будет, если я нажму на это?", None),
    ("Nothing happens.", "Ничего не произойдёт.", None),
    ("If you disturb me, I'll kill you.", "Если ты меня побеспокоишь, я тебя убью.", None),
    ("If you leave now, you'll catch the train.", "Если уйдёшь сейчас, успеешь на поезд.", None),
    ("If I see him, I'll tell him.", "Если я его увижу, я ему скажу.", None),
    ("If you're good, you'll get a reward.", "Если будешь хорошо себя вести, получишь награду.", None),
    ("If it works, it works.", "Если работает — работает.", None),
    ("If not, we'll try again.", "Если нет — попробуем ещё раз.", None),
    ("Do whatever you want.", "Делай что хочешь.", None),
    ("Suit yourself.", "Как знаешь.", None),
    ("It's up to you.", "Решать тебе.", None),
    ("Whatever works.", "Что работает, то и хорошо.", None),
    ("It depends.", "Как посмотреть.", None),
    ("In that case…", "В таком случае…", None),
    ("In any case, call me.", "В любом случае позвони мне.", None),
    ("Just in case.", "На всякий случай.", None),
    ("You never know.", "Всякое бывает.", None),
    ("Better safe than sorry.", "Бережёного бог бережёт.", None),
    ("If I were you, I'd go.", "На твоём месте я бы пошёл.", None),
    ("Unless it rains, we'll walk.", "Если не будет дождя, пойдём пешком.", None),
    ("Unless you object.", "Если только ты не против.", None),
    ("As long as you're happy.", "Лишь бы ты был счастлив.", None),
]

B11 = [
    ("If I had more time, I would travel.", "Если бы у меня было больше времени, я бы путешествовал.", None),
    ("If I had time, I would travel.", "Если бы у меня было время, я бы путешествовал.", None),
    ("I would travel the world.", "Я бы путешествовал по миру.", None),
    ("If I were rich, I would buy a house.", "Если бы я был богат, я бы купил дом.", None),
    ("If she were here, she would help.", "Если бы она была здесь, она бы помогла.", None),
    ("If I knew the answer, I would tell you.", "Если бы я знал ответ, я бы тебе сказал.", None),
    ("If we had a car, we would drive.", "Если бы у нас была машина, мы бы поехали.", None),
    ("If he studied harder, he would pass.", "Если бы он учился усерднее, он бы сдал.", None),
    ("I would go if I could.", "Я бы пошёл, если бы мог.", None),
    ("She would stay if you asked.", "Она бы осталась, если бы ты попросил.", None),
    ("I would help you if I had time.", "Я бы помог тебе, если бы было время.", None),
    ("They would win if they played better.", "Они бы выиграли, если бы играли лучше.", None),
    ("If I won the lottery, I would travel the world.", "Если бы я выиграл в лотерею, я бы объехал мир.", None),
    ("What would you do if you were the boss?", "Что бы ты делал, если бы был начальником?", None),
    ("What would you buy if you had the money?", "Что бы ты купил, если бы были деньги?", None),
    ("I would relax.", "Я бы отдыхал.", None),
    ("I would sleep all day.", "Я бы спал весь день.", None),
    ("I would learn to fly.", "Я бы научился летать.", None),
    ("If I could choose, I would live by the sea.", "Если бы я мог выбрать, я бы жил у моря.", None),
    ("If it weren't so far, we would go more often.", "Если бы это было не так далеко, мы бы ходили туда чаще.", None),
    ("If I were younger, I would try again.", "Если бы я был моложе, я бы попробовал снова.", None),
    ("Nah, I'd win.", "Не-а, я бы выиграл.", None),
    ("I'd rather fight for my life than live it.", "Я бы скорее сражался за жизнь, чем просто жил.", None),
    ("I would rather stay.", "Я бы лучше остался.", None),
    ("I would rather not talk about it.", "Я бы предпочёл об этом не говорить.", None),
    ("Would you rather stay or go?", "Ты бы лучше остался или пошёл?", None),
    ("If only I knew.", "Если бы я только знал.", None),
    ("If only it were Friday.", "Если бы сегодня была пятница.", None),
    ("Life would be easier.", "Жизнь была бы проще.", None),
    ("It would be nice.", "Было бы неплохо.", None),
    ("That would be great.", "Было бы здорово.", None),
    ("Dream on!", "Мечтай!", None),
    ("In your dreams.", "В мечтах.", None),
    ("Maybe someday.", "Может, когда-нибудь.", None),
    ("Someday, but not today.", "Когда-нибудь, но не сегодня.", None),
    ("It's just a dream.", "Это просто мечта.", None),
    ("Dreams come true.", "Мечты сбываются.", None),
    ("If I had known, I would have come.", "Если бы я знал, я бы пришёл.", None),
    ("If we had left earlier, we would have caught it.", "Если бы мы вышли раньше, мы бы успели.", None),
    ("If you had told me!", "Если бы ты мне сказал!", None),
    ("You would have loved it.", "Тебе бы понравилось.", None),
    ("It would have been different.", "Всё было бы иначе.", None),
    ("No use crying over spilt milk.", "Слезами делу не поможешь.", None),
    ("Second chances are rare.", "Вторые шансы редки.", None),
    ("Next time.", "В следующий раз.", None),
    ("There's always next time.", "Всегда есть следующий раз.", None),
]

B12 = [
    ("I wish I were there.", "Жаль, что меня там нет.", None),
    ("I wish I had more time.", "Жаль, что у меня мало времени.", None),
    ("I wish I could fly.", "Жаль, что я не умею летать.", None),
    ("I wish it were Friday.", "Жаль, что сегодня не пятница.", None),
    ("I wish I knew.", "Жаль, что я не знаю.", None),
    ("I wish I had known.", "Жаль, что я не знал.", None),
    ("She wishes she were taller.", "Она жалеет, что она не выше.", None),
    ("He wishes he had studied.", "Он жалеет, что не учился.", None),
    ("We wish you were here.", "Жаль, что тебя здесь нет.", None),
    ("I wish you would stop.", "Хотел бы я, чтобы ты прекратил.", None),
    ("I wish it would stop raining.", "Хотел бы я, чтобы дождь прекратился.", None),
    ("I wish they would be quiet.", "Хотел бы я, чтобы они заткнулись.", None),
    ("If only I were younger.", "Если бы я был только моложе.", None),
    ("If only we had more money.", "Если бы только у нас было больше денег.", None),
    ("If only she could come.", "Если бы только она могла прийти.", None),
    ("If only I had listened!", "Если бы я только слушал!", None),
    ("I regret nothing.", "Я ни о чём не жалею.", None),
    ("I should have called.", "Надо было позвонить.", None),
    ("I shouldn't have said that.", "Не надо было это говорить.", None),
    ("You should have told me.", "Тебе следовало мне сказать.", None),
    ("We could have won.", "Мы могли бы выиграть.", None),
    ("It could have been worse.", "Могло быть и хуже.", None),
    ("It would have been fun.", "Было бы весело.", None),
    ("If I had known, I would have gone.", "Если бы я знал, я бы пошёл.", None),
    ("No regrets.", "Без сожалений.", None),
    ("What's done is done.", "Сделанного не воротишь.", None),
    ("The past is the past.", "Прошлое в прошлом.", None),
    ("Don't look back.", "Не оглядывайся.", None),
    ("Move forward.", "Двигайся вперёд.", None),
    ("Learn from it.", "Сделай выводы.", None),
    ("Everything happens for a reason.", "Всё происходит не просто так.", None),
    ("It was meant to be.", "Так было суждено.", None),
    ("It wasn't meant to be.", "Этому не суждено было случиться.", None),
    ("Some other time.", "Как-нибудь в другой раз.", None),
    ("Maybe next time.", "Может, в следующий раз.", None),
    ("It's not the end of the world.", "Это не конец света.", None),
    ("Cheer up!", "Не унывай!", None),
    ("Look on the bright side.", "Смотри на светлую сторону.", None),
    ("Every cloud has a silver lining.", "Нет худа без добра.", None),
    ("Time heals.", "Время лечит.", None),
    ("This too shall pass.", "И это пройдёт.", None),
    ("Better days are coming.", "Лучшие дни впереди.", None),
    ("Never say never.", "Никогда не говори «никогда».", None),
    ("One can dream.", "Помечтать-то можно.", None),
]

B13 = [
    ("I used to live in London.", "Я раньше жил в Лондоне.", None),
    ("I used to live here.", "Я раньше жил здесь.", None),
    ("She used to play the piano.", "Она раньше играла на пианино.", None),
    ("I used to play the piano.", "Я раньше играл на пианино.", None),
    ("He used to smoke.", "Он раньше курил.", None),
    ("We used to go there every summer.", "Мы раньше ездили туда каждое лето.", None),
    ("They used to be friends.", "Раньше они были друзьями.", None),
    ("I used to like it.", "Раньше мне это нравилось.", None),
    ("She used to work here.", "Она раньше работала здесь.", None),
    ("He used to be shy.", "Раньше он был застенчивым.", None),
    ("I didn't use to like coffee.", "Раньше я не любил кофе.", None),
    ("She didn't use to drive.", "Раньше она не водила машину.", None),
    ("We didn't use to travel much.", "Раньше мы мало путешествовали.", None),
    ("He didn't use to be so serious.", "Раньше он не был таким серьёзным.", None),
    ("Did you use to play sports?", "Ты раньше занимался спортом?", None),
    ("Did she use to live here?", "Она раньше жила здесь?", None),
    ("Where did you use to go on holiday?", "Куда ты раньше ездил в отпуск?", None),
    ("I used to be an adventurer like you.", "Раньше я был искателем приключений, как ты.", None),
    ("Then I took an arrow in the knee.", "А потом мне прострелили колено.", None),
    ("I'm used to it.", "Я привык.", None),
    ("She is used to the cold.", "Она привыкла к холоду.", None),
    ("He is used to working at night.", "Он привык работать ночью.", None),
    ("I'm not used to this weather.", "Я не привык к такой погоде.", None),
    ("You'll get used to it.", "Ты привыкнешь.", None),
    ("I can't get used to it.", "Не могу привыкнуть.", None),
    ("It takes time to get used to.", "Нужно время, чтобы привыкнуть.", None),
    ("When I was a child, we played outside.", "В детстве мы играли на улице.", None),
    ("Back then, everything was different.", "Тогда всё было иначе.", None),
    ("Things change.", "Всё меняется.", None),
    ("People change.", "Люди меняются.", None),
    ("Those were the days.", "Вот это были времена.", None),
    ("Good old days.", "Старые добрые времена.", None),
    ("I miss those times.", "Я скучаю по тем временам.", None),
    ("Do you remember?", "Помнишь?", None),
    ("Those were good times.", "Это было хорошее время.", None),
    ("We were young then.", "Мы были тогда молоды.", None),
    ("Where did the time go?", "Куда ушло время?", None),
    ("It feels like yesterday.", "Кажется, это было вчера.", None),
    ("A lifetime ago.", "Целая жизнь прошла.", None),
    ("Not anymore.", "Уже нет.", None),
    ("Not like before.", "Уже не как раньше.", None),
    ("That was then, this is now.", "Тогда было тогда, сейчас — сейчас.", None),
    ("Times have changed.", "Времена изменились.", None),
    ("Nothing lasts forever.", "Ничто не вечно.", None),
    ("Life goes on.", "Жизнь продолжается.", None),
    ("Here and now.", "Здесь и сейчас.", None),
]

B14 = [
    ("If it rains, I'll stay at home.", "Если пойдёт дождь, я останусь дома.", None),
    ("I'll stay at home.", "Я останусь дома.", None),
    ("If I had time, I would help you.", "Если бы у меня было время, я бы помог.", None),
    ("If I had known, I would have come.", "Если бы я знал, я бы пришёл.", None),
    ("I wish I were there.", "Жаль, что меня там нет.", None),
    ("I wish I had known.", "Жаль, что я не знал.", None),
    ("I used to live in Rome.", "Я раньше жил в Риме.", None),
    ("She used to play tennis.", "Она раньше играла в теннис.", None),
    ("I'm used to getting up early.", "Я привык рано вставать.", None),
    ("I would rather stay.", "Я бы лучше остался.", None),
    ("What would you do if you won?", "Что бы ты сделал, если бы выиграл?", None),
    ("If only I could!", "Если бы я только мог!", None),
    ("You should have told me.", "Тебе следовало сказать мне.", None),
    ("We could have met.", "Мы могли бы встретиться.", None),
    ("If you heat ice, it melts.", "Если нагреть лёд, он тает.", None),
    ("If you asked, she would help.", "Если бы ты попросил, она бы помогла.", None),
    ("If we miss the bus, we'll walk.", "Если опоздаем на автобус, пойдём пешком.", None),
    ("Unless it rains, we'll go.", "Если не будет дождя, мы пойдём.", None),
    ("I didn't use to like tea.", "Раньше я не любил чай.", None),
    ("Did you use to travel a lot?", "Ты раньше много путешествовал?", None),
    ("I used to, but not anymore.", "Раньше да, но уже нет.", None),
    ("I wish it would stop.", "Хотел бы я, чтобы это прекратилось.", None),
    ("I wish you were here.", "Жаль, что тебя здесь нет.", None),
    ("If I were you…", "На твоём месте…", None),
    ("In your shoes…", "На твоём месте…", None),
    ("If I had a choice…", "Если бы у меня был выбор…", None),
    ("It would be better.", "Было бы лучше.", None),
    ("It could happen.", "Это может случиться.", None),
    ("You never know.", "Всякое бывает.", None),
    ("That's life.", "Такова жизнь.", None),
    ("Such is life.", "Такова уж жизнь.", None),
    ("What if it doesn't work?", "А если не сработает?", None),
    ("What if we're wrong?", "А если мы неправы?", None),
    ("Then we'll try again.", "Тогда попробуем снова.", None),
    ("Then plan B.", "Тогда план Б.", None),
    ("There's always a plan B.", "План Б есть всегда.", None),
    ("Backup plan.", "Запасной план.", None),
    ("Worst case, we lose.", "В худшем случае проиграем.", None),
    ("Best case, we win.", "В лучшем случае выиграем.", None),
    ("Either way, we learn.", "В любом случае мы научимся.", None),
    ("Win or learn.", "Победи или научись.", None),
    ("No failure, only feedback.", "Нет поражений — только обратная связь.", None),
    ("Try and try again.", "Пробуй и пробуй снова.", None),
    ("If at first you don't succeed…", "Если сначала не получилось…", None),
    ("…try, try again.", "…пробуй, пробуй ещё.", None),
    ("I will stay at home.", "Я останусь дома.", None),
    ("I will travel the world.", "Я путешествую по миру.", None),
]

RULE_B01 = """**Present Perfect: have + V3.**
have/has + 3-я форма: I **have finished**. She **has arrived**.
Результат сейчас: I **have lost** my keys (и сейчас их нет).
−: I **haven't finished**. ?: **Have** you **finished**?
Стоп: это не «прошедшее время» — это настоящее о прошлом!"""

RULE_B02 = """**already / never / ever.**
**already** = «уже»: I have **already** eaten.
**never** = «никогда»: I have **never** been to Japan.
**ever** = «когда-нибудь» (вопросы): **Have** you **ever** been to Italy?
been to = «был (и вернулся)»; gone to = «поехал (там)»."""

RULE_B03 = """**just / yet / recently.**
**just** = «только что»: I have **just** finished.
**yet** = «ещё» (−) / «уже» (?): I haven't finished **yet**.
**recently / lately** = «в последнее время».
Разница: just now + Past Simple / just + Present Perfect."""

RULE_B04 = """**3-я форма неправильных глаголов.**
be→been, go→gone, see→seen, do→done, take→taken, know→known,
write→written, eat→eaten, speak→spoken, forget→forgotten, break→broken…
have/has + V3: He **has gone**. I have never **flown**.
Топ-50 V3 форм — интенсив-урок."""

RULE_B05 = """**Повторение №15: Present Perfect база.**
have/has + V3; already, never, ever, just, yet, recently;
been to vs gone to; have + V3 как «результат сейчас».
Диктант: маркеры подскажут время — слушай внимательно."""

RULE_B06 = """**Present Perfect vs Past Simple.**
Результат/опыт (когда — не важно): I **have seen** it. — Present Perfect
Момент в прошлом (yesterday, ago, last…): I **saw** it **yesterday**.
⚠️ Ловушка ЛТ-16: с точным прошедшим временем — только Past Simple:
❌ I have seen it yesterday → I **saw** it yesterday."""

RULE_B07 = """**Present Perfect Continuous.**
have/has been + V-ing: I **have been learning** for two years.
= «делаю уже сколько-то» (процесс до сих пор):
How long **have** you **been waiting**? — I**'ve been waiting** for 20 min.
Результат процесса: I'm tired — I **have been running**."""

RULE_B08 = """**Past Perfect: had + V3.**
Предшествование: действие ДО другого прошедшего:
I **had finished** before you **came**. (сначала finished — потом came)
Маркеры: by the time, before, after, already, never…before.
She said she **had** already **eaten**."""

RULE_B09 = """**Повторение №16: совершенные времена.**
Present Perfect (have+V3), PPC (have been+Ving), Past Perfect (had+V3).
Контрольная: выбери время, поставь форму, найди ошибку.
Стратегия: маркер → время; результат-сейчас → Perfect; процесс → PPC."""

RULE_B10 = """**Условные 0 и 1.**
0 (закон): **If** you heat water, it **boils**. (настоящее в обеих)
1 (реальное будущее): **If it rains**, I **'ll stay**. (if+настоящее, will)
⚠️ Ловушка ЛТ-17: в if-части НЕТ will: ❌ if it will rain → if it rains."""

RULE_B11 = """**Условное 2 (гипотеза).**
**If** + Past Simple, **would** + 1-я форма:
If I **had** more time, I **would travel**.
were для всех лиц: If I **were** you…
Нереально сейчас: мечты, «если бы…»."""

RULE_B12 = """**wish: сожаления.**
**I wish** + Past Simple = «жаль, что не так сейчас»: I wish I **were** there.
**I wish** + would = «хотел бы, чтобы перестал»: I wish it **would stop**.
**If only** = то же, но сильнее: If only I **knew**!
should have / could have — упущенные возможности."""

RULE_B13 = """**used to.**
**used to** + 1-я форма = «раньше было» (сейчас нет):
I **used to live** in London. ? : **Did** you **use to** play?
be/get **used to** + -ing = «привык»: I'**m used to getting** up early.
Разница: «раньше было» vs «привычка сейчас»."""

RULE_B14 = """**Повторение №17: условия и привычки.**
Условные 0/1/2: if + настоящее/will; if + Past/would; if + had/would have.
wish + were/would; used to «раньше» vs be used to «привык».
Стратегия: «реально или гипотеза?» → 1 или 2; «сейчас или раньше?» → be/get."""

LESSONS_B1_B2 = [
    {
        "id": "les-b-01", "module": "mod-b-1",
        "title": "Present Perfect: have + V3",
        "gp_id": "gp-b-01", "gp_title": "Present Perfect введение",
        "rule_md": RULE_B01,
        "phrases": B01,
        "rule_cloze": [
            ("I ___ finished.", ["have"]),
            ("She ___ arrived.", ["has"]),
            ("___ you seen the film?", ["Have"]),
        ],
        "quotes": [("q-solo-leveling-0002", "I've"), ("q-solo-leveling-0002", "been")],
        "trap_id": "trap-didnt-past",
        "vocab_band": {"list": "ngsl-spoken", "from": 3761, "to": 3820},
        "phrasebook_topic": None,
        "quotes_topic": "perfect",
        "bebris_video": {"lesson": "2.51", "playlist_index": 602, "youtube_id": "e9vi3UqDrNc", "title": None},
        "answer_question": [("Have you finished?", "I have finished.")],
        "find_error": [("I have finish.", "I have finished.")],
        "verb_tense": [
            ("He ___ left.", "PP", ["has"]),
            ("We ___ eaten.", "PP", ["have"]),
            ("___ she arrived?", "PP", ["Has"]),
        ],
    },
    {
        "id": "les-b-02", "module": "mod-b-1",
        "title": "already / never / ever",
        "gp_id": "gp-b-02", "gp_title": "Маркеры Present Perfect",
        "rule_md": RULE_B02,
        "phrases": B02,
        "rule_cloze": [
            ("I have ___ eaten.", ["already"]),
            ("I have ___ been to Japan.", ["never"]),
            ("Have you ___ been to Italy?", ["ever"]),
        ],
        "quotes": [("q-igry-0015", "have"), ("q-solo-leveling-0002", "been")],
        "trap_id": "trap-didnt-past",
        "vocab_band": {"list": "ngsl-spoken", "from": 3821, "to": 3880},
        "phrasebook_topic": "smalltalk",
        "quotes_topic": "perfect",
        "bebris_video": {"lesson": "2.51", "playlist_index": 602, "youtube_id": "e9vi3UqDrNc", "title": None},
        "answer_question": [("Have you ever been to Italy?", "I have never been to Japan.")],
        "find_error": [("I have ever been to London.", "I have never been to London.")],
        "verb_tense": [
            ("She has ___ left.", "уже", ["already"]),
            ("He has ___ flown.", "никогда", ["never"]),
            ("Have you ___ tried it?", "когда-нибудь", ["ever"]),
        ],
    },
    {
        "id": "les-b-03", "module": "mod-b-1",
        "title": "just / yet / recently",
        "gp_id": "gp-b-03", "gp_title": "just, yet, recently",
        "rule_md": RULE_B03,
        "phrases": B03,
        "rule_cloze": [
            ("I have ___ finished.", ["just"]),
            ("I haven't finished ___.", ["yet"]),
            ("Has she come ___?", ["yet"]),
        ],
        "quotes": [("q-solo-leveling-0002", "this"), ("q-jujutsu-kaisen-0002", "alone")],
        "trap_id": "trap-didnt-past",
        "vocab_band": {"list": "ngsl-spoken", "from": 3881, "to": 3940},
        "phrasebook_topic": None,
        "quotes_topic": "perfect",
        "bebris_video": None,
        "answer_question": [("Have you finished yet?", "Not yet.")],
        "find_error": [("I have just now finished.", "I have just finished.")],
        "verb_tense": [
            ("He has just ___. (уйти)", "PP", ["left"]),
            ("We haven't decided ___.", "ещё", ["yet"]),
            ("I have ___ changed my job.", "недавно", ["recently"]),
        ],
    },
    {
        "id": "les-b-04", "module": "mod-b-1",
        "title": "3-я форма: топ-50 неправильных глаголов",
        "gp_id": "gp-b-04", "gp_title": "V3-интенсив",
        "rule_md": RULE_B04,
        "phrases": B04,
        "rule_cloze": [
            ("go — went — ___", ["gone"]),
            ("see — saw — ___", ["seen"]),
            ("write — wrote — ___", ["written"]),
        ],
        "quotes": [("q-igry-0015", "died"), ("q-memy-0006", "killed")],
        "trap_id": "trap-didnt-past",
        "vocab_band": {"list": "ngsl-spoken", "from": 3941, "to": 4000},
        "phrasebook_topic": None,
        "quotes_topic": "perfect",
        "bebris_video": {"lesson": "2.101", "playlist_index": 652, "youtube_id": "Zkc-HfcTxYg", "title": None},
        "answer_question": [("Have you ever flown?", "I have never flown.")],
        "find_error": [("He has went.", "He has gone.")],
        "verb_tense": [
            ("eat — ate — ___", "V3", ["eaten"]),
            ("know — knew — ___", "V3", ["known"]),
            ("break — broke — ___", "V3", ["broken"]),
        ],
    },
    {
        "id": "les-b-05", "module": "mod-b-1",
        "title": "Повторение №15 + диктант",
        "gp_id": "gp-b-05", "gp_title": "Повторение: Present Perfect база",
        "rule_md": RULE_B05,
        "phrases": B05,
        "rule_cloze": [
            ("I have ___ seen it. (уже)", ["already"]),
            ("She hasn't arrived ___.", ["yet"]),
            ("___ you ever tried it?", ["Have"]),
        ],
        "quotes": [("q-solo-leveling-0002", "I've"), ("q-igry-0015", "died")],
        "trap_id": "trap-didnt-past",
        "vocab_band": {"list": "ngsl-spoken", "from": 4001, "to": 4060},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("How have you been?", "I have been fine, thanks.")],
        "find_error": [("I have see it.", "I have seen it.")],
        "verb_tense": [
            ("He has broken his ___.", "нога", ["leg"]),
            ("We have ___ each other for years.", "знать", ["known"]),
            ("It has ___ to rain.", "начаться", ["started"]),
        ],
    },
    {
        "id": "les-b-06", "module": "mod-b-1",
        "title": "Present Perfect vs Past Simple",
        "gp_id": "gp-b-06", "gp_title": "Контраст времён",
        "rule_md": RULE_B06,
        "phrases": B06,
        "rule_cloze": [
            ("I ___ the film yesterday.", ["saw"]),
            ("I ___ seen the film. (без маркера)", ["have"]),
            ("She ___ to Paris last year.", ["went"]),
        ],
        "quotes": [("q-berserk-0018", "do"), ("q-berserk-0018", "for")],
        "trap_id": "trap-present-perfect",
        "vocab_band": {"list": "ngsl-spoken", "from": 4061, "to": 4120},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("When did you see it?", "I saw it two days ago.")],
        "find_error": [("I have seen him yesterday.", "I saw him yesterday.")],
        "verb_tense": [
            ("I ___ him two days ago.", "точное время", ["saw"]),
            ("She ___ just called.", "только что", ["has"]),
            ("___ you watch the game?", "прош. точн.", ["Did"]),
        ],
    },
    {
        "id": "les-b-07", "module": "mod-b-1",
        "title": "Present Perfect Continuous",
        "gp_id": "gp-b-07", "gp_title": "have been + V-ing",
        "rule_md": RULE_B07,
        "phrases": B07,
        "rule_cloze": [
            ("How long have you been ___ English?", ["learning"]),
            ("I have been ___ here for ten years.", ["living"]),
            ("She has been ___ all day.", ["working"]),
        ],
        "quotes": [("q-solo-leveling-0002", "leveling"), ("q-solo-leveling-0002", "whole")],
        "trap_id": "trap-present-perfect",
        "vocab_band": {"list": "ngsl-spoken", "from": 4121, "to": 4180},
        "phrasebook_topic": "smalltalk",
        "quotes_topic": "perfect",
        "bebris_video": {"lesson": "2.201", "playlist_index": 752, "youtube_id": "IxjdanDgqWE", "title": None},
        "answer_question": [("How long have you been waiting?", "I have been waiting for twenty minutes.")],
        "find_error": [("I have been learn English for two years.", "I have been learning English for two years.")],
        "verb_tense": [
            ("He has been ___ for two hours.", "ждать", ["waiting"]),
            ("It has been ___ all day.", "идти (о дожде)", ["raining"]),
            ("How long have you been ___ here?", "жить", ["living"]),
        ],
    },
    {
        "id": "les-b-08", "module": "mod-b-1",
        "title": "Past Perfect: had + V3",
        "gp_id": "gp-b-08", "gp_title": "Предшествование в прошлом",
        "rule_md": RULE_B08,
        "phrases": B08,
        "rule_cloze": [
            ("I ___ finished before you came.", ["had"]),
            ("She ___ left when I arrived.", ["had"]),
            ("The film had ___ started.", ["already"]),
        ],
        "quotes": [("q-berserk-0018", "something"), ("q-berserk-0018", "yourself")],
        "trap_id": "trap-present-perfect",
        "vocab_band": {"list": "ngsl-spoken", "from": 4181, "to": 4240},
        "phrasebook_topic": None,
        "quotes_topic": "perfect",
        "bebris_video": {"lesson": "2.86", "playlist_index": 637, "youtube_id": "fNZOGDWS1bI", "title": None},
        "answer_question": [("What had happened?", "The bus had gone when we got there.")],
        "find_error": [("I had finish before you came.", "I had finished before you came.")],
        "verb_tense": [
            ("He ___ eaten before the trip.", "предшеств.", ["had"]),
            ("The train ___ left without us.", "предшеств.", ["had"]),
            ("She said she ___ already eaten.", "предшеств.", ["had"]),
        ],
    },
    {
        "id": "les-b-09", "module": "mod-b-1",
        "title": "Повторение №16: контрольная-тренировка",
        "gp_id": "gp-b-09", "gp_title": "Контрольная: совершенные времена",
        "rule_md": RULE_B09,
        "phrases": B09,
        "rule_cloze": [
            ("I have been ___ for an hour.", ["waiting"]),
            ("She had ___ gone.", ["already"]),
            ("I went to Rome ___ year.", ["last"]),
        ],
        "quotes": [("q-memy-0006", "die"), ("q-solo-leveling-0002", "I've")],
        "trap_id": "trap-present-perfect",
        "vocab_band": {"list": "ngsl-spoken", "from": 4241, "to": 4300},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("Have you finished yet?", "I have finished.")],
        "find_error": [("I had finish before you came.", "I had finished before you came.")],
        "verb_tense": [
            ("I ___ been learning for two years.", "PPC", ["have"]),
            ("He had ___ the window.", "V3 от break", ["broken"]),
            ("I have ___ him for years.", "V3 от know", ["known"]),
        ],
        "transform": [
            ("I finish.", "perfect", "I have finished."),
            ("She arrives.", "perfect", "She has arrived."),
            ("He left.", "past perfect", "He had left."),
        ],
    },
    {
        "id": "les-b-10", "module": "mod-b-2",
        "title": "Условные 0 и 1: if + will",
        "gp_id": "gp-b-10", "gp_title": "If it rains, I'll stay",
        "rule_md": RULE_B10,
        "phrases": B10,
        "rule_cloze": [
            ("If it ___, I'll stay at home.", ["rains"]),
            ("If you help me, I'll ___ faster.", ["finish"]),
            ("If you ___ this button, the light comes on.", ["press"]),
        ],
        "quotes": [("q-berserk-0001", "if"), ("q-berserk-0001", "I'll")],
        "trap_id": "trap-if-will",
        "vocab_band": {"list": "ngsl-spoken", "from": 4301, "to": 4360},
        "phrasebook_topic": None,
        "quotes_topic": "conditionals",
        "bebris_video": {"lesson": "2.307", "playlist_index": 858, "youtube_id": "MC0EPmPnTH8", "title": None},
        "answer_question": [("What will you do if it rains?", "I'll stay at home.")],
        "find_error": [("If it will rain, I'll stay at home.", "If it rains, I'll stay at home.")],
        "verb_tense": [
            ("If you ___ water, it boils.", "закон", ["heat"]),
            ("If she calls, ___ her I'm busy.", "скажи", ["tell"]),
            ("If you don't hurry, you ___ be late.", "следствие", ["'ll", "will"]),
        ],
    },
    {
        "id": "les-b-11", "module": "mod-b-2",
        "title": "Условное 2: If I had…, I would…",
        "gp_id": "gp-b-11", "gp_title": "Гипотезы и мечты",
        "rule_md": RULE_B11,
        "phrases": B11,
        "rule_cloze": [
            ("If I ___ more time, I would travel.", ["had"]),
            ("If I were rich, I ___ buy a house.", ["would"]),
            ("What would you ___ if you were the boss?", ["do"]),
        ],
        "quotes": [("q-jujutsu-kaisen-0002", "Earth"), ("q-berserk-0002", "rather")],
        "trap_id": "trap-if-will",
        "vocab_band": {"list": "ngsl-spoken", "from": 4361, "to": 4420},
        "phrasebook_topic": None,
        "quotes_topic": "conditionals",
        "bebris_video": {"lesson": "2.316", "playlist_index": 867, "youtube_id": "V5PCgdjBQf8", "title": None},
        "answer_question": [("What would you do if you won the lottery?", "I would travel the world.")],
        "find_error": [("If I would have time, I would travel.", "If I had time, I would travel.")],
        "verb_tense": [
            ("If I ___ you, I'd go.", "быть (сослаг.)", ["were"]),
            ("She would stay if you ___.", "попросить (прош.)", ["asked"]),
            ("If we ___ a car, we would drive.", "усл.2", ["had"]),
        ],
    },
    {
        "id": "les-b-12", "module": "mod-b-2",
        "title": "wish: сожаления",
        "gp_id": "gp-b-12", "gp_title": "I wish I were there",
        "rule_md": RULE_B12,
        "phrases": B12,
        "rule_cloze": [
            ("I wish I ___ there.", ["were"]),
            ("I wish I ___ more time.", ["had"]),
            ("If only I ___ known!", ["had"]),
        ],
        "quotes": [("q-berserk-0002", "rather"), ("q-game-of-thrones-0014", "win")],
        "trap_id": "trap-if-will",
        "vocab_band": {"list": "ngsl-spoken", "from": 4421, "to": 4480},
        "phrasebook_topic": None,
        "quotes_topic": "conditionals",
        "bebris_video": {"lesson": "2.319", "playlist_index": 870, "youtube_id": "EEMmcyY2nvc", "title": None},
        "answer_question": [("Do you regret anything?", "I regret nothing.")],
        "find_error": [("I wish I am there.", "I wish I were there.")],
        "verb_tense": [
            ("I wish I ___ fly.", "мочь (сослаг.)", ["could"]),
            ("I wish it ___ stop raining.", "прекратить", ["would"]),
            ("I should ___ called.", "надо было", ["have"]),
        ],
    },
    {
        "id": "les-b-13", "module": "mod-b-2",
        "title": "used to: «раньше»",
        "gp_id": "gp-b-13", "gp_title": "used to + be used to",
        "rule_md": RULE_B13,
        "phrases": B13,
        "rule_cloze": [
            ("I ___ to live in London.", ["used"]),
            ("I'm ___ to it.", ["used"]),
            ("Did you ___ to play sports?", ["use"]),
        ],
        "quotes": [("q-igry-0003", "used"), ("q-igry-0003", "took")],
        "trap_id": "trap-to-home",
        "vocab_band": {"list": "ngsl-spoken", "from": 4481, "to": 4540},
        "phrasebook_topic": "smalltalk",
        "quotes_topic": "past",
        "bebris_video": {"lesson": "2.334", "playlist_index": 885, "youtube_id": "NzG1Hio8rO0", "title": None},
        "answer_question": [("Did you use to play sports?", "I used to play the piano.")],
        "find_error": [("I am used to live here.", "I used to live here.")],
        "verb_tense": [
            ("I used to ___ in Rome.", "жить", ["live"]),
            ("She is used to ___ up early.", "вставать", ["getting"]),
            ("You'll get ___ to it.", "привыкнуть", ["used"]),
        ],
    },
    {
        "id": "les-b-14", "module": "mod-b-2",
        "title": "Повторение №17",
        "gp_id": "gp-b-14", "gp_title": "Повторение: условия и привычки",
        "rule_md": RULE_B14,
        "phrases": B14,
        "rule_cloze": [
            ("If I ___ time, I would help you.", ["had"]),
            ("I wish I ___ there.", ["were"]),
            ("I ___ to live in Rome.", ["used"]),
        ],
        "quotes": [("q-berserk-0001", "if"), ("q-igry-0003", "used")],
        "trap_id": "trap-if-will",
        "vocab_band": {"list": "ngsl-spoken", "from": 4541, "to": 4600},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("What would you do if you won?", "I would relax.")],
        "find_error": [("If I would have time, I would help you.", "If I had time, I would help you.")],
        "verb_tense": [
            ("If it ___, I'll stay.", "условие 1", ["rains"]),
            ("If I were rich, I ___ buy a house.", "условие 2", ["would"]),
            ("I'm used to ___ up early.", "привычка", ["getting"]),
        ],
        "transform": [
            ("I stay at home.", "future", "I will stay at home."),
            ("I travel the world.", "future", "I will travel the world."),
        ],
    },
]
