#!/usr/bin/env python3
"""Пулы уроков A1 «Времена под микроскопом» (A-01…A-06) и A2 «Модальные
в прошедшем» (A-07…A-11) — план M16#16.1–16.2. specs/01 §9.
"""

A01 = [
    ("This time tomorrow I'll be flying to Rome.", "Завтра в это время я буду лететь в Рим.", None),
    ("Don't call at eight — I'll be cooking.", "Не звони в восемь — я буду готовить.", None),
    ("She'll be waiting for us at the airport.", "Она будет ждать нас в аэропорту.", None),
    ("We'll be arriving at noon.", "Мы прибудем в полдень.", None),
    ("He'll be sleeping when you get home.", "Он будет спать, когда ты придёшь домой.", None),
    ("They'll be having dinner at seven.", "Они будут ужинать в семь.", None),
    ("I'll be working all day tomorrow.", "Я буду работать весь день завтра.", None),
    ("The train will be leaving at six.", "Поезд будет отправляться в шесть.", None),
    ("What will you be doing this time next week?", "Что ты будешь делать в это время на следующей неделе?", None),
    ("I'll be travelling around Europe.", "Я буду путешествовать по Европе.", None),
    ("Will you be using the car tomorrow?", "Ты будешь пользоваться машиной завтра?", None),
    ("She won't be working on Friday.", "Она не будет работать в пятницу.", None),
    ("We won't be staying long.", "Мы не останемся надолго.", None),
    ("I won't be needing it.", "Мне это не понадобится.", None),
    ("The sun will be setting when we land.", "Солнце будет садиться, когда мы приземлимся.", None),
    ("Everyone will be watching.", "Все будут смотреть.", None),
    ("The world will be sleeping.", "Мир будет спать.", None),
    ("I'll be thinking of you.", "Я буду думать о тебе.", None),
    ("She'll be studying for her exam.", "Она будет готовиться к экзамену.", None),
    ("We'll be living in Berlin by then.", "К тому времени мы будем жить в Берлине.", None),
    ("This time tomorrow, I'll be lying on a beach.", "Завтра в это время я буду лежать на пляже.", None),
    ("Don't worry — I'll be waiting.", "Не волнуйся — я буду ждать.", None),
    ("While you're sleeping, I'll be working.", "Пока ты будешь спать, я буду работать.", None),
    ("The children will be playing in the garden.", "Дети будут играть в саду.", None),
    ("At this rate, we'll be losing money.", "Такими темпами мы будем терять деньги.", None),
    ("I'll be there.", "Я буду там.", None),
    ("She'll be late.", "Она опоздает.", None),
    ("We'll be ready.", "Мы будем готовы.", None),
    ("They'll be waiting.", "Они будут ждать.", None),
    ("He'll be sleeping.", "Он будет спать.", None),
    ("I'll be cooking dinner.", "Я буду готовить ужин.", None),
]

A02 = [
    ("By next year, he'll have finished his degree.", "К следующему году он закончит учёбу.", None),
    ("By the time you arrive, I'll have cooked dinner.", "К твоему приходу я уже приготовлю ужин.", None),
    ("She'll have left by then.", "К тому времени она уже уедет.", None),
    ("We'll have been married for ten years.", "К тому времени мы будем женаты десять лет.", None),
    ("They'll have sold everything by Friday.", "К пятнице они всё продадут.", None),
    ("I'll have read the book by then.", "К тому времени я уже прочитаю книгу.", None),
    ("He'll have forgotten by tomorrow.", "К завтрашнему дню он уже забудет.", None),
    ("The plane will have landed by six.", "Самолёт уже приземлится к шести.", None),
    ("Will you have finished by five?", "Ты закончишь к пяти?", None),
    ("She won't have heard the news yet.", "Она ещё не услышит новость.", None),
    ("We won't have arrived by then.", "Мы ещё не приедем к тому времени.", None),
    ("In two years, I'll have learned English.", "Через два года я выучу английский.", None),
    ("By 2030, they'll have built the bridge.", "К 2030 году они построят мост.", None),
    ("By the end of the month, I'll have saved enough.", "К концу месяца я накоплю достаточно.", None),
    ("She'll have written three books by now.", "К этому времени она напишет три книги.", None),
    ("He'll have been working there for twenty years.", "К тому времени он будет работать там двадцать лет.", None),
    ("Everything will have changed.", "Всё изменится.", None),
    ("Nothing will have happened.", "Ничего не случится.", None),
    ("The results will have been announced.", "Результаты уже будут объявлены.", None),
    ("It will have been a long journey.", "Это будет долгое путешествие.", None),
    ("I'll have finished.", "Я закончу.", None),
    ("She'll have left.", "Она уедет.", None),
    ("We'll have arrived.", "Мы приедем.", None),
    ("They'll have eaten.", "Они поедят.", None),
    ("He'll have gone.", "Он уйдёт.", None),
    ("He'll have forgotten by tomorrow.", "Он забудет к завтрашнему дню.", None),
]

A03 = [
    ("I work every day.", "Я работаю каждый день. (Present Simple)", None),
    ("I am working now.", "Я сейчас работаю. (Present Continuous)", None),
    ("I have worked here for years.", "Я работаю здесь много лет. (Present Perfect)", None),
    ("I have been working all morning.", "Я работаю всё утро. (Present Perfect Continuous)", None),
    ("I worked yesterday.", "Я работал вчера. (Past Simple)", None),
    ("I was working when you called.", "Я работал, когда ты позвонил. (Past Continuous)", None),
    ("I had worked before you came.", "Я работал до твоего прихода. (Past Perfect)", None),
    ("I had been working for hours.", "Я работал уже часами. (Past Perfect Continuous)", None),
    ("I will work tomorrow.", "Я буду работать завтра. (Future Simple)", None),
    ("I will be working at eight.", "Я буду работать в восемь. (Future Continuous)", None),
    ("I will have worked by then.", "Я уже закончу работу к тому времени. (Future Perfect)", None),
    ("She cooks dinner every day.", "Она готовит ужин каждый день.", None),
    ("She is cooking right now.", "Она готовит прямо сейчас.", None),
    ("She has cooked the meal.", "Она приготовила еду.", None),
    ("She cooked yesterday.", "Она готовила вчера.", None),
    ("She was cooking when I arrived.", "Она готовила, когда я пришёл.", None),
    ("She will cook tomorrow.", "Она будет готовить завтра.", None),
    ("He plays football on Sundays.", "Он играет в футбол по воскресеньям.", None),
    ("He is playing now.", "Он играет сейчас.", None),
    ("He played last week.", "Он играл на прошлой неделе.", None),
    ("He was playing when it started to rain.", "Он играл, когда начался дождь.", None),
    ("He will play next Sunday.", "Он будет играть в следующее воскресенье.", None),
    ("yesterday — Past Simple", "вчера — простое прошедшее", None),
    ("now — Present Continuous", "сейчас — настоящее длительное", None),
    ("every day — Present Simple", "каждый день — простое настоящее", None),
    ("since 2020 — Present Perfect", "с 2020 года — настоящее совершенное", None),
    ("tomorrow — Future Simple", "завтра — простое будущее", None),
    ("when I arrived — Past Continuous", "когда я пришёл — прошедшее длительное", None),
    ("by then — Future Perfect", "к тому времени — будущее совершенное", None),
    ("Choose the tense by the marker.", "Выбирай время по маркеру.", None),
]

A04 = [
    ("The road is being repaired.", "Дорогу сейчас ремонтируют.", None),
    ("The house is being built.", "Дом строится.", None),
    ("The problem is being solved.", "Проблема решается.", None),
    ("The new law is being discussed.", "Новый закон обсуждается.", None),
    ("The rooms are being cleaned.", "Комнаты убирают.", None),
    ("The bridge has been built.", "Мост построен.", None),
    ("The work has been finished.", "Работа завершена.", None),
    ("The tickets have been booked.", "Билеты забронированы.", None),
    ("The message has been sent.", "Сообщение отправлено.", None),
    ("Everything has been arranged.", "Всё устроено.", None),
    ("The results have been announced.", "Результаты объявлены.", None),
    ("The letter had been sent before I called.", "Письмо было отправлено до моего звонка.", None),
    ("The house had been sold by then.", "Дом был продан к тому времени.", None),
    ("The room had been cleaned when I arrived.", "Комната была убрана, когда я пришёл.", None),
    ("The road will have been repaired by June.", "Дорогу отремонтируют к июню.", None),
    ("The project will have been completed by Friday.", "Проект будет завершён к пятнице.", None),
    ("The building was being renovated.", "Здание ремонтировалось.", None),
    ("The road was being repaired when we drove past.", "Дорогу ремонтировали, когда мы проезжали.", None),
    ("This must be done today.", "Это нужно сделать сегодня.", None),
    ("The report must be submitted by Monday.", "Отчёт нужно подать к понедельнику.", None),
    ("This can be fixed.", "Это можно починить.", None),
    ("It should be done carefully.", "Это нужно делать осторожно.", None),
    ("The room needs to be cleaned.", "Комнату нужно убрать.", None),
    ("He is said to be rich.", "Говорят, что он богат.", None),
    ("She is believed to be innocent.", "Считается, что она невиновна.", None),
    ("It is expected to rain.", "Ожидаются дожди.", None),
    ("It is being built.", "Это строится.", None),
    ("The work is done.", "Работа сделана.", None),
    ("The road is closed.", "Дорога закрыта.", None),
    ("The house is sold.", "Дом продан.", None),
    ("The task is finished.", "Задача завершена.", None),
]

A05 = [
    ("This must be done.", "Это нужно сделать.", None),
    ("The report must be finished by Monday.", "Отчёт нужно закончить к понедельнику.", None),
    ("The form has to be filled in.", "Форму нужно заполнить.", None),
    ("The room should be cleaned.", "Комнату следует убрать.", None),
    ("It can be done online.", "Это можно сделать онлайн.", None),
    ("Tickets can be bought at the station.", "Билеты можно купить на вокзале.", None),
    ("This could be arranged.", "Это можно устроить.", None),
    ("The results will be announced tomorrow.", "Результаты объявят завтра.", None),
    ("A new school will be built here.", "Здесь построят новую школу.", None),
    ("The problem will be solved soon.", "Проблема скоро будет решена.", None),
    ("The road is being repaired.", "Дорогу сейчас ремонтируют.", None),
    ("The house has been sold.", "Дом продан.", None),
    ("English is spoken all over the world.", "На английском говорят во всём мире.", None),
    ("This brand is made in Italy.", "Этот бренд производится в Италии.", None),
    ("The winner will be chosen by the jury.", "Победителя выберет жюри.", None),
    ("The best player was selected for the team.", "Лучший игрок был выбран в команду.", None),
    ("He was awarded a prize.", "Он был награждён призом.", None),
    ("She was given a medal.", "Ей дали медаль.", None),
    ("We were invited to the party.", "Нас пригласили на вечеринку.", None),
    ("They were told to wait.", "Им сказали ждать.", None),
    ("I was asked to help.", "Меня попросили помочь.", None),
    ("It is considered rude.", "Это считается грубым.", None),
    ("Smoking is not allowed here.", "Здесь курить запрещено.", None),
    ("Photography is prohibited.", "Фотографировать запрещено.", None),
    ("Credit cards are accepted.", "Кредитные карты принимаются.", None),
]

A06 = [
    ("The road is being repaired.", "Дорогу сейчас ремонтируют.", None),
    ("The house has been sold.", "Дом продан.", None),
    ("This must be done today.", "Это нужно сделать сегодня.", None),
    ("By next year, he'll have finished.", "К следующему году он закончит.", None),
    ("I'll be flying to Rome tomorrow.", "Завтра я буду лететь в Рим.", None),
    ("She'll have left by then.", "К тому времени она уже уедет.", None),
    ("I'll be working all day.", "Я буду работать весь день.", None),
    ("The results will have been announced.", "Результаты уже будут объявлены.", None),
    ("I work every day.", "Я работаю каждый день.", None),
    ("I worked yesterday.", "Я работал вчера.", None),
    ("I am working now.", "Я сейчас работаю.", None),
    ("I was working when you called.", "Я работал, когда ты позвонил.", None),
    ("I have worked here for years.", "Я работаю здесь много лет.", None),
    ("I had worked before you came.", "Я работал до твоего прихода.", None),
    ("I will work tomorrow.", "Я буду работать завтра.", None),
    ("She cooks, she is cooking, she cooked.", "Она готовит, готовит сейчас, готовила.", None),
    ("The house was built, is being built, will be built.", "Дом построен, строится, будет построен.", None),
    ("Everything has been arranged.", "Всё устроено.", None),
    ("It can be done.", "Это можно сделать.", None),
    ("The report should be submitted.", "Отчёт следует подать.", None),
    ("This time tomorrow I'll be lying on a beach.", "Завтра в это время я буду лежать на пляже.", None),
    ("By the end of the month, I'll have saved enough.", "К концу месяца я накоплю достаточно.", None),
    ("Will you have finished by five?", "Ты закончишь к пяти?", None),
    ("What will you be doing next week?", "Что ты будешь делать на следующей неделе?", None),
    ("The bridge has been built.", "Мост построен.", None),
    ("The new law is being discussed.", "Новый закон обсуждается.", None),
    ("yesterday — Past Simple", "вчера — прошедшее", None),
    ("now — Present Continuous", "сейчас — настоящее длительное", None),
    ("by then — Future Perfect", "к тому времени — будущее совершенное", None),
    ("Choose the tense by the marker.", "Выбирай время по маркеру.", None),
]

A07 = [
    ("He must have forgotten.", "Должно быть, он забыл.", None),
    ("She must have left already.", "Должно быть, она уже ушла.", None),
    ("They must have missed the bus.", "Должно быть, они опоздали на автобус.", None),
    ("It must have rained last night.", "Должно быть, ночью шёл дождь.", None),
    ("You must have worked hard.", "Ты, должно быть, усердно работал.", None),
    ("He can't have said that.", "Не может быть, чтобы он это сказал.", None),
    ("She can't have forgotten.", "Не может быть, чтобы она забыла.", None),
    ("They can't have finished already.", "Не может быть, чтобы они уже закончили.", None),
    ("He can't have lied to me.", "Не может быть, чтобы он мне солгал.", None),
    ("She may have changed her mind.", "Возможно, она передумала.", None),
    ("He may have missed the train.", "Возможно, он опоздал на поезд.", None),
    ("They may have gone home.", "Возможно, они пошли домой.", None),
    ("She might have taken it.", "Возможно, она это взяла.", None),
    ("He might have forgotten.", "Возможно, он забыл.", None),
    ("They might have been delayed.", "Возможно, их задержали.", None),
    ("She could have won.", "Она могла бы победить.", None),
    ("He could have helped.", "Он мог бы помочь.", None),
    ("We could have caught the train.", "Мы могли бы успеть на поезд.", None),
    ("You should have called.", "Тебе следовало позвонить.", None),
    ("I should have studied more.", "Надо было учиться больше.", None),
    ("She shouldn't have said that.", "Ей не следовало этого говорить.", None),
    ("He shouldn't have driven so fast.", "Ему не следовало так быстро ехать.", None),
    ("I shouldn't have eaten so much.", "Не надо было так много есть.", None),
    ("You should have told me.", "Тебе следовало мне сказать.", None),
    ("I should have known better.", "Мне следовало быть умнее.", None),
    ("We should have booked earlier.", "Нам следовало бронировать раньше.", None),
    ("She must have been tired.", "Она, должно быть, устала.", None),
    ("He must have been in a hurry.", "Он, должно быть, спешил.", None),
    ("They can't have been happy.", "Не может быть, чтобы они были счастливы.", None),
    ("I would have helped if I could.", "Я бы помог, если бы мог.", None),
    ("You would have loved it.", "Тебе бы понравилось.", None),
    ("It would have been different.", "Всё было бы иначе.", None),
    ("Who could have done this?", "Кто мог это сделать?", None),
    ("What could have happened?", "Что могло случиться?", None),
    ("Where could she have gone?", "Куда она могла уйти?", None),
]

A08 = [
    ("You should have called me.", "Тебе следовало мне позвонить.", None),
    ("I should have studied harder.", "Надо было учиться усерднее.", None),
    ("We should have left earlier.", "Нам следовало выйти раньше.", None),
    ("She should have asked for help.", "Ей следовало попросить помощи.", None),
    ("He should have listened to me.", "Ему следовало меня послушать.", None),
    ("I shouldn't have said that.", "Не надо было это говорить.", None),
    ("You shouldn't have gone there.", "Тебе не следовало туда ходить.", None),
    ("She shouldn't have spent so much.", "Ей не следовало столько тратить.", None),
    ("We shouldn't have stayed so late.", "Нам не следовало так долго оставаться.", None),
    ("He shouldn't have driven.", "Ему не следовало вести машину.", None),
    ("I shouldn't have eaten that cake.", "Не надо было есть тот торт.", None),
    ("You could have warned me!", "Мог бы меня предупредить!", None),
    ("She could have been a doctor.", "Она могла бы стать врачом.", None),
    ("We could have won the game.", "Мы могли бы выиграть игру.", None),
    ("He could have died!", "Он мог погибнуть!", None),
    ("I could have gone to university.", "Я мог бы пойти в университет.", None),
    ("If only I had known!", "Если бы я только знал!", None),
    ("If only we had more time!", "Если бы только у нас было больше времени!", None),
    ("If only she had listened!", "Если бы она только слушала!", None),
    ("I wish I had studied.", "Жаль, что я не учился.", None),
    ("I wish I had known.", "Жаль, что я не знал.", None),
    ("I wish we had stayed.", "Жаль, что мы не остались.", None),
    ("She wishes she had tried harder.", "Она жалеет, что не старалась сильнее.", None),
    ("He wishes he hadn't said it.", "Он жалеет, что сказал это.", None),
    ("I wish I hadn't gone.", "Жаль, что я пошёл.", None),
    ("It's too late now.", "Сейчас уже поздно.", None),
    ("What's done is done.", "Сделанного не воротишь.", None),
    ("No use crying over spilt milk.", "Слезами делу не поможешь.", None),
    ("Hindsight is always 20/20.", "Задним умом все крепки.", None),
    ("You live and learn.", "Век живи — век учись.", None),
    ("Learn from your mistakes.", "Учись на своих ошибках.", None),
    ("Better luck next time.", "Удачи в следующий раз.", None),
    ("Everyone makes mistakes.", "Все ошибаются.", None),
    ("To err is human.", "Человеку свойственно ошибаться.", None),
    ("Forgive yourself.", "Прости себя.", None),
]

A09 = [
    ("If I had studied, I would have passed.", "Если бы я учился, я бы сдал.", None),
    ("If she had known, she would have come.", "Если бы она знала, она бы пришла.", None),
    ("If we had left earlier, we would have caught the train.", "Если бы мы вышли раньше, мы бы успели на поезд.", None),
    ("If he had asked me, I would have helped.", "Если бы он меня спросил, я бы помог.", None),
    ("If they had tried harder, they would have won.", "Если бы они старались сильнее, они бы выиграли.", None),
    ("If I had known, I would have told you.", "Если бы я знал, я бы тебе сказал.", None),
    ("If she had been there, she would have seen it.", "Если бы она была там, она бы это видела.", None),
    ("If we had booked, we would have got a room.", "Если бы мы забронировали, мы бы получили номер.", None),
    ("If I hadn't been so tired, I would have gone.", "Если бы я не был так устал, я бы пошёл.", None),
    ("If he hadn't lied, she would have stayed.", "Если бы он не солгал, она бы осталась.", None),
    ("If they hadn't arrived late, they would have seen the start.", "Если бы они не опоздали, они бы увидели начало.", None),
    ("I wouldn't have done it if I had known.", "Я бы не сделал этого, если бы знал.", None),
    ("She wouldn't have left if you had asked her.", "Она бы не ушла, если бы ты её попросил.", None),
    ("We wouldn't have missed it if we had checked.", "Мы бы не пропустили это, если бы проверили.", None),
    ("Would you have gone if you had known?", "Ты бы пошёл, если бы знал?", None),
    ("What would you have done?", "Что бы ты сделал?", None),
    ("Where would they have stayed?", "Где бы они остановились?", None),
    ("Who would have thought?", "Кто бы мог подумать?", None),
    ("I would have helped if I could have.", "Я бы помог, если бы мог.", None),
    ("If only I had studied!", "Если бы я только учился!", None),
    ("I should have studied.", "Надо было учиться.", None),
    ("I could have passed.", "Я мог бы сдать.", None),
    ("If I were you, I would have apologized.", "На твоём месте я бы извинился.", None),
    ("Being a child is not a sin.", "Быть ребёнком — не грех.", None),
    ("You died.", "Ты умер.", None),
    ("What if it had happened to you?", "А если бы это случилось с тобой?", None),
    ("It could have been worse.", "Могло быть и хуже.", None),
    ("Everything happens for a reason.", "Всё происходит не просто так.", None),
    ("The past cannot be changed.", "Прошлое нельзя изменить.", None),
    ("But the future can.", "Но будущее — можно.", None),
    ("I wish I knew.", "Жаль, что не знаю.", None),
    ("I wish I could.", "Жаль, что не могу.", None),
    ("I wish I had.", "Жаль, что не было.", None),
    ("If only I knew!", "Если бы знал!", None),
    ("If only I could!", "Если бы мог!", None),
]

A10 = [
    ("I wish I knew.", "Жаль, что не знаю.", None),
    ("I wish I could.", "Жаль, что не могу.", None),
    ("I wish I can.", "Жаль, что нет.", None),
    ("If only I knew!", "Если бы знать!", None),
    ("If only I could!", "Если бы смочь!", None),
    ("If only I had!", "Если бы иметь!", None),
    ("If I had studied, I would have passed.", "Если бы я учился, я бы сдал.", None),
    ("If I were rich, I would travel.", "Если бы я был богат, я бы путешествовал.", None),
    ("If it rains, I'll stay at home.", "Если пойдёт дождь, я останусь дома.", None),
    ("I wish I had known.", "Жаль, что я не знал.", None),
    ("I wish I were there.", "Жаль, что меня там нет.", None),
    ("I wish it would stop raining.", "Хотел бы я, чтобы дождь прекратился.", None),
    ("If I had worked harder, I would be rich now.", "Если бы я работал усерднее, я был бы сейчас богат.", None),
    ("If I had learned to swim, I would be at the beach now.", "Если бы я научился плавать, я был бы сейчас на пляже.", None),
    ("If she hadn't missed the train, she would be here now.", "Если бы она не опоздала на поезд, она была бы сейчас здесь.", None),
    ("If we had booked, we would be inside now.", "Если бы мы забронировали, мы были бы сейчас внутри.", None),
    ("He didn't study, so he failed.", "Он не учился, поэтому провалился.", None),
    ("If he had studied, he would have passed.", "Если бы он учился, он бы сдал.", None),
    ("I didn't know, so I didn't help.", "Я не знал, поэтому не помог.", None),
    ("If I had known, I would have helped.", "Если бы я знал, я бы помог.", None),
    ("She was late, so she missed the meeting.", "Она опоздала, поэтому пропустила встречу.", None),
    ("If she hadn't been late, she would have seen it.", "Если бы она не опоздала, она бы это видела.", None),
    ("I wish I had studied harder at school.", "Жаль, что я не учился усерднее в школе.", None),
    ("I wish I had learned to play the piano.", "Жаль, что я не научился играть на пианино.", None),
    ("I wish I hadn't said that.", "Жаль, что я это сказал.", None),
    ("I wish I had traveled more when I was young.", "Жаль, что я мало путешествовал в молодости.", None),
    ("He wishes he had taken that job.", "Он жалеет, что не взял ту работу.", None),
    ("She wishes she hadn't married him.", "Она жалеет, что вышла за него замуж.", None),
    ("If only I could turn back time!", "Если бы я мог повернуть время вспять!", None),
    ("What's done is done.", "Сделанного не воротишь.", None),
    ("You can't change the past.", "Прошлое не изменишь.", None),
    ("But you can change the future.", "Но будущее изменить можно.", None),
    ("Mixed: past condition → present result.", "Смешанное: условие в прошлом → результат сейчас.", None),
    ("If I had saved money, I would be travelling now.", "Если бы я копил деньги, я бы сейчас путешествовал.", None),
    ("If he hadn't overslept, he wouldn't be so stressed.", "Если бы он не проспал, он не был бы таким напряжённым.", None),
]

A11 = [
    ("He must have forgotten.", "Должно быть, он забыл.", None),
    ("She can't have said that.", "Не может быть, чтобы она это сказала.", None),
    ("You should have called.", "Тебе следовало позвонить.", None),
    ("I shouldn't have said that.", "Не надо было это говорить.", None),
    ("If I had studied, I would have passed.", "Если бы я учился, я бы сдал.", None),
    ("I wish I had known.", "Жаль, что я не знал.", None),
    ("She may have changed her mind.", "Возможно, она передумала.", None),
    ("They might have been delayed.", "Возможно, их задержали.", None),
    ("We could have won.", "Мы могли бы выиграть.", None),
    ("If only I had known!", "Если бы я только знал!", None),
    ("He must have been tired.", "Он, должно быть, устал.", None),
    ("It can't have been easy.", "Не может быть, чтобы это было легко.", None),
    ("You could have told me!", "Мог бы мне сказать!", None),
    ("I would have helped.", "Я бы помог.", None),
    ("She shouldn't have gone there.", "Ей не следовало туда ходить.", None),
    ("If she had known, she would have come.", "Если бы она знала, она бы пришла.", None),
    ("If we had left earlier, we would have caught it.", "Если бы мы вышли раньше, мы бы успели.", None),
    ("I wish I hadn't said it.", "Жаль, что я это сказал.", None),
    ("What would you have done?", "Что бы ты сделал?", None),
    ("Where could she have gone?", "Куда она могла уйти?", None),
    ("It would have been different.", "Всё было бы иначе.", None),
    ("Who would have thought?", "Кто бы мог подумать?", None),
    ("Everything happens for a reason.", "Всё происходит не просто так.", None),
    ("Learn from your mistakes.", "Учись на своих ошибках.", None),
    ("Better late than never.", "Лучше поздно, чем никогда.", None),
    ("If only I could turn back time!", "Если бы я мог повернуть время вспять!", None),
    ("The past cannot be changed.", "Прошлое нельзя изменить.", None),
    ("But the future can.", "Но будущее — можно.", None),
    ("I wish I knew.", "Жаль, что не знаю.", None),
    ("I wish I could.", "Жаль, что не могу.", None),
    ("I wish I had.", "Жаль, что не было.", None),
    ("If only I knew!", "Если бы знал!", None),
    ("If only I could!", "Если бы мог!", None),
    ("I wish I knew.", "Жаль, что не знаю.", None),
    ("I wish I could.", "Жаль, что не могу.", None),
    ("I wish I had.", "Жаль, что не было.", None),
    ("If only I knew!", "Если бы знал!", None),
    ("If only I could!", "Если бы мог!", None),
    ("It's too late now.", "Сейчас уже поздно.", None),
    ("Move on.", "Двигайся дальше.", None),
]

RULE_A01 = """**Future Continuous: will be + V-ing.**
Процесс в будущем: This time tomorrow I'**ll be flying** to Rome.
«Занят в момент»: Don't call at eight — I'**ll be cooking**.
Запрос вежливо: **Will** you **be using** the car tomorrow?"""

RULE_A02 = """**Future Perfect: will have + V3.**
Завершённость к моменту: By next year, he'**ll have finished**.
Маркеры: by then, by the time, by 2030, in two years.
She'**ll have left** by then. = «уже уедет к тому времени»."""

RULE_A03 = """**Карта всех 12 времён.**
Present: I work / I am working / I have worked / I have been working
Past: I worked / I was working / I had worked / I had been working
Future: I will work / I will be working / I will have worked
Выбирай время по маркеру: yesterday → Past, now → Pres.Cont., every day → Pres.S."""

RULE_A04 = """**Пассив: Continuous и Perfect.**
Pres.Cont.Passive: is/are **being** + V3: The road **is being repaired**.
Pres.Perf.Passive: has/have **been** + V3: The bridge **has been built**.
Past Perf.Passive: had been + V3: The house **had been sold**."""

RULE_A05 = """**Пассив: будущее и модальные.**
Future Passive: will **be** + V3: The results **will be announced**.
Modal Passive: must/can/should **be** + V3: This **must be done**.
Выбор: актив (кто делает) vs пассив (что происходит)."""

RULE_A06 = """**Повторение №21: все времена + пассив.**
Future Continuous/Perfect; все 12 времён по маркерам; пассив всех
времен (is made / was built / is being built / has been built / will be done).
Контрольная: выбери время и залог."""

RULE_A07 = """**must have / can't have / may have done.**
**must have** + V3 = «должно быть» (уверенность):
He **must have forgotten**.
**can't have** + V3 = «не может быть»:
He **can't have said** that.
**may/might have** + V3 = «возможно»:
She **may have changed** her mind."""

RULE_A08 = """**should have done: сожаления и упрёки.**
**should have** + V3 = «надо было»: You **should have called**.
**shouldn't have** + V3 = «не надо было»: I **shouldn't have said** that.
**could have** + V3 = «мог бы»: We **could have won**.
wish + had + V3 = «жаль, что не…»: I **wish I had studied**."""

RULE_A09 = """**3-е условное: нереальное прошлое.**
**If** + Past Perfect, **would have** + V3:
If I **had studied**, I **would have passed**.
Если бы… тогда (обе части — в прошлом, изменить нельзя).
Отрицание: If he **hadn't lied**, she **would have stayed**."""

RULE_A10 = """**Смешанные условные + wish глубже.**
Прошлое → настоящее: If I **had saved** money, I **would be** rich **now**.
wish + Past Perfect = «жаль, что не…» в прошлом:
I wish I **had studied**. (= I didn't study)
wish + wouldn't = раздражение: I wish it **would stop**."""

RULE_A11 = """**Повторение №22: модальные в прошедшем.**
must have / can't have / may have — догадки о прошлом.
should(n't) have — сожаления. could have — упущенное.
3-е условное (if had… would have). wish + had V3.
Контрольная: выбери форму, найди ошибку."""

LESSONS_A1_A2 = [
    {
        "id": "les-a-01", "module": "mod-a-1",
        "title": "Future Continuous: she'll be cooking",
        "gp_id": "gp-a-01", "gp_title": "Процесс в будущем",
        "rule_md": RULE_A01,
        "phrases": A01,
        "rule_cloze": [
            ("This time tomorrow I'll be ___ to Rome. (лететь)", ["flying"]),
            ("She'll be ___ for us. (ждать)", ["waiting"]),
            ("What will you be ___ next week? (делать)", ["doing"]),
        ],
        "quotes": [("q-supernatural-0010", "working"), ("q-stranger-things-0007", "doing")],
        "trap_id": "trap-present-perfect",
        "vocab_band": {"list": "ngsl-spoken", "from": 5501, "to": 5560},
        "phrasebook_topic": "smalltalk",
        "quotes_topic": "future",
        "bebris_video": {"lesson": "2.196", "playlist_index": 747, "youtube_id": "6k6QwYL6NzA", "title": None},
        "answer_question": [("What will you be doing next week?", "I'll be travelling around Europe.")],
        "find_error": [("I'll be cook at eight.", "I'll be cooking dinner.")],
        "verb_tense": [
            ("He'll be ___ when you get home. (спать)", "форма", ["sleeping"]),
            ("The train will be ___ at six. (отправляться)", "форма", ["leaving"]),
            ("I won't be ___ it. (нужно будет)", "форма", ["needing"]),
        ],
    },
    {
        "id": "les-a-02", "module": "mod-a-1",
        "title": "Future Perfect: he'll have finished",
        "gp_id": "gp-a-02", "gp_title": "Завершённость к моменту",
        "rule_md": RULE_A02,
        "phrases": A02,
        "rule_cloze": [
            ("By next year, he'll have ___ his degree. (закончить)", ["finished"]),
            ("She'll have ___ by then. (уехать)", ["left"]),
            ("Will you have ___ by five? (закончить)", ["finished"]),
        ],
        "quotes": [("q-igry-0015", "died"), ("q-attack-on-titan-0012", "received")],
        "trap_id": "trap-present-perfect",
        "vocab_band": {"list": "ngsl-spoken", "from": 5561, "to": 5620},
        "phrasebook_topic": None,
        "quotes_topic": "future",
        "bebris_video": {"lesson": "2.211", "playlist_index": 762, "youtube_id": "JSHrZuAy9uo", "title": None},
        "answer_question": [("Will you have finished by five?", "I'll have read the book by then.")],
        "find_error": [("He'll have finish by then.", "He'll have forgotten by tomorrow.")],
        "verb_tense": [
            ("The plane will have ___ by six. (приземлиться)", "форма", ["landed"]),
            ("We'll have been ___ for ten years. (женаты)", "форма", ["married"]),
            ("Everything will have ___. (измениться)", "форма", ["changed"]),
        ],
    },
    {
        "id": "les-a-03", "module": "mod-a-1",
        "title": "Карта всех 12 времён",
        "gp_id": "gp-a-03", "gp_title": "Выбор времени по маркеру",
        "rule_md": RULE_A03,
        "phrases": A03,
        "rule_cloze": [
            ("I ___ every day. (каждый день)", ["work"]),
            ("I ___ yesterday. (вчера)", ["worked"]),
            ("I ___ now. (сейчас)", ["am working"]),
        ],
        "quotes": [("q-lord-of-the-rings-0017", "decide"), ("q-star-wars-0014", "know")],
        "trap_id": "trap-present-perfect",
        "vocab_band": {"list": "ngsl-spoken", "from": 5621, "to": 5680},
        "phrasebook_topic": None,
        "quotes_topic": "tenses",
        "bebris_video": {"lesson": "2.193", "playlist_index": 744, "youtube_id": "fhiXo0tmZTM", "title": None},
        "answer_question": [("What marker means Past Simple?", "yesterday — Past Simple")],
        "find_error": [("I am work every day.", "I work every day.")],
        "verb_tense": [
            ("I was ___ when you called. (работать)", "форма", ["working"]),
            ("I have ___ here for years. (работать)", "форма", ["worked"]),
            ("I will ___ tomorrow. (работать)", "форма", ["work"]),
        ],
    },
    {
        "id": "les-a-04", "module": "mod-a-1",
        "title": "Пассив: Continuous и Perfect",
        "gp_id": "gp-a-04", "gp_title": "being + V3 / been + V3",
        "rule_md": RULE_A04,
        "phrases": A04,
        "rule_cloze": [
            ("The road is ___ repaired.", ["being"]),
            ("The bridge has been ___. (построить)", ["built"]),
            ("The house had been ___ by then. (продать)", ["sold"]),
        ],
        "quotes": [("q-jujutsu-kaisen-0007", "Being"), ("q-memy-0006", "killed")],
        "trap_id": "trap-present-perfect",
        "vocab_band": {"list": "ngsl-spoken", "from": 5681, "to": 5740},
        "phrasebook_topic": None,
        "quotes_topic": "passive",
        "bebris_video": {"lesson": "2.226", "playlist_index": 777, "youtube_id": "k30PW6j0i50", "title": None},
        "answer_question": [("What is being done?", "The road is being repaired.")],
        "find_error": [("The road is been repaired.", "The road is being repaired.")],
        "verb_tense": [
            ("The house has been ___. (продать)", "форма", ["sold"]),
            ("The message has been ___. (отправить)", "форма", ["sent"]),
            ("The road will have been ___ by June. (ремонтировать)", "форма", ["repaired"]),
        ],
    },
    {
        "id": "les-a-05", "module": "mod-a-1",
        "title": "Пассив: будущее и модальные",
        "gp_id": "gp-a-05", "gp_title": "will be / must be done",
        "rule_md": RULE_A05,
        "phrases": A05,
        "rule_cloze": [
            ("The results will be ___ tomorrow. (объявить)", ["announced"]),
            ("This must be ___ today. (сделать)", ["done"]),
            ("It can be ___ online. (сделать)", ["done"]),
        ],
        "quotes": [("q-memy-0006", "killed"), ("q-supernatural-0025", "keep")],
        "trap_id": "trap-present-perfect",
        "vocab_band": {"list": "ngsl-spoken", "from": 5741, "to": 5800},
        "phrasebook_topic": None,
        "quotes_topic": "passive",
        "bebris_video": {"lesson": "2.221", "playlist_index": 772, "youtube_id": "_QTpE9YRIog", "title": None},
        "answer_question": [("When will the results be announced?", "The results will be announced tomorrow.")],
        "find_error": [("This must been done today.", "This must be done today.")],
        "verb_tense": [
            ("The form has to be ___ in. (заполнить)", "форма", ["filled"]),
            ("A new school will be ___ here. (построить)", "форма", ["built"]),
            ("Tickets can be ___ at the station. (купить)", "форма", ["bought"]),
        ],
    },
    {
        "id": "les-a-06", "module": "mod-a-1",
        "title": "Повторение №21",
        "gp_id": "gp-a-06", "gp_title": "Повторение модуля A1",
        "rule_md": RULE_A06,
        "phrases": A06,
        "rule_cloze": [
            ("I'll be ___ tomorrow. (работать)", ["working"]),
            ("She'll have ___ by then. (уехать)", ["left"]),
            ("The road is ___ repaired.", ["being"]),
        ],
        "quotes": [("q-igry-0015", "died"), ("q-attack-on-titan-0012", "received")],
        "trap_id": "trap-present-perfect",
        "vocab_band": {"list": "ngsl-spoken", "from": 5801, "to": 5860},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("What will you be doing?", "I'll be working all day.")],
        "find_error": [("The road is been repaired.", "The road is being repaired.")],
        "verb_tense": [
            ("yesterday — Past ___", "форма", ["Simple"]),
            ("now — Present ___", "форма", ["Continuous"]),
            ("by then — Future ___", "форма", ["Perfect"]),
        ],
    },
    {
        "id": "les-a-07", "module": "mod-a-2",
        "title": "must have / can't have: догадки о прошлом",
        "gp_id": "gp-a-07", "gp_title": "Модальные + have + V3",
        "rule_md": RULE_A07,
        "phrases": A07,
        "rule_cloze": [
            ("He must ___ forgotten.", ["have"]),
            ("She can't ___ said that.", ["have"]),
            ("They may ___ gone home.", ["have"]),
        ],
        "quotes": [("q-berserk-0016", "tortured"), ("q-berserk-0016", "wounded")],
        "trap_id": "trap-present-perfect",
        "vocab_band": {"list": "ngsl-spoken", "from": 5861, "to": 5920},
        "phrasebook_topic": None,
        "quotes_topic": "modals",
        "bebris_video": {"lesson": "2.297", "playlist_index": 848, "youtube_id": "RIPD00DDXEk", "title": None},
        "answer_question": [("Where is he?", "She may have changed her mind.")],
        "find_error": [("He must has forgotten.", "He must have forgotten.")],
        "verb_tense": [
            ("She must ___ left already.", "форма", ["have"]),
            ("He can't ___ lied to me.", "форма", ["have"]),
            ("They might ___ been delayed.", "форма", ["have"]),
        ],
    },
    {
        "id": "les-a-08", "module": "mod-a-2",
        "title": "should have done: сожаления",
        "gp_id": "gp-a-08", "gp_title": "Сожаления и упрёки",
        "rule_md": RULE_A08,
        "phrases": A08,
        "rule_cloze": [
            ("You should ___ called me.", ["have"]),
            ("I shouldn't ___ said that.", ["have"]),
            ("We could ___ won.", ["have"]),
        ],
        "quotes": [("q-berserk-0018", "something"), ("q-supernatural-0011", "want")],
        "trap_id": "trap-present-perfect",
        "vocab_band": {"list": "ngsl-spoken", "from": 5921, "to": 5980},
        "phrasebook_topic": None,
        "quotes_topic": "regrets",
        "bebris_video": {"lesson": "2.303", "playlist_index": 854, "youtube_id": "eE_sqWpL-lo", "title": None},
        "answer_question": [("Did you study?", "I should have studied more.")],
        "find_error": [("You should has called.", "You should have called.")],
        "verb_tense": [
            ("I wish I ___ studied.", "форма", ["had"]),
            ("She shouldn't ___ gone there.", "форма", ["have"]),
            ("We could ___ caught the train.", "форма", ["have"]),
        ],
    },
    {
        "id": "les-a-09", "module": "mod-a-2",
        "title": "3-е условное: If I had studied…",
        "gp_id": "gp-a-09", "gp_title": "Нереальное прошлое",
        "rule_md": RULE_A09,
        "phrases": A09,
        "rule_cloze": [
            ("If I ___ studied, I would have passed.", ["had"]),
            ("If she ___ known, she would have come.", ["had"]),
            ("I wouldn't have done it if I ___ known.", ["had"]),
        ],
        "quotes": [("q-jujutsu-kaisen-0007", "Being"), ("q-lord-of-the-rings-0002", "will")],
        "trap_id": "trap-if-will",
        "vocab_band": {"list": "ngsl-spoken", "from": 5981, "to": 6040},
        "phrasebook_topic": None,
        "quotes_topic": "conditionals",
        "bebris_video": {"lesson": "2.310", "playlist_index": 861, "youtube_id": "a2NXNeUKhcU", "title": None},
        "answer_question": [("What would you have done?", "I would have helped.")],
        "find_error": [("If I would have studied, I would have passed.", "If I had studied, I would have passed.")],
        "verb_tense": [
            ("If we ___ left earlier, we would have caught it.", "форма", ["had"]),
            ("If he ___ lied, she would have stayed.", "форма", ["hadn't", "had not"]),
            ("Would you ___ gone if you had known?", "форма", ["have"]),
        ],
    },
    {
        "id": "les-a-10", "module": "mod-a-2",
        "title": "Смешанные условные + wish глубже",
        "gp_id": "gp-a-10", "gp_title": "Mixed conditionals",
        "rule_md": RULE_A10,
        "phrases": A10,
        "rule_cloze": [
            ("If I ___ worked harder, I would be rich now.", ["had"]),
            ("I wish I ___ known.", ["had"]),
            ("If she hadn't missed the train, she ___ be here now.", ["would"]),
        ],
        "quotes": [("q-berserk-0018", "yourself"), ("q-game-of-thrones-0014", "win")],
        "trap_id": "trap-if-will",
        "vocab_band": {"list": "ngsl-spoken", "from": 6041, "to": 6100},
        "phrasebook_topic": None,
        "quotes_topic": "conditionals",
        "bebris_video": {"lesson": "2.319", "playlist_index": 870, "youtube_id": "EEMmcyY2nvc", "title": None},
        "answer_question": [("What do you wish?", "I wish I had known.")],
        "find_error": [("If I had worked harder, I would been rich now.", "If I had worked harder, I would be rich now.")],
        "verb_tense": [
            ("I wish I ___ learned to swim.", "форма", ["had"]),
            ("If he ___ overslept, he wouldn't be stressed.", "форма", ["hadn't", "had not"]),
            ("I wish I ___ said that.", "форма", ["hadn't", "had not"]),
        ],
    },
    {
        "id": "les-a-11", "module": "mod-a-2",
        "title": "Повторение №22: контрольная",
        "gp_id": "gp-a-11", "gp_title": "Контрольная: модальные в прошедшем",
        "rule_md": RULE_A11,
        "phrases": A11,
        "rule_cloze": [
            ("He must ___ forgotten.", ["have"]),
            ("If I ___ studied, I would have passed.", ["had"]),
            ("I wish I ___ known.", ["had"]),
        ],
        "quotes": [("q-berserk-0016", "tortured"), ("q-igry-0003", "used")],
        "trap_id": "trap-if-will",
        "vocab_band": {"list": "ngsl-spoken", "from": 6101, "to": 6160},
        "phrasebook_topic": None,
        "quotes_topic": "mixed",
        "bebris_video": None,
        "answer_question": [("What do you wish you had done?", "I wish I had studied.")],
        "find_error": [("If I would have studied, I would have passed.", "If I had studied, I would have passed.")],
        "verb_tense": [
            ("She can't ___ said that.", "форма", ["have"]),
            ("You should ___ called.", "форма", ["have"]),
            ("I wouldn't have done it if I ___ known.", "форма", ["had"]),
        ],
    },
]
